//
//  ConditionTests.swift
//  ConditionTests
//
//  Generated from FHIR 0.4.0.3958 on 2015-01-20.
//  2015, SMART Platforms.
//

import XCTest
import SwiftFHIR


class ConditionTests: FHIRModelTestCase
{
	func instantiateFrom(filename: String) -> Condition? {
		let json = readJSONFile(filename)
		let instance = Condition(json: json)
		XCTAssertNotNil(instance, "Must have instantiated a test instance")
		return instance
	}
	
	func testCondition1() {
		let inst = instantiateFrom("condition-example-f001-heart.canonical.json")
		XCTAssertNotNil(inst, "Must have instantiated a Condition instance")
		
		XCTAssertEqual(inst!.asserter!.display!, "P. van de Heuvel")
		XCTAssertEqual(inst!.asserter!.reference!, "Patient/f001")
		XCTAssertEqual(inst!.category!.coding![0].code!, "439401001")
		XCTAssertEqual(inst!.category!.coding![0].display!, "diagnosis")
		XCTAssertEqual(inst!.category!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.code!.coding![0].code!, "368009")
		XCTAssertEqual(inst!.code!.coding![0].display!, "Heart valve disorder")
		XCTAssertEqual(inst!.code!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.dateAsserted!.description, "2011-10-05")
		XCTAssertEqual(inst!.encounter!.reference!, "Encounter/f001")
		XCTAssertEqual(inst!.evidence![0].code!.coding![0].code!, "426396005")
		XCTAssertEqual(inst!.evidence![0].code!.coding![0].display!, "Cardiac chest pain")
		XCTAssertEqual(inst!.evidence![0].code!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.location![0].code!.coding![0].code!, "40768004")
		XCTAssertEqual(inst!.location![0].code!.coding![0].display!, "Left thorax")
		XCTAssertEqual(inst!.location![0].code!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.location![0].detail!, "heart structure")
		XCTAssertEqual(inst!.onsetDateTime!.description, "2011-08-05")
		XCTAssertEqual(inst!.severity!.coding![0].code!, "6736007")
		XCTAssertEqual(inst!.severity!.coding![0].display!, "Moderate")
		XCTAssertEqual(inst!.severity!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.status!, "confirmed")
		XCTAssertEqual(inst!.subject!.display!, "P. van de Heuvel")
		XCTAssertEqual(inst!.subject!.reference!, "Patient/f001")
	}
	
	func testCondition2() {
		let inst = instantiateFrom("condition-example-f001-heart.canonical.json")
		XCTAssertNotNil(inst, "Must have instantiated a Condition instance")
		
		XCTAssertEqual(inst!.asserter!.display!, "P. van de Heuvel")
		XCTAssertEqual(inst!.asserter!.reference!, "Patient/f001")
		XCTAssertEqual(inst!.category!.coding![0].code!, "439401001")
		XCTAssertEqual(inst!.category!.coding![0].display!, "diagnosis")
		XCTAssertEqual(inst!.category!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.code!.coding![0].code!, "368009")
		XCTAssertEqual(inst!.code!.coding![0].display!, "Heart valve disorder")
		XCTAssertEqual(inst!.code!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.dateAsserted!.description, "2011-10-05")
		XCTAssertEqual(inst!.encounter!.reference!, "Encounter/f001")
		XCTAssertEqual(inst!.evidence![0].code!.coding![0].code!, "426396005")
		XCTAssertEqual(inst!.evidence![0].code!.coding![0].display!, "Cardiac chest pain")
		XCTAssertEqual(inst!.evidence![0].code!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.location![0].code!.coding![0].code!, "40768004")
		XCTAssertEqual(inst!.location![0].code!.coding![0].display!, "Left thorax")
		XCTAssertEqual(inst!.location![0].code!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.location![0].detail!, "heart structure")
		XCTAssertEqual(inst!.onsetDateTime!.description, "2011-08-05")
		XCTAssertEqual(inst!.severity!.coding![0].code!, "6736007")
		XCTAssertEqual(inst!.severity!.coding![0].display!, "Moderate")
		XCTAssertEqual(inst!.severity!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.status!, "confirmed")
		XCTAssertEqual(inst!.subject!.display!, "P. van de Heuvel")
		XCTAssertEqual(inst!.subject!.reference!, "Patient/f001")
	}
	
	func testCondition3() {
		let inst = instantiateFrom("condition-example-f001-heart.json")
		XCTAssertNotNil(inst, "Must have instantiated a Condition instance")
		
		XCTAssertEqual(inst!.asserter!.display!, "P. van de Heuvel")
		XCTAssertEqual(inst!.asserter!.reference!, "Patient/f001")
		XCTAssertEqual(inst!.category!.coding![0].code!, "439401001")
		XCTAssertEqual(inst!.category!.coding![0].display!, "diagnosis")
		XCTAssertEqual(inst!.category!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.code!.coding![0].code!, "368009")
		XCTAssertEqual(inst!.code!.coding![0].display!, "Heart valve disorder")
		XCTAssertEqual(inst!.code!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.dateAsserted!.description, "2011-10-05")
		XCTAssertEqual(inst!.encounter!.reference!, "Encounter/f001")
		XCTAssertEqual(inst!.evidence![0].code!.coding![0].code!, "426396005")
		XCTAssertEqual(inst!.evidence![0].code!.coding![0].display!, "Cardiac chest pain")
		XCTAssertEqual(inst!.evidence![0].code!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.location![0].code!.coding![0].code!, "40768004")
		XCTAssertEqual(inst!.location![0].code!.coding![0].display!, "Left thorax")
		XCTAssertEqual(inst!.location![0].code!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.location![0].detail!, "heart structure")
		XCTAssertEqual(inst!.onsetDateTime!.description, "2011-08-05")
		XCTAssertEqual(inst!.severity!.coding![0].code!, "6736007")
		XCTAssertEqual(inst!.severity!.coding![0].display!, "Moderate")
		XCTAssertEqual(inst!.severity!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.status!, "confirmed")
		XCTAssertEqual(inst!.subject!.display!, "P. van de Heuvel")
		XCTAssertEqual(inst!.subject!.reference!, "Patient/f001")
	}
	
	func testCondition4() {
		let inst = instantiateFrom("condition-example-f002-lung.canonical.json")
		XCTAssertNotNil(inst, "Must have instantiated a Condition instance")
		
		XCTAssertEqual(inst!.asserter!.display!, "P. van de Heuvel")
		XCTAssertEqual(inst!.asserter!.reference!, "Patient/f001")
		XCTAssertEqual(inst!.category!.coding![0].code!, "439401001")
		XCTAssertEqual(inst!.category!.coding![0].display!, "diagnosis")
		XCTAssertEqual(inst!.category!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.code!.coding![0].code!, "254637007")
		XCTAssertEqual(inst!.code!.coding![0].display!, "NSCLC - Non-small cell lung cancer")
		XCTAssertEqual(inst!.code!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.dateAsserted!.description, "2012-06-03")
		XCTAssertEqual(inst!.encounter!.reference!, "Encounter/f002")
		XCTAssertEqual(inst!.evidence![0].code!.coding![0].code!, "169069000")
		XCTAssertEqual(inst!.evidence![0].code!.coding![0].display!, "CT of thorax")
		XCTAssertEqual(inst!.evidence![0].code!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.location![0].code!.coding![0].code!, "51185008")
		XCTAssertEqual(inst!.location![0].code!.coding![0].display!, "Thorax")
		XCTAssertEqual(inst!.location![0].code!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.location![0].detail!, "lung")
		XCTAssertEqual(inst!.onsetDateTime!.description, "2011-05-05")
		XCTAssertEqual(inst!.severity!.coding![0].code!, "24484000")
		XCTAssertEqual(inst!.severity!.coding![0].display!, "Severe")
		XCTAssertEqual(inst!.severity!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.stage!.summary!.coding![0].code!, "258219007")
		XCTAssertEqual(inst!.stage!.summary!.coding![0].display!, "stage II")
		XCTAssertEqual(inst!.stage!.summary!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.status!, "confirmed")
		XCTAssertEqual(inst!.subject!.display!, "P. van de Heuvel")
		XCTAssertEqual(inst!.subject!.reference!, "Patient/f001")
	}
	
	func testCondition5() {
		let inst = instantiateFrom("condition-example-f002-lung.json")
		XCTAssertNotNil(inst, "Must have instantiated a Condition instance")
		
		XCTAssertEqual(inst!.asserter!.display!, "P. van de Heuvel")
		XCTAssertEqual(inst!.asserter!.reference!, "Patient/f001")
		XCTAssertEqual(inst!.category!.coding![0].code!, "439401001")
		XCTAssertEqual(inst!.category!.coding![0].display!, "diagnosis")
		XCTAssertEqual(inst!.category!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.code!.coding![0].code!, "254637007")
		XCTAssertEqual(inst!.code!.coding![0].display!, "NSCLC - Non-small cell lung cancer")
		XCTAssertEqual(inst!.code!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.dateAsserted!.description, "2012-06-03")
		XCTAssertEqual(inst!.encounter!.reference!, "Encounter/f002")
		XCTAssertEqual(inst!.evidence![0].code!.coding![0].code!, "169069000")
		XCTAssertEqual(inst!.evidence![0].code!.coding![0].display!, "CT of thorax")
		XCTAssertEqual(inst!.evidence![0].code!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.location![0].code!.coding![0].code!, "51185008")
		XCTAssertEqual(inst!.location![0].code!.coding![0].display!, "Thorax")
		XCTAssertEqual(inst!.location![0].code!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.location![0].detail!, "lung")
		XCTAssertEqual(inst!.onsetDateTime!.description, "2011-05-05")
		XCTAssertEqual(inst!.severity!.coding![0].code!, "24484000")
		XCTAssertEqual(inst!.severity!.coding![0].display!, "Severe")
		XCTAssertEqual(inst!.severity!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.stage!.summary!.coding![0].code!, "258219007")
		XCTAssertEqual(inst!.stage!.summary!.coding![0].display!, "stage II")
		XCTAssertEqual(inst!.stage!.summary!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.status!, "confirmed")
		XCTAssertEqual(inst!.subject!.display!, "P. van de Heuvel")
		XCTAssertEqual(inst!.subject!.reference!, "Patient/f001")
	}
	
	func testCondition6() {
		let inst = instantiateFrom("condition-example-f003-abscess.canonical.json")
		XCTAssertNotNil(inst, "Must have instantiated a Condition instance")
		
		XCTAssertEqual(inst!.asserter!.display!, "P. van de Heuvel")
		XCTAssertEqual(inst!.asserter!.reference!, "Patient/f001")
		XCTAssertEqual(inst!.category!.coding![0].code!, "439401001")
		XCTAssertEqual(inst!.category!.coding![0].display!, "diagnosis")
		XCTAssertEqual(inst!.category!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.code!.coding![0].code!, "18099001")
		XCTAssertEqual(inst!.code!.coding![0].display!, "Retropharyngeal abscess")
		XCTAssertEqual(inst!.code!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.dateAsserted!.description, "2012-02-20")
		XCTAssertEqual(inst!.encounter!.reference!, "Encounter/f003")
		XCTAssertEqual(inst!.evidence![0].code!.coding![0].code!, "169068008")
		XCTAssertEqual(inst!.evidence![0].code!.coding![0].display!, "CT of neck")
		XCTAssertEqual(inst!.evidence![0].code!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.location![0].code!.coding![0].code!, "280193007")
		XCTAssertEqual(inst!.location![0].code!.coding![0].display!, "Entire retropharyngeal area")
		XCTAssertEqual(inst!.location![0].code!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.onsetDateTime!.description, "2012-02-27")
		XCTAssertEqual(inst!.severity!.coding![0].code!, "371923003")
		XCTAssertEqual(inst!.severity!.coding![0].display!, "Mild to moderate")
		XCTAssertEqual(inst!.severity!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.status!, "confirmed")
		XCTAssertEqual(inst!.subject!.display!, "P. van de Heuvel")
		XCTAssertEqual(inst!.subject!.reference!, "Patient/f001")
	}
	
	func testCondition7() {
		let inst = instantiateFrom("condition-example-f003-abscess.json")
		XCTAssertNotNil(inst, "Must have instantiated a Condition instance")
		
		XCTAssertEqual(inst!.asserter!.display!, "P. van de Heuvel")
		XCTAssertEqual(inst!.asserter!.reference!, "Patient/f001")
		XCTAssertEqual(inst!.category!.coding![0].code!, "439401001")
		XCTAssertEqual(inst!.category!.coding![0].display!, "diagnosis")
		XCTAssertEqual(inst!.category!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.code!.coding![0].code!, "18099001")
		XCTAssertEqual(inst!.code!.coding![0].display!, "Retropharyngeal abscess")
		XCTAssertEqual(inst!.code!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.dateAsserted!.description, "2012-02-20")
		XCTAssertEqual(inst!.encounter!.reference!, "Encounter/f003")
		XCTAssertEqual(inst!.evidence![0].code!.coding![0].code!, "169068008")
		XCTAssertEqual(inst!.evidence![0].code!.coding![0].display!, "CT of neck")
		XCTAssertEqual(inst!.evidence![0].code!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.location![0].code!.coding![0].code!, "280193007")
		XCTAssertEqual(inst!.location![0].code!.coding![0].display!, "Entire retropharyngeal area")
		XCTAssertEqual(inst!.location![0].code!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.onsetDateTime!.description, "2012-02-27")
		XCTAssertEqual(inst!.severity!.coding![0].code!, "371923003")
		XCTAssertEqual(inst!.severity!.coding![0].display!, "Mild to moderate")
		XCTAssertEqual(inst!.severity!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.status!, "confirmed")
		XCTAssertEqual(inst!.subject!.display!, "P. van de Heuvel")
		XCTAssertEqual(inst!.subject!.reference!, "Patient/f001")
	}
	
	func testCondition8() {
		let inst = instantiateFrom("condition-example-f201-fever.canonical.json")
		XCTAssertNotNil(inst, "Must have instantiated a Condition instance")
		
		XCTAssertEqual(inst!.asserter!.reference!, "Practitioner/f201")
		XCTAssertEqual(inst!.category!.coding![0].code!, "55607006")
		XCTAssertEqual(inst!.category!.coding![0].display!, "Problem")
		XCTAssertEqual(inst!.category!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.category!.coding![1].code!, "condition")
		XCTAssertEqual(inst!.category!.coding![1].system!.absoluteString!, "http://hl7.org/fhir/condition-category")
		XCTAssertEqual(inst!.code!.coding![0].code!, "386661006")
		XCTAssertEqual(inst!.code!.coding![0].display!, "Fever")
		XCTAssertEqual(inst!.code!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.dateAsserted!.description, "2013-04-04")
		XCTAssertEqual(inst!.dueTo![0].target!.display!, "TPF chemokuur")
		XCTAssertEqual(inst!.dueTo![0].target!.reference!, "Procedure/f201")
		XCTAssertEqual(inst!.dueTo![1].target!.display!, "bacterial infection")
		XCTAssertEqual(inst!.dueTo![1].target!.reference!, "Condition/f205")
		XCTAssertEqual(inst!.encounter!.reference!, "Encounter/f201")
		XCTAssertEqual(inst!.evidence![0].code!.coding![0].code!, "258710007")
		XCTAssertEqual(inst!.evidence![0].code!.coding![0].display!, "degrees C")
		XCTAssertEqual(inst!.evidence![0].code!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.evidence![0].detail![0].display!, "Temperature")
		XCTAssertEqual(inst!.evidence![0].detail![0].reference!, "Observation/f202")
		XCTAssertEqual(inst!.location![0].code!.coding![0].code!, "38266002")
		XCTAssertEqual(inst!.location![0].code!.coding![0].display!, "Entire body as a whole")
		XCTAssertEqual(inst!.location![0].code!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.onsetDateTime!.description, "2013-04-02")
		XCTAssertEqual(inst!.severity!.coding![0].code!, "255604002")
		XCTAssertEqual(inst!.severity!.coding![0].display!, "Mild")
		XCTAssertEqual(inst!.severity!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.status!, "confirmed")
		XCTAssertEqual(inst!.subject!.display!, "Roel")
		XCTAssertEqual(inst!.subject!.reference!, "Patient/f201")
	}
	
	func testCondition9() {
		let inst = instantiateFrom("condition-example-f201-fever.json")
		XCTAssertNotNil(inst, "Must have instantiated a Condition instance")
		
		XCTAssertEqual(inst!.asserter!.reference!, "Practitioner/f201")
		XCTAssertEqual(inst!.category!.coding![0].code!, "55607006")
		XCTAssertEqual(inst!.category!.coding![0].display!, "Problem")
		XCTAssertEqual(inst!.category!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.category!.coding![1].code!, "condition")
		XCTAssertEqual(inst!.category!.coding![1].system!.absoluteString!, "http://hl7.org/fhir/condition-category")
		XCTAssertEqual(inst!.code!.coding![0].code!, "386661006")
		XCTAssertEqual(inst!.code!.coding![0].display!, "Fever")
		XCTAssertEqual(inst!.code!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.dateAsserted!.description, "2013-04-04")
		XCTAssertEqual(inst!.dueTo![0].target!.display!, "TPF chemokuur")
		XCTAssertEqual(inst!.dueTo![0].target!.reference!, "Procedure/f201")
		XCTAssertEqual(inst!.dueTo![1].target!.display!, "bacterial infection")
		XCTAssertEqual(inst!.dueTo![1].target!.reference!, "Condition/f205")
		XCTAssertEqual(inst!.encounter!.reference!, "Encounter/f201")
		XCTAssertEqual(inst!.evidence![0].code!.coding![0].code!, "258710007")
		XCTAssertEqual(inst!.evidence![0].code!.coding![0].display!, "degrees C")
		XCTAssertEqual(inst!.evidence![0].code!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.evidence![0].detail![0].display!, "Temperature")
		XCTAssertEqual(inst!.evidence![0].detail![0].reference!, "Observation/f202")
		XCTAssertEqual(inst!.location![0].code!.coding![0].code!, "38266002")
		XCTAssertEqual(inst!.location![0].code!.coding![0].display!, "Entire body as a whole")
		XCTAssertEqual(inst!.location![0].code!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.onsetDateTime!.description, "2013-04-02")
		XCTAssertEqual(inst!.severity!.coding![0].code!, "255604002")
		XCTAssertEqual(inst!.severity!.coding![0].display!, "Mild")
		XCTAssertEqual(inst!.severity!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.status!, "confirmed")
		XCTAssertEqual(inst!.subject!.display!, "Roel")
		XCTAssertEqual(inst!.subject!.reference!, "Patient/f201")
	}
	
	func testCondition10() {
		let inst = instantiateFrom("condition-example-f202-malignancy.canonical.json")
		XCTAssertNotNil(inst, "Must have instantiated a Condition instance")
		
		XCTAssertEqual(inst!.category!.coding![0].code!, "diagnose")
		XCTAssertEqual(inst!.category!.coding![0].system!.absoluteString!, "http://hl7.org/fhir/condition-category")
		XCTAssertEqual(inst!.certainty!.coding![0].code!, "17162000")
		XCTAssertEqual(inst!.certainty!.coding![0].display!, "Certain")
		XCTAssertEqual(inst!.certainty!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.code!.coding![0].code!, "363346000")
		XCTAssertEqual(inst!.code!.coding![0].display!, "Malignant neoplastic disease")
		XCTAssertEqual(inst!.code!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.dateAsserted!.description, "2012-12-01")
		XCTAssertEqual(inst!.evidence![0].detail![0].display!, "Erasmus' diagnostic report of Roel's tumor")
		XCTAssertEqual(inst!.evidence![0].detail![0].reference!, "DiagnosticReport/f201")
		XCTAssertEqual(inst!.location![0].code!.coding![0].code!, "361355005")
		XCTAssertEqual(inst!.location![0].code!.coding![0].display!, "Entire head and neck")
		XCTAssertEqual(inst!.location![0].code!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.onsetAge!.code!, "258707000")
		XCTAssertEqual(inst!.onsetAge!.system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.onsetAge!.units!, "years")
		XCTAssertEqual(inst!.onsetAge!.value!, NSDecimalNumber(string: "52"))
		XCTAssertEqual(inst!.severity!.coding![0].code!, "24484000")
		XCTAssertEqual(inst!.severity!.coding![0].display!, "Severe")
		XCTAssertEqual(inst!.severity!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.status!, "confirmed")
		XCTAssertEqual(inst!.subject!.display!, "Roel")
		XCTAssertEqual(inst!.subject!.reference!, "Patient/f201")
	}
}
