//
//  MedicationPrescriptionTests.swift
//  MedicationPrescriptionTests
//
//  Generated from FHIR 0.0.82.2943 on 2014-10-26.
//  2014, SMART Platforms.
//

import Cocoa
import XCTest
import SwiftFHIR


class MedicationPrescriptionTests: FHIRModelTestCase
{
	func instantiateFrom(filename: String) -> MedicationPrescription? {
		let json = readJSONFile(filename)
		let instance = MedicationPrescription(json: json)
		XCTAssertNotNil(instance, "Must have instantiated a test instance")
		return instance
	}
	
	func testMedicationPrescription1() {
		let inst = instantiateFrom("medicationprescription-example-f001-combivent.json")
		XCTAssertNotNil(inst, "Must have instantiated a MedicationPrescription instance")
	
		XCTAssertEqual(inst!.dateWritten!, NSDate.dateFromISOString("2013-05-25T19:32:52+01:00")!)
		XCTAssertEqual(inst!.dispense!.numberOfRepeatsAllowed!, 20)	
		XCTAssertEqual(inst!.dispense!.quantity!.code!, "ug")
		XCTAssertEqual(inst!.dispense!.quantity!.system!, NSURL(string: "urn:oid:2.16.840.1.113883.6.8")!)	
		XCTAssertEqual(inst!.dispense!.quantity!.units!, "mcg")
		XCTAssertEqual(inst!.dispense!.quantity!.value!, 100)
		XCTAssertEqual(inst!.dispense!.validityPeriod!.end!, NSDate.dateFromISOString("2013-05-30")!)
		XCTAssertEqual(inst!.dispense!.validityPeriod!.start!, NSDate.dateFromISOString("2013-04-08")!)	
		XCTAssertEqual(inst!.dosageInstruction![0].additionalInstructions!.text!, "for use during pregnancy, contact physician")	
		XCTAssertEqual(inst!.dosageInstruction![0].doseQuantity!.code!, "ml")
		XCTAssertEqual(inst!.dosageInstruction![0].doseQuantity!.system!, NSURL(string: "http://unitsofmeasure.org")!)	
		XCTAssertEqual(inst!.dosageInstruction![0].doseQuantity!.units!, "ml")
		XCTAssertEqual(inst!.dosageInstruction![0].doseQuantity!.value!, 10)	
		XCTAssertEqual(inst!.dosageInstruction![0].route!.coding![0].code!, "394899003")	
		XCTAssertEqual(inst!.dosageInstruction![0].route!.coding![0].display!, "oral administration of treatment")
		XCTAssertEqual(inst!.dosageInstruction![0].route!.coding![0].system!, NSURL(string: "http://snomed.info/sct")!)	
		XCTAssertEqual(inst!.dosageInstruction![0].site!.coding![0].code!, "181220002")	
		XCTAssertEqual(inst!.dosageInstruction![0].site!.coding![0].display!, "Entire oral cavity")
		XCTAssertEqual(inst!.dosageInstruction![0].site!.coding![0].system!, NSURL(string: "http://snomed.info/sct")!)	
		XCTAssertEqual(inst!.dosageInstruction![0].text!, "3 tot 4 maal daags 1 flacon")
		XCTAssertEqual(inst!.dosageInstruction![0].timingSchedule!.event![0].end!, NSDate.dateFromISOString("2013-11-05")!)
		XCTAssertEqual(inst!.dosageInstruction![0].timingSchedule!.event![0].start!, NSDate.dateFromISOString("2013-08-04")!)
		XCTAssertEqual(inst!.dosageInstruction![0].timingSchedule!.repeat!.duration!, 1)
		XCTAssertEqual(inst!.dosageInstruction![0].timingSchedule!.repeat!.frequency!, 3)	
		XCTAssertEqual(inst!.dosageInstruction![0].timingSchedule!.repeat!.units!, "d")	
		XCTAssertEqual(inst!.encounter!.display!, "visit who leads to this priscription")	
		XCTAssertEqual(inst!.encounter!.reference!, "Encounter/f001")
		XCTAssertEqual(inst!.identifier![0].system!, NSURL(string: "http://www.bmc/portal/prescriptions")!)	
		XCTAssertEqual(inst!.identifier![0].use!, "official")	
		XCTAssertEqual(inst!.identifier![0].value!, "order9837293")	
		XCTAssertEqual(inst!.medication!.display!, "prescribed medication")	
		XCTAssertEqual(inst!.medication!.reference!, "Medication/f001")	
		XCTAssertEqual(inst!.patient!.display!, "P. van den Heuvel")	
		XCTAssertEqual(inst!.patient!.reference!, "Patient/f001")	
		XCTAssertEqual(inst!.prescriber!.display!, "R.A. van den Berk")	
		XCTAssertEqual(inst!.prescriber!.reference!, "Practitioner/f006")	
		XCTAssertEqual(inst!.reasonCodeableConcept!.coding![0].code!, "13645005")	
		XCTAssertEqual(inst!.reasonCodeableConcept!.coding![0].display!, "Chronic obstructive pulmonary disease")
		XCTAssertEqual(inst!.reasonCodeableConcept!.coding![0].system!, NSURL(string: "http://snomed.info/sct")!)	
		XCTAssertEqual(inst!.status!, "active")	
		XCTAssertEqual(inst!.text!.div!, "<div>\n      <p>\n        <b>Generated Narrative</b>\n      </p>\n      <p>\n        <b>identifier</b>: order9837293 (official)\n      </p>\n      <p>\n        <b>dateWritten</b>: 25-May 2013 19:32\n      </p>\n      <p>\n        <b>status</b>: active\n      </p>\n      <p>\n        <b>patient</b>: P. van den Heuvel\n      </p>\n      <p>\n        <b>prescriber</b>: R.A. van den Berk\n      </p>\n      <p>\n        <b>encounter</b>: visit who leads to this priscription\n      </p>\n      <p>\n        <b>reason[x]</b>: \n        <span title=\"Codes: {http://snomed.info/sct 13645005}\">Chronic obstructive pulmonary disease</span>\n      </p>\n      <p>\n        <b>medication</b>: prescribed medication\n      </p>\n      <h3>DosageInstructions</h3>\n      <table class=\"grid\">\n        <tr>\n          <td>\n            <b>Text</b>\n          </td>\n          <td>\n            <b>AdditionalInstructions</b>\n          </td>\n          <td>\n            <b>Timing[x]</b>\n          </td>\n          <td>\n            <b>AsNeeded[x]</b>\n          </td>\n          <td>\n            <b>Site</b>\n          </td>\n          <td>\n            <b>Route</b>\n          </td>\n          <td>\n            <b>Method</b>\n          </td>\n          <td>\n            <b>DoseQuantity</b>\n          </td>\n          <td>\n            <b>Rate</b>\n          </td>\n          <td>\n            <b>MaxDosePerPeriod</b>\n          </td>\n        </tr>\n        <tr>\n          <td>3 tot 4 maal daags 1 flacon</td>\n          <td>\n            <span title=\"Codes: \">for use during pregnancy, contact physician</span>\n          </td>\n          <td>Starting 4-Aug 2013 --&gt; 5-Nov 2013, 3 per 1 days</td>\n          <td> </td>\n          <td>\n            <span title=\"Codes: {http://snomed.info/sct 181220002}\">Entire oral cavity</span>\n          </td>\n          <td>\n            <span title=\"Codes: {http://snomed.info/sct 394899003}\">oral administration of treatment</span>\n          </td>\n          <td> </td>\n          <td>10 ml</td>\n          <td> </td>\n          <td> </td>\n        </tr>\n      </table>\n      <h3>Dispenses</h3>\n      <table class=\"grid\">\n        <tr>\n          <td>\n            <b>Medication</b>\n          </td>\n          <td>\n            <b>ValidityPeriod</b>\n          </td>\n          <td>\n            <b>NumberOfRepeatsAllowed</b>\n          </td>\n          <td>\n            <b>Quantity</b>\n          </td>\n          <td>\n            <b>ExpectedSupplyDuration</b>\n          </td>\n        </tr>\n        <tr>\n          <td> </td>\n          <td>8-Apr 2013 --&gt; 30-May 2013</td>\n          <td>20</td>\n          <td>100 mcg</td>\n          <td>40 days</td>\n        </tr>\n      </table>\n    </div>")	
		XCTAssertEqual(inst!.text!.status!, "generated")
	}
	
	func testMedicationPrescription2() {
		let inst = instantiateFrom("medicationprescription-example-f002-crestor.json")
		XCTAssertNotNil(inst, "Must have instantiated a MedicationPrescription instance")
	
		XCTAssertEqual(inst!.dateWritten!, NSDate.dateFromISOString("2013-04-08")!)	
		XCTAssertEqual(inst!.dispense!.quantity!.code!, "46992007")
		XCTAssertEqual(inst!.dispense!.quantity!.system!, NSURL(string: "http://snomed.info/sct")!)
		XCTAssertEqual(inst!.dispense!.quantity!.value!, 90)
		XCTAssertEqual(inst!.dispense!.validityPeriod!.start!, NSDate.dateFromISOString("2013-04-08")!)	
		XCTAssertEqual(inst!.dosageInstruction![0].doseQuantity!.code!, "mg")
		XCTAssertEqual(inst!.dosageInstruction![0].doseQuantity!.system!, NSURL(string: "http://unitsofmeasure.org")!)	
		XCTAssertEqual(inst!.dosageInstruction![0].doseQuantity!.units!, "mg")
		XCTAssertEqual(inst!.dosageInstruction![0].doseQuantity!.value!, 10)	
		XCTAssertEqual(inst!.dosageInstruction![0].route!.coding![0].code!, "386359008")	
		XCTAssertEqual(inst!.dosageInstruction![0].route!.coding![0].display!, "Administration of drug or medicament via oral route")
		XCTAssertEqual(inst!.dosageInstruction![0].route!.coding![0].system!, NSURL(string: "http://snomed.info/sct")!)	
		XCTAssertEqual(inst!.dosageInstruction![0].site!.coding![0].code!, "181220002")	
		XCTAssertEqual(inst!.dosageInstruction![0].site!.coding![0].display!, "Entire oral cavity")
		XCTAssertEqual(inst!.dosageInstruction![0].site!.coding![0].system!, NSURL(string: "http://snomed.info/sct")!)
		XCTAssertEqual(inst!.dosageInstruction![0].timingSchedule!.event![0].start!, NSDate.dateFromISOString("2013-08-04")!)
		XCTAssertEqual(inst!.dosageInstruction![0].timingSchedule!.repeat!.duration!, 1)
		XCTAssertEqual(inst!.dosageInstruction![0].timingSchedule!.repeat!.frequency!, 1)	
		XCTAssertEqual(inst!.dosageInstruction![0].timingSchedule!.repeat!.units!, "d")	
		XCTAssertEqual(inst!.encounter!.display!, "encounter who leads to this priscription")	
		XCTAssertEqual(inst!.encounter!.reference!, "Encounter/f001")
		XCTAssertEqual(inst!.identifier![0].system!, NSURL(string: "http://www.bmc.nl/portal/prescriptions")!)	
		XCTAssertEqual(inst!.identifier![0].use!, "official")	
		XCTAssertEqual(inst!.identifier![0].value!, "order9837343")	
		XCTAssertEqual(inst!.medication!.display!, "prescribed medication")	
		XCTAssertEqual(inst!.medication!.reference!, "Medication/f002")	
		XCTAssertEqual(inst!.patient!.display!, "P. van den Heuvel")	
		XCTAssertEqual(inst!.patient!.reference!, "Patient/f001")	
		XCTAssertEqual(inst!.prescriber!.display!, "R.A. van den Berk")	
		XCTAssertEqual(inst!.prescriber!.reference!, "Practitioner/f006")	
		XCTAssertEqual(inst!.reasonCodeableConcept!.coding![0].code!, "28036006")	
		XCTAssertEqual(inst!.reasonCodeableConcept!.coding![0].display!, "High density lipoprotein cholesterol level")
		XCTAssertEqual(inst!.reasonCodeableConcept!.coding![0].system!, NSURL(string: "http://snomed.info/sct")!)	
		XCTAssertEqual(inst!.status!, "active")	
		XCTAssertEqual(inst!.text!.div!, "<div>\n      <p>\n        <b>Generated Narrative</b>\n      </p>\n      <p>\n        <b>identifier</b>: order9837343 (official)\n      </p>\n      <p>\n        <b>dateWritten</b>: 8-Apr 2013\n      </p>\n      <p>\n        <b>status</b>: active\n      </p>\n      <p>\n        <b>patient</b>: P. van den Heuvel\n      </p>\n      <p>\n        <b>prescriber</b>: R.A. van den Berk\n      </p>\n      <p>\n        <b>encounter</b>: encounter who leads to this priscription\n      </p>\n      <p>\n        <b>reason[x]</b>: \n        <span title=\"Codes: {http://snomed.info/sct 28036006}\">High density lipoprotein cholesterol level</span>\n      </p>\n      <p>\n        <b>medication</b>: prescribed medication\n      </p>\n      <h3>DosageInstructions</h3>\n      <table class=\"grid\">\n        <tr>\n          <td>\n            <b>Text</b>\n          </td>\n          <td>\n            <b>AdditionalInstructions</b>\n          </td>\n          <td>\n            <b>Timing[x]</b>\n          </td>\n          <td>\n            <b>AsNeeded[x]</b>\n          </td>\n          <td>\n            <b>Site</b>\n          </td>\n          <td>\n            <b>Route</b>\n          </td>\n          <td>\n            <b>Method</b>\n          </td>\n          <td>\n            <b>DoseQuantity</b>\n          </td>\n          <td>\n            <b>Rate</b>\n          </td>\n          <td>\n            <b>MaxDosePerPeriod</b>\n          </td>\n        </tr>\n        <tr>\n          <td> </td>\n          <td> </td>\n          <td>Starting 4-Aug 2013 --&gt; (ongoing), Once per 1 days</td>\n          <td> </td>\n          <td>\n            <span title=\"Codes: {http://snomed.info/sct 181220002}\">Entire oral cavity</span>\n          </td>\n          <td>\n            <span title=\"Codes: {http://snomed.info/sct 386359008}\">Administration of drug or medicament via oral route</span>\n          </td>\n          <td> </td>\n          <td>10 mg</td>\n          <td> </td>\n          <td> </td>\n        </tr>\n      </table>\n      <h3>Dispenses</h3>\n      <table class=\"grid\">\n        <tr>\n          <td>\n            <b>Medication</b>\n          </td>\n          <td>\n            <b>ValidityPeriod</b>\n          </td>\n          <td>\n            <b>NumberOfRepeatsAllowed</b>\n          </td>\n          <td>\n            <b>Quantity</b>\n          </td>\n          <td>\n            <b>ExpectedSupplyDuration</b>\n          </td>\n        </tr>\n        <tr>\n          <td> </td>\n          <td>8-Apr 2013 --&gt; (ongoing)</td>\n          <td> </td>\n          <td>90 46992007</td>\n          <td> </td>\n        </tr>\n      </table>\n    </div>")	
		XCTAssertEqual(inst!.text!.status!, "generated")
	}
	
	func testMedicationPrescription3() {
		let inst = instantiateFrom("medicationprescription-example-f003-tolbutamide.json")
		XCTAssertNotNil(inst, "Must have instantiated a MedicationPrescription instance")
	
		XCTAssertEqual(inst!.dateWritten!, NSDate.dateFromISOString("2011-05-01")!)	
		XCTAssertEqual(inst!.dispense!.quantity!.code!, "46992007")
		XCTAssertEqual(inst!.dispense!.quantity!.system!, NSURL(string: "http://snomed.info/sct")!)
		XCTAssertEqual(inst!.dispense!.quantity!.value!, 90)
		XCTAssertEqual(inst!.dispense!.validityPeriod!.start!, NSDate.dateFromISOString("2011-05-01")!)	
		XCTAssertEqual(inst!.dosageInstruction![0].doseQuantity!.code!, "mg")
		XCTAssertEqual(inst!.dosageInstruction![0].doseQuantity!.system!, NSURL(string: "http://unitsofmeasure.org")!)	
		XCTAssertEqual(inst!.dosageInstruction![0].doseQuantity!.units!, "mg")
		XCTAssertEqual(inst!.dosageInstruction![0].doseQuantity!.value!, 500)	
		XCTAssertEqual(inst!.dosageInstruction![0].route!.coding![0].code!, "386359008")	
		XCTAssertEqual(inst!.dosageInstruction![0].route!.coding![0].display!, "Administration of drug or medicament via oral route")
		XCTAssertEqual(inst!.dosageInstruction![0].route!.coding![0].system!, NSURL(string: "http://snomed.info/sct")!)	
		XCTAssertEqual(inst!.dosageInstruction![0].site!.coding![0].code!, "181220002")	
		XCTAssertEqual(inst!.dosageInstruction![0].site!.coding![0].display!, "Entire oral cavity")
		XCTAssertEqual(inst!.dosageInstruction![0].site!.coding![0].system!, NSURL(string: "http://snomed.info/sct")!)
		XCTAssertEqual(inst!.dosageInstruction![0].timingSchedule!.event![0].start!, NSDate.dateFromISOString("2011-05-01")!)
		XCTAssertEqual(inst!.dosageInstruction![0].timingSchedule!.repeat!.duration!, 1)
		XCTAssertEqual(inst!.dosageInstruction![0].timingSchedule!.repeat!.frequency!, 3)	
		XCTAssertEqual(inst!.dosageInstruction![0].timingSchedule!.repeat!.units!, "d")	
		XCTAssertEqual(inst!.encounter!.display!, "encounter who leads to this priscription")	
		XCTAssertEqual(inst!.encounter!.reference!, "Encounter/f002")
		XCTAssertEqual(inst!.identifier![0].system!, NSURL(string: "http://www.bmc.nl/portal/prescriptions")!)	
		XCTAssertEqual(inst!.identifier![0].use!, "official")	
		XCTAssertEqual(inst!.identifier![0].value!, "order9845343")	
		XCTAssertEqual(inst!.medication!.display!, "prescribed medication")	
		XCTAssertEqual(inst!.medication!.reference!, "Medication/f003")	
		XCTAssertEqual(inst!.patient!.display!, "P. van den Heuvel")	
		XCTAssertEqual(inst!.patient!.reference!, "Patient/f001")	
		XCTAssertEqual(inst!.prescriber!.display!, "S.M. Heps")	
		XCTAssertEqual(inst!.prescriber!.reference!, "Practitioner/f007")	
		XCTAssertEqual(inst!.reasonCodeableConcept!.coding![0].code!, "444780001")	
		XCTAssertEqual(inst!.reasonCodeableConcept!.coding![0].display!, "High glucose level in blood")
		XCTAssertEqual(inst!.reasonCodeableConcept!.coding![0].system!, NSURL(string: "http://snomed.info/sct")!)	
		XCTAssertEqual(inst!.status!, "active")	
		XCTAssertEqual(inst!.text!.div!, "<div>\n      <p>\n        <b>Generated Narrative</b>\n      </p>\n      <p>\n        <b>identifier</b>: order9845343 (official)\n      </p>\n      <p>\n        <b>dateWritten</b>: 1-May 2011\n      </p>\n      <p>\n        <b>status</b>: active\n      </p>\n      <p>\n        <b>patient</b>: P. van den Heuvel\n      </p>\n      <p>\n        <b>prescriber</b>: S.M. Heps\n      </p>\n      <p>\n        <b>encounter</b>: encounter who leads to this priscription\n      </p>\n      <p>\n        <b>reason[x]</b>: \n        <span title=\"Codes: {http://snomed.info/sct 444780001}\">High glucose level in blood</span>\n      </p>\n      <p>\n        <b>medication</b>: prescribed medication\n      </p>\n      <h3>DosageInstructions</h3>\n      <table class=\"grid\">\n        <tr>\n          <td>\n            <b>Text</b>\n          </td>\n          <td>\n            <b>AdditionalInstructions</b>\n          </td>\n          <td>\n            <b>Timing[x]</b>\n          </td>\n          <td>\n            <b>AsNeeded[x]</b>\n          </td>\n          <td>\n            <b>Site</b>\n          </td>\n          <td>\n            <b>Route</b>\n          </td>\n          <td>\n            <b>Method</b>\n          </td>\n          <td>\n            <b>DoseQuantity</b>\n          </td>\n          <td>\n            <b>Rate</b>\n          </td>\n          <td>\n            <b>MaxDosePerPeriod</b>\n          </td>\n        </tr>\n        <tr>\n          <td> </td>\n          <td> </td>\n          <td>Starting 1-May 2011 --&gt; (ongoing), 3 per 1 days</td>\n          <td> </td>\n          <td>\n            <span title=\"Codes: {http://snomed.info/sct 181220002}\">Entire oral cavity</span>\n          </td>\n          <td>\n            <span title=\"Codes: {http://snomed.info/sct 386359008}\">Administration of drug or medicament via oral route</span>\n          </td>\n          <td> </td>\n          <td>500 mg</td>\n          <td> </td>\n          <td> </td>\n        </tr>\n      </table>\n      <h3>Dispenses</h3>\n      <table class=\"grid\">\n        <tr>\n          <td>\n            <b>Medication</b>\n          </td>\n          <td>\n            <b>ValidityPeriod</b>\n          </td>\n          <td>\n            <b>NumberOfRepeatsAllowed</b>\n          </td>\n          <td>\n            <b>Quantity</b>\n          </td>\n          <td>\n            <b>ExpectedSupplyDuration</b>\n          </td>\n        </tr>\n        <tr>\n          <td> </td>\n          <td>1-May 2011 --&gt; (ongoing)</td>\n          <td> </td>\n          <td>90 46992007</td>\n          <td> </td>\n        </tr>\n      </table>\n    </div>")	
		XCTAssertEqual(inst!.text!.status!, "generated")
	}
	
	func testMedicationPrescription4() {
		let inst = instantiateFrom("medicationprescription-example-f004-metoprolol.json")
		XCTAssertNotNil(inst, "Must have instantiated a MedicationPrescription instance")
	
		XCTAssertEqual(inst!.dateWritten!, NSDate.dateFromISOString("2011-05-01")!)	
		XCTAssertEqual(inst!.dispense!.quantity!.code!, "46992007")
		XCTAssertEqual(inst!.dispense!.quantity!.system!, NSURL(string: "http://snomed.info/sct")!)
		XCTAssertEqual(inst!.dispense!.quantity!.value!, 90)
		XCTAssertEqual(inst!.dispense!.validityPeriod!.start!, NSDate.dateFromISOString("2011-05-01")!)	
		XCTAssertEqual(inst!.dosageInstruction![0].doseQuantity!.code!, "mg")
		XCTAssertEqual(inst!.dosageInstruction![0].doseQuantity!.system!, NSURL(string: "http://unitsofmeasure.org")!)	
		XCTAssertEqual(inst!.dosageInstruction![0].doseQuantity!.units!, "mg")
		XCTAssertEqual(inst!.dosageInstruction![0].doseQuantity!.value!, 50)	
		XCTAssertEqual(inst!.dosageInstruction![0].route!.coding![0].code!, "386359008")	
		XCTAssertEqual(inst!.dosageInstruction![0].route!.coding![0].display!, "Administration of drug or medicament via oral route")
		XCTAssertEqual(inst!.dosageInstruction![0].route!.coding![0].system!, NSURL(string: "http://snomed.info/sct")!)	
		XCTAssertEqual(inst!.dosageInstruction![0].site!.coding![0].code!, "181220002")	
		XCTAssertEqual(inst!.dosageInstruction![0].site!.coding![0].display!, "Entire oral cavity")
		XCTAssertEqual(inst!.dosageInstruction![0].site!.coding![0].system!, NSURL(string: "http://snomed.info/sct")!)
		XCTAssertEqual(inst!.dosageInstruction![0].timingSchedule!.event![0].start!, NSDate.dateFromISOString("2011-05-01")!)
		XCTAssertEqual(inst!.dosageInstruction![0].timingSchedule!.repeat!.duration!, 1)
		XCTAssertEqual(inst!.dosageInstruction![0].timingSchedule!.repeat!.frequency!, 1)	
		XCTAssertEqual(inst!.dosageInstruction![0].timingSchedule!.repeat!.units!, "d")	
		XCTAssertEqual(inst!.encounter!.display!, "encounter who leads to this priscription")	
		XCTAssertEqual(inst!.encounter!.reference!, "Encounter/f001")
		XCTAssertEqual(inst!.identifier![0].system!, NSURL(string: "http://www.bmc.nl/portal/prescriptions")!)	
		XCTAssertEqual(inst!.identifier![0].use!, "official")	
		XCTAssertEqual(inst!.identifier![0].value!, "order9845343")	
		XCTAssertEqual(inst!.medication!.display!, "prescribed medication")	
		XCTAssertEqual(inst!.medication!.reference!, "Medication/f004")	
		XCTAssertEqual(inst!.patient!.display!, "P. van den Heuvel")	
		XCTAssertEqual(inst!.patient!.reference!, "Patient/f001")	
		XCTAssertEqual(inst!.prescriber!.display!, "S.M. Heps")	
		XCTAssertEqual(inst!.prescriber!.reference!, "Practitioner/f007")	
		XCTAssertEqual(inst!.reasonCodeableConcept!.coding![0].code!, "38341003")	
		XCTAssertEqual(inst!.reasonCodeableConcept!.coding![0].display!, "High blood pressure")
		XCTAssertEqual(inst!.reasonCodeableConcept!.coding![0].system!, NSURL(string: "http://snomed.info/sct")!)	
		XCTAssertEqual(inst!.status!, "active")	
		XCTAssertEqual(inst!.text!.div!, "<div>\n      <p>\n        <b>Generated Narrative</b>\n      </p>\n      <p>\n        <b>identifier</b>: order9845343 (official)\n      </p>\n      <p>\n        <b>dateWritten</b>: 1-May 2011\n      </p>\n      <p>\n        <b>status</b>: active\n      </p>\n      <p>\n        <b>patient</b>: P. van den Heuvel\n      </p>\n      <p>\n        <b>prescriber</b>: S.M. Heps\n      </p>\n      <p>\n        <b>encounter</b>: encounter who leads to this priscription\n      </p>\n      <p>\n        <b>reason[x]</b>: \n        <span title=\"Codes: {http://snomed.info/sct 38341003}\">High blood pressure</span>\n      </p>\n      <p>\n        <b>medication</b>: prescribed medication\n      </p>\n      <h3>DosageInstructions</h3>\n      <table class=\"grid\">\n        <tr>\n          <td>\n            <b>Text</b>\n          </td>\n          <td>\n            <b>AdditionalInstructions</b>\n          </td>\n          <td>\n            <b>Timing[x]</b>\n          </td>\n          <td>\n            <b>AsNeeded[x]</b>\n          </td>\n          <td>\n            <b>Site</b>\n          </td>\n          <td>\n            <b>Route</b>\n          </td>\n          <td>\n            <b>Method</b>\n          </td>\n          <td>\n            <b>DoseQuantity</b>\n          </td>\n          <td>\n            <b>Rate</b>\n          </td>\n          <td>\n            <b>MaxDosePerPeriod</b>\n          </td>\n        </tr>\n        <tr>\n          <td> </td>\n          <td> </td>\n          <td>Starting 1-May 2011 --&gt; (ongoing), Once per 1 days</td>\n          <td> </td>\n          <td>\n            <span title=\"Codes: {http://snomed.info/sct 181220002}\">Entire oral cavity</span>\n          </td>\n          <td>\n            <span title=\"Codes: {http://snomed.info/sct 386359008}\">Administration of drug or medicament via oral route</span>\n          </td>\n          <td> </td>\n          <td>50 mg</td>\n          <td> </td>\n          <td> </td>\n        </tr>\n      </table>\n      <h3>Dispenses</h3>\n      <table class=\"grid\">\n        <tr>\n          <td>\n            <b>Medication</b>\n          </td>\n          <td>\n            <b>ValidityPeriod</b>\n          </td>\n          <td>\n            <b>NumberOfRepeatsAllowed</b>\n          </td>\n          <td>\n            <b>Quantity</b>\n          </td>\n          <td>\n            <b>ExpectedSupplyDuration</b>\n          </td>\n        </tr>\n        <tr>\n          <td> </td>\n          <td>1-May 2011 --&gt; (ongoing)</td>\n          <td> </td>\n          <td>90 46992007</td>\n          <td> </td>\n        </tr>\n      </table>\n    </div>")	
		XCTAssertEqual(inst!.text!.status!, "generated")
	}
	
	func testMedicationPrescription5() {
		let inst = instantiateFrom("medicationprescription-example-f005-enalapril.json")
		XCTAssertNotNil(inst, "Must have instantiated a MedicationPrescription instance")
	
		XCTAssertEqual(inst!.dateWritten!, NSDate.dateFromISOString("2011-05-01")!)	
		XCTAssertEqual(inst!.dispense!.quantity!.code!, "46992007")
		XCTAssertEqual(inst!.dispense!.quantity!.system!, NSURL(string: "http://snomed.info/sct")!)
		XCTAssertEqual(inst!.dispense!.quantity!.value!, 28)
		XCTAssertEqual(inst!.dispense!.validityPeriod!.start!, NSDate.dateFromISOString("2011-05-01")!)	
		XCTAssertEqual(inst!.dosageInstruction![0].doseQuantity!.code!, "mg")
		XCTAssertEqual(inst!.dosageInstruction![0].doseQuantity!.system!, NSURL(string: "http://unitsofmeasure.org")!)	
		XCTAssertEqual(inst!.dosageInstruction![0].doseQuantity!.units!, "mg")
		XCTAssertEqual(inst!.dosageInstruction![0].doseQuantity!.value!, 5)	
		XCTAssertEqual(inst!.dosageInstruction![0].route!.coding![0].code!, "386359008")	
		XCTAssertEqual(inst!.dosageInstruction![0].route!.coding![0].display!, "Administration of drug or medicament via oral route")
		XCTAssertEqual(inst!.dosageInstruction![0].route!.coding![0].system!, NSURL(string: "http://snomed.info/sct")!)	
		XCTAssertEqual(inst!.dosageInstruction![0].site!.coding![0].code!, "181220002")	
		XCTAssertEqual(inst!.dosageInstruction![0].site!.coding![0].display!, "Entire oral cavity")
		XCTAssertEqual(inst!.dosageInstruction![0].site!.coding![0].system!, NSURL(string: "http://snomed.info/sct")!)
		XCTAssertEqual(inst!.dosageInstruction![0].timingSchedule!.event![0].start!, NSDate.dateFromISOString("2011-05-01")!)
		XCTAssertEqual(inst!.dosageInstruction![0].timingSchedule!.repeat!.duration!, 1)
		XCTAssertEqual(inst!.dosageInstruction![0].timingSchedule!.repeat!.frequency!, 1)	
		XCTAssertEqual(inst!.dosageInstruction![0].timingSchedule!.repeat!.units!, "d")	
		XCTAssertEqual(inst!.encounter!.display!, "encounter who leads to this priscription")	
		XCTAssertEqual(inst!.encounter!.reference!, "Encounter/f001")
		XCTAssertEqual(inst!.identifier![0].system!, NSURL(string: "http://www.bmc.nl/portal/prescriptions")!)	
		XCTAssertEqual(inst!.identifier![0].use!, "official")	
		XCTAssertEqual(inst!.identifier![0].value!, "order9823343")	
		XCTAssertEqual(inst!.medication!.display!, "prescribed medication")	
		XCTAssertEqual(inst!.medication!.reference!, "Medication/f005")	
		XCTAssertEqual(inst!.patient!.display!, "P. van den Heuvel")	
		XCTAssertEqual(inst!.patient!.reference!, "Patient/f001")	
		XCTAssertEqual(inst!.prescriber!.display!, "S.M. Heps")	
		XCTAssertEqual(inst!.prescriber!.reference!, "Practitioner/f007")	
		XCTAssertEqual(inst!.reasonCodeableConcept!.coding![0].code!, "38341003")	
		XCTAssertEqual(inst!.reasonCodeableConcept!.coding![0].display!, "High blood pressure")
		XCTAssertEqual(inst!.reasonCodeableConcept!.coding![0].system!, NSURL(string: "http://snomed.info/sct")!)	
		XCTAssertEqual(inst!.status!, "active")	
		XCTAssertEqual(inst!.text!.div!, "<div>\n      <p>\n        <b>Generated Narrative</b>\n      </p>\n      <p>\n        <b>identifier</b>: order9823343 (official)\n      </p>\n      <p>\n        <b>dateWritten</b>: 1-May 2011\n      </p>\n      <p>\n        <b>status</b>: active\n      </p>\n      <p>\n        <b>patient</b>: P. van den Heuvel\n      </p>\n      <p>\n        <b>prescriber</b>: S.M. Heps\n      </p>\n      <p>\n        <b>encounter</b>: encounter who leads to this priscription\n      </p>\n      <p>\n        <b>reason[x]</b>: \n        <span title=\"Codes: {http://snomed.info/sct 38341003}\">High blood pressure</span>\n      </p>\n      <p>\n        <b>medication</b>: prescribed medication\n      </p>\n      <h3>DosageInstructions</h3>\n      <table class=\"grid\">\n        <tr>\n          <td>\n            <b>Text</b>\n          </td>\n          <td>\n            <b>AdditionalInstructions</b>\n          </td>\n          <td>\n            <b>Timing[x]</b>\n          </td>\n          <td>\n            <b>AsNeeded[x]</b>\n          </td>\n          <td>\n            <b>Site</b>\n          </td>\n          <td>\n            <b>Route</b>\n          </td>\n          <td>\n            <b>Method</b>\n          </td>\n          <td>\n            <b>DoseQuantity</b>\n          </td>\n          <td>\n            <b>Rate</b>\n          </td>\n          <td>\n            <b>MaxDosePerPeriod</b>\n          </td>\n        </tr>\n        <tr>\n          <td> </td>\n          <td> </td>\n          <td>Starting 1-May 2011 --&gt; (ongoing), Once per 1 days</td>\n          <td> </td>\n          <td>\n            <span title=\"Codes: {http://snomed.info/sct 181220002}\">Entire oral cavity</span>\n          </td>\n          <td>\n            <span title=\"Codes: {http://snomed.info/sct 386359008}\">Administration of drug or medicament via oral route</span>\n          </td>\n          <td> </td>\n          <td>5 mg</td>\n          <td> </td>\n          <td> </td>\n        </tr>\n      </table>\n      <h3>Dispenses</h3>\n      <table class=\"grid\">\n        <tr>\n          <td>\n            <b>Medication</b>\n          </td>\n          <td>\n            <b>ValidityPeriod</b>\n          </td>\n          <td>\n            <b>NumberOfRepeatsAllowed</b>\n          </td>\n          <td>\n            <b>Quantity</b>\n          </td>\n          <td>\n            <b>ExpectedSupplyDuration</b>\n          </td>\n        </tr>\n        <tr>\n          <td> </td>\n          <td>1-May 2011 --&gt; (ongoing)</td>\n          <td> </td>\n          <td>28 46992007</td>\n          <td> </td>\n        </tr>\n      </table>\n    </div>")	
		XCTAssertEqual(inst!.text!.status!, "generated")
	}
	
	func testMedicationPrescription6() {
		let inst = instantiateFrom("medicationprescription-example-f201-salmeterol.json")
		XCTAssertNotNil(inst, "Must have instantiated a MedicationPrescription instance")
	
		XCTAssertEqual(inst!.dateWritten!, NSDate.dateFromISOString("2013-03-11")!)	
		XCTAssertEqual(inst!.dosageInstruction![0].doseQuantity!.code!, "PUFF")
		XCTAssertEqual(inst!.dosageInstruction![0].doseQuantity!.system!, NSURL(string: "http://hl7.org/fhir/v3/orderableDrugForm")!)
		XCTAssertEqual(inst!.dosageInstruction![0].doseQuantity!.value!, 1)	
		XCTAssertEqual(inst!.dosageInstruction![0].maxDosePerPeriod!.denominator!.code!, "259032004")
		XCTAssertEqual(inst!.dosageInstruction![0].maxDosePerPeriod!.denominator!.system!, NSURL(string: "http://snomed.info/sct")!)	
		XCTAssertEqual(inst!.dosageInstruction![0].maxDosePerPeriod!.denominator!.units!, "daily")
		XCTAssertEqual(inst!.dosageInstruction![0].maxDosePerPeriod!.denominator!.value!, 1)	
		XCTAssertEqual(inst!.dosageInstruction![0].maxDosePerPeriod!.numerator!.code!, "415215001")
		XCTAssertEqual(inst!.dosageInstruction![0].maxDosePerPeriod!.numerator!.system!, NSURL(string: "http://snomed.info/sct")!)	
		XCTAssertEqual(inst!.dosageInstruction![0].maxDosePerPeriod!.numerator!.units!, "puffs")
		XCTAssertEqual(inst!.dosageInstruction![0].maxDosePerPeriod!.numerator!.value!, 2)	
		XCTAssertEqual(inst!.dosageInstruction![0].method!.coding![0].code!, "320276009")	
		XCTAssertEqual(inst!.dosageInstruction![0].method!.coding![0].display!, "Salmeterol+fluticasone 25/250ug inhaler")
		XCTAssertEqual(inst!.dosageInstruction![0].method!.coding![0].system!, NSURL(string: "http://snomed.info/sct")!)	
		XCTAssertEqual(inst!.dosageInstruction![0].route!.coding![0].code!, "321667001")	
		XCTAssertEqual(inst!.dosageInstruction![0].route!.coding![0].display!, "Respiratory tract")
		XCTAssertEqual(inst!.dosageInstruction![0].route!.coding![0].system!, NSURL(string: "http://snomed.info/sct")!)	
		XCTAssertEqual(inst!.dosageInstruction![0].site!.coding![0].code!, "74262004")	
		XCTAssertEqual(inst!.dosageInstruction![0].site!.coding![0].display!, "Oral cavity")
		XCTAssertEqual(inst!.dosageInstruction![0].site!.coding![0].system!, NSURL(string: "http://snomed.info/sct")!)	
		XCTAssertEqual(inst!.dosageInstruction![0].text!, "aerosol 25/250ug/do 120do 2x - 1 dose - daily")
		XCTAssertEqual(inst!.dosageInstruction![0].timingSchedule!.event![0].end!, NSDate.dateFromISOString("2013-05-11")!)
		XCTAssertEqual(inst!.dosageInstruction![0].timingSchedule!.event![0].start!, NSDate.dateFromISOString("2013-03-11")!)
		XCTAssertEqual(inst!.dosageInstruction![0].timingSchedule!.repeat!.duration!, 1)
		XCTAssertEqual(inst!.dosageInstruction![0].timingSchedule!.repeat!.frequency!, 2)	
		XCTAssertEqual(inst!.dosageInstruction![0].timingSchedule!.repeat!.units!, "d")	
		XCTAssertEqual(inst!.medication!.display!, "25ug Salmeterol + 250ug Fluticasone")	
		XCTAssertEqual(inst!.medication!.reference!, "Medication/f201")	
		XCTAssertEqual(inst!.patient!.display!, "Roel")	
		XCTAssertEqual(inst!.patient!.reference!, "Patient/f201")	
		XCTAssertEqual(inst!.prescriber!.display!, "Dokter Bonsig")	
		XCTAssertEqual(inst!.prescriber!.reference!, "Practitioner/f201")	
		XCTAssertEqual(inst!.reasonResource!.display!, "fever")	
		XCTAssertEqual(inst!.reasonResource!.reference!, "Condition/f201")	
		XCTAssertEqual(inst!.status!, "active")	
		XCTAssertEqual(inst!.text!.div!, "<div>\n      <p>\n        <b>Generated Narrative</b>\n      </p>\n      <p>\n        <b>dateWritten</b>: 11-Mar 2013\n      </p>\n      <p>\n        <b>status</b>: active\n      </p>\n      <p>\n        <b>patient</b>: Roel\n      </p>\n      <p>\n        <b>prescriber</b>: Dokter Bonsig\n      </p>\n      <p>\n        <b>reason[x]</b>: fever\n      </p>\n      <p>\n        <b>medication</b>: 25ug Salmeterol + 250ug Fluticasone\n      </p>\n      <h3>DosageInstructions</h3>\n      <table class=\"grid\">\n        <tr>\n          <td>\n            <b>Text</b>\n          </td>\n          <td>\n            <b>AdditionalInstructions</b>\n          </td>\n          <td>\n            <b>Timing[x]</b>\n          </td>\n          <td>\n            <b>AsNeeded[x]</b>\n          </td>\n          <td>\n            <b>Site</b>\n          </td>\n          <td>\n            <b>Route</b>\n          </td>\n          <td>\n            <b>Method</b>\n          </td>\n          <td>\n            <b>DoseQuantity</b>\n          </td>\n          <td>\n            <b>Rate</b>\n          </td>\n          <td>\n            <b>MaxDosePerPeriod</b>\n          </td>\n        </tr>\n        <tr>\n          <td>aerosol 25/250ug/do 120do 2x - 1 dose - daily</td>\n          <td> </td>\n          <td>Starting 11-Mar 2013 --&gt; 11-May 2013, 2 per 1 days</td>\n          <td> </td>\n          <td>\n            <span title=\"Codes: {http://snomed.info/sct 74262004}\">Oral cavity</span>\n          </td>\n          <td>\n            <span title=\"Codes: {http://snomed.info/sct 321667001}\">Respiratory tract</span>\n          </td>\n          <td>\n            <span title=\"Codes: {http://snomed.info/sct 320276009}\">Salmeterol+fluticasone 25/250ug inhaler</span>\n          </td>\n          <td>1 PUFF</td>\n          <td> </td>\n          <td>2 puffs/1 daily</td>\n        </tr>\n      </table>\n    </div>")	
		XCTAssertEqual(inst!.text!.status!, "generated")
	}
	
	func testMedicationPrescription7() {
		let inst = instantiateFrom("medicationprescription-example-f202-flucloxacilline.json")
		XCTAssertNotNil(inst, "Must have instantiated a MedicationPrescription instance")
	
		XCTAssertEqual(inst!.dateWritten!, NSDate.dateFromISOString("2013-03-11")!)	
		XCTAssertEqual(inst!.dosageInstruction![0].maxDosePerPeriod!.denominator!.code!, "258702006")
		XCTAssertEqual(inst!.dosageInstruction![0].maxDosePerPeriod!.denominator!.system!, NSURL(string: "http://snomed.info/sct")!)	
		XCTAssertEqual(inst!.dosageInstruction![0].maxDosePerPeriod!.denominator!.units!, "hours")
		XCTAssertEqual(inst!.dosageInstruction![0].maxDosePerPeriod!.denominator!.value!, 24)	
		XCTAssertEqual(inst!.dosageInstruction![0].maxDosePerPeriod!.numerator!.code!, "258682000")
		XCTAssertEqual(inst!.dosageInstruction![0].maxDosePerPeriod!.numerator!.system!, NSURL(string: "http://snomed.info/sct")!)	
		XCTAssertEqual(inst!.dosageInstruction![0].maxDosePerPeriod!.numerator!.units!, "gram")
		XCTAssertEqual(inst!.dosageInstruction![0].maxDosePerPeriod!.numerator!.value!, 12)	
		XCTAssertEqual(inst!.dosageInstruction![0].method!.coding![0].code!, "323493005")	
		XCTAssertEqual(inst!.dosageInstruction![0].method!.coding![0].display!, "Injected floxacillin")
		XCTAssertEqual(inst!.dosageInstruction![0].method!.coding![0].system!, NSURL(string: "http://snomed.info/sct")!)	
		XCTAssertEqual(inst!.dosageInstruction![0].route!.coding![0].code!, "47625008")	
		XCTAssertEqual(inst!.dosageInstruction![0].route!.coding![0].display!, "Intravenous route")
		XCTAssertEqual(inst!.dosageInstruction![0].route!.coding![0].system!, NSURL(string: "http://snomed.info/sct")!)	
		XCTAssertEqual(inst!.dosageInstruction![0].text!, "Flucloxacilline 12g/24h")
		XCTAssertEqual(inst!.dosageInstruction![0].timingSchedule!.event![0].end!, NSDate.dateFromISOString("2013-03-21")!)
		XCTAssertEqual(inst!.dosageInstruction![0].timingSchedule!.event![0].start!, NSDate.dateFromISOString("2013-03-11")!)	
		XCTAssertEqual(inst!.encounter!.display!, "Roel's encounter on March eleventh 2013")	
		XCTAssertEqual(inst!.encounter!.reference!, "Encounter/f203")	
		XCTAssertEqual(inst!.medication!.display!, "Flucloxacilline")	
		XCTAssertEqual(inst!.medication!.reference!, "Medication/f202")	
		XCTAssertEqual(inst!.patient!.display!, "Roel")	
		XCTAssertEqual(inst!.patient!.reference!, "Patient/f201")	
		XCTAssertEqual(inst!.prescriber!.reference!, "Practitioner/f201")	
		XCTAssertEqual(inst!.reasonResource!.display!, "sepsis")	
		XCTAssertEqual(inst!.reasonResource!.reference!, "Condition/f203")	
		XCTAssertEqual(inst!.status!, "completed")	
		XCTAssertEqual(inst!.text!.div!, "<div>\n      <p>\n        <b>Generated Narrative</b>\n      </p>\n      <p>\n        <b>dateWritten</b>: 11-Mar 2013\n      </p>\n      <p>\n        <b>status</b>: completed\n      </p>\n      <p>\n        <b>patient</b>: Roel\n      </p>\n      <p>\n        <b>prescriber</b>: \n        <a href=\"practitioner-example-f201-ab.html\">UZI-nummer = 12345678901 (official); Dokter Bronsig(official); Male; birthDate: 24-Dec 1956; Implementation of planned interventions; Medical oncologist</a>\n      </p>\n      <p>\n        <b>encounter</b>: Roel's encounter on March eleventh 2013\n      </p>\n      <p>\n        <b>reason[x]</b>: sepsis\n      </p>\n      <p>\n        <b>medication</b>: Flucloxacilline\n      </p>\n      <h3>DosageInstructions</h3>\n      <table class=\"grid\">\n        <tr>\n          <td>\n            <b>Text</b>\n          </td>\n          <td>\n            <b>AdditionalInstructions</b>\n          </td>\n          <td>\n            <b>Timing[x]</b>\n          </td>\n          <td>\n            <b>AsNeeded[x]</b>\n          </td>\n          <td>\n            <b>Site</b>\n          </td>\n          <td>\n            <b>Route</b>\n          </td>\n          <td>\n            <b>Method</b>\n          </td>\n          <td>\n            <b>DoseQuantity</b>\n          </td>\n          <td>\n            <b>Rate</b>\n          </td>\n          <td>\n            <b>MaxDosePerPeriod</b>\n          </td>\n        </tr>\n        <tr>\n          <td>Flucloxacilline 12g/24h</td>\n          <td> </td>\n          <td>11-Mar 2013 --&gt; 21-Mar 2013</td>\n          <td> </td>\n          <td> </td>\n          <td>\n            <span title=\"Codes: {http://snomed.info/sct 47625008}\">Intravenous route</span>\n          </td>\n          <td>\n            <span title=\"Codes: {http://snomed.info/sct 323493005}\">Injected floxacillin</span>\n          </td>\n          <td> </td>\n          <td> </td>\n          <td>12 gram/24 hours</td>\n        </tr>\n      </table>\n    </div>")	
		XCTAssertEqual(inst!.text!.status!, "generated")
	}
	
	func testMedicationPrescription8() {
		let inst = instantiateFrom("medicationprescription-example-f203-paracetamol.json")
		XCTAssertNotNil(inst, "Must have instantiated a MedicationPrescription instance")
	
		XCTAssertEqual(inst!.dateWritten!, NSDate.dateFromISOString("2013-04-04")!)	
		XCTAssertEqual(inst!.dosageInstruction![0].maxDosePerPeriod!.denominator!.code!, "258702006")
		XCTAssertEqual(inst!.dosageInstruction![0].maxDosePerPeriod!.denominator!.system!, NSURL(string: "http://snomed.info/sct")!)	
		XCTAssertEqual(inst!.dosageInstruction![0].maxDosePerPeriod!.denominator!.units!, "hours")
		XCTAssertEqual(inst!.dosageInstruction![0].maxDosePerPeriod!.denominator!.value!, 24)	
		XCTAssertEqual(inst!.dosageInstruction![0].maxDosePerPeriod!.numerator!.code!, "258684004")
		XCTAssertEqual(inst!.dosageInstruction![0].maxDosePerPeriod!.numerator!.system!, NSURL(string: "http://snomed.info/sct")!)	
		XCTAssertEqual(inst!.dosageInstruction![0].maxDosePerPeriod!.numerator!.units!, "milligram")
		XCTAssertEqual(inst!.dosageInstruction![0].maxDosePerPeriod!.numerator!.value!, 3000)	
		XCTAssertEqual(inst!.dosageInstruction![0].method!.coding![0].code!, "322236009")	
		XCTAssertEqual(inst!.dosageInstruction![0].method!.coding![0].display!, "Paracetamol 500mg tablet")
		XCTAssertEqual(inst!.dosageInstruction![0].method!.coding![0].system!, NSURL(string: "http://snomed.info/sct")!)	
		XCTAssertEqual(inst!.dosageInstruction![0].text!, "Paracetamol 3xdaags 1000mg")	
		XCTAssertEqual(inst!.encounter!.display!, "Roel's encounter on April fourth 2013")	
		XCTAssertEqual(inst!.encounter!.reference!, "Encounter/f201")	
		XCTAssertEqual(inst!.medication!.display!, "Paracetamol")	
		XCTAssertEqual(inst!.medication!.reference!, "Medication/f203")	
		XCTAssertEqual(inst!.patient!.display!, "Roel")	
		XCTAssertEqual(inst!.patient!.reference!, "Patient/f201")	
		XCTAssertEqual(inst!.prescriber!.reference!, "Practitioner/f201")	
		XCTAssertEqual(inst!.reasonResource!.display!, "fever")	
		XCTAssertEqual(inst!.reasonResource!.reference!, "Condition/f201")	
		XCTAssertEqual(inst!.status!, "active")	
		XCTAssertEqual(inst!.text!.div!, "<div>\n      <p>\n        <b>Generated Narrative</b>\n      </p>\n      <p>\n        <b>dateWritten</b>: 4-Apr 2013\n      </p>\n      <p>\n        <b>status</b>: active\n      </p>\n      <p>\n        <b>patient</b>: Roel\n      </p>\n      <p>\n        <b>prescriber</b>: \n        <a href=\"practitioner-example-f201-ab.html\">UZI-nummer = 12345678901 (official); Dokter Bronsig(official); Male; birthDate: 24-Dec 1956; Implementation of planned interventions; Medical oncologist</a>\n      </p>\n      <p>\n        <b>encounter</b>: Roel's encounter on April fourth 2013\n      </p>\n      <p>\n        <b>reason[x]</b>: fever\n      </p>\n      <p>\n        <b>medication</b>: Paracetamol\n      </p>\n      <h3>DosageInstructions</h3>\n      <table class=\"grid\">\n        <tr>\n          <td>\n            <b>Text</b>\n          </td>\n          <td>\n            <b>AdditionalInstructions</b>\n          </td>\n          <td>\n            <b>Timing[x]</b>\n          </td>\n          <td>\n            <b>AsNeeded[x]</b>\n          </td>\n          <td>\n            <b>Site</b>\n          </td>\n          <td>\n            <b>Route</b>\n          </td>\n          <td>\n            <b>Method</b>\n          </td>\n          <td>\n            <b>DoseQuantity</b>\n          </td>\n          <td>\n            <b>Rate</b>\n          </td>\n          <td>\n            <b>MaxDosePerPeriod</b>\n          </td>\n        </tr>\n        <tr>\n          <td>Paracetamol 3xdaags 1000mg</td>\n          <td> </td>\n          <td> </td>\n          <td> </td>\n          <td> </td>\n          <td> </td>\n          <td>\n            <span title=\"Codes: {http://snomed.info/sct 322236009}\">Paracetamol 500mg tablet</span>\n          </td>\n          <td> </td>\n          <td> </td>\n          <td>3000 milligram/24 hours</td>\n        </tr>\n      </table>\n    </div>")	
		XCTAssertEqual(inst!.text!.status!, "generated")
	}
}
