//
//  NutritionOrderTests.swift
//  NutritionOrderTests
//
//  Generated from FHIR 0.4.0.3903 on 2014-12-22.
//  2014, SMART Platforms.
//

import Cocoa
import XCTest
import SwiftFHIR


class NutritionOrderTests: FHIRModelTestCase
{
	func instantiateFrom(filename: String) -> NutritionOrder? {
		let json = readJSONFile(filename)
		let instance = NutritionOrder(json: json)
		XCTAssertNotNil(instance, "Must have instantiated a test instance")
		return instance
	}
	
	func testNutritionOrder1() {
		let inst = instantiateFrom("nutritionorder-enteralbolus-example.canonical.json")
		XCTAssertNotNil(inst, "Must have instantiated a NutritionOrder instance")
	
		XCTAssertEqual(inst!.allergyIntolerance![0].display!, "Cashew Nuts")
		XCTAssertEqual(inst!.allergyIntolerance![0].reference!, "AllergyIntolerance/example")
		XCTAssertEqual(inst!.dateTime!, NSDate.dateFromISOString("2014-09-17")!)
		XCTAssertEqual(inst!.encounter!.display!, "Inpatient")
		XCTAssertEqual(inst!.encounter!.reference!, "Encounter/example")
		XCTAssertEqual(inst!.excludeFoodModifier![0].coding![0].code!, "227493005")
		XCTAssertEqual(inst!.excludeFoodModifier![0].coding![0].display!, "Cashew Nut")
		XCTAssertEqual(inst!.excludeFoodModifier![0].coding![0].system!, NSURL(string: "http://snomed.info/sct")!)
		XCTAssertEqual(inst!.excludeFoodModifier![0].coding![0].version!, "20140730")
		XCTAssertEqual(inst!.foodPreferenceModifier![0].coding![0].code!, "dairy-free")
		XCTAssertEqual(inst!.foodPreferenceModifier![0].coding![0].system!, NSURL(string: "http://hl7.org/fhir/diet")!)
		XCTAssertEqual(inst!.foodPreferenceModifier![0].coding![0].valueSet!.display!, "PatientDiet")
		XCTAssertEqual(inst!.foodPreferenceModifier![0].coding![0].valueSet!.reference!, "http://hl7.org/fhir/vs/encounter-diet")
		XCTAssertEqual(inst!.identifier![0].system!, NSURL(string: "http://www.acme.org/nutritionorders")!)
		XCTAssertEqual(inst!.identifier![0].value!, "123")
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveName!, "Acme Additive")
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveType!.coding![0].code!, "427298002")
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveType!.coding![0].display!, "Enteral dietary supplement")
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveType!.coding![0].system!, NSURL(string: "http://snomed.info/sct")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveType!.coding![0].valueSet!.display!, "EnteralFormulaAdditiveType")
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveType!.coding![0].valueSet!.reference!, "http://hl7.org/fhir/vs/entformula-additive")
		XCTAssertEqual(inst!.item![0].enteralFormula!.baseFormulaName!, "Acme High Protein Formula")
		XCTAssertEqual(inst!.item![0].enteralFormula!.baseFormulaType!.coding![0].code!, "659311000124118")
		XCTAssertEqual(inst!.item![0].enteralFormula!.baseFormulaType!.coding![0].display!, "Adult high protein formula")
		XCTAssertEqual(inst!.item![0].enteralFormula!.baseFormulaType!.coding![0].system!, NSURL(string: "http://usextension/snomed.info/sct")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.caloricDensity!.code!, "cal/mL")
		XCTAssertEqual(inst!.item![0].enteralFormula!.caloricDensity!.system!, NSURL(string: "http://unitsofmeasure.org")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.caloricDensity!.units!, "calories per milliliter")
		XCTAssertEqual(inst!.item![0].enteralFormula!.caloricDensity!.value!, NSDecimalNumber(string: "1.5"))
		XCTAssertEqual(inst!.item![0].enteralFormula!.maxVolumeToDeliver!.code!, "mL")
		XCTAssertEqual(inst!.item![0].enteralFormula!.maxVolumeToDeliver!.system!, NSURL(string: "http://unitsofmeasure.org")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.maxVolumeToDeliver!.units!, "milliliter")
		XCTAssertEqual(inst!.item![0].enteralFormula!.maxVolumeToDeliver!.value!, NSDecimalNumber(string: "1440"))
		XCTAssertEqual(inst!.item![0].enteralFormula!.quantity!.code!, "mL")
		XCTAssertEqual(inst!.item![0].enteralFormula!.quantity!.system!, NSURL(string: "http://unitsofmeasure.org")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.quantity!.units!, "milliliters")
		XCTAssertEqual(inst!.item![0].enteralFormula!.quantity!.value!, NSDecimalNumber(string: "240"))
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.denominator!.code!, "h")
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.denominator!.system!, NSURL(string: "http://unitsofmeasure.org")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.denominator!.units!, "hr")
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.denominator!.value!, NSDecimalNumber(string: "4"))
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.numerator!.code!, "mL")
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.numerator!.system!, NSURL(string: "http://unitsofmeasure.org")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.numerator!.units!, "milliliters")
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.numerator!.value!, NSDecimalNumber(string: "240"))
		XCTAssertEqual(inst!.item![0].enteralFormula!.routeofAdministration!.coding![0].code!, "GT")
		XCTAssertEqual(inst!.item![0].enteralFormula!.routeofAdministration!.coding![0].display!, "Instillation, gastrostomy tube")
		XCTAssertEqual(inst!.item![0].enteralFormula!.routeofAdministration!.coding![0].system!, NSURL(string: "http://hl7.org/fhir/v3/RouteOfAdministration")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.routeofAdministration!.coding![0].valueSet!.display!, "EnteralRouteOfAdministration")
		XCTAssertEqual(inst!.item![0].enteralFormula!.routeofAdministration!.coding![0].valueSet!.reference!, "http://hl7.org/fhir/vs/enteral-route")
		XCTAssertTrue(inst!.item![0].isInEffect!)
		XCTAssertEqual(inst!.item![0].scheduledPeriod!.start!, NSDate.dateFromISOString("2014-09-17")!)
		XCTAssertEqual(inst!.orderer!.display!, "Dr Adam Careful")
		XCTAssertEqual(inst!.orderer!.reference!, "Practitioner/example")
		XCTAssertEqual(inst!.status!, "active")
		XCTAssertEqual(inst!.subject!.display!, "Peter Chalmers")
		XCTAssertEqual(inst!.subject!.reference!, "Patient/example")
	}
	
	func testNutritionOrder2() {
		let inst = instantiateFrom("nutritionorder-enteralbolus-example.canonical.json")
		XCTAssertNotNil(inst, "Must have instantiated a NutritionOrder instance")
	
		XCTAssertEqual(inst!.allergyIntolerance![0].display!, "Cashew Nuts")
		XCTAssertEqual(inst!.allergyIntolerance![0].reference!, "AllergyIntolerance/example")
		XCTAssertEqual(inst!.dateTime!, NSDate.dateFromISOString("2014-09-17")!)
		XCTAssertEqual(inst!.encounter!.display!, "Inpatient")
		XCTAssertEqual(inst!.encounter!.reference!, "Encounter/example")
		XCTAssertEqual(inst!.excludeFoodModifier![0].coding![0].code!, "227493005")
		XCTAssertEqual(inst!.excludeFoodModifier![0].coding![0].display!, "Cashew Nut")
		XCTAssertEqual(inst!.excludeFoodModifier![0].coding![0].system!, NSURL(string: "http://snomed.info/sct")!)
		XCTAssertEqual(inst!.excludeFoodModifier![0].coding![0].version!, "20140730")
		XCTAssertEqual(inst!.foodPreferenceModifier![0].coding![0].code!, "dairy-free")
		XCTAssertEqual(inst!.foodPreferenceModifier![0].coding![0].system!, NSURL(string: "http://hl7.org/fhir/diet")!)
		XCTAssertEqual(inst!.foodPreferenceModifier![0].coding![0].valueSet!.display!, "PatientDiet")
		XCTAssertEqual(inst!.foodPreferenceModifier![0].coding![0].valueSet!.reference!, "http://hl7.org/fhir/vs/encounter-diet")
		XCTAssertEqual(inst!.identifier![0].system!, NSURL(string: "http://www.acme.org/nutritionorders")!)
		XCTAssertEqual(inst!.identifier![0].value!, "123")
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveName!, "Acme Additive")
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveType!.coding![0].code!, "427298002")
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveType!.coding![0].display!, "Enteral dietary supplement")
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveType!.coding![0].system!, NSURL(string: "http://snomed.info/sct")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveType!.coding![0].valueSet!.display!, "EnteralFormulaAdditiveType")
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveType!.coding![0].valueSet!.reference!, "http://hl7.org/fhir/vs/entformula-additive")
		XCTAssertEqual(inst!.item![0].enteralFormula!.baseFormulaName!, "Acme High Protein Formula")
		XCTAssertEqual(inst!.item![0].enteralFormula!.baseFormulaType!.coding![0].code!, "659311000124118")
		XCTAssertEqual(inst!.item![0].enteralFormula!.baseFormulaType!.coding![0].display!, "Adult high protein formula")
		XCTAssertEqual(inst!.item![0].enteralFormula!.baseFormulaType!.coding![0].system!, NSURL(string: "http://usextension/snomed.info/sct")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.caloricDensity!.code!, "cal/mL")
		XCTAssertEqual(inst!.item![0].enteralFormula!.caloricDensity!.system!, NSURL(string: "http://unitsofmeasure.org")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.caloricDensity!.units!, "calories per milliliter")
		XCTAssertEqual(inst!.item![0].enteralFormula!.caloricDensity!.value!, NSDecimalNumber(string: "1.5"))
		XCTAssertEqual(inst!.item![0].enteralFormula!.maxVolumeToDeliver!.code!, "mL")
		XCTAssertEqual(inst!.item![0].enteralFormula!.maxVolumeToDeliver!.system!, NSURL(string: "http://unitsofmeasure.org")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.maxVolumeToDeliver!.units!, "milliliter")
		XCTAssertEqual(inst!.item![0].enteralFormula!.maxVolumeToDeliver!.value!, NSDecimalNumber(string: "1440"))
		XCTAssertEqual(inst!.item![0].enteralFormula!.quantity!.code!, "mL")
		XCTAssertEqual(inst!.item![0].enteralFormula!.quantity!.system!, NSURL(string: "http://unitsofmeasure.org")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.quantity!.units!, "milliliters")
		XCTAssertEqual(inst!.item![0].enteralFormula!.quantity!.value!, NSDecimalNumber(string: "240"))
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.denominator!.code!, "h")
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.denominator!.system!, NSURL(string: "http://unitsofmeasure.org")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.denominator!.units!, "hr")
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.denominator!.value!, NSDecimalNumber(string: "4"))
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.numerator!.code!, "mL")
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.numerator!.system!, NSURL(string: "http://unitsofmeasure.org")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.numerator!.units!, "milliliters")
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.numerator!.value!, NSDecimalNumber(string: "240"))
		XCTAssertEqual(inst!.item![0].enteralFormula!.routeofAdministration!.coding![0].code!, "GT")
		XCTAssertEqual(inst!.item![0].enteralFormula!.routeofAdministration!.coding![0].display!, "Instillation, gastrostomy tube")
		XCTAssertEqual(inst!.item![0].enteralFormula!.routeofAdministration!.coding![0].system!, NSURL(string: "http://hl7.org/fhir/v3/RouteOfAdministration")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.routeofAdministration!.coding![0].valueSet!.display!, "EnteralRouteOfAdministration")
		XCTAssertEqual(inst!.item![0].enteralFormula!.routeofAdministration!.coding![0].valueSet!.reference!, "http://hl7.org/fhir/vs/enteral-route")
		XCTAssertTrue(inst!.item![0].isInEffect!)
		XCTAssertEqual(inst!.item![0].scheduledPeriod!.start!, NSDate.dateFromISOString("2014-09-17")!)
		XCTAssertEqual(inst!.orderer!.display!, "Dr Adam Careful")
		XCTAssertEqual(inst!.orderer!.reference!, "Practitioner/example")
		XCTAssertEqual(inst!.status!, "active")
		XCTAssertEqual(inst!.subject!.display!, "Peter Chalmers")
		XCTAssertEqual(inst!.subject!.reference!, "Patient/example")
	}
	
	func testNutritionOrder3() {
		let inst = instantiateFrom("nutritionorder-enteralbolus-example.json")
		XCTAssertNotNil(inst, "Must have instantiated a NutritionOrder instance")
	
		XCTAssertEqual(inst!.allergyIntolerance![0].display!, "Cashew Nuts")
		XCTAssertEqual(inst!.allergyIntolerance![0].reference!, "AllergyIntolerance/example")
		XCTAssertEqual(inst!.dateTime!, NSDate.dateFromISOString("2014-09-17")!)
		XCTAssertEqual(inst!.encounter!.display!, "Inpatient")
		XCTAssertEqual(inst!.encounter!.reference!, "Encounter/example")
		XCTAssertEqual(inst!.excludeFoodModifier![0].coding![0].code!, "227493005")
		XCTAssertEqual(inst!.excludeFoodModifier![0].coding![0].display!, "Cashew Nut")
		XCTAssertEqual(inst!.excludeFoodModifier![0].coding![0].system!, NSURL(string: "http://snomed.info/sct")!)
		XCTAssertEqual(inst!.excludeFoodModifier![0].coding![0].version!, "20140730")
		XCTAssertEqual(inst!.foodPreferenceModifier![0].coding![0].code!, "dairy-free")
		XCTAssertEqual(inst!.foodPreferenceModifier![0].coding![0].system!, NSURL(string: "http://hl7.org/fhir/diet")!)
		XCTAssertEqual(inst!.foodPreferenceModifier![0].coding![0].valueSet!.display!, "PatientDiet")
		XCTAssertEqual(inst!.foodPreferenceModifier![0].coding![0].valueSet!.reference!, "http://hl7.org/fhir/vs/encounter-diet")
		XCTAssertEqual(inst!.identifier![0].system!, NSURL(string: "http://www.acme.org/nutritionorders")!)
		XCTAssertEqual(inst!.identifier![0].value!, "123")
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveName!, "Acme Additive")
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveType!.coding![0].code!, "427298002")
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveType!.coding![0].display!, "Enteral dietary supplement")
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveType!.coding![0].system!, NSURL(string: "http://snomed.info/sct")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveType!.coding![0].valueSet!.display!, "EnteralFormulaAdditiveType")
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveType!.coding![0].valueSet!.reference!, "http://hl7.org/fhir/vs/entformula-additive")
		XCTAssertEqual(inst!.item![0].enteralFormula!.baseFormulaName!, "Acme High Protein Formula")
		XCTAssertEqual(inst!.item![0].enteralFormula!.baseFormulaType!.coding![0].code!, "659311000124118")
		XCTAssertEqual(inst!.item![0].enteralFormula!.baseFormulaType!.coding![0].display!, "Adult high protein formula")
		XCTAssertEqual(inst!.item![0].enteralFormula!.baseFormulaType!.coding![0].system!, NSURL(string: "http://usextension/snomed.info/sct")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.caloricDensity!.code!, "cal/mL")
		XCTAssertEqual(inst!.item![0].enteralFormula!.caloricDensity!.system!, NSURL(string: "http://unitsofmeasure.org")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.caloricDensity!.units!, "calories per milliliter")
		XCTAssertEqual(inst!.item![0].enteralFormula!.caloricDensity!.value!, NSDecimalNumber(string: "1.5"))
		XCTAssertEqual(inst!.item![0].enteralFormula!.maxVolumeToDeliver!.code!, "mL")
		XCTAssertEqual(inst!.item![0].enteralFormula!.maxVolumeToDeliver!.system!, NSURL(string: "http://unitsofmeasure.org")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.maxVolumeToDeliver!.units!, "milliliter")
		XCTAssertEqual(inst!.item![0].enteralFormula!.maxVolumeToDeliver!.value!, NSDecimalNumber(string: "1440"))
		XCTAssertEqual(inst!.item![0].enteralFormula!.quantity!.code!, "mL")
		XCTAssertEqual(inst!.item![0].enteralFormula!.quantity!.system!, NSURL(string: "http://unitsofmeasure.org")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.quantity!.units!, "milliliters")
		XCTAssertEqual(inst!.item![0].enteralFormula!.quantity!.value!, NSDecimalNumber(string: "240"))
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.denominator!.code!, "h")
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.denominator!.system!, NSURL(string: "http://unitsofmeasure.org")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.denominator!.units!, "hr")
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.denominator!.value!, NSDecimalNumber(string: "4"))
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.numerator!.code!, "mL")
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.numerator!.system!, NSURL(string: "http://unitsofmeasure.org")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.numerator!.units!, "milliliters")
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.numerator!.value!, NSDecimalNumber(string: "240"))
		XCTAssertEqual(inst!.item![0].enteralFormula!.routeofAdministration!.coding![0].code!, "GT")
		XCTAssertEqual(inst!.item![0].enteralFormula!.routeofAdministration!.coding![0].display!, "Instillation, gastrostomy tube")
		XCTAssertEqual(inst!.item![0].enteralFormula!.routeofAdministration!.coding![0].system!, NSURL(string: "http://hl7.org/fhir/v3/RouteOfAdministration")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.routeofAdministration!.coding![0].valueSet!.display!, "EnteralRouteOfAdministration")
		XCTAssertEqual(inst!.item![0].enteralFormula!.routeofAdministration!.coding![0].valueSet!.reference!, "http://hl7.org/fhir/vs/enteral-route")
		XCTAssertTrue(inst!.item![0].isInEffect!)
		XCTAssertEqual(inst!.item![0].scheduledPeriod!.start!, NSDate.dateFromISOString("2014-09-17")!)
		XCTAssertEqual(inst!.orderer!.display!, "Dr Adam Careful")
		XCTAssertEqual(inst!.orderer!.reference!, "Practitioner/example")
		XCTAssertEqual(inst!.status!, "active")
		XCTAssertEqual(inst!.subject!.display!, "Peter Chalmers")
		XCTAssertEqual(inst!.subject!.reference!, "Patient/example")
	}
	
	func testNutritionOrder4() {
		let inst = instantiateFrom("nutritionorder-enteralcontinuous-example.canonical.json")
		XCTAssertNotNil(inst, "Must have instantiated a NutritionOrder instance")
	
		XCTAssertEqual(inst!.allergyIntolerance![0].display!, "Cashew Nuts")
		XCTAssertEqual(inst!.allergyIntolerance![0].reference!, "AllergyIntolerance/example")
		XCTAssertEqual(inst!.dateTime!, NSDate.dateFromISOString("2014-09-17")!)
		XCTAssertEqual(inst!.encounter!.display!, "Inpatient")
		XCTAssertEqual(inst!.encounter!.reference!, "Encounter/example")
		XCTAssertEqual(inst!.excludeFoodModifier![0].coding![0].code!, "227493005")
		XCTAssertEqual(inst!.excludeFoodModifier![0].coding![0].display!, "Cashew Nut")
		XCTAssertEqual(inst!.excludeFoodModifier![0].coding![0].system!, NSURL(string: "http://snomed.info/sct")!)
		XCTAssertEqual(inst!.excludeFoodModifier![0].coding![0].version!, "20140730")
		XCTAssertEqual(inst!.foodPreferenceModifier![0].coding![0].code!, "dairy-free")
		XCTAssertEqual(inst!.foodPreferenceModifier![0].coding![0].system!, NSURL(string: "http://hl7.org/fhir/diet")!)
		XCTAssertEqual(inst!.foodPreferenceModifier![0].coding![0].valueSet!.display!, "PatientDiet")
		XCTAssertEqual(inst!.foodPreferenceModifier![0].coding![0].valueSet!.reference!, "http://hl7.org/fhir/vs/encounter-diet")
		XCTAssertEqual(inst!.identifier![0].system!, NSURL(string: "http://www.acme.org/nutritionorders")!)
		XCTAssertEqual(inst!.identifier![0].value!, "123")
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveName!, "Acme MCT Oil")
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveType!.coding![0].code!, "427298002")
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveType!.coding![0].display!, "Enteral dietary supplement")
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveType!.coding![0].system!, NSURL(string: "http://snomed.info/sct")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveType!.coding![0].valueSet!.display!, "Medium chain triglyceride supplementation")
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveType!.coding![0].valueSet!.reference!, "http://hl7.org/fhir/vs/entformula-additive")
		XCTAssertEqual(inst!.item![0].enteralFormula!.administrationInstructions!, "Hold feedings from 7 pm to 7 am. Add MCT oil to increase calories from 1.0 cal/mL to 1.5 cal/mL")
		XCTAssertEqual(inst!.item![0].enteralFormula!.baseFormulaName!, " Acme Diabetes Formula")
		XCTAssertEqual(inst!.item![0].enteralFormula!.baseFormulaType!.coding![0].code!, "6547210000124112")
		XCTAssertEqual(inst!.item![0].enteralFormula!.baseFormulaType!.coding![0].display!, "Diabetic specialty enteral formula")
		XCTAssertEqual(inst!.item![0].enteralFormula!.baseFormulaType!.coding![0].system!, NSURL(string: "http://snomed-us.info/sct")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.caloricDensity!.code!, "cal/mL")
		XCTAssertEqual(inst!.item![0].enteralFormula!.caloricDensity!.system!, NSURL(string: "http://unitsofmeasure.org")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.caloricDensity!.units!, "calories per milliliter")
		XCTAssertEqual(inst!.item![0].enteralFormula!.caloricDensity!.value!, NSDecimalNumber(string: "1"))
		XCTAssertEqual(inst!.item![0].enteralFormula!.maxVolumeToDeliver!.code!, "mL")
		XCTAssertEqual(inst!.item![0].enteralFormula!.maxVolumeToDeliver!.system!, NSURL(string: "http://unitsofmeasure.org")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.maxVolumeToDeliver!.units!, "milliliter")
		XCTAssertEqual(inst!.item![0].enteralFormula!.maxVolumeToDeliver!.value!, NSDecimalNumber(string: "880"))
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.denominator!.code!, "h")
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.denominator!.system!, NSURL(string: "http://unitsofmeasure.org")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.denominator!.units!, "hr")
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.denominator!.value!, NSDecimalNumber(string: "1"))
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.numerator!.code!, "mL")
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.numerator!.system!, NSURL(string: "http://unitsofmeasure.org")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.numerator!.units!, "millilters")
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.numerator!.value!, NSDecimalNumber(string: "60"))
		XCTAssertEqual(inst!.item![0].enteralFormula!.rateAdjustment!.units!, "milliliters every 4 hours")
		XCTAssertEqual(inst!.item![0].enteralFormula!.rateAdjustment!.value!, NSDecimalNumber(string: "10"))
		XCTAssertEqual(inst!.item![0].enteralFormula!.routeofAdministration!.coding![0].code!, "NGT")
		XCTAssertEqual(inst!.item![0].enteralFormula!.routeofAdministration!.coding![0].display!, "Instillation, nasogastrostomy tube")
		XCTAssertEqual(inst!.item![0].enteralFormula!.routeofAdministration!.coding![0].system!, NSURL(string: "http://hl7.org/fhir/v3/RouteOfAdministration")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.routeofAdministration!.coding![0].valueSet!.display!, "EnteralRouteOfAdministration")
		XCTAssertEqual(inst!.item![0].enteralFormula!.routeofAdministration!.coding![0].valueSet!.reference!, "http://hl7.org/fhir/vs/enteral-route")
		XCTAssertTrue(inst!.item![0].isInEffect!)
		XCTAssertEqual(inst!.item![0].scheduledPeriod!.start!, NSDate.dateFromISOString("2014-09-17")!)
		XCTAssertEqual(inst!.orderer!.display!, "Peter Chalmers")
		XCTAssertEqual(inst!.orderer!.reference!, "Patient/example")
		XCTAssertEqual(inst!.status!, "active")
		XCTAssertEqual(inst!.subject!.display!, "Dr Adam Careful")
		XCTAssertEqual(inst!.subject!.reference!, "Practitioner/example")
	}
	
	func testNutritionOrder5() {
		let inst = instantiateFrom("nutritionorder-enteralcontinuous-example.json")
		XCTAssertNotNil(inst, "Must have instantiated a NutritionOrder instance")
	
		XCTAssertEqual(inst!.allergyIntolerance![0].display!, "Cashew Nuts")
		XCTAssertEqual(inst!.allergyIntolerance![0].reference!, "AllergyIntolerance/example")
		XCTAssertEqual(inst!.dateTime!, NSDate.dateFromISOString("2014-09-17")!)
		XCTAssertEqual(inst!.encounter!.display!, "Inpatient")
		XCTAssertEqual(inst!.encounter!.reference!, "Encounter/example")
		XCTAssertEqual(inst!.excludeFoodModifier![0].coding![0].code!, "227493005")
		XCTAssertEqual(inst!.excludeFoodModifier![0].coding![0].display!, "Cashew Nut")
		XCTAssertEqual(inst!.excludeFoodModifier![0].coding![0].system!, NSURL(string: "http://snomed.info/sct")!)
		XCTAssertEqual(inst!.excludeFoodModifier![0].coding![0].version!, "20140730")
		XCTAssertEqual(inst!.foodPreferenceModifier![0].coding![0].code!, "dairy-free")
		XCTAssertEqual(inst!.foodPreferenceModifier![0].coding![0].system!, NSURL(string: "http://hl7.org/fhir/diet")!)
		XCTAssertEqual(inst!.foodPreferenceModifier![0].coding![0].valueSet!.display!, "PatientDiet")
		XCTAssertEqual(inst!.foodPreferenceModifier![0].coding![0].valueSet!.reference!, "http://hl7.org/fhir/vs/encounter-diet")
		XCTAssertEqual(inst!.identifier![0].system!, NSURL(string: "http://www.acme.org/nutritionorders")!)
		XCTAssertEqual(inst!.identifier![0].value!, "123")
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveName!, "Acme MCT Oil")
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveType!.coding![0].code!, "427298002")
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveType!.coding![0].display!, "Enteral dietary supplement")
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveType!.coding![0].system!, NSURL(string: "http://snomed.info/sct")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveType!.coding![0].valueSet!.display!, "Medium chain triglyceride supplementation")
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveType!.coding![0].valueSet!.reference!, "http://hl7.org/fhir/vs/entformula-additive")
		XCTAssertEqual(inst!.item![0].enteralFormula!.administrationInstructions!, "Hold feedings from 7 pm to 7 am. Add MCT oil to increase calories from 1.0 cal/mL to 1.5 cal/mL")
		XCTAssertEqual(inst!.item![0].enteralFormula!.baseFormulaName!, " Acme Diabetes Formula")
		XCTAssertEqual(inst!.item![0].enteralFormula!.baseFormulaType!.coding![0].code!, "6547210000124112")
		XCTAssertEqual(inst!.item![0].enteralFormula!.baseFormulaType!.coding![0].display!, "Diabetic specialty enteral formula")
		XCTAssertEqual(inst!.item![0].enteralFormula!.baseFormulaType!.coding![0].system!, NSURL(string: "http://snomed-us.info/sct")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.caloricDensity!.code!, "cal/mL")
		XCTAssertEqual(inst!.item![0].enteralFormula!.caloricDensity!.system!, NSURL(string: "http://unitsofmeasure.org")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.caloricDensity!.units!, "calories per milliliter")
		XCTAssertEqual(inst!.item![0].enteralFormula!.caloricDensity!.value!, NSDecimalNumber(string: "1"))
		XCTAssertEqual(inst!.item![0].enteralFormula!.maxVolumeToDeliver!.code!, "mL")
		XCTAssertEqual(inst!.item![0].enteralFormula!.maxVolumeToDeliver!.system!, NSURL(string: "http://unitsofmeasure.org")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.maxVolumeToDeliver!.units!, "milliliter")
		XCTAssertEqual(inst!.item![0].enteralFormula!.maxVolumeToDeliver!.value!, NSDecimalNumber(string: "880"))
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.denominator!.code!, "h")
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.denominator!.system!, NSURL(string: "http://unitsofmeasure.org")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.denominator!.units!, "hr")
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.denominator!.value!, NSDecimalNumber(string: "1"))
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.numerator!.code!, "mL")
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.numerator!.system!, NSURL(string: "http://unitsofmeasure.org")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.numerator!.units!, "millilters")
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.numerator!.value!, NSDecimalNumber(string: "60"))
		XCTAssertEqual(inst!.item![0].enteralFormula!.rateAdjustment!.units!, "milliliters every 4 hours")
		XCTAssertEqual(inst!.item![0].enteralFormula!.rateAdjustment!.value!, NSDecimalNumber(string: "10"))
		XCTAssertEqual(inst!.item![0].enteralFormula!.routeofAdministration!.coding![0].code!, "NGT")
		XCTAssertEqual(inst!.item![0].enteralFormula!.routeofAdministration!.coding![0].display!, "Instillation, nasogastrostomy tube")
		XCTAssertEqual(inst!.item![0].enteralFormula!.routeofAdministration!.coding![0].system!, NSURL(string: "http://hl7.org/fhir/v3/RouteOfAdministration")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.routeofAdministration!.coding![0].valueSet!.display!, "EnteralRouteOfAdministration")
		XCTAssertEqual(inst!.item![0].enteralFormula!.routeofAdministration!.coding![0].valueSet!.reference!, "http://hl7.org/fhir/vs/enteral-route")
		XCTAssertTrue(inst!.item![0].isInEffect!)
		XCTAssertEqual(inst!.item![0].scheduledPeriod!.start!, NSDate.dateFromISOString("2014-09-17")!)
		XCTAssertEqual(inst!.orderer!.display!, "Peter Chalmers")
		XCTAssertEqual(inst!.orderer!.reference!, "Patient/example")
		XCTAssertEqual(inst!.status!, "active")
		XCTAssertEqual(inst!.subject!.display!, "Dr Adam Careful")
		XCTAssertEqual(inst!.subject!.reference!, "Practitioner/example")
	}
	
	func testNutritionOrder6() {
		let inst = instantiateFrom("nutritionorder-example.canonical.json")
		XCTAssertNotNil(inst, "Must have instantiated a NutritionOrder instance")
	
		XCTAssertEqual(inst!.dateTime!, NSDate.dateFromISOString("2014-09-17")!)
		XCTAssertTrue(inst!.item![0].isInEffect!)
		XCTAssertEqual(inst!.item![0].oralDiet!.type![0].text!, "Low Calorie Diet")
		XCTAssertEqual(inst!.subject!.display!, "Paula Patient Chalmers")
	}
	
	func testNutritionOrder7() {
		let inst = instantiateFrom("nutritionorder-example.json")
		XCTAssertNotNil(inst, "Must have instantiated a NutritionOrder instance")
	
		XCTAssertEqual(inst!.dateTime!, NSDate.dateFromISOString("2014-09-17")!)
		XCTAssertTrue(inst!.item![0].isInEffect!)
		XCTAssertEqual(inst!.item![0].oralDiet!.type![0].text!, "Low Calorie Diet")
		XCTAssertEqual(inst!.subject!.display!, "Paula Patient Chalmers")
	}
	
	func testNutritionOrder8() {
		let inst = instantiateFrom("nutritionorder-infantenteral-example.canonical.json")
		XCTAssertNotNil(inst, "Must have instantiated a NutritionOrder instance")
	
		XCTAssertEqual(inst!.allergyIntolerance![0].display!, "Cashew Nuts")
		XCTAssertEqual(inst!.allergyIntolerance![0].reference!, "AllergyIntolerance/example")
		XCTAssertEqual(inst!.dateTime!, NSDate.dateFromISOString("2014-09-17")!)
		XCTAssertEqual(inst!.encounter!.display!, "Inpatient")
		XCTAssertEqual(inst!.encounter!.reference!, "Encounter/example")
		XCTAssertEqual(inst!.excludeFoodModifier![0].coding![0].code!, "227493005")
		XCTAssertEqual(inst!.excludeFoodModifier![0].coding![0].display!, "Cashew Nut")
		XCTAssertEqual(inst!.excludeFoodModifier![0].coding![0].system!, NSURL(string: "http://snomed.info/sct")!)
		XCTAssertEqual(inst!.excludeFoodModifier![0].coding![0].version!, "20140730")
		XCTAssertEqual(inst!.foodPreferenceModifier![0].coding![0].code!, "nut-free")
		XCTAssertEqual(inst!.foodPreferenceModifier![0].coding![0].system!, NSURL(string: "http://hl7.org/fhir/diet")!)
		XCTAssertEqual(inst!.foodPreferenceModifier![0].coding![0].valueSet!.display!, "PatientDiet")
		XCTAssertEqual(inst!.foodPreferenceModifier![0].coding![0].valueSet!.reference!, "http://hl7.org/fhir/vs/encounter-diet")
		XCTAssertEqual(inst!.identifier![0].system!, NSURL(string: "http://www.acme.org/nutritionorders")!)
		XCTAssertEqual(inst!.identifier![0].value!, "123")
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveName!, "Acme High Carbohydrate Additive")
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveType!.coding![0].code!, "226307009")
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveType!.coding![0].display!, "Carbohydrate supplement")
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveType!.coding![0].system!, NSURL(string: "http://snomed.info/sct")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveType!.coding![0].valueSet!.display!, "EnteralFormulaAdditiveType")
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveType!.coding![0].valueSet!.reference!, "http://hl7.org/fhir/vs/entformula-additive")
		XCTAssertEqual(inst!.item![0].enteralFormula!.administrationInstructions!, "Add high calorie high carbohydrate additive to increase cal/oz from 24 cal/oz to 27 cal/oz.")
		XCTAssertEqual(inst!.item![0].enteralFormula!.baseFormulaName!, "Acme Infant Formula + Iron")
		XCTAssertEqual(inst!.item![0].enteralFormula!.baseFormulaType!.coding![0].code!, "412414007")
		XCTAssertEqual(inst!.item![0].enteralFormula!.baseFormulaType!.coding![0].display!, "infant formula + iron")
		XCTAssertEqual(inst!.item![0].enteralFormula!.baseFormulaType!.coding![0].system!, NSURL(string: "http://snomed.info/sct")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.caloricDensity!.code!, "cal/[foz_us]")
		XCTAssertEqual(inst!.item![0].enteralFormula!.caloricDensity!.system!, NSURL(string: "http://unitsofmeasure.org")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.caloricDensity!.units!, "calories per ounce")
		XCTAssertEqual(inst!.item![0].enteralFormula!.caloricDensity!.value!, NSDecimalNumber(string: "20"))
		XCTAssertEqual(inst!.item![0].enteralFormula!.maxVolumeToDeliver!.code!, "[foz_us]")
		XCTAssertEqual(inst!.item![0].enteralFormula!.maxVolumeToDeliver!.system!, NSURL(string: "http://unitsofmeasure.org")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.maxVolumeToDeliver!.units!, "ounces")
		XCTAssertEqual(inst!.item![0].enteralFormula!.maxVolumeToDeliver!.value!, NSDecimalNumber(string: "32"))
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.denominator!.code!, "h")
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.denominator!.system!, NSURL(string: "http://unitsofmeasure.org")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.denominator!.units!, "hr")
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.denominator!.value!, NSDecimalNumber(string: "3"))
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.numerator!.code!, "[foz_us]")
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.numerator!.system!, NSURL(string: "http://unitsofmeasure.org")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.numerator!.units!, "oz")
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.numerator!.value!, NSDecimalNumber(string: "4"))
		XCTAssertEqual(inst!.item![0].enteralFormula!.routeofAdministration!.coding![0].code!, "PO")
		XCTAssertEqual(inst!.item![0].enteralFormula!.routeofAdministration!.coding![0].display!, "Swallow, oral")
		XCTAssertTrue(inst!.item![0].enteralFormula!.routeofAdministration!.coding![0].primary!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.routeofAdministration!.coding![0].system!, NSURL(string: "http://hl7.org/fhir/v3/RouteOfAdministration")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.routeofAdministration!.coding![0].valueSet!.display!, "EnteralRouteOfAdministration")
		XCTAssertEqual(inst!.item![0].enteralFormula!.routeofAdministration!.coding![0].valueSet!.reference!, "http://hl7.org/fhir/vs/enteral-route")
		XCTAssertTrue(inst!.item![0].isInEffect!)
		XCTAssertEqual(inst!.item![0].scheduledPeriod!.start!, NSDate.dateFromISOString("2014-09-17")!)
		XCTAssertEqual(inst!.orderer!.display!, "Peter Chalmers")
		XCTAssertEqual(inst!.orderer!.reference!, "Patient/example")
		XCTAssertEqual(inst!.status!, "active")
		XCTAssertEqual(inst!.subject!.display!, "Dr Adam Careful")
		XCTAssertEqual(inst!.subject!.reference!, "Practitioner/example")
	}
	
	func testNutritionOrder9() {
		let inst = instantiateFrom("nutritionorder-infantenteral-example.json")
		XCTAssertNotNil(inst, "Must have instantiated a NutritionOrder instance")
	
		XCTAssertEqual(inst!.allergyIntolerance![0].display!, "Cashew Nuts")
		XCTAssertEqual(inst!.allergyIntolerance![0].reference!, "AllergyIntolerance/example")
		XCTAssertEqual(inst!.dateTime!, NSDate.dateFromISOString("2014-09-17")!)
		XCTAssertEqual(inst!.encounter!.display!, "Inpatient")
		XCTAssertEqual(inst!.encounter!.reference!, "Encounter/example")
		XCTAssertEqual(inst!.excludeFoodModifier![0].coding![0].code!, "227493005")
		XCTAssertEqual(inst!.excludeFoodModifier![0].coding![0].display!, "Cashew Nut")
		XCTAssertEqual(inst!.excludeFoodModifier![0].coding![0].system!, NSURL(string: "http://snomed.info/sct")!)
		XCTAssertEqual(inst!.excludeFoodModifier![0].coding![0].version!, "20140730")
		XCTAssertEqual(inst!.foodPreferenceModifier![0].coding![0].code!, "nut-free")
		XCTAssertEqual(inst!.foodPreferenceModifier![0].coding![0].system!, NSURL(string: "http://hl7.org/fhir/diet")!)
		XCTAssertEqual(inst!.foodPreferenceModifier![0].coding![0].valueSet!.display!, "PatientDiet")
		XCTAssertEqual(inst!.foodPreferenceModifier![0].coding![0].valueSet!.reference!, "http://hl7.org/fhir/vs/encounter-diet")
		XCTAssertEqual(inst!.identifier![0].system!, NSURL(string: "http://www.acme.org/nutritionorders")!)
		XCTAssertEqual(inst!.identifier![0].value!, "123")
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveName!, "Acme High Carbohydrate Additive")
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveType!.coding![0].code!, "226307009")
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveType!.coding![0].display!, "Carbohydrate supplement")
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveType!.coding![0].system!, NSURL(string: "http://snomed.info/sct")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveType!.coding![0].valueSet!.display!, "EnteralFormulaAdditiveType")
		XCTAssertEqual(inst!.item![0].enteralFormula!.additiveType!.coding![0].valueSet!.reference!, "http://hl7.org/fhir/vs/entformula-additive")
		XCTAssertEqual(inst!.item![0].enteralFormula!.administrationInstructions!, "Add high calorie high carbohydrate additive to increase cal/oz from 24 cal/oz to 27 cal/oz.")
		XCTAssertEqual(inst!.item![0].enteralFormula!.baseFormulaName!, "Acme Infant Formula + Iron")
		XCTAssertEqual(inst!.item![0].enteralFormula!.baseFormulaType!.coding![0].code!, "412414007")
		XCTAssertEqual(inst!.item![0].enteralFormula!.baseFormulaType!.coding![0].display!, "infant formula + iron")
		XCTAssertEqual(inst!.item![0].enteralFormula!.baseFormulaType!.coding![0].system!, NSURL(string: "http://snomed.info/sct")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.caloricDensity!.code!, "cal/[foz_us]")
		XCTAssertEqual(inst!.item![0].enteralFormula!.caloricDensity!.system!, NSURL(string: "http://unitsofmeasure.org")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.caloricDensity!.units!, "calories per ounce")
		XCTAssertEqual(inst!.item![0].enteralFormula!.caloricDensity!.value!, NSDecimalNumber(string: "20"))
		XCTAssertEqual(inst!.item![0].enteralFormula!.maxVolumeToDeliver!.code!, "[foz_us]")
		XCTAssertEqual(inst!.item![0].enteralFormula!.maxVolumeToDeliver!.system!, NSURL(string: "http://unitsofmeasure.org")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.maxVolumeToDeliver!.units!, "ounces")
		XCTAssertEqual(inst!.item![0].enteralFormula!.maxVolumeToDeliver!.value!, NSDecimalNumber(string: "32"))
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.denominator!.code!, "h")
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.denominator!.system!, NSURL(string: "http://unitsofmeasure.org")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.denominator!.units!, "hr")
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.denominator!.value!, NSDecimalNumber(string: "3"))
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.numerator!.code!, "[foz_us]")
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.numerator!.system!, NSURL(string: "http://unitsofmeasure.org")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.numerator!.units!, "oz")
		XCTAssertEqual(inst!.item![0].enteralFormula!.rate!.numerator!.value!, NSDecimalNumber(string: "4"))
		XCTAssertEqual(inst!.item![0].enteralFormula!.routeofAdministration!.coding![0].code!, "PO")
		XCTAssertEqual(inst!.item![0].enteralFormula!.routeofAdministration!.coding![0].display!, "Swallow, oral")
		XCTAssertTrue(inst!.item![0].enteralFormula!.routeofAdministration!.coding![0].primary!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.routeofAdministration!.coding![0].system!, NSURL(string: "http://hl7.org/fhir/v3/RouteOfAdministration")!)
		XCTAssertEqual(inst!.item![0].enteralFormula!.routeofAdministration!.coding![0].valueSet!.display!, "EnteralRouteOfAdministration")
		XCTAssertEqual(inst!.item![0].enteralFormula!.routeofAdministration!.coding![0].valueSet!.reference!, "http://hl7.org/fhir/vs/enteral-route")
		XCTAssertTrue(inst!.item![0].isInEffect!)
		XCTAssertEqual(inst!.item![0].scheduledPeriod!.start!, NSDate.dateFromISOString("2014-09-17")!)
		XCTAssertEqual(inst!.orderer!.display!, "Peter Chalmers")
		XCTAssertEqual(inst!.orderer!.reference!, "Patient/example")
		XCTAssertEqual(inst!.status!, "active")
		XCTAssertEqual(inst!.subject!.display!, "Dr Adam Careful")
		XCTAssertEqual(inst!.subject!.reference!, "Practitioner/example")
	}
}
