//
//  ObservationTests.swift
//  ObservationTests
//
//  Generated from FHIR 0.0.81.2382 on 2014-09-16.
//  Copyright (c) 2014 SMART Platforms. All rights reserved.
//

import Cocoa
import XCTest
import SwiftFHIR


class ObservationTests: FHIRModelTestCase
{
	func instantiateFrom(filename: String) -> Observation? {
		let json = readJSONFile(filename)
		let instance = Observation(json: json)
		XCTAssertNotNil(instance, "Must have instantiated a test instance")
		return instance
	}
	
	func testObservation1() {
		let inst = instantiateFrom("observation-example-f001-glucose.json")
		XCTAssertNotNil(inst, "Must have instantiated a Observation instance")
	
		XCTAssertEqual(inst!.appliesPeriod!.end!, NSDate.dateFromISOString("2013-04-05T09:30:10+01:00")!)
		XCTAssertEqual(inst!.appliesPeriod!.start!, NSDate.dateFromISOString("2013-04-02T09:30:10+01:00")!)	
		XCTAssertEqual(inst!.bodySite!.coding![0].code!, "308046002")	
		XCTAssertEqual(inst!.bodySite!.coding![0].display!, "Superficial forearm vein")
		XCTAssertEqual(inst!.bodySite!.coding![0].system!, NSURL(string: "http://snomed.info/sct"))
		XCTAssertEqual(inst!.identifier!.system!, NSURL(string: "http://www.bmc.nl/zorgportal/identifiers/observations"))	
		XCTAssertEqual(inst!.identifier!.use!, "official")	
		XCTAssertEqual(inst!.identifier!.value!, "6323")	
		XCTAssertEqual(inst!.interpretation!.coding![0].code!, "A")	
		XCTAssertEqual(inst!.interpretation!.coding![0].display!, "abnormal")
		XCTAssertEqual(inst!.interpretation!.coding![0].system!, NSURL(string: "http://hl7.org/fhir/v2/0078"))
		XCTAssertEqual(inst!.issued!, NSDate.dateFromISOString("2013-04-03T15:30:10+01:00")!)	
		XCTAssertEqual(inst!.method!.coding![0].code!, "120220003")	
		XCTAssertEqual(inst!.method!.coding![0].display!, "Injection to forearm")
		XCTAssertEqual(inst!.method!.coding![0].system!, NSURL(string: "http://snomed.info/sct"))	
		XCTAssertEqual(inst!.name!.coding![0].code!, "2339-0")	
		XCTAssertEqual(inst!.name!.coding![0].display!, "Glucose [Mass/volume] in Blood")
		XCTAssertEqual(inst!.name!.coding![0].system!, NSURL(string: "http://loinc.org"))	
		XCTAssertEqual(inst!.referenceRange![0].high!.code!, "mmol/l")
		XCTAssertEqual(inst!.referenceRange![0].high!.system!, NSURL(string: "http://unitsofmeasure.org"))	
		XCTAssertEqual(inst!.referenceRange![0].high!.units!, "mmol/l")
		XCTAssertEqual(inst!.referenceRange![0].high!.value!, 6.2)	
		XCTAssertEqual(inst!.referenceRange![0].low!.code!, "mmol/l")
		XCTAssertEqual(inst!.referenceRange![0].low!.system!, NSURL(string: "http://unitsofmeasure.org"))	
		XCTAssertEqual(inst!.referenceRange![0].low!.units!, "mmol/l")
		XCTAssertEqual(inst!.referenceRange![0].low!.value!, 3.1)	
		XCTAssertEqual(inst!.reliability!, "ok")	
		XCTAssertEqual(inst!.status!, "final")	
		XCTAssertEqual(inst!.text!.div!, "<div>\n      <p>\n        <b>Generated Narrative</b>\n      </p>\n      <p>\n        <b>name</b>: \n        <span title=\"Codes: {http://loinc.org 2339-0}\">Glucose [Mass/volume] in Blood</span>\n      </p>\n      <p>\n        <b>value[x]</b>: 6.3 mmol/l\n      </p>\n      <p>\n        <b>interpretation</b>: \n        <span title=\"Codes: {http://hl7.org/fhir/v2/0078 A}\">abnormal</span>\n      </p>\n      <p>\n        <b>applies[x]</b>: 2-Apr 2013 9:30 --&gt; 5-Apr 2013 9:30\n      </p>\n      <p>\n        <b>issued</b>: 3-Apr 2013 15:30\n      </p>\n      <p>\n        <b>status</b>: final_\n      </p>\n      <p>\n        <b>reliability</b>: ok\n      </p>\n      <p>\n        <b>bodySite</b>: \n        <span title=\"Codes: {http://snomed.info/sct 308046002}\">Superficial forearm vein</span>\n      </p>\n      <p>\n        <b>method</b>: \n        <span title=\"Codes: {http://snomed.info/sct 120220003}\">Injection to forearm</span>\n      </p>\n      <p>\n        <b>identifier</b>: 6323 (official)\n      </p>\n      <p>\n        <b>subject</b>: P. van de Heuvel\n      </p>\n      <p>\n        <b>performer</b>: A. Langeveld\n      </p>\n      <h3>ReferenceRanges</h3>\n      <table class=\"grid\">\n        <tr>\n          <td>\n            <b>Low</b>\n          </td>\n          <td>\n            <b>High</b>\n          </td>\n          <td>\n            <b>Meaning</b>\n          </td>\n          <td>\n            <b>Age</b>\n          </td>\n        </tr>\n        <tr>\n          <td>3.1 mmol/l</td>\n          <td>6.2 mmol/l</td>\n          <td> </td>\n          <td> </td>\n        </tr>\n      </table>\n    </div>")	
		XCTAssertEqual(inst!.text!.status!, "generated")	
		XCTAssertEqual(inst!.valueQuantity!.code!, "mmol/l")
		XCTAssertEqual(inst!.valueQuantity!.system!, NSURL(string: "http://unitsofmeasure.org"))	
		XCTAssertEqual(inst!.valueQuantity!.units!, "mmol/l")
		XCTAssertEqual(inst!.valueQuantity!.value!, 6.3)
	}
	
	func testObservation2() {
		let inst = instantiateFrom("observation-example-f002-excess.json")
		XCTAssertNotNil(inst, "Must have instantiated a Observation instance")
	
		XCTAssertEqual(inst!.appliesPeriod!.end!, NSDate.dateFromISOString("2013-04-05T10:30:10+01:00")!)
		XCTAssertEqual(inst!.appliesPeriod!.start!, NSDate.dateFromISOString("2013-04-02T10:30:10+01:00")!)	
		XCTAssertEqual(inst!.bodySite!.coding![0].code!, "308046002")	
		XCTAssertEqual(inst!.bodySite!.coding![0].display!, "Superficial forearm vein")
		XCTAssertEqual(inst!.bodySite!.coding![0].system!, NSURL(string: "http://snomed.info/sct"))
		XCTAssertEqual(inst!.identifier!.system!, NSURL(string: "http://www.bmc.nl/zorgportal/identifiers/observations"))	
		XCTAssertEqual(inst!.identifier!.use!, "official")	
		XCTAssertEqual(inst!.identifier!.value!, "6324")	
		XCTAssertEqual(inst!.interpretation!.coding![0].code!, "A")	
		XCTAssertEqual(inst!.interpretation!.coding![0].display!, "abnormal")
		XCTAssertEqual(inst!.interpretation!.coding![0].system!, NSURL(string: "http://hl7.org/fhir/v2/0078"))
		XCTAssertEqual(inst!.issued!, NSDate.dateFromISOString("2013-04-03T15:30:10+01:00")!)	
		XCTAssertEqual(inst!.method!.coding![0].code!, "120220003")	
		XCTAssertEqual(inst!.method!.coding![0].display!, "Injection to forearm")
		XCTAssertEqual(inst!.method!.coding![0].system!, NSURL(string: "http://snomed.info/sct"))	
		XCTAssertEqual(inst!.name!.coding![0].code!, "11555-0")	
		XCTAssertEqual(inst!.name!.coding![0].display!, "Base excess in Blood by calculation")
		XCTAssertEqual(inst!.name!.coding![0].system!, NSURL(string: "http://loinc.org"))	
		XCTAssertEqual(inst!.referenceRange![0].high!.code!, "mmol/l")
		XCTAssertEqual(inst!.referenceRange![0].high!.system!, NSURL(string: "http://unitsofmeasure.org"))	
		XCTAssertEqual(inst!.referenceRange![0].high!.units!, "mmol/l")
		XCTAssertEqual(inst!.referenceRange![0].high!.value!, 11.2)	
		XCTAssertEqual(inst!.referenceRange![0].low!.code!, "mmol/l")
		XCTAssertEqual(inst!.referenceRange![0].low!.system!, NSURL(string: "http://unitsofmeasure.org"))	
		XCTAssertEqual(inst!.referenceRange![0].low!.units!, "mmol/l")
		XCTAssertEqual(inst!.referenceRange![0].low!.value!, 7.1)	
		XCTAssertEqual(inst!.reliability!, "ok")	
		XCTAssertEqual(inst!.status!, "final")	
		XCTAssertEqual(inst!.text!.div!, "<div>\n      <p>\n        <b>Generated Narrative</b>\n      </p>\n      <p>\n        <b>name</b>: \n        <span title=\"Codes: {http://loinc.org 11555-0}\">Base excess in Blood by calculation</span>\n      </p>\n      <p>\n        <b>value[x]</b>: 12.6 mmol/l\n      </p>\n      <p>\n        <b>interpretation</b>: \n        <span title=\"Codes: {http://hl7.org/fhir/v2/0078 A}\">abnormal</span>\n      </p>\n      <p>\n        <b>applies[x]</b>: 2-Apr 2013 10:30 --&gt; 5-Apr 2013 10:30\n      </p>\n      <p>\n        <b>issued</b>: 3-Apr 2013 15:30\n      </p>\n      <p>\n        <b>status</b>: final_\n      </p>\n      <p>\n        <b>reliability</b>: ok\n      </p>\n      <p>\n        <b>bodySite</b>: \n        <span title=\"Codes: {http://snomed.info/sct 308046002}\">Superficial forearm vein</span>\n      </p>\n      <p>\n        <b>method</b>: \n        <span title=\"Codes: {http://snomed.info/sct 120220003}\">Injection to forearm</span>\n      </p>\n      <p>\n        <b>identifier</b>: 6324 (official)\n      </p>\n      <p>\n        <b>subject</b>: P. van de Heuvel\n      </p>\n      <p>\n        <b>performer</b>: A. Langeveld\n      </p>\n      <h3>ReferenceRanges</h3>\n      <table class=\"grid\">\n        <tr>\n          <td>\n            <b>Low</b>\n          </td>\n          <td>\n            <b>High</b>\n          </td>\n          <td>\n            <b>Meaning</b>\n          </td>\n          <td>\n            <b>Age</b>\n          </td>\n        </tr>\n        <tr>\n          <td>7.1 mmol/l</td>\n          <td>11.2 mmol/l</td>\n          <td> </td>\n          <td> </td>\n        </tr>\n      </table>\n    </div>")	
		XCTAssertEqual(inst!.text!.status!, "generated")	
		XCTAssertEqual(inst!.valueQuantity!.code!, "mmol/l")
		XCTAssertEqual(inst!.valueQuantity!.system!, NSURL(string: "http://unitsofmeasure.org"))	
		XCTAssertEqual(inst!.valueQuantity!.units!, "mmol/l")
		XCTAssertEqual(inst!.valueQuantity!.value!, 12.6)
	}
	
	func testObservation3() {
		let inst = instantiateFrom("observation-example-f003-co2.json")
		XCTAssertNotNil(inst, "Must have instantiated a Observation instance")
	
		XCTAssertEqual(inst!.appliesPeriod!.end!, NSDate.dateFromISOString("2013-04-05T10:30:10+01:00")!)
		XCTAssertEqual(inst!.appliesPeriod!.start!, NSDate.dateFromISOString("2013-04-02T10:30:10+01:00")!)	
		XCTAssertEqual(inst!.bodySite!.coding![0].code!, "308046002")	
		XCTAssertEqual(inst!.bodySite!.coding![0].display!, "Superficial forearm vein")
		XCTAssertEqual(inst!.bodySite!.coding![0].system!, NSURL(string: "http://snomed.info/sct"))
		XCTAssertEqual(inst!.identifier!.system!, NSURL(string: "http://www.bmc.nl/zorgportal/identifiers/observations"))	
		XCTAssertEqual(inst!.identifier!.use!, "official")	
		XCTAssertEqual(inst!.identifier!.value!, "6325")	
		XCTAssertEqual(inst!.interpretation!.coding![0].code!, "A")	
		XCTAssertEqual(inst!.interpretation!.coding![0].display!, "abnormal")
		XCTAssertEqual(inst!.interpretation!.coding![0].system!, NSURL(string: "http://hl7.org/fhir/v2/0078"))
		XCTAssertEqual(inst!.issued!, NSDate.dateFromISOString("2013-04-03T15:30:10+01:00")!)	
		XCTAssertEqual(inst!.method!.coding![0].code!, "120220003")	
		XCTAssertEqual(inst!.method!.coding![0].display!, "Injection to forearm")
		XCTAssertEqual(inst!.method!.coding![0].system!, NSURL(string: "http://snomed.info/sct"))	
		XCTAssertEqual(inst!.name!.coding![0].code!, "11557-6")	
		XCTAssertEqual(inst!.name!.coding![0].display!, "Carbon dioxide [Partial pressure] in Blood")
		XCTAssertEqual(inst!.name!.coding![0].system!, NSURL(string: "http://loinc.org"))	
		XCTAssertEqual(inst!.referenceRange![0].high!.code!, "mmol/l")
		XCTAssertEqual(inst!.referenceRange![0].high!.system!, NSURL(string: "http://unitsofmeasure.org"))	
		XCTAssertEqual(inst!.referenceRange![0].high!.units!, "mmol/l")
		XCTAssertEqual(inst!.referenceRange![0].high!.value!, 11.2)	
		XCTAssertEqual(inst!.referenceRange![0].low!.code!, "mmol/l")
		XCTAssertEqual(inst!.referenceRange![0].low!.system!, NSURL(string: "http://unitsofmeasure.org"))	
		XCTAssertEqual(inst!.referenceRange![0].low!.units!, "mmol/l")
		XCTAssertEqual(inst!.referenceRange![0].low!.value!, 7.1)	
		XCTAssertEqual(inst!.reliability!, "ok")	
		XCTAssertEqual(inst!.status!, "final")	
		XCTAssertEqual(inst!.text!.div!, "<div>\n      <p>\n        <b>Generated Narrative</b>\n      </p>\n      <p>\n        <b>name</b>: \n        <span title=\"Codes: {http://loinc.org 11557-6}\">Carbon dioxide [Partial pressure] in Blood</span>\n      </p>\n      <p>\n        <b>value[x]</b>: 6.2 mm[Hg]\n      </p>\n      <p>\n        <b>interpretation</b>: \n        <span title=\"Codes: {http://hl7.org/fhir/v2/0078 A}\">abnormal</span>\n      </p>\n      <p>\n        <b>applies[x]</b>: 2-Apr 2013 10:30 --&gt; 5-Apr 2013 10:30\n      </p>\n      <p>\n        <b>issued</b>: 3-Apr 2013 15:30\n      </p>\n      <p>\n        <b>status</b>: final_\n      </p>\n      <p>\n        <b>reliability</b>: ok\n      </p>\n      <p>\n        <b>bodySite</b>: \n        <span title=\"Codes: {http://snomed.info/sct 308046002}\">Superficial forearm vein</span>\n      </p>\n      <p>\n        <b>method</b>: \n        <span title=\"Codes: {http://snomed.info/sct 120220003}\">Injection to forearm</span>\n      </p>\n      <p>\n        <b>identifier</b>: 6325 (official)\n      </p>\n      <p>\n        <b>subject</b>: P. van de Heuvel\n      </p>\n      <p>\n        <b>performer</b>: A. Langeveld\n      </p>\n      <h3>ReferenceRanges</h3>\n      <table class=\"grid\">\n        <tr>\n          <td>\n            <b>Low</b>\n          </td>\n          <td>\n            <b>High</b>\n          </td>\n          <td>\n            <b>Meaning</b>\n          </td>\n          <td>\n            <b>Age</b>\n          </td>\n        </tr>\n        <tr>\n          <td>7.1 mmol/l</td>\n          <td>11.2 mmol/l</td>\n          <td> </td>\n          <td> </td>\n        </tr>\n      </table>\n    </div>")	
		XCTAssertEqual(inst!.text!.status!, "generated")	
		XCTAssertEqual(inst!.valueQuantity!.code!, "mm[Hg]")
		XCTAssertEqual(inst!.valueQuantity!.system!, NSURL(string: "http://unitsofmeasure.org"))	
		XCTAssertEqual(inst!.valueQuantity!.units!, "mm[Hg]")
		XCTAssertEqual(inst!.valueQuantity!.value!, 6.2)
	}
	
	func testObservation4() {
		let inst = instantiateFrom("observation-example-f004-hemoglobin.json")
		XCTAssertNotNil(inst, "Must have instantiated a Observation instance")
	
		XCTAssertEqual(inst!.appliesPeriod!.end!, NSDate.dateFromISOString("2013-04-05T10:30:10+01:00")!)
		XCTAssertEqual(inst!.appliesPeriod!.start!, NSDate.dateFromISOString("2013-04-02T10:30:10+01:00")!)	
		XCTAssertEqual(inst!.bodySite!.coding![0].code!, "308046002")	
		XCTAssertEqual(inst!.bodySite!.coding![0].display!, "Superficial forearm vein")
		XCTAssertEqual(inst!.bodySite!.coding![0].system!, NSURL(string: "http://snomed.info/sct"))
		XCTAssertEqual(inst!.identifier!.system!, NSURL(string: "http://www.bmc.nl/zorgportal/identifiers/observations"))	
		XCTAssertEqual(inst!.identifier!.use!, "official")	
		XCTAssertEqual(inst!.identifier!.value!, "6326")	
		XCTAssertEqual(inst!.interpretation!.coding![0].code!, "A")	
		XCTAssertEqual(inst!.interpretation!.coding![0].display!, "abnormal")
		XCTAssertEqual(inst!.interpretation!.coding![0].system!, NSURL(string: "http://hl7.org/fhir/v2/0078"))
		XCTAssertEqual(inst!.issued!, NSDate.dateFromISOString("2013-04-03T15:30:10+01:00")!)	
		XCTAssertEqual(inst!.method!.coding![0].code!, "120220003")	
		XCTAssertEqual(inst!.method!.coding![0].display!, "Injection to forearm")
		XCTAssertEqual(inst!.method!.coding![0].system!, NSURL(string: "http://snomed.info/sct"))	
		XCTAssertEqual(inst!.name!.coding![0].code!, "28540-3")	
		XCTAssertEqual(inst!.name!.coding![0].display!, "Erythrocyte mean corpuscular hemoglobin concentration [Mass/volume]")
		XCTAssertEqual(inst!.name!.coding![0].system!, NSURL(string: "http://loinc.org"))	
		XCTAssertEqual(inst!.referenceRange![0].high!.code!, "g/dl")
		XCTAssertEqual(inst!.referenceRange![0].high!.system!, NSURL(string: "http://unitsofmeasure.org"))	
		XCTAssertEqual(inst!.referenceRange![0].high!.units!, "g/dl")
		XCTAssertEqual(inst!.referenceRange![0].high!.value!, 36)	
		XCTAssertEqual(inst!.referenceRange![0].low!.code!, "g/dl")
		XCTAssertEqual(inst!.referenceRange![0].low!.system!, NSURL(string: "http://unitsofmeasure.org"))	
		XCTAssertEqual(inst!.referenceRange![0].low!.units!, "g/dl")
		XCTAssertEqual(inst!.referenceRange![0].low!.value!, 32)	
		XCTAssertEqual(inst!.reliability!, "ok")	
		XCTAssertEqual(inst!.status!, "final")	
		XCTAssertEqual(inst!.text!.div!, "<div>\n      <p>\n        <b>Generated Narrative</b>\n      </p>\n      <p>\n        <b>name</b>: \n        <span title=\"Codes: {http://loinc.org 28540-3}\">Erythrocyte mean corpuscular hemoglobin concentration [Mass/volume]</span>\n      </p>\n      <p>\n        <b>value[x]</b>: 18.7 g/dl\n      </p>\n      <p>\n        <b>interpretation</b>: \n        <span title=\"Codes: {http://hl7.org/fhir/v2/0078 A}\">abnormal</span>\n      </p>\n      <p>\n        <b>applies[x]</b>: 2-Apr 2013 10:30 --&gt; 5-Apr 2013 10:30\n      </p>\n      <p>\n        <b>issued</b>: 3-Apr 2013 15:30\n      </p>\n      <p>\n        <b>status</b>: final_\n      </p>\n      <p>\n        <b>reliability</b>: ok\n      </p>\n      <p>\n        <b>bodySite</b>: \n        <span title=\"Codes: {http://snomed.info/sct 308046002}\">Superficial forearm vein</span>\n      </p>\n      <p>\n        <b>method</b>: \n        <span title=\"Codes: {http://snomed.info/sct 120220003}\">Injection to forearm</span>\n      </p>\n      <p>\n        <b>identifier</b>: 6326 (official)\n      </p>\n      <p>\n        <b>subject</b>: P. van de Heuvel\n      </p>\n      <p>\n        <b>performer</b>: A. Langeveld\n      </p>\n      <h3>ReferenceRanges</h3>\n      <table class=\"grid\">\n        <tr>\n          <td>\n            <b>Low</b>\n          </td>\n          <td>\n            <b>High</b>\n          </td>\n          <td>\n            <b>Meaning</b>\n          </td>\n          <td>\n            <b>Age</b>\n          </td>\n        </tr>\n        <tr>\n          <td>32 g/dl</td>\n          <td>36 g/dl</td>\n          <td> </td>\n          <td> </td>\n        </tr>\n      </table>\n    </div>")	
		XCTAssertEqual(inst!.text!.status!, "generated")	
		XCTAssertEqual(inst!.valueQuantity!.code!, "g/dl")
		XCTAssertEqual(inst!.valueQuantity!.system!, NSURL(string: "http://unitsofmeasure.org"))	
		XCTAssertEqual(inst!.valueQuantity!.units!, "g/dl")
		XCTAssertEqual(inst!.valueQuantity!.value!, 18.7)
	}
	
	func testObservation5() {
		let inst = instantiateFrom("observation-example-f005-hemoglobin.json")
		XCTAssertNotNil(inst, "Must have instantiated a Observation instance")
	
		XCTAssertEqual(inst!.appliesPeriod!.end!, NSDate.dateFromISOString("2013-04-05T10:30:10+01:00")!)
		XCTAssertEqual(inst!.appliesPeriod!.start!, NSDate.dateFromISOString("2013-04-02T10:30:10+01:00")!)	
		XCTAssertEqual(inst!.bodySite!.coding![0].code!, "308046002")	
		XCTAssertEqual(inst!.bodySite!.coding![0].display!, "Superficial forearm vein")
		XCTAssertEqual(inst!.bodySite!.coding![0].system!, NSURL(string: "http://snomed.info/sct"))
		XCTAssertEqual(inst!.identifier!.system!, NSURL(string: "http://www.bmc.nl/zorgportal/identifiers/observations"))	
		XCTAssertEqual(inst!.identifier!.use!, "official")	
		XCTAssertEqual(inst!.identifier!.value!, "6327")	
		XCTAssertEqual(inst!.interpretation!.coding![0].code!, "L")	
		XCTAssertEqual(inst!.interpretation!.coding![0].display!, "low")
		XCTAssertEqual(inst!.interpretation!.coding![0].system!, NSURL(string: "http://hl7.org/fhir/v2/0078"))
		XCTAssertEqual(inst!.issued!, NSDate.dateFromISOString("2013-04-03T15:30:10+01:00")!)	
		XCTAssertEqual(inst!.method!.coding![0].code!, "120220003")	
		XCTAssertEqual(inst!.method!.coding![0].display!, "Injection to forearm")
		XCTAssertEqual(inst!.method!.coding![0].system!, NSURL(string: "http://snomed.info/sct"))	
		XCTAssertEqual(inst!.name!.coding![0].code!, "30350-3")	
		XCTAssertEqual(inst!.name!.coding![0].display!, "Hemoglobin [Mass/volume] in Venous blood")
		XCTAssertEqual(inst!.name!.coding![0].system!, NSURL(string: "http://loinc.org"))	
		XCTAssertEqual(inst!.referenceRange![0].high!.code!, "g/dl")
		XCTAssertEqual(inst!.referenceRange![0].high!.system!, NSURL(string: "http://unitsofmeasure.org"))	
		XCTAssertEqual(inst!.referenceRange![0].high!.units!, "g/dl")
		XCTAssertEqual(inst!.referenceRange![0].high!.value!, 10)	
		XCTAssertEqual(inst!.referenceRange![0].low!.code!, "g/dl")
		XCTAssertEqual(inst!.referenceRange![0].low!.system!, NSURL(string: "http://unitsofmeasure.org"))	
		XCTAssertEqual(inst!.referenceRange![0].low!.units!, "g/dl")
		XCTAssertEqual(inst!.referenceRange![0].low!.value!, 7.5)	
		XCTAssertEqual(inst!.reliability!, "ok")	
		XCTAssertEqual(inst!.status!, "final")	
		XCTAssertEqual(inst!.text!.div!, "<div>\n      <p>\n        <b>Generated Narrative</b>\n      </p>\n      <p>\n        <b>name</b>: \n        <span title=\"Codes: {http://loinc.org 30350-3}\">Hemoglobin [Mass/volume] in Venous blood</span>\n      </p>\n      <p>\n        <b>value[x]</b>: 7.2 g/dl\n      </p>\n      <p>\n        <b>interpretation</b>: \n        <span title=\"Codes: {http://hl7.org/fhir/v2/0078 L}\">low</span>\n      </p>\n      <p>\n        <b>applies[x]</b>: 2-Apr 2013 10:30 --&gt; 5-Apr 2013 10:30\n      </p>\n      <p>\n        <b>issued</b>: 3-Apr 2013 15:30\n      </p>\n      <p>\n        <b>status</b>: final_\n      </p>\n      <p>\n        <b>reliability</b>: ok\n      </p>\n      <p>\n        <b>bodySite</b>: \n        <span title=\"Codes: {http://snomed.info/sct 308046002}\">Superficial forearm vein</span>\n      </p>\n      <p>\n        <b>method</b>: \n        <span title=\"Codes: {http://snomed.info/sct 120220003}\">Injection to forearm</span>\n      </p>\n      <p>\n        <b>identifier</b>: 6327 (official)\n      </p>\n      <p>\n        <b>subject</b>: P. van de Heuvel\n      </p>\n      <p>\n        <b>performer</b>: A. Langeveld\n      </p>\n      <h3>ReferenceRanges</h3>\n      <table class=\"grid\">\n        <tr>\n          <td>\n            <b>Low</b>\n          </td>\n          <td>\n            <b>High</b>\n          </td>\n          <td>\n            <b>Meaning</b>\n          </td>\n          <td>\n            <b>Age</b>\n          </td>\n        </tr>\n        <tr>\n          <td>7.5 g/dl</td>\n          <td>10 g/dl</td>\n          <td> </td>\n          <td> </td>\n        </tr>\n      </table>\n    </div>")	
		XCTAssertEqual(inst!.text!.status!, "generated")	
		XCTAssertEqual(inst!.valueQuantity!.code!, "g/dl")
		XCTAssertEqual(inst!.valueQuantity!.system!, NSURL(string: "http://unitsofmeasure.org"))	
		XCTAssertEqual(inst!.valueQuantity!.units!, "g/dl")
		XCTAssertEqual(inst!.valueQuantity!.value!, 7.2)
	}
	
	func testObservation6() {
		let inst = instantiateFrom("observation-example-f201-bmi.json")
		XCTAssertNotNil(inst, "Must have instantiated a Observation instance")
		
		XCTAssertEqual(inst!.bodySite!.coding![0].code!, "38266002")	
		XCTAssertEqual(inst!.bodySite!.coding![0].display!, "Entire body as a whole")
		XCTAssertEqual(inst!.bodySite!.coding![0].system!, NSURL(string: "http://snomed.info/sct"))	
		XCTAssertEqual(inst!.interpretation!.coding![0].code!, "75540009")	
		XCTAssertEqual(inst!.interpretation!.coding![0].display!, "High")
		XCTAssertEqual(inst!.interpretation!.coding![0].system!, NSURL(string: "http://snomed.info/sct"))	
		XCTAssertEqual(inst!.interpretation!.coding![1].code!, "H")
		XCTAssertEqual(inst!.interpretation!.coding![1].system!, NSURL(string: "http://hl7.org/fhir/v2/0078"))
		XCTAssertEqual(inst!.issued!, NSDate.dateFromISOString("2013-04-04T13:27:00+01:00")!)	
		XCTAssertEqual(inst!.method!.coding![0].code!, "122869004")	
		XCTAssertEqual(inst!.method!.coding![0].display!, "Measurement - action")
		XCTAssertEqual(inst!.method!.coding![0].system!, NSURL(string: "http://snomed.info/sct"))	
		XCTAssertEqual(inst!.name!.coding![0].code!, "60621009")	
		XCTAssertEqual(inst!.name!.coding![0].display!, "Body mass index")
		XCTAssertEqual(inst!.name!.coding![0].system!, NSURL(string: "http://snomed.info/sct"))	
		XCTAssertEqual(inst!.name!.coding![1].code!, "39156-5")	
		XCTAssertEqual(inst!.name!.coding![1].display!, "Body mass index (BMI) [Ratio]")
		XCTAssertEqual(inst!.name!.coding![1].system!, NSURL(string: "http://loinc.org"))	
		XCTAssertEqual(inst!.name!.text!, "BMI")
		XCTAssertEqual(inst!.referenceRange![0].high!.value!, 20)	
		XCTAssertEqual(inst!.referenceRange![0].meaning!.coding![0].code!, "310252000")	
		XCTAssertEqual(inst!.referenceRange![0].meaning!.coding![0].display!, "Low BMI")
		XCTAssertEqual(inst!.referenceRange![0].meaning!.coding![0].system!, NSURL(string: "http://snomed.info/sct"))
		XCTAssertEqual(inst!.referenceRange![1].high!.value!, 25)
		XCTAssertEqual(inst!.referenceRange![1].low!.value!, 20)	
		XCTAssertEqual(inst!.referenceRange![1].meaning!.coding![0].code!, "412768003")	
		XCTAssertEqual(inst!.referenceRange![1].meaning!.coding![0].display!, "Normal BMI")
		XCTAssertEqual(inst!.referenceRange![1].meaning!.coding![0].system!, NSURL(string: "http://snomed.info/sct"))
		XCTAssertEqual(inst!.referenceRange![2].high!.value!, 30)
		XCTAssertEqual(inst!.referenceRange![2].low!.value!, 25)	
		XCTAssertEqual(inst!.referenceRange![2].meaning!.coding![0].code!, "162863004")	
		XCTAssertEqual(inst!.referenceRange![2].meaning!.coding![0].display!, "Overweight")
		XCTAssertEqual(inst!.referenceRange![2].meaning!.coding![0].system!, NSURL(string: "http://snomed.info/sct"))
		XCTAssertEqual(inst!.referenceRange![3].high!.value!, 40)
		XCTAssertEqual(inst!.referenceRange![3].low!.value!, 30)	
		XCTAssertEqual(inst!.referenceRange![3].meaning!.coding![0].code!, "162864005")	
		XCTAssertEqual(inst!.referenceRange![3].meaning!.coding![0].display!, "Obesity")
		XCTAssertEqual(inst!.referenceRange![3].meaning!.coding![0].system!, NSURL(string: "http://snomed.info/sct"))
		XCTAssertEqual(inst!.referenceRange![4].low!.value!, 40)	
		XCTAssertEqual(inst!.referenceRange![4].meaning!.coding![0].code!, "162864005")	
		XCTAssertEqual(inst!.referenceRange![4].meaning!.coding![0].display!, "Severe obesity")
		XCTAssertEqual(inst!.referenceRange![4].meaning!.coding![0].system!, NSURL(string: "http://snomed.info/sct"))	
		XCTAssertEqual(inst!.related![0].type!, "derived-from")	
		XCTAssertEqual(inst!.related![1].type!, "derived-from")	
		XCTAssertEqual(inst!.reliability!, "ok")	
		XCTAssertEqual(inst!.status!, "final")	
		XCTAssertEqual(inst!.text!.div!, "<div>\n      <p>\n        <b>Generated Narrative</b>\n      </p>\n      <p>\n        <b>name</b>: \n        <span title=\"Codes: {http://snomed.info/sct 60621009}, {http://loinc.org 39156-5}\">BMI</span>\n      </p>\n      <p>\n        <b>value[x]</b>: 31.31 null\n      </p>\n      <p>\n        <b>interpretation</b>: \n        <span title=\"Codes: {http://snomed.info/sct 75540009}, {http://hl7.org/fhir/v2/0078 H}\">High</span>\n      </p>\n      <p>\n        <b>issued</b>: 4-Apr 2013 13:27\n      </p>\n      <p>\n        <b>status</b>: final_\n      </p>\n      <p>\n        <b>reliability</b>: ok\n      </p>\n      <p>\n        <b>bodySite</b>: \n        <span title=\"Codes: {http://snomed.info/sct 38266002}\">Entire body as a whole</span>\n      </p>\n      <p>\n        <b>method</b>: \n        <span title=\"Codes: {http://snomed.info/sct 122869004}\">Measurement - action</span>\n      </p>\n      <p>\n        <b>subject</b>: Roel\n      </p>\n      <p>\n        <b>performer</b>: \n        <a href=\"practitioner-example-f201-ab.html\">UZI-nummer = 12345678901 (official); Dokter Bronsig(official); Male; birthDate: 24-Dec 1956; Implementation of planned interventions; Medical oncologist</a>\n      </p>\n      <h3>ReferenceRanges</h3>\n      <table class=\"grid\">\n        <tr>\n          <td>\n            <b>Low</b>\n          </td>\n          <td>\n            <b>High</b>\n          </td>\n          <td>\n            <b>Meaning</b>\n          </td>\n          <td>\n            <b>Age</b>\n          </td>\n        </tr>\n        <tr>\n          <td> </td>\n          <td>20 null</td>\n          <td>\n            <span title=\"Codes: {http://snomed.info/sct 310252000}\">Low BMI</span>\n          </td>\n          <td> </td>\n        </tr>\n        <tr>\n          <td>20 null</td>\n          <td>25 null</td>\n          <td>\n            <span title=\"Codes: {http://snomed.info/sct 412768003}\">Normal BMI</span>\n          </td>\n          <td> </td>\n        </tr>\n        <tr>\n          <td>25 null</td>\n          <td>30 null</td>\n          <td>\n            <span title=\"Codes: {http://snomed.info/sct 162863004}\">Overweight</span>\n          </td>\n          <td> </td>\n        </tr>\n        <tr>\n          <td>30 null</td>\n          <td>40 null</td>\n          <td>\n            <span title=\"Codes: {http://snomed.info/sct 162864005}\">Obesity</span>\n          </td>\n          <td> </td>\n        </tr>\n        <tr>\n          <td>40 null</td>\n          <td> </td>\n          <td>\n            <span title=\"Codes: {http://snomed.info/sct 162864005}\">Severe obesity</span>\n          </td>\n          <td> </td>\n        </tr>\n      </table>\n      <h3>Relateds</h3>\n      <table class=\"grid\">\n        <tr>\n          <td>\n            <b>Type</b>\n          </td>\n          <td>\n            <b>Target</b>\n          </td>\n        </tr>\n        <tr>\n          <td>derivedfrom</td>\n          <td>Length; 182 centimeter; final_; ok</td>\n        </tr>\n        <tr>\n          <td>derivedfrom</td>\n          <td>Weight; 103.7 kilogram; final_; ok</td>\n        </tr>\n      </table>\n    </div>")	
		XCTAssertEqual(inst!.text!.status!, "generated")
		XCTAssertEqual(inst!.valueQuantity!.value!, 31.31)
	}
	
	func testObservation7() {
		let inst = instantiateFrom("observation-example-f202-temperature.json")
		XCTAssertNotNil(inst, "Must have instantiated a Observation instance")
		
		XCTAssertEqual(inst!.bodySite!.coding![0].code!, "38266002")	
		XCTAssertEqual(inst!.bodySite!.coding![0].display!, "Entire body as a whole")
		XCTAssertEqual(inst!.bodySite!.coding![0].system!, NSURL(string: "http://snomed.info/sct"))	
		XCTAssertEqual(inst!.interpretation!.coding![0].code!, "H")
		XCTAssertEqual(inst!.interpretation!.coding![0].system!, NSURL(string: "http://hl7.org/fhir/v2/0078"))
		XCTAssertEqual(inst!.issued!, NSDate.dateFromISOString("2013-04-04T13:27:00+01:00")!)	
		XCTAssertEqual(inst!.method!.coding![0].code!, "89003005")	
		XCTAssertEqual(inst!.method!.coding![0].display!, "Oral temperature taking")
		XCTAssertEqual(inst!.method!.coding![0].system!, NSURL(string: "http://snomed.info/sct"))	
		XCTAssertEqual(inst!.name!.coding![0].code!, "415945006")	
		XCTAssertEqual(inst!.name!.coding![0].display!, "Oral temperature")
		XCTAssertEqual(inst!.name!.coding![0].system!, NSURL(string: "http://snomed.info/sct"))	
		XCTAssertEqual(inst!.name!.coding![1].code!, "8310-5")	
		XCTAssertEqual(inst!.name!.coding![1].display!, "Body temperature")
		XCTAssertEqual(inst!.name!.coding![1].system!, NSURL(string: "http://loinc.org"))	
		XCTAssertEqual(inst!.name!.text!, "Body temperature")	
		XCTAssertEqual(inst!.referenceRange![0].low!.units!, "degrees C")
		XCTAssertEqual(inst!.referenceRange![0].low!.value!, 37.5)	
		XCTAssertEqual(inst!.reliability!, "questionable")	
		XCTAssertEqual(inst!.status!, "entered in error")	
		XCTAssertEqual(inst!.text!.div!, "<div>\n      <p>\n        <b>Generated Narrative</b>\n      </p>\n      <p>\n        <b>name</b>: \n        <span title=\"Codes: {http://snomed.info/sct 415945006}, {http://loinc.org 8310-5}\">Body temperature</span>\n      </p>\n      <p>\n        <b>value[x]</b>: 39 degrees C\n      </p>\n      <p>\n        <b>interpretation</b>: \n        <span title=\"Codes: {http://hl7.org/fhir/v2/0078 H}\">Above high normal</span>\n      </p>\n      <p>\n        <b>issued</b>: 4-Apr 2013 13:27\n      </p>\n      <p>\n        <b>status</b>: enteredInError\n      </p>\n      <p>\n        <b>reliability</b>: questionable\n      </p>\n      <p>\n        <b>bodySite</b>: \n        <span title=\"Codes: {http://snomed.info/sct 38266002}\">Entire body as a whole</span>\n      </p>\n      <p>\n        <b>method</b>: \n        <span title=\"Codes: {http://snomed.info/sct 89003005}\">Oral temperature taking</span>\n      </p>\n      <p>\n        <b>subject</b>: Roel\n      </p>\n      <p>\n        <b>performer</b>: \n        <a href=\"practitioner-example-f201-ab.html\">UZI-nummer = 12345678901 (official); Dokter Bronsig(official); Male; birthDate: 24-Dec 1956; Implementation of planned interventions; Medical oncologist</a>\n      </p>\n      <h3>ReferenceRanges</h3>\n      <table class=\"grid\">\n        <tr>\n          <td>\n            <b>Low</b>\n          </td>\n          <td>\n            <b>High</b>\n          </td>\n          <td>\n            <b>Meaning</b>\n          </td>\n          <td>\n            <b>Age</b>\n          </td>\n        </tr>\n        <tr>\n          <td>37.5 degrees C</td>\n          <td> </td>\n          <td> </td>\n          <td> </td>\n        </tr>\n      </table>\n    </div>")	
		XCTAssertEqual(inst!.text!.status!, "generated")	
		XCTAssertEqual(inst!.valueQuantity!.code!, "258710007")
		XCTAssertEqual(inst!.valueQuantity!.system!, NSURL(string: "http://snomed.info/sct"))	
		XCTAssertEqual(inst!.valueQuantity!.units!, "degrees C")
		XCTAssertEqual(inst!.valueQuantity!.value!, 39)
	}
	
	func testObservation8() {
		let inst = instantiateFrom("observation-example-f203-bicarbonate.json")
		XCTAssertNotNil(inst, "Must have instantiated a Observation instance")
		
		XCTAssertEqual(inst!.identifier!.label!, "Bicarbonaat value of Roel on April 2013 - 03720")
		XCTAssertEqual(inst!.identifier!.system!, NSURL(string: "https://intranet.aumc.nl/labvalues"))	
		XCTAssertEqual(inst!.identifier!.value!, "1304-03720-Bicarbonate")	
		XCTAssertEqual(inst!.interpretation!.coding![0].code!, "166698001")	
		XCTAssertEqual(inst!.interpretation!.coding![0].display!, "Serum bicarbonate level normal")
		XCTAssertEqual(inst!.interpretation!.coding![0].system!, NSURL(string: "http://snomed.info/sct"))	
		XCTAssertEqual(inst!.interpretation!.coding![1].code!, "N")
		XCTAssertEqual(inst!.interpretation!.coding![1].system!, NSURL(string: "http://hl7.org/fhir/v2/0078"))
		XCTAssertEqual(inst!.issued!, NSDate.dateFromISOString("2013-04-04T14:34:00+01:00")!)	
		XCTAssertEqual(inst!.method!.coding![0].code!, "271239003")	
		XCTAssertEqual(inst!.method!.coding![0].display!, "Serum bicarbonate measurement")
		XCTAssertEqual(inst!.method!.coding![0].system!, NSURL(string: "http://snomed.info/sct"))	
		XCTAssertEqual(inst!.name!.coding![0].code!, "365722008")	
		XCTAssertEqual(inst!.name!.coding![0].display!, "Bicarbonate level")
		XCTAssertEqual(inst!.name!.coding![0].system!, NSURL(string: "http://snomed.info/sct"))
		XCTAssertEqual(inst!.referenceRange![0].high!.value!, 29)
		XCTAssertEqual(inst!.referenceRange![0].low!.value!, 22)	
		XCTAssertEqual(inst!.referenceRange![0].meaning!.coding![0].code!, "normal")	
		XCTAssertEqual(inst!.referenceRange![0].meaning!.coding![0].display!, "Normal Range")
		XCTAssertEqual(inst!.referenceRange![0].meaning!.coding![0].system!, NSURL(string: "http://hl7.org/fhir/referencerange-meaning"))	
		XCTAssertEqual(inst!.reliability!, "ok")	
		XCTAssertEqual(inst!.status!, "final")	
		XCTAssertEqual(inst!.text!.div!, "<div>\n      <p>\n        <b>Generated Narrative</b>\n      </p>\n      <p>\n        <b>name</b>: \n        <span title=\"Codes: {http://snomed.info/sct 365722008}\">Bicarbonate level</span>\n      </p>\n      <p>\n        <b>value[x]</b>: 28 mmol/L\n      </p>\n      <p>\n        <b>interpretation</b>: \n        <span title=\"Codes: {http://snomed.info/sct 166698001}, {http://hl7.org/fhir/v2/0078 N}\">Serum bicarbonate level normal</span>\n      </p>\n      <p>\n        <b>issued</b>: 4-Apr 2013 14:34\n      </p>\n      <p>\n        <b>status</b>: final_\n      </p>\n      <p>\n        <b>reliability</b>: ok\n      </p>\n      <p>\n        <b>method</b>: \n        <span title=\"Codes: {http://snomed.info/sct 271239003}\">Serum bicarbonate measurement</span>\n      </p>\n      <p>\n        <b>identifier</b>: Bicarbonaat value of Roel on April 2013 - 03720 = 1304-03720-Bicarbonate\n      </p>\n      <p>\n        <b>subject</b>: Roel\n      </p>\n      <p>\n        <b>performer</b>: Luigi Maas\n      </p>\n      <h3>ReferenceRanges</h3>\n      <table class=\"grid\">\n        <tr>\n          <td>\n            <b>Low</b>\n          </td>\n          <td>\n            <b>High</b>\n          </td>\n          <td>\n            <b>Meaning</b>\n          </td>\n          <td>\n            <b>Age</b>\n          </td>\n        </tr>\n        <tr>\n          <td>22 null</td>\n          <td>29 null</td>\n          <td>\n            <span title=\"Codes: {http://hl7.org/fhir/referencerange-meaning normal}\">Normal Range</span>\n          </td>\n          <td> </td>\n        </tr>\n      </table>\n    </div>")	
		XCTAssertEqual(inst!.text!.status!, "generated")	
		XCTAssertEqual(inst!.valueQuantity!.code!, "258813002")
		XCTAssertEqual(inst!.valueQuantity!.system!, NSURL(string: "http://snomed.info/sct"))	
		XCTAssertEqual(inst!.valueQuantity!.units!, "mmol/L")
		XCTAssertEqual(inst!.valueQuantity!.value!, 28)
	}
	
	func testObservation9() {
		let inst = instantiateFrom("observation-example-f204-creatinine.json")
		XCTAssertNotNil(inst, "Must have instantiated a Observation instance")
		
		XCTAssertEqual(inst!.identifier!.label!, "Creatinine value of Roel on April 2013 - 03720")
		XCTAssertEqual(inst!.identifier!.system!, NSURL(string: "https://intranet.aumc.nl/labvalues"))	
		XCTAssertEqual(inst!.identifier!.value!, "1304-03720-Creatinine")	
		XCTAssertEqual(inst!.interpretation!.coding![0].code!, "166717003")	
		XCTAssertEqual(inst!.interpretation!.coding![0].display!, "Serum creatinine raised")
		XCTAssertEqual(inst!.interpretation!.coding![0].system!, NSURL(string: "http://snomed.info/sct"))	
		XCTAssertEqual(inst!.interpretation!.coding![1].code!, "H")
		XCTAssertEqual(inst!.interpretation!.coding![1].system!, NSURL(string: "http://hl7.org/fhir/v2/0078"))
		XCTAssertEqual(inst!.issued!, NSDate.dateFromISOString("2013-04-04T14:34:00+01:00")!)	
		XCTAssertEqual(inst!.method!.coding![0].code!, "113075003")	
		XCTAssertEqual(inst!.method!.coding![0].display!, "Creatinine measurement, serum")
		XCTAssertEqual(inst!.method!.coding![0].system!, NSURL(string: "http://snomed.info/sct"))	
		XCTAssertEqual(inst!.name!.coding![0].code!, "365756002")	
		XCTAssertEqual(inst!.name!.coding![0].display!, "Creatinine level")
		XCTAssertEqual(inst!.name!.coding![0].system!, NSURL(string: "http://snomed.info/sct"))
		XCTAssertEqual(inst!.referenceRange![0].high!.value!, 104)
		XCTAssertEqual(inst!.referenceRange![0].low!.value!, 64)	
		XCTAssertEqual(inst!.referenceRange![0].meaning!.coding![0].code!, "normal")	
		XCTAssertEqual(inst!.referenceRange![0].meaning!.coding![0].display!, "Normal Range")
		XCTAssertEqual(inst!.referenceRange![0].meaning!.coding![0].system!, NSURL(string: "http://hl7.org/fhir/referencerange-meaning"))	
		XCTAssertEqual(inst!.reliability!, "ok")	
		XCTAssertEqual(inst!.status!, "final")	
		XCTAssertEqual(inst!.text!.div!, "<div>\n      <p>\n        <b>Generated Narrative</b>\n      </p>\n      <p>\n        <b>name</b>: \n        <span title=\"Codes: {http://snomed.info/sct 365756002}\">Creatinine level</span>\n      </p>\n      <p>\n        <b>value[x]</b>: 122 umol/L\n      </p>\n      <p>\n        <b>interpretation</b>: \n        <span title=\"Codes: {http://snomed.info/sct 166717003}, {http://hl7.org/fhir/v2/0078 H}\">Serum creatinine raised</span>\n      </p>\n      <p>\n        <b>issued</b>: 4-Apr 2013 14:34\n      </p>\n      <p>\n        <b>status</b>: final_\n      </p>\n      <p>\n        <b>reliability</b>: ok\n      </p>\n      <p>\n        <b>method</b>: \n        <span title=\"Codes: {http://snomed.info/sct 113075003}\">Creatinine measurement, serum</span>\n      </p>\n      <p>\n        <b>identifier</b>: Creatinine value of Roel on April 2013 - 03720 = 1304-03720-Creatinine\n      </p>\n      <p>\n        <b>subject</b>: Roel\n      </p>\n      <p>\n        <b>performer</b>: Luigi Maas\n      </p>\n      <h3>ReferenceRanges</h3>\n      <table class=\"grid\">\n        <tr>\n          <td>\n            <b>Low</b>\n          </td>\n          <td>\n            <b>High</b>\n          </td>\n          <td>\n            <b>Meaning</b>\n          </td>\n          <td>\n            <b>Age</b>\n          </td>\n        </tr>\n        <tr>\n          <td>64 null</td>\n          <td>104 null</td>\n          <td>\n            <span title=\"Codes: {http://hl7.org/fhir/referencerange-meaning normal}\">Normal Range</span>\n          </td>\n          <td> </td>\n        </tr>\n      </table>\n    </div>")	
		XCTAssertEqual(inst!.text!.status!, "generated")	
		XCTAssertEqual(inst!.valueQuantity!.code!, "258814008")
		XCTAssertEqual(inst!.valueQuantity!.system!, NSURL(string: "http://snomed.info/sct"))	
		XCTAssertEqual(inst!.valueQuantity!.units!, "umol/L")
		XCTAssertEqual(inst!.valueQuantity!.value!, 122)
	}
	
	func testObservation10() {
		let inst = instantiateFrom("observation-example-f205-egfr.json")
		XCTAssertNotNil(inst, "Must have instantiated a Observation instance")
		
		XCTAssertEqual(inst!.identifier!.label!, "eGFR value of Roel on April 2013 - 03720")
		XCTAssertEqual(inst!.identifier!.system!, NSURL(string: "https://intranet.aumc.nl/labvalues"))	
		XCTAssertEqual(inst!.identifier!.value!, "1304-03720-eGFR")	
		XCTAssertEqual(inst!.interpretation!.coding![0].code!, "427038005")	
		XCTAssertEqual(inst!.interpretation!.coding![0].display!, "Negative for epidermal growth factor receptor expression (Non-small cell lung cancer)")
		XCTAssertEqual(inst!.interpretation!.coding![0].system!, NSURL(string: "http://snomed.info/sct"))	
		XCTAssertEqual(inst!.interpretation!.coding![1].code!, "NEG")
		XCTAssertEqual(inst!.interpretation!.coding![1].system!, NSURL(string: "http://hl7.org/fhir/v2/0078"))
		XCTAssertEqual(inst!.issued!, NSDate.dateFromISOString("2013-04-04T14:34:00+01:00")!)	
		XCTAssertEqual(inst!.method!.coding![0].code!, "129266000")	
		XCTAssertEqual(inst!.method!.coding![0].display!, "Measurement")
		XCTAssertEqual(inst!.method!.coding![0].system!, NSURL(string: "http://snomed.info/sct"))	
		XCTAssertEqual(inst!.name!.coding![0].code!, "409402009")	
		XCTAssertEqual(inst!.name!.coding![0].display!, "Epidermal Growth Factor Receptor")
		XCTAssertEqual(inst!.name!.coding![0].system!, NSURL(string: "http://snomed.info/sct"))	
		XCTAssertEqual(inst!.referenceRange![0].high!.units!, "mL/min")
		XCTAssertEqual(inst!.referenceRange![0].high!.value!, 60)	
		XCTAssertEqual(inst!.reliability!, "ok")	
		XCTAssertEqual(inst!.status!, "final")	
		XCTAssertEqual(inst!.text!.div!, "<div>\n      <p>\n        <b>Generated Narrative</b>\n      </p>\n      <p>\n        <b>name</b>: \n        <span title=\"Codes: {http://snomed.info/sct 409402009}\">Epidermal Growth Factor Receptor</span>\n      </p>\n      <p>\n        <b>value[x]</b>: 54 mL/min\n      </p>\n      <p>\n        <b>interpretation</b>: \n        <span title=\"Codes: {http://snomed.info/sct 427038005}, {http://hl7.org/fhir/v2/0078 NEG}\">Negative for epidermal growth factor receptor expression (Non-small cell lung cancer)</span>\n      </p>\n      <p>\n        <b>issued</b>: 4-Apr 2013 14:34\n      </p>\n      <p>\n        <b>status</b>: final_\n      </p>\n      <p>\n        <b>reliability</b>: ok\n      </p>\n      <p>\n        <b>method</b>: \n        <span title=\"Codes: {http://snomed.info/sct 129266000}\">Measurement</span>\n      </p>\n      <p>\n        <b>identifier</b>: eGFR value of Roel on April 2013 - 03720 = 1304-03720-eGFR\n      </p>\n      <p>\n        <b>subject</b>: Roel\n      </p>\n      <p>\n        <b>performer</b>: Luigi Maas\n      </p>\n      <h3>ReferenceRanges</h3>\n      <table class=\"grid\">\n        <tr>\n          <td>\n            <b>Low</b>\n          </td>\n          <td>\n            <b>High</b>\n          </td>\n          <td>\n            <b>Meaning</b>\n          </td>\n          <td>\n            <b>Age</b>\n          </td>\n        </tr>\n        <tr>\n          <td> </td>\n          <td>60 mL/min</td>\n          <td> </td>\n          <td> </td>\n        </tr>\n      </table>\n    </div>")	
		XCTAssertEqual(inst!.text!.status!, "generated")	
		XCTAssertEqual(inst!.valueQuantity!.code!, "258859000")
		XCTAssertEqual(inst!.valueQuantity!.system!, NSURL(string: "http://snomed.info/sct"))	
		XCTAssertEqual(inst!.valueQuantity!.units!, "mL/min")
		XCTAssertEqual(inst!.valueQuantity!.value!, 54)
	}
	
	func testObservation11() {
		let inst = instantiateFrom("observation-example-f206-staphylococcus.json")
		XCTAssertNotNil(inst, "Must have instantiated a Observation instance")
		
		XCTAssertEqual(inst!.interpretation!.coding![0].code!, "POS")
		XCTAssertEqual(inst!.interpretation!.coding![0].system!, NSURL(string: "http://hl7.org/fhir/v2/0078"))
		XCTAssertEqual(inst!.issued!, NSDate.dateFromISOString("2013-03-11T10:28:00+01:00")!)	
		XCTAssertEqual(inst!.method!.coding![0].code!, "104177005")	
		XCTAssertEqual(inst!.method!.coding![0].display!, "Blood culture for bacteria, including anaerobic screen")
		XCTAssertEqual(inst!.method!.coding![0].system!, NSURL(string: "http://snomed.info/sct"))	
		XCTAssertEqual(inst!.name!.coding![0].code!, "104177005")	
		XCTAssertEqual(inst!.name!.coding![0].display!, "Blood culture for bacteria, including anaerobic screen")
		XCTAssertEqual(inst!.name!.coding![0].system!, NSURL(string: "http://snomed.info/sct"))	
		XCTAssertEqual(inst!.reliability!, "ok")	
		XCTAssertEqual(inst!.status!, "final")	
		XCTAssertEqual(inst!.text!.div!, "<div>\n      <p>\n        <b>Generated Narrative</b>\n      </p>\n      <p>\n        <b>name</b>: \n        <span title=\"Codes: {http://snomed.info/sct 104177005}\">Blood culture for bacteria, including anaerobic screen</span>\n      </p>\n      <p>\n        <b>value[x]</b>: \n        <span title=\"Codes: {http://snomed.info/sct 8745002}\">Gram-positive bacteria</span>\n      </p>\n      <p>\n        <b>interpretation</b>: \n        <span title=\"Codes: {http://hl7.org/fhir/v2/0078 POS}\">Positive</span>\n      </p>\n      <p>\n        <b>issued</b>: 11-Mar 2013 10:28\n      </p>\n      <p>\n        <b>status</b>: final_\n      </p>\n      <p>\n        <b>reliability</b>: ok\n      </p>\n      <p>\n        <b>method</b>: \n        <span title=\"Codes: {http://snomed.info/sct 104177005}\">Blood culture for bacteria, including anaerobic screen</span>\n      </p>\n      <p>\n        <b>subject</b>: Roel\n      </p>\n      <p>\n        <b>performer</b>: Luigi Maas\n      </p>\n    </div>")	
		XCTAssertEqual(inst!.text!.status!, "generated")	
		XCTAssertEqual(inst!.valueCodeableConcept!.coding![0].code!, "8745002")	
		XCTAssertEqual(inst!.valueCodeableConcept!.coding![0].display!, "Gram-positive bacteria")
		XCTAssertEqual(inst!.valueCodeableConcept!.coding![0].system!, NSURL(string: "http://snomed.info/sct"))
	}
}
