//
//  ObservationTests.swift
//  ObservationTests
//
//  Generated from FHIR 0.4.0.3958 on 2015-01-20.
//  2015, SMART Platforms.
//

import XCTest
import SwiftFHIR


class ObservationTests: FHIRModelTestCase
{
	func instantiateFrom(filename: String) -> Observation? {
		let json = readJSONFile(filename)
		let instance = Observation(json: json)
		XCTAssertNotNil(instance, "Must have instantiated a test instance")
		return instance
	}
	
	func testObservation1() {
		let inst = instantiateFrom("observation-example-f001-glucose.canonical.json")
		XCTAssertNotNil(inst, "Must have instantiated a Observation instance")
		
		XCTAssertEqual(inst!.appliesPeriod!.end!.description, "2013-04-05T09:30:10+01:00")
		XCTAssertEqual(inst!.appliesPeriod!.start!.description, "2013-04-02T09:30:10+01:00")
		XCTAssertEqual(inst!.bodySite!.coding![0].code!, "308046002")
		XCTAssertEqual(inst!.bodySite!.coding![0].display!, "Superficial forearm vein")
		XCTAssertEqual(inst!.bodySite!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.identifier!.system!.absoluteString!, "http://www.bmc.nl/zorgportal/identifiers/observations")
		XCTAssertEqual(inst!.identifier!.use!, "official")
		XCTAssertEqual(inst!.identifier!.value!, "6323")
		XCTAssertEqual(inst!.interpretation!.coding![0].code!, "A")
		XCTAssertEqual(inst!.interpretation!.coding![0].display!, "abnormal")
		XCTAssertEqual(inst!.interpretation!.coding![0].system!.absoluteString!, "http://hl7.org/fhir/v2/0078")
		XCTAssertEqual(inst!.issued!.description, "2013-04-03T15:30:10+01:00")
		XCTAssertEqual(inst!.method!.coding![0].code!, "120220003")
		XCTAssertEqual(inst!.method!.coding![0].display!, "Injection to forearm")
		XCTAssertEqual(inst!.method!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.name!.coding![0].code!, "15074-8")
		XCTAssertEqual(inst!.name!.coding![0].display!, "Glucose [Moles/volume] in Blood")
		XCTAssertEqual(inst!.name!.coding![0].system!.absoluteString!, "http://loinc.org")
		XCTAssertEqual(inst!.performer![0].display!, "A. Langeveld")
		XCTAssertEqual(inst!.performer![0].reference!, "Practitioner/f005")
		XCTAssertEqual(inst!.referenceRange![0].high!.code!, "mmol/L")
		XCTAssertEqual(inst!.referenceRange![0].high!.system!.absoluteString!, "http://unitsofmeasure.org")
		XCTAssertEqual(inst!.referenceRange![0].high!.units!, "mmol/l")
		XCTAssertEqual(inst!.referenceRange![0].high!.value!, NSDecimalNumber(string: "6.2"))
		XCTAssertEqual(inst!.referenceRange![0].low!.code!, "mmol/L")
		XCTAssertEqual(inst!.referenceRange![0].low!.system!.absoluteString!, "http://unitsofmeasure.org")
		XCTAssertEqual(inst!.referenceRange![0].low!.units!, "mmol/l")
		XCTAssertEqual(inst!.referenceRange![0].low!.value!, NSDecimalNumber(string: "3.1"))
		XCTAssertEqual(inst!.reliability!, "ok")
		XCTAssertEqual(inst!.status!, "final")
		XCTAssertEqual(inst!.subject!.display!, "P. van de Heuvel")
		XCTAssertEqual(inst!.subject!.reference!, "Patient/f001")
		XCTAssertEqual(inst!.valueQuantity!.code!, "mmol/L")
		XCTAssertEqual(inst!.valueQuantity!.system!.absoluteString!, "http://unitsofmeasure.org")
		XCTAssertEqual(inst!.valueQuantity!.units!, "mmol/l")
		XCTAssertEqual(inst!.valueQuantity!.value!, NSDecimalNumber(string: "6.3"))
	}
	
	func testObservation2() {
		let inst = instantiateFrom("observation-example-f001-glucose.canonical.json")
		XCTAssertNotNil(inst, "Must have instantiated a Observation instance")
		
		XCTAssertEqual(inst!.appliesPeriod!.end!.description, "2013-04-05T09:30:10+01:00")
		XCTAssertEqual(inst!.appliesPeriod!.start!.description, "2013-04-02T09:30:10+01:00")
		XCTAssertEqual(inst!.bodySite!.coding![0].code!, "308046002")
		XCTAssertEqual(inst!.bodySite!.coding![0].display!, "Superficial forearm vein")
		XCTAssertEqual(inst!.bodySite!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.identifier!.system!.absoluteString!, "http://www.bmc.nl/zorgportal/identifiers/observations")
		XCTAssertEqual(inst!.identifier!.use!, "official")
		XCTAssertEqual(inst!.identifier!.value!, "6323")
		XCTAssertEqual(inst!.interpretation!.coding![0].code!, "A")
		XCTAssertEqual(inst!.interpretation!.coding![0].display!, "abnormal")
		XCTAssertEqual(inst!.interpretation!.coding![0].system!.absoluteString!, "http://hl7.org/fhir/v2/0078")
		XCTAssertEqual(inst!.issued!.description, "2013-04-03T15:30:10+01:00")
		XCTAssertEqual(inst!.method!.coding![0].code!, "120220003")
		XCTAssertEqual(inst!.method!.coding![0].display!, "Injection to forearm")
		XCTAssertEqual(inst!.method!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.name!.coding![0].code!, "15074-8")
		XCTAssertEqual(inst!.name!.coding![0].display!, "Glucose [Moles/volume] in Blood")
		XCTAssertEqual(inst!.name!.coding![0].system!.absoluteString!, "http://loinc.org")
		XCTAssertEqual(inst!.performer![0].display!, "A. Langeveld")
		XCTAssertEqual(inst!.performer![0].reference!, "Practitioner/f005")
		XCTAssertEqual(inst!.referenceRange![0].high!.code!, "mmol/L")
		XCTAssertEqual(inst!.referenceRange![0].high!.system!.absoluteString!, "http://unitsofmeasure.org")
		XCTAssertEqual(inst!.referenceRange![0].high!.units!, "mmol/l")
		XCTAssertEqual(inst!.referenceRange![0].high!.value!, NSDecimalNumber(string: "6.2"))
		XCTAssertEqual(inst!.referenceRange![0].low!.code!, "mmol/L")
		XCTAssertEqual(inst!.referenceRange![0].low!.system!.absoluteString!, "http://unitsofmeasure.org")
		XCTAssertEqual(inst!.referenceRange![0].low!.units!, "mmol/l")
		XCTAssertEqual(inst!.referenceRange![0].low!.value!, NSDecimalNumber(string: "3.1"))
		XCTAssertEqual(inst!.reliability!, "ok")
		XCTAssertEqual(inst!.status!, "final")
		XCTAssertEqual(inst!.subject!.display!, "P. van de Heuvel")
		XCTAssertEqual(inst!.subject!.reference!, "Patient/f001")
		XCTAssertEqual(inst!.valueQuantity!.code!, "mmol/L")
		XCTAssertEqual(inst!.valueQuantity!.system!.absoluteString!, "http://unitsofmeasure.org")
		XCTAssertEqual(inst!.valueQuantity!.units!, "mmol/l")
		XCTAssertEqual(inst!.valueQuantity!.value!, NSDecimalNumber(string: "6.3"))
	}
	
	func testObservation3() {
		let inst = instantiateFrom("observation-example-f001-glucose.json")
		XCTAssertNotNil(inst, "Must have instantiated a Observation instance")
		
		XCTAssertEqual(inst!.appliesPeriod!.end!.description, "2013-04-05T09:30:10+01:00")
		XCTAssertEqual(inst!.appliesPeriod!.start!.description, "2013-04-02T09:30:10+01:00")
		XCTAssertEqual(inst!.bodySite!.coding![0].code!, "308046002")
		XCTAssertEqual(inst!.bodySite!.coding![0].display!, "Superficial forearm vein")
		XCTAssertEqual(inst!.bodySite!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.identifier!.system!.absoluteString!, "http://www.bmc.nl/zorgportal/identifiers/observations")
		XCTAssertEqual(inst!.identifier!.use!, "official")
		XCTAssertEqual(inst!.identifier!.value!, "6323")
		XCTAssertEqual(inst!.interpretation!.coding![0].code!, "A")
		XCTAssertEqual(inst!.interpretation!.coding![0].display!, "abnormal")
		XCTAssertEqual(inst!.interpretation!.coding![0].system!.absoluteString!, "http://hl7.org/fhir/v2/0078")
		XCTAssertEqual(inst!.issued!.description, "2013-04-03T15:30:10+01:00")
		XCTAssertEqual(inst!.method!.coding![0].code!, "120220003")
		XCTAssertEqual(inst!.method!.coding![0].display!, "Injection to forearm")
		XCTAssertEqual(inst!.method!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.name!.coding![0].code!, "15074-8")
		XCTAssertEqual(inst!.name!.coding![0].display!, "Glucose [Moles/volume] in Blood")
		XCTAssertEqual(inst!.name!.coding![0].system!.absoluteString!, "http://loinc.org")
		XCTAssertEqual(inst!.performer![0].display!, "A. Langeveld")
		XCTAssertEqual(inst!.performer![0].reference!, "Practitioner/f005")
		XCTAssertEqual(inst!.referenceRange![0].high!.code!, "mmol/L")
		XCTAssertEqual(inst!.referenceRange![0].high!.system!.absoluteString!, "http://unitsofmeasure.org")
		XCTAssertEqual(inst!.referenceRange![0].high!.units!, "mmol/l")
		XCTAssertEqual(inst!.referenceRange![0].high!.value!, NSDecimalNumber(string: "6.2"))
		XCTAssertEqual(inst!.referenceRange![0].low!.code!, "mmol/L")
		XCTAssertEqual(inst!.referenceRange![0].low!.system!.absoluteString!, "http://unitsofmeasure.org")
		XCTAssertEqual(inst!.referenceRange![0].low!.units!, "mmol/l")
		XCTAssertEqual(inst!.referenceRange![0].low!.value!, NSDecimalNumber(string: "3.1"))
		XCTAssertEqual(inst!.reliability!, "ok")
		XCTAssertEqual(inst!.status!, "final")
		XCTAssertEqual(inst!.subject!.display!, "P. van de Heuvel")
		XCTAssertEqual(inst!.subject!.reference!, "Patient/f001")
		XCTAssertEqual(inst!.valueQuantity!.code!, "mmol/L")
		XCTAssertEqual(inst!.valueQuantity!.system!.absoluteString!, "http://unitsofmeasure.org")
		XCTAssertEqual(inst!.valueQuantity!.units!, "mmol/l")
		XCTAssertEqual(inst!.valueQuantity!.value!, NSDecimalNumber(string: "6.3"))
	}
	
	func testObservation4() {
		let inst = instantiateFrom("observation-example-f002-excess.canonical.json")
		XCTAssertNotNil(inst, "Must have instantiated a Observation instance")
		
		XCTAssertEqual(inst!.appliesPeriod!.end!.description, "2013-04-05T10:30:10+01:00")
		XCTAssertEqual(inst!.appliesPeriod!.start!.description, "2013-04-02T10:30:10+01:00")
		XCTAssertEqual(inst!.bodySite!.coding![0].code!, "308046002")
		XCTAssertEqual(inst!.bodySite!.coding![0].display!, "Superficial forearm vein")
		XCTAssertEqual(inst!.bodySite!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.identifier!.system!.absoluteString!, "http://www.bmc.nl/zorgportal/identifiers/observations")
		XCTAssertEqual(inst!.identifier!.use!, "official")
		XCTAssertEqual(inst!.identifier!.value!, "6324")
		XCTAssertEqual(inst!.interpretation!.coding![0].code!, "A")
		XCTAssertEqual(inst!.interpretation!.coding![0].display!, "abnormal")
		XCTAssertEqual(inst!.interpretation!.coding![0].system!.absoluteString!, "http://hl7.org/fhir/v2/0078")
		XCTAssertEqual(inst!.issued!.description, "2013-04-03T15:30:10+01:00")
		XCTAssertEqual(inst!.method!.coding![0].code!, "120220003")
		XCTAssertEqual(inst!.method!.coding![0].display!, "Injection to forearm")
		XCTAssertEqual(inst!.method!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.name!.coding![0].code!, "11555-0")
		XCTAssertEqual(inst!.name!.coding![0].display!, "Base excess in Blood by calculation")
		XCTAssertEqual(inst!.name!.coding![0].system!.absoluteString!, "http://loinc.org")
		XCTAssertEqual(inst!.performer![0].display!, "A. Langeveld")
		XCTAssertEqual(inst!.performer![0].reference!, "Practitioner/f005")
		XCTAssertEqual(inst!.referenceRange![0].high!.code!, "mmol/L")
		XCTAssertEqual(inst!.referenceRange![0].high!.system!.absoluteString!, "http://unitsofmeasure.org")
		XCTAssertEqual(inst!.referenceRange![0].high!.units!, "mmol/l")
		XCTAssertEqual(inst!.referenceRange![0].high!.value!, NSDecimalNumber(string: "11.2"))
		XCTAssertEqual(inst!.referenceRange![0].low!.code!, "mmol/L")
		XCTAssertEqual(inst!.referenceRange![0].low!.system!.absoluteString!, "http://unitsofmeasure.org")
		XCTAssertEqual(inst!.referenceRange![0].low!.units!, "mmol/l")
		XCTAssertEqual(inst!.referenceRange![0].low!.value!, NSDecimalNumber(string: "7.1"))
		XCTAssertEqual(inst!.reliability!, "ok")
		XCTAssertEqual(inst!.status!, "final")
		XCTAssertEqual(inst!.subject!.display!, "P. van de Heuvel")
		XCTAssertEqual(inst!.subject!.reference!, "Patient/f001")
		XCTAssertEqual(inst!.valueQuantity!.code!, "mmol/L")
		XCTAssertEqual(inst!.valueQuantity!.system!.absoluteString!, "http://unitsofmeasure.org")
		XCTAssertEqual(inst!.valueQuantity!.units!, "mmol/l")
		XCTAssertEqual(inst!.valueQuantity!.value!, NSDecimalNumber(string: "12.6"))
	}
	
	func testObservation5() {
		let inst = instantiateFrom("observation-example-f002-excess.json")
		XCTAssertNotNil(inst, "Must have instantiated a Observation instance")
		
		XCTAssertEqual(inst!.appliesPeriod!.end!.description, "2013-04-05T10:30:10+01:00")
		XCTAssertEqual(inst!.appliesPeriod!.start!.description, "2013-04-02T10:30:10+01:00")
		XCTAssertEqual(inst!.bodySite!.coding![0].code!, "308046002")
		XCTAssertEqual(inst!.bodySite!.coding![0].display!, "Superficial forearm vein")
		XCTAssertEqual(inst!.bodySite!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.identifier!.system!.absoluteString!, "http://www.bmc.nl/zorgportal/identifiers/observations")
		XCTAssertEqual(inst!.identifier!.use!, "official")
		XCTAssertEqual(inst!.identifier!.value!, "6324")
		XCTAssertEqual(inst!.interpretation!.coding![0].code!, "A")
		XCTAssertEqual(inst!.interpretation!.coding![0].display!, "abnormal")
		XCTAssertEqual(inst!.interpretation!.coding![0].system!.absoluteString!, "http://hl7.org/fhir/v2/0078")
		XCTAssertEqual(inst!.issued!.description, "2013-04-03T15:30:10+01:00")
		XCTAssertEqual(inst!.method!.coding![0].code!, "120220003")
		XCTAssertEqual(inst!.method!.coding![0].display!, "Injection to forearm")
		XCTAssertEqual(inst!.method!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.name!.coding![0].code!, "11555-0")
		XCTAssertEqual(inst!.name!.coding![0].display!, "Base excess in Blood by calculation")
		XCTAssertEqual(inst!.name!.coding![0].system!.absoluteString!, "http://loinc.org")
		XCTAssertEqual(inst!.performer![0].display!, "A. Langeveld")
		XCTAssertEqual(inst!.performer![0].reference!, "Practitioner/f005")
		XCTAssertEqual(inst!.referenceRange![0].high!.code!, "mmol/L")
		XCTAssertEqual(inst!.referenceRange![0].high!.system!.absoluteString!, "http://unitsofmeasure.org")
		XCTAssertEqual(inst!.referenceRange![0].high!.units!, "mmol/l")
		XCTAssertEqual(inst!.referenceRange![0].high!.value!, NSDecimalNumber(string: "11.2"))
		XCTAssertEqual(inst!.referenceRange![0].low!.code!, "mmol/L")
		XCTAssertEqual(inst!.referenceRange![0].low!.system!.absoluteString!, "http://unitsofmeasure.org")
		XCTAssertEqual(inst!.referenceRange![0].low!.units!, "mmol/l")
		XCTAssertEqual(inst!.referenceRange![0].low!.value!, NSDecimalNumber(string: "7.1"))
		XCTAssertEqual(inst!.reliability!, "ok")
		XCTAssertEqual(inst!.status!, "final")
		XCTAssertEqual(inst!.subject!.display!, "P. van de Heuvel")
		XCTAssertEqual(inst!.subject!.reference!, "Patient/f001")
		XCTAssertEqual(inst!.valueQuantity!.code!, "mmol/L")
		XCTAssertEqual(inst!.valueQuantity!.system!.absoluteString!, "http://unitsofmeasure.org")
		XCTAssertEqual(inst!.valueQuantity!.units!, "mmol/l")
		XCTAssertEqual(inst!.valueQuantity!.value!, NSDecimalNumber(string: "12.6"))
	}
	
	func testObservation6() {
		let inst = instantiateFrom("observation-example-f003-co2.canonical.json")
		XCTAssertNotNil(inst, "Must have instantiated a Observation instance")
		
		XCTAssertEqual(inst!.appliesPeriod!.end!.description, "2013-04-05T10:30:10+01:00")
		XCTAssertEqual(inst!.appliesPeriod!.start!.description, "2013-04-02T10:30:10+01:00")
		XCTAssertEqual(inst!.bodySite!.coding![0].code!, "308046002")
		XCTAssertEqual(inst!.bodySite!.coding![0].display!, "Superficial forearm vein")
		XCTAssertEqual(inst!.bodySite!.coding![0].system!.absoluteString!, "http://snomed.info/id")
		XCTAssertEqual(inst!.identifier!.system!.absoluteString!, "http://www.bmc.nl/zorgportal/identifiers/observations")
		XCTAssertEqual(inst!.identifier!.use!, "official")
		XCTAssertEqual(inst!.identifier!.value!, "6325")
		XCTAssertEqual(inst!.interpretation!.coding![0].code!, "A")
		XCTAssertEqual(inst!.interpretation!.coding![0].display!, "abnormal")
		XCTAssertEqual(inst!.interpretation!.coding![0].system!.absoluteString!, "http://hl7.org/fhir/v2/0078")
		XCTAssertEqual(inst!.issued!.description, "2013-04-03T15:30:10+01:00")
		XCTAssertEqual(inst!.method!.coding![0].code!, "120220003")
		XCTAssertEqual(inst!.method!.coding![0].display!, "Injection to forearm")
		XCTAssertEqual(inst!.method!.coding![0].system!.absoluteString!, "http://snomed.info/id")
		XCTAssertEqual(inst!.name!.coding![0].code!, "11557-6")
		XCTAssertEqual(inst!.name!.coding![0].display!, "Carbon dioxide in blood")
		XCTAssertEqual(inst!.name!.coding![0].system!.absoluteString!, "http://loinc.org")
		XCTAssertEqual(inst!.performer![0].display!, "A. Langeveld")
		XCTAssertEqual(inst!.performer![0].reference!, "Practitioner/f005")
		XCTAssertEqual(inst!.referenceRange![0].high!.code!, "kPa")
		XCTAssertEqual(inst!.referenceRange![0].high!.system!.absoluteString!, "http://unitsofmeasure.org")
		XCTAssertEqual(inst!.referenceRange![0].high!.units!, "kPa")
		XCTAssertEqual(inst!.referenceRange![0].high!.value!, NSDecimalNumber(string: "6.0"))
		XCTAssertEqual(inst!.referenceRange![0].low!.code!, "kPa")
		XCTAssertEqual(inst!.referenceRange![0].low!.system!.absoluteString!, "http://unitsofmeasure.org")
		XCTAssertEqual(inst!.referenceRange![0].low!.units!, "kPa")
		XCTAssertEqual(inst!.referenceRange![0].low!.value!, NSDecimalNumber(string: "4.8"))
		XCTAssertEqual(inst!.reliability!, "ok")
		XCTAssertEqual(inst!.status!, "final")
		XCTAssertEqual(inst!.subject!.display!, "P. van de Heuvel")
		XCTAssertEqual(inst!.subject!.reference!, "Patient/f001")
		XCTAssertEqual(inst!.valueQuantity!.code!, "kPa")
		XCTAssertEqual(inst!.valueQuantity!.system!.absoluteString!, "http://unitsofmeasure.org")
		XCTAssertEqual(inst!.valueQuantity!.units!, "kPa")
		XCTAssertEqual(inst!.valueQuantity!.value!, NSDecimalNumber(string: "6.2"))
	}
	
	func testObservation7() {
		let inst = instantiateFrom("observation-example-f003-co2.json")
		XCTAssertNotNil(inst, "Must have instantiated a Observation instance")
		
		XCTAssertEqual(inst!.appliesPeriod!.end!.description, "2013-04-05T10:30:10+01:00")
		XCTAssertEqual(inst!.appliesPeriod!.start!.description, "2013-04-02T10:30:10+01:00")
		XCTAssertEqual(inst!.bodySite!.coding![0].code!, "308046002")
		XCTAssertEqual(inst!.bodySite!.coding![0].display!, "Superficial forearm vein")
		XCTAssertEqual(inst!.bodySite!.coding![0].system!.absoluteString!, "http://snomed.info/id")
		XCTAssertEqual(inst!.identifier!.system!.absoluteString!, "http://www.bmc.nl/zorgportal/identifiers/observations")
		XCTAssertEqual(inst!.identifier!.use!, "official")
		XCTAssertEqual(inst!.identifier!.value!, "6325")
		XCTAssertEqual(inst!.interpretation!.coding![0].code!, "A")
		XCTAssertEqual(inst!.interpretation!.coding![0].display!, "abnormal")
		XCTAssertEqual(inst!.interpretation!.coding![0].system!.absoluteString!, "http://hl7.org/fhir/v2/0078")
		XCTAssertEqual(inst!.issued!.description, "2013-04-03T15:30:10+01:00")
		XCTAssertEqual(inst!.method!.coding![0].code!, "120220003")
		XCTAssertEqual(inst!.method!.coding![0].display!, "Injection to forearm")
		XCTAssertEqual(inst!.method!.coding![0].system!.absoluteString!, "http://snomed.info/id")
		XCTAssertEqual(inst!.name!.coding![0].code!, "11557-6")
		XCTAssertEqual(inst!.name!.coding![0].display!, "Carbon dioxide in blood")
		XCTAssertEqual(inst!.name!.coding![0].system!.absoluteString!, "http://loinc.org")
		XCTAssertEqual(inst!.performer![0].display!, "A. Langeveld")
		XCTAssertEqual(inst!.performer![0].reference!, "Practitioner/f005")
		XCTAssertEqual(inst!.referenceRange![0].high!.code!, "kPa")
		XCTAssertEqual(inst!.referenceRange![0].high!.system!.absoluteString!, "http://unitsofmeasure.org")
		XCTAssertEqual(inst!.referenceRange![0].high!.units!, "kPa")
		XCTAssertEqual(inst!.referenceRange![0].high!.value!, NSDecimalNumber(string: "6.0"))
		XCTAssertEqual(inst!.referenceRange![0].low!.code!, "kPa")
		XCTAssertEqual(inst!.referenceRange![0].low!.system!.absoluteString!, "http://unitsofmeasure.org")
		XCTAssertEqual(inst!.referenceRange![0].low!.units!, "kPa")
		XCTAssertEqual(inst!.referenceRange![0].low!.value!, NSDecimalNumber(string: "4.8"))
		XCTAssertEqual(inst!.reliability!, "ok")
		XCTAssertEqual(inst!.status!, "final")
		XCTAssertEqual(inst!.subject!.display!, "P. van de Heuvel")
		XCTAssertEqual(inst!.subject!.reference!, "Patient/f001")
		XCTAssertEqual(inst!.valueQuantity!.code!, "kPa")
		XCTAssertEqual(inst!.valueQuantity!.system!.absoluteString!, "http://unitsofmeasure.org")
		XCTAssertEqual(inst!.valueQuantity!.units!, "kPa")
		XCTAssertEqual(inst!.valueQuantity!.value!, NSDecimalNumber(string: "6.2"))
	}
	
	func testObservation8() {
		let inst = instantiateFrom("observation-example-f004-erythrocyte.canonical.json")
		XCTAssertNotNil(inst, "Must have instantiated a Observation instance")
		
		XCTAssertEqual(inst!.appliesPeriod!.end!.description, "2013-04-05T10:30:10+01:00")
		XCTAssertEqual(inst!.appliesPeriod!.start!.description, "2013-04-02T10:30:10+01:00")
		XCTAssertEqual(inst!.bodySite!.coding![0].code!, "308046002")
		XCTAssertEqual(inst!.bodySite!.coding![0].display!, "Superficial forearm vein")
		XCTAssertEqual(inst!.bodySite!.coding![0].system!.absoluteString!, "http://snomed.info/id")
		XCTAssertEqual(inst!.identifier!.system!.absoluteString!, "http://www.bmc.nl/zorgportal/identifiers/observations")
		XCTAssertEqual(inst!.identifier!.use!, "official")
		XCTAssertEqual(inst!.identifier!.value!, "6326")
		XCTAssertEqual(inst!.interpretation!.coding![0].code!, "A")
		XCTAssertEqual(inst!.interpretation!.coding![0].display!, "abnormal")
		XCTAssertEqual(inst!.interpretation!.coding![0].system!.absoluteString!, "http://hl7.org/fhir/v2/0078")
		XCTAssertEqual(inst!.issued!.description, "2013-04-03T15:30:10+01:00")
		XCTAssertEqual(inst!.method!.coding![0].code!, "120220003")
		XCTAssertEqual(inst!.method!.coding![0].display!, "Injection to forearm")
		XCTAssertEqual(inst!.method!.coding![0].system!.absoluteString!, "http://snomed.info/id")
		XCTAssertEqual(inst!.name!.coding![0].code!, "789-8")
		XCTAssertEqual(inst!.name!.coding![0].display!, "Erythrocytes [#/volume] in Blood by Automated count")
		XCTAssertEqual(inst!.name!.coding![0].system!.absoluteString!, "http://loinc.org")
		XCTAssertEqual(inst!.performer![0].display!, "A. Langeveld")
		XCTAssertEqual(inst!.performer![0].reference!, "Practitioner/f005")
		XCTAssertEqual(inst!.referenceRange![0].high!.code!, "10*12/L")
		XCTAssertEqual(inst!.referenceRange![0].high!.system!.absoluteString!, "http://unitsofmeasure.org")
		XCTAssertEqual(inst!.referenceRange![0].high!.units!, "10^12/L")
		XCTAssertEqual(inst!.referenceRange![0].high!.value!, NSDecimalNumber(string: "5.8"))
		XCTAssertEqual(inst!.referenceRange![0].low!.code!, "10*12/L")
		XCTAssertEqual(inst!.referenceRange![0].low!.system!.absoluteString!, "http://unitsofmeasure.org")
		XCTAssertEqual(inst!.referenceRange![0].low!.units!, "10^12/L")
		XCTAssertEqual(inst!.referenceRange![0].low!.value!, NSDecimalNumber(string: "4.4"))
		XCTAssertEqual(inst!.reliability!, "ok")
		XCTAssertEqual(inst!.status!, "final")
		XCTAssertEqual(inst!.subject!.display!, "P. van de Heuvel")
		XCTAssertEqual(inst!.subject!.reference!, "Patient/f001")
		XCTAssertEqual(inst!.valueQuantity!.code!, "10*12/L")
		XCTAssertEqual(inst!.valueQuantity!.system!.absoluteString!, "http://unitsofmeasure.org")
		XCTAssertEqual(inst!.valueQuantity!.units!, "10^12/L")
		XCTAssertEqual(inst!.valueQuantity!.value!, NSDecimalNumber(string: "4.12"))
	}
	
	func testObservation9() {
		let inst = instantiateFrom("observation-example-f004-erythrocyte.json")
		XCTAssertNotNil(inst, "Must have instantiated a Observation instance")
		
		XCTAssertEqual(inst!.appliesPeriod!.end!.description, "2013-04-05T10:30:10+01:00")
		XCTAssertEqual(inst!.appliesPeriod!.start!.description, "2013-04-02T10:30:10+01:00")
		XCTAssertEqual(inst!.bodySite!.coding![0].code!, "308046002")
		XCTAssertEqual(inst!.bodySite!.coding![0].display!, "Superficial forearm vein")
		XCTAssertEqual(inst!.bodySite!.coding![0].system!.absoluteString!, "http://snomed.info/id")
		XCTAssertEqual(inst!.identifier!.system!.absoluteString!, "http://www.bmc.nl/zorgportal/identifiers/observations")
		XCTAssertEqual(inst!.identifier!.use!, "official")
		XCTAssertEqual(inst!.identifier!.value!, "6326")
		XCTAssertEqual(inst!.interpretation!.coding![0].code!, "A")
		XCTAssertEqual(inst!.interpretation!.coding![0].display!, "abnormal")
		XCTAssertEqual(inst!.interpretation!.coding![0].system!.absoluteString!, "http://hl7.org/fhir/v2/0078")
		XCTAssertEqual(inst!.issued!.description, "2013-04-03T15:30:10+01:00")
		XCTAssertEqual(inst!.method!.coding![0].code!, "120220003")
		XCTAssertEqual(inst!.method!.coding![0].display!, "Injection to forearm")
		XCTAssertEqual(inst!.method!.coding![0].system!.absoluteString!, "http://snomed.info/id")
		XCTAssertEqual(inst!.name!.coding![0].code!, "789-8")
		XCTAssertEqual(inst!.name!.coding![0].display!, "Erythrocytes [#/volume] in Blood by Automated count")
		XCTAssertEqual(inst!.name!.coding![0].system!.absoluteString!, "http://loinc.org")
		XCTAssertEqual(inst!.performer![0].display!, "A. Langeveld")
		XCTAssertEqual(inst!.performer![0].reference!, "Practitioner/f005")
		XCTAssertEqual(inst!.referenceRange![0].high!.code!, "10*12/L")
		XCTAssertEqual(inst!.referenceRange![0].high!.system!.absoluteString!, "http://unitsofmeasure.org")
		XCTAssertEqual(inst!.referenceRange![0].high!.units!, "10^12/L")
		XCTAssertEqual(inst!.referenceRange![0].high!.value!, NSDecimalNumber(string: "5.8"))
		XCTAssertEqual(inst!.referenceRange![0].low!.code!, "10*12/L")
		XCTAssertEqual(inst!.referenceRange![0].low!.system!.absoluteString!, "http://unitsofmeasure.org")
		XCTAssertEqual(inst!.referenceRange![0].low!.units!, "10^12/L")
		XCTAssertEqual(inst!.referenceRange![0].low!.value!, NSDecimalNumber(string: "4.4"))
		XCTAssertEqual(inst!.reliability!, "ok")
		XCTAssertEqual(inst!.status!, "final")
		XCTAssertEqual(inst!.subject!.display!, "P. van de Heuvel")
		XCTAssertEqual(inst!.subject!.reference!, "Patient/f001")
		XCTAssertEqual(inst!.valueQuantity!.code!, "10*12/L")
		XCTAssertEqual(inst!.valueQuantity!.system!.absoluteString!, "http://unitsofmeasure.org")
		XCTAssertEqual(inst!.valueQuantity!.units!, "10^12/L")
		XCTAssertEqual(inst!.valueQuantity!.value!, NSDecimalNumber(string: "4.12"))
	}
	
	func testObservation10() {
		let inst = instantiateFrom("observation-example-f005-hemoglobin.canonical.json")
		XCTAssertNotNil(inst, "Must have instantiated a Observation instance")
		
		XCTAssertEqual(inst!.appliesPeriod!.end!.description, "2013-04-05T10:30:10+01:00")
		XCTAssertEqual(inst!.appliesPeriod!.start!.description, "2013-04-02T10:30:10+01:00")
		XCTAssertEqual(inst!.bodySite!.coding![0].code!, "308046002")
		XCTAssertEqual(inst!.bodySite!.coding![0].display!, "Superficial forearm vein")
		XCTAssertEqual(inst!.bodySite!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.identifier!.system!.absoluteString!, "http://www.bmc.nl/zorgportal/identifiers/observations")
		XCTAssertEqual(inst!.identifier!.use!, "official")
		XCTAssertEqual(inst!.identifier!.value!, "6327")
		XCTAssertEqual(inst!.interpretation!.coding![0].code!, "L")
		XCTAssertEqual(inst!.interpretation!.coding![0].display!, "low")
		XCTAssertEqual(inst!.interpretation!.coding![0].system!.absoluteString!, "http://hl7.org/fhir/v2/0078")
		XCTAssertEqual(inst!.issued!.description, "2013-04-03T15:30:10+01:00")
		XCTAssertEqual(inst!.method!.coding![0].code!, "120220003")
		XCTAssertEqual(inst!.method!.coding![0].display!, "Injection to forearm")
		XCTAssertEqual(inst!.method!.coding![0].system!.absoluteString!, "http://snomed.info/sct")
		XCTAssertEqual(inst!.name!.coding![0].code!, "30350-3")
		XCTAssertEqual(inst!.name!.coding![0].display!, "Hemoglobin [Mass/volume] in Venous blood")
		XCTAssertEqual(inst!.name!.coding![0].system!.absoluteString!, "http://loinc.org")
		XCTAssertEqual(inst!.performer![0].display!, "A. Langeveld")
		XCTAssertEqual(inst!.performer![0].reference!, "Practitioner/f005")
		XCTAssertEqual(inst!.referenceRange![0].high!.code!, "g/dL")
		XCTAssertEqual(inst!.referenceRange![0].high!.system!.absoluteString!, "http://unitsofmeasure.org")
		XCTAssertEqual(inst!.referenceRange![0].high!.units!, "g/dl")
		XCTAssertEqual(inst!.referenceRange![0].high!.value!, NSDecimalNumber(string: "10"))
		XCTAssertEqual(inst!.referenceRange![0].low!.code!, "g/dL")
		XCTAssertEqual(inst!.referenceRange![0].low!.system!.absoluteString!, "http://unitsofmeasure.org")
		XCTAssertEqual(inst!.referenceRange![0].low!.units!, "g/dl")
		XCTAssertEqual(inst!.referenceRange![0].low!.value!, NSDecimalNumber(string: "7.5"))
		XCTAssertEqual(inst!.reliability!, "ok")
		XCTAssertEqual(inst!.status!, "final")
		XCTAssertEqual(inst!.subject!.display!, "P. van de Heuvel")
		XCTAssertEqual(inst!.subject!.reference!, "Patient/f001")
		XCTAssertEqual(inst!.valueQuantity!.code!, "g/dL")
		XCTAssertEqual(inst!.valueQuantity!.system!.absoluteString!, "http://unitsofmeasure.org")
		XCTAssertEqual(inst!.valueQuantity!.units!, "g/dl")
		XCTAssertEqual(inst!.valueQuantity!.value!, NSDecimalNumber(string: "7.2"))
	}
}
