//
//  OralHealthClaimTests.swift
//  OralHealthClaimTests
//
//  Generated from FHIR 0.4.0.4394 on 2015-03-11.
//  2015, SMART Platforms.
//

import XCTest
import SwiftFHIR


class OralHealthClaimTests: FHIRModelTestCase
{
	func instantiateFrom(# filename: String) -> OralHealthClaim {
		return instantiateFrom(json: readJSONFile(filename)!)
	}
	
	func instantiateFrom(# json: JSONDictionary) -> OralHealthClaim {
		let instance = OralHealthClaim(json: json)
		XCTAssertNotNil(instance, "Must have instantiated a test instance")
		return instance
	}
	
	func testOralHealthClaim1() {
		let instance = testOralHealthClaim1_impl()
		testOralHealthClaim1_impl(json: instance.asJSON())
	}
	
	func testOralHealthClaim1_impl(json: JSONDictionary? = nil) -> OralHealthClaim {
		let inst = (nil != json) ? instantiateFrom(json: json!) : instantiateFrom(filename: "oralhealthclaim-example-average.json")
		
		XCTAssertEqual(inst.coverage![0].coverage!.reference!, "Coverage/9876B1")
		XCTAssertTrue(inst.coverage![0].focal!)
		XCTAssertEqual(inst.coverage![0].relationship!.code!, "self")
		XCTAssertEqual(inst.coverage![0].sequence!, 1)
		XCTAssertEqual(inst.created!.description, "2014-08-16")
		XCTAssertEqual(inst.diagnosis![0].diagnosis!.code!, "123456")
		XCTAssertEqual(inst.diagnosis![0].sequence!, 1)
		XCTAssertEqual(inst.id!, "100151")
		XCTAssertEqual(inst.identifier![0].system!.absoluteString!, "http://happyvalley.com/claims")
		XCTAssertEqual(inst.identifier![0].value!, "12346")
		XCTAssertEqual(inst.item![0].net!.code!, "USD")
		XCTAssertEqual(inst.item![0].net!.system!.absoluteString!, "urn:std:iso:4217")
		XCTAssertEqual(inst.item![0].net!.value!, NSDecimalNumber(string: "135.57"))
		XCTAssertEqual(inst.item![0].provider!.reference!, "Practitioner/1")
		XCTAssertEqual(inst.item![0].sequence!, 1)
		XCTAssertEqual(inst.item![0].service!.code!, "1200")
		XCTAssertEqual(inst.item![0].service!.system!.absoluteString!, "http://hl7.org/fhir/oralservicecodes")
		XCTAssertEqual(inst.item![0].serviceDate!.description, "2014-08-16")
		XCTAssertEqual(inst.item![0].type!.code!, "service")
		XCTAssertEqual(inst.item![0].unitPrice!.code!, "USD")
		XCTAssertEqual(inst.item![0].unitPrice!.system!.absoluteString!, "urn:std:iso:4217")
		XCTAssertEqual(inst.item![0].unitPrice!.value!, NSDecimalNumber(string: "135.57"))
		XCTAssertEqual(inst.item![1].bodySite!.code!, "21")
		XCTAssertEqual(inst.item![1].bodySite!.system!.absoluteString!, "http://fdi.org/fhir/oraltoothcodes")
		XCTAssertEqual(inst.item![1].net!.code!, "USD")
		XCTAssertEqual(inst.item![1].net!.system!.absoluteString!, "urn:std:iso:4217")
		XCTAssertEqual(inst.item![1].net!.value!, NSDecimalNumber(string: "105.0"))
		XCTAssertEqual(inst.item![1].provider!.reference!, "Practitioner/1")
		XCTAssertEqual(inst.item![1].sequence!, 2)
		XCTAssertEqual(inst.item![1].service!.code!, "21211")
		XCTAssertEqual(inst.item![1].service!.system!.absoluteString!, "http://hl7.org/fhir/oralservicecodes")
		XCTAssertEqual(inst.item![1].serviceDate!.description, "2014-08-16")
		XCTAssertEqual(inst.item![1].subSite![0].code!, "L")
		XCTAssertEqual(inst.item![1].subSite![0].system!.absoluteString!, "http://fdi.org/fhir/oralsurfacecodes")
		XCTAssertEqual(inst.item![1].type!.code!, "service")
		XCTAssertEqual(inst.item![1].unitPrice!.code!, "USD")
		XCTAssertEqual(inst.item![1].unitPrice!.system!.absoluteString!, "urn:std:iso:4217")
		XCTAssertEqual(inst.item![1].unitPrice!.value!, NSDecimalNumber(string: "105.0"))
		XCTAssertEqual(inst.item![2].bodySite!.code!, "36")
		XCTAssertEqual(inst.item![2].bodySite!.system!.absoluteString!, "http://fdi.org/fhir/oraltoothcodes")
		XCTAssertEqual(inst.item![2].detail![0].net!.code!, "USD")
		XCTAssertEqual(inst.item![2].detail![0].net!.system!.absoluteString!, "urn:std:iso:4217")
		XCTAssertEqual(inst.item![2].detail![0].net!.value!, NSDecimalNumber(string: "750.0"))
		XCTAssertEqual(inst.item![2].detail![0].sequence!, 1)
		XCTAssertEqual(inst.item![2].detail![0].service!.code!, "27211")
		XCTAssertEqual(inst.item![2].detail![0].service!.system!.absoluteString!, "http://hl7.org/fhir/oralservicecodes")
		XCTAssertEqual(inst.item![2].detail![0].type!.code!, "service")
		XCTAssertEqual(inst.item![2].detail![0].unitPrice!.code!, "USD")
		XCTAssertEqual(inst.item![2].detail![0].unitPrice!.system!.absoluteString!, "urn:std:iso:4217")
		XCTAssertEqual(inst.item![2].detail![0].unitPrice!.value!, NSDecimalNumber(string: "750.0"))
		XCTAssertEqual(inst.item![2].detail![1].net!.code!, "USD")
		XCTAssertEqual(inst.item![2].detail![1].net!.system!.absoluteString!, "urn:std:iso:4217")
		XCTAssertEqual(inst.item![2].detail![1].net!.value!, NSDecimalNumber(string: "350.0"))
		XCTAssertEqual(inst.item![2].detail![1].sequence!, 2)
		XCTAssertEqual(inst.item![2].detail![1].service!.code!, "lab")
		XCTAssertEqual(inst.item![2].detail![1].service!.system!.absoluteString!, "http://hl7.org/fhir/oralservicecodes")
		XCTAssertEqual(inst.item![2].detail![1].type!.code!, "service")
		XCTAssertEqual(inst.item![2].detail![1].unitPrice!.code!, "USD")
		XCTAssertEqual(inst.item![2].detail![1].unitPrice!.system!.absoluteString!, "urn:std:iso:4217")
		XCTAssertEqual(inst.item![2].detail![1].unitPrice!.value!, NSDecimalNumber(string: "350.0"))
		XCTAssertEqual(inst.item![2].net!.code!, "USD")
		XCTAssertEqual(inst.item![2].net!.system!.absoluteString!, "urn:std:iso:4217")
		XCTAssertEqual(inst.item![2].net!.value!, NSDecimalNumber(string: "1100.0"))
		XCTAssertEqual(inst.item![2].provider!.reference!, "Practitioner/1")
		XCTAssertEqual(inst.item![2].sequence!, 3)
		XCTAssertEqual(inst.item![2].service!.code!, "27211")
		XCTAssertEqual(inst.item![2].service!.system!.absoluteString!, "http://hl7.org/fhir/oralservicecodes")
		XCTAssertEqual(inst.item![2].serviceDate!.description, "2014-08-16")
		XCTAssertEqual(inst.item![2].type!.code!, "group")
		XCTAssertEqual(inst.item![2].unitPrice!.code!, "USD")
		XCTAssertEqual(inst.item![2].unitPrice!.system!.absoluteString!, "urn:std:iso:4217")
		XCTAssertEqual(inst.item![2].unitPrice!.value!, NSDecimalNumber(string: "1100.0"))
		XCTAssertEqual(inst.organization!.reference!, "Organization/1")
		XCTAssertEqual(inst.patient!.reference!, "Patient/1")
		XCTAssertEqual(inst.payee!.type!.code!, "provider")
		XCTAssertEqual(inst.priority!.code!, "normal")
		XCTAssertEqual(inst.target!.reference!, "Organization/2")
		XCTAssertEqual(inst.text!.div!, "<div>A human-readable rendering of the Oral Health Claim</div>")
		XCTAssertEqual(inst.text!.status!, "generated")
		XCTAssertEqual(inst.use!, "complete")
		
		return inst
	}
	
	func testOralHealthClaim2() {
		let instance = testOralHealthClaim2_impl()
		testOralHealthClaim2_impl(json: instance.asJSON())
	}
	
	func testOralHealthClaim2_impl(json: JSONDictionary? = nil) -> OralHealthClaim {
		let inst = (nil != json) ? instantiateFrom(json: json!) : instantiateFrom(filename: "oralhealthclaim-example-contained.json")
		
		XCTAssertEqual(inst.coverage![0].coverage!.reference!, "#coverage-1")
		XCTAssertTrue(inst.coverage![0].focal!)
		XCTAssertEqual(inst.coverage![0].relationship!.code!, "self")
		XCTAssertEqual(inst.coverage![0].sequence!, 1)
		XCTAssertEqual(inst.created!.description, "2014-08-16")
		XCTAssertEqual(inst.diagnosis![0].diagnosis!.code!, "123456")
		XCTAssertEqual(inst.diagnosis![0].sequence!, 1)
		XCTAssertEqual(inst.id!, "100152")
		XCTAssertEqual(inst.identifier![0].system!.absoluteString!, "http://happyvalley.com/claims")
		XCTAssertEqual(inst.identifier![0].value!, "12347")
		XCTAssertEqual(inst.item![0].net!.code!, "USD")
		XCTAssertEqual(inst.item![0].net!.system!.absoluteString!, "urn:std:iso:4217")
		XCTAssertEqual(inst.item![0].net!.value!, NSDecimalNumber(string: "135.57"))
		XCTAssertEqual(inst.item![0].provider!.reference!, "#practitioner-1")
		XCTAssertEqual(inst.item![0].sequence!, 1)
		XCTAssertEqual(inst.item![0].service!.code!, "1200")
		XCTAssertEqual(inst.item![0].serviceDate!.description, "2014-08-16")
		XCTAssertEqual(inst.item![0].type!.code!, "service")
		XCTAssertEqual(inst.item![0].unitPrice!.code!, "USD")
		XCTAssertEqual(inst.item![0].unitPrice!.system!.absoluteString!, "urn:std:iso:4217")
		XCTAssertEqual(inst.item![0].unitPrice!.value!, NSDecimalNumber(string: "135.57"))
		XCTAssertEqual(inst.organization!.reference!, "#organization-1")
		XCTAssertEqual(inst.patient!.reference!, "#patient-1")
		XCTAssertEqual(inst.payee!.type!.code!, "provider")
		XCTAssertEqual(inst.priority!.code!, "normal")
		XCTAssertEqual(inst.target!.reference!, "#organization-2")
		XCTAssertEqual(inst.text!.div!, "<div>A human-readable rendering of the Oral Health Claim</div>")
		XCTAssertEqual(inst.text!.status!, "generated")
		XCTAssertEqual(inst.use!, "complete")
		
		return inst
	}
	
	func testOralHealthClaim3() {
		let instance = testOralHealthClaim3_impl()
		testOralHealthClaim3_impl(json: instance.asJSON())
	}
	
	func testOralHealthClaim3_impl(json: JSONDictionary? = nil) -> OralHealthClaim {
		let inst = (nil != json) ? instantiateFrom(json: json!) : instantiateFrom(filename: "oralhealthclaim-example-orthoplan.json")
		
		XCTAssertEqual(inst.coverage![0].coverage!.reference!, "Coverage/9876B1")
		XCTAssertTrue(inst.coverage![0].focal!)
		XCTAssertEqual(inst.coverage![0].relationship!.code!, "self")
		XCTAssertEqual(inst.coverage![0].sequence!, 1)
		XCTAssertEqual(inst.created!.description, "2015-03-16")
		XCTAssertEqual(inst.diagnosis![0].diagnosis!.code!, "123457")
		XCTAssertEqual(inst.diagnosis![0].diagnosis!.system!.absoluteString!, "http://hl7.org/fhir/icd-10")
		XCTAssertEqual(inst.diagnosis![0].sequence!, 1)
		XCTAssertEqual(inst.id!, "100153")
		XCTAssertEqual(inst.identifier![0].system!.absoluteString!, "http://happyvalley.com/claims")
		XCTAssertEqual(inst.identifier![0].value!, "12355")
		XCTAssertEqual(inst.item![0].detail![0].net!.code!, "USD")
		XCTAssertEqual(inst.item![0].detail![0].net!.system!.absoluteString!, "urn:std:iso:4217")
		XCTAssertEqual(inst.item![0].detail![0].net!.value!, NSDecimalNumber(string: "1000.0"))
		XCTAssertEqual(inst.item![0].detail![0].sequence!, 1)
		XCTAssertEqual(inst.item![0].detail![0].service!.code!, "ORTHOEXAM")
		XCTAssertEqual(inst.item![0].detail![0].service!.system!.absoluteString!, "http://hl7.org/fhir/oralservicecodes")
		XCTAssertEqual(inst.item![0].detail![0].type!.code!, "service")
		XCTAssertEqual(inst.item![0].detail![0].type!.system!.absoluteString!, "http://hl7.org/fhir/actinvoicegroupcode")
		XCTAssertEqual(inst.item![0].detail![0].unitPrice!.code!, "USD")
		XCTAssertEqual(inst.item![0].detail![0].unitPrice!.system!.absoluteString!, "urn:std:iso:4217")
		XCTAssertEqual(inst.item![0].detail![0].unitPrice!.value!, NSDecimalNumber(string: "1000.0"))
		XCTAssertEqual(inst.item![0].detail![1].net!.code!, "USD")
		XCTAssertEqual(inst.item![0].detail![1].net!.system!.absoluteString!, "urn:std:iso:4217")
		XCTAssertEqual(inst.item![0].detail![1].net!.value!, NSDecimalNumber(string: "1500.0"))
		XCTAssertEqual(inst.item![0].detail![1].sequence!, 2)
		XCTAssertEqual(inst.item![0].detail![1].service!.code!, "ORTHODIAG")
		XCTAssertEqual(inst.item![0].detail![1].service!.system!.absoluteString!, "http://hl7.org/fhir/oralservicecodes")
		XCTAssertEqual(inst.item![0].detail![1].type!.code!, "service")
		XCTAssertEqual(inst.item![0].detail![1].type!.system!.absoluteString!, "http://hl7.org/fhir/actinvoicegroupcode")
		XCTAssertEqual(inst.item![0].detail![1].unitPrice!.code!, "USD")
		XCTAssertEqual(inst.item![0].detail![1].unitPrice!.system!.absoluteString!, "urn:std:iso:4217")
		XCTAssertEqual(inst.item![0].detail![1].unitPrice!.value!, NSDecimalNumber(string: "1500.0"))
		XCTAssertEqual(inst.item![0].detail![2].net!.code!, "USD")
		XCTAssertEqual(inst.item![0].detail![2].net!.system!.absoluteString!, "urn:std:iso:4217")
		XCTAssertEqual(inst.item![0].detail![2].net!.value!, NSDecimalNumber(string: "500.0"))
		XCTAssertEqual(inst.item![0].detail![2].sequence!, 3)
		XCTAssertEqual(inst.item![0].detail![2].service!.code!, "ORTHOINITIAL")
		XCTAssertEqual(inst.item![0].detail![2].service!.system!.absoluteString!, "http://hl7.org/fhir/oralservicecodes")
		XCTAssertEqual(inst.item![0].detail![2].type!.code!, "service")
		XCTAssertEqual(inst.item![0].detail![2].type!.system!.absoluteString!, "http://hl7.org/fhir/actinvoicegroupcode")
		XCTAssertEqual(inst.item![0].detail![2].unitPrice!.code!, "USD")
		XCTAssertEqual(inst.item![0].detail![2].unitPrice!.system!.absoluteString!, "urn:std:iso:4217")
		XCTAssertEqual(inst.item![0].detail![2].unitPrice!.value!, NSDecimalNumber(string: "500.0"))
		XCTAssertEqual(inst.item![0].detail![3].quantity!.value!, NSDecimalNumber(string: "24"))
		XCTAssertEqual(inst.item![0].detail![3].sequence!, 4)
		XCTAssertEqual(inst.item![0].detail![3].service!.code!, "ORTHOMONTHS")
		XCTAssertEqual(inst.item![0].detail![3].service!.system!.absoluteString!, "http://hl7.org/fhir/oralservicecodes")
		XCTAssertEqual(inst.item![0].detail![3].type!.code!, "service")
		XCTAssertEqual(inst.item![0].detail![3].type!.system!.absoluteString!, "http://hl7.org/fhir/actinvoicegroupcode")
		XCTAssertEqual(inst.item![0].detail![4].net!.code!, "USD")
		XCTAssertEqual(inst.item![0].detail![4].net!.system!.absoluteString!, "urn:std:iso:4217")
		XCTAssertEqual(inst.item![0].detail![4].net!.value!, NSDecimalNumber(string: "250.0"))
		XCTAssertEqual(inst.item![0].detail![4].quantity!.value!, NSDecimalNumber(string: "24"))
		XCTAssertEqual(inst.item![0].detail![4].sequence!, 5)
		XCTAssertEqual(inst.item![0].detail![4].service!.code!, "ORTHOPERIODIC")
		XCTAssertEqual(inst.item![0].detail![4].service!.system!.absoluteString!, "http://hl7.org/fhir/oralservicecodes")
		XCTAssertEqual(inst.item![0].detail![4].type!.code!, "service")
		XCTAssertEqual(inst.item![0].detail![4].type!.system!.absoluteString!, "http://hl7.org/fhir/actinvoicegroupcode")
		XCTAssertEqual(inst.item![0].detail![4].unitPrice!.code!, "USD")
		XCTAssertEqual(inst.item![0].detail![4].unitPrice!.system!.absoluteString!, "urn:std:iso:4217")
		XCTAssertEqual(inst.item![0].detail![4].unitPrice!.value!, NSDecimalNumber(string: "250.0"))
		XCTAssertEqual(inst.item![0].diagnosisLinkId![0], 1)
		XCTAssertEqual(inst.item![0].net!.code!, "USD")
		XCTAssertEqual(inst.item![0].net!.system!.absoluteString!, "urn:std:iso:4217")
		XCTAssertEqual(inst.item![0].net!.value!, NSDecimalNumber(string: "9000.0"))
		XCTAssertEqual(inst.item![0].provider!.reference!, "Practitioner/1")
		XCTAssertEqual(inst.item![0].sequence!, 1)
		XCTAssertEqual(inst.item![0].service!.code!, "ORTHPLAN")
		XCTAssertEqual(inst.item![0].service!.system!.absoluteString!, "http://hl7.org/fhir/oralservicecodes")
		XCTAssertEqual(inst.item![0].serviceDate!.description, "2015-05-16")
		XCTAssertEqual(inst.item![0].type!.code!, "group")
		XCTAssertEqual(inst.item![0].type!.system!.absoluteString!, "http://hl7.org/fhir/actinvoicegroupcode")
		XCTAssertEqual(inst.item![0].unitPrice!.code!, "USD")
		XCTAssertEqual(inst.item![0].unitPrice!.system!.absoluteString!, "urn:std:iso:4217")
		XCTAssertEqual(inst.item![0].unitPrice!.value!, NSDecimalNumber(string: "9000.0"))
		XCTAssertEqual(inst.item![1].bodySite!.code!, "21")
		XCTAssertEqual(inst.item![1].bodySite!.system!.absoluteString!, "http://fdi.org/fhir/oraltoothcodes")
		XCTAssertEqual(inst.item![1].net!.code!, "USD")
		XCTAssertEqual(inst.item![1].net!.system!.absoluteString!, "urn:std:iso:4217")
		XCTAssertEqual(inst.item![1].net!.value!, NSDecimalNumber(string: "105.0"))
		XCTAssertEqual(inst.item![1].provider!.reference!, "Practitioner/1")
		XCTAssertEqual(inst.item![1].sequence!, 2)
		XCTAssertEqual(inst.item![1].service!.code!, "21211")
		XCTAssertEqual(inst.item![1].service!.system!.absoluteString!, "http://hl7.org/fhir/oralservicecodes")
		XCTAssertEqual(inst.item![1].serviceDate!.description, "2014-08-16")
		XCTAssertEqual(inst.item![1].subSite![0].code!, "L")
		XCTAssertEqual(inst.item![1].subSite![0].system!.absoluteString!, "http://fdi.org/fhir/oralsurfacecodes")
		XCTAssertEqual(inst.item![1].type!.code!, "service")
		XCTAssertEqual(inst.item![1].unitPrice!.code!, "USD")
		XCTAssertEqual(inst.item![1].unitPrice!.system!.absoluteString!, "urn:std:iso:4217")
		XCTAssertEqual(inst.item![1].unitPrice!.value!, NSDecimalNumber(string: "105.0"))
		XCTAssertEqual(inst.item![2].bodySite!.code!, "36")
		XCTAssertEqual(inst.item![2].bodySite!.system!.absoluteString!, "http://fdi.org/fhir/oraltoothcodes")
		XCTAssertEqual(inst.item![2].detail![0].net!.code!, "USD")
		XCTAssertEqual(inst.item![2].detail![0].net!.system!.absoluteString!, "urn:std:iso:4217")
		XCTAssertEqual(inst.item![2].detail![0].net!.value!, NSDecimalNumber(string: "750.0"))
		XCTAssertEqual(inst.item![2].detail![0].sequence!, 1)
		XCTAssertEqual(inst.item![2].detail![0].service!.code!, "27211")
		XCTAssertEqual(inst.item![2].detail![0].service!.system!.absoluteString!, "http://hl7.org/fhir/oralservicecodes")
		XCTAssertEqual(inst.item![2].detail![0].type!.code!, "service")
		XCTAssertEqual(inst.item![2].detail![0].unitPrice!.code!, "USD")
		XCTAssertEqual(inst.item![2].detail![0].unitPrice!.system!.absoluteString!, "urn:std:iso:4217")
		XCTAssertEqual(inst.item![2].detail![0].unitPrice!.value!, NSDecimalNumber(string: "750.0"))
		XCTAssertEqual(inst.item![2].detail![1].net!.code!, "USD")
		XCTAssertEqual(inst.item![2].detail![1].net!.system!.absoluteString!, "urn:std:iso:4217")
		XCTAssertEqual(inst.item![2].detail![1].net!.value!, NSDecimalNumber(string: "350.0"))
		XCTAssertEqual(inst.item![2].detail![1].sequence!, 2)
		XCTAssertEqual(inst.item![2].detail![1].service!.code!, "lab")
		XCTAssertEqual(inst.item![2].detail![1].service!.system!.absoluteString!, "http://hl7.org/fhir/oralservicecodes")
		XCTAssertEqual(inst.item![2].detail![1].type!.code!, "service")
		XCTAssertEqual(inst.item![2].detail![1].unitPrice!.code!, "USD")
		XCTAssertEqual(inst.item![2].detail![1].unitPrice!.system!.absoluteString!, "urn:std:iso:4217")
		XCTAssertEqual(inst.item![2].detail![1].unitPrice!.value!, NSDecimalNumber(string: "350.0"))
		XCTAssertEqual(inst.item![2].net!.code!, "USD")
		XCTAssertEqual(inst.item![2].net!.system!.absoluteString!, "urn:std:iso:4217")
		XCTAssertEqual(inst.item![2].net!.value!, NSDecimalNumber(string: "1100.0"))
		XCTAssertEqual(inst.item![2].provider!.reference!, "Practitioner/1")
		XCTAssertEqual(inst.item![2].sequence!, 3)
		XCTAssertEqual(inst.item![2].service!.code!, "27211")
		XCTAssertEqual(inst.item![2].service!.system!.absoluteString!, "http://hl7.org/fhir/oralservicecodes")
		XCTAssertEqual(inst.item![2].serviceDate!.description, "2014-08-16")
		XCTAssertEqual(inst.item![2].type!.code!, "group")
		XCTAssertEqual(inst.item![2].unitPrice!.code!, "USD")
		XCTAssertEqual(inst.item![2].unitPrice!.system!.absoluteString!, "urn:std:iso:4217")
		XCTAssertEqual(inst.item![2].unitPrice!.value!, NSDecimalNumber(string: "1100.0"))
		XCTAssertEqual(inst.organization!.reference!, "Organization/1")
		XCTAssertEqual(inst.patient!.reference!, "Patient/1")
		XCTAssertEqual(inst.payee!.type!.code!, "provider")
		XCTAssertEqual(inst.priority!.code!, "normal")
		XCTAssertEqual(inst.target!.reference!, "Organization/2")
		XCTAssertEqual(inst.text!.div!, "<div>A human-readable rendering of the Oral Health Claim</div>")
		XCTAssertEqual(inst.text!.status!, "generated")
		XCTAssertEqual(inst.use!, "proposed")
		
		return inst
	}
	
	func testOralHealthClaim4() {
		let instance = testOralHealthClaim4_impl()
		testOralHealthClaim4_impl(json: instance.asJSON())
	}
	
	func testOralHealthClaim4_impl(json: JSONDictionary? = nil) -> OralHealthClaim {
		let inst = (nil != json) ? instantiateFrom(json: json!) : instantiateFrom(filename: "oralhealthclaim-example.json")
		
		XCTAssertEqual(inst.coverage![0].coverage!.reference!, "Coverage/9876B1")
		XCTAssertTrue(inst.coverage![0].focal!)
		XCTAssertEqual(inst.coverage![0].relationship!.code!, "self")
		XCTAssertEqual(inst.coverage![0].sequence!, 1)
		XCTAssertEqual(inst.created!.description, "2014-08-16")
		XCTAssertEqual(inst.diagnosis![0].diagnosis!.code!, "123456")
		XCTAssertEqual(inst.diagnosis![0].sequence!, 1)
		XCTAssertEqual(inst.id!, "100150")
		XCTAssertEqual(inst.identifier![0].system!.absoluteString!, "http://happyvalley.com/claims")
		XCTAssertEqual(inst.identifier![0].value!, "12345")
		XCTAssertEqual(inst.item![0].net!.code!, "USD")
		XCTAssertEqual(inst.item![0].net!.system!.absoluteString!, "urn:std:iso:4217")
		XCTAssertEqual(inst.item![0].net!.value!, NSDecimalNumber(string: "135.57"))
		XCTAssertEqual(inst.item![0].provider!.reference!, "Practitioner/1")
		XCTAssertEqual(inst.item![0].sequence!, 1)
		XCTAssertEqual(inst.item![0].service!.code!, "1200")
		XCTAssertEqual(inst.item![0].serviceDate!.description, "2014-08-16")
		XCTAssertEqual(inst.item![0].type!.code!, "service")
		XCTAssertEqual(inst.item![0].unitPrice!.code!, "USD")
		XCTAssertEqual(inst.item![0].unitPrice!.system!.absoluteString!, "urn:std:iso:4217")
		XCTAssertEqual(inst.item![0].unitPrice!.value!, NSDecimalNumber(string: "135.57"))
		XCTAssertEqual(inst.organization!.reference!, "Organization/1")
		XCTAssertEqual(inst.patient!.reference!, "Patient/1")
		XCTAssertEqual(inst.payee!.type!.code!, "provider")
		XCTAssertEqual(inst.priority!.code!, "normal")
		XCTAssertEqual(inst.target!.reference!, "Organization/2")
		XCTAssertEqual(inst.text!.div!, "<div>A human-readable rendering of the Oral Health Claim</div>")
		XCTAssertEqual(inst.text!.status!, "generated")
		XCTAssertEqual(inst.use!, "complete")
		
		return inst
	}
}
