//
//  OralHealthClaimTests.swift
//  OralHealthClaimTests
//
//  Generated from FHIR 0.4.0.3903 on 2014-12-22.
//  2014, SMART Platforms.
//

import Cocoa
import XCTest
import SwiftFHIR


class OralHealthClaimTests: FHIRModelTestCase
{
	func instantiateFrom(filename: String) -> OralHealthClaim? {
		let json = readJSONFile(filename)
		let instance = OralHealthClaim(json: json)
		XCTAssertNotNil(instance, "Must have instantiated a test instance")
		return instance
	}
	
	func testOralHealthClaim1() {
		let inst = instantiateFrom("oralhealthclaim-example-average.canonical.json")
		XCTAssertNotNil(inst, "Must have instantiated a OralHealthClaim instance")
	
		XCTAssertEqual(inst!.coverage![0].coverage!.reference!, "Coverage/9876B1")
		XCTAssertTrue(inst!.coverage![0].focal!)
		XCTAssertEqual(inst!.coverage![0].relationship!.code!, "self")
		XCTAssertEqual(inst!.coverage![0].sequence!, 1)
		XCTAssertEqual(inst!.created!, NSDate.dateFromISOString("2014-08-16")!)
		XCTAssertEqual(inst!.diagnosis![0].diagnosis!.code!, "123456")
		XCTAssertEqual(inst!.diagnosis![0].sequence!, 1)
		XCTAssertEqual(inst!.identifier![0].system!, NSURL(string: "http://happyvalley.com/claims")!)
		XCTAssertEqual(inst!.identifier![0].value!, "12346")
		XCTAssertEqual(inst!.item![0].net!.code!, "USD")
		XCTAssertEqual(inst!.item![0].net!.system!, NSURL(string: "urn:std:iso:4217")!)
		XCTAssertEqual(inst!.item![0].net!.value!, NSDecimalNumber(string: "135.57"))
		XCTAssertEqual(inst!.item![0].provider!.reference!, "Practitioner/1")
		XCTAssertEqual(inst!.item![0].sequence!, 1)
		XCTAssertEqual(inst!.item![0].service!.code!, "1200")
		XCTAssertEqual(inst!.item![0].service!.system!, NSURL(string: "http://hl7.org/fhir/oralservicecodes")!)
		XCTAssertEqual(inst!.item![0].serviceDate!, NSDate.dateFromISOString("2014-08-16")!)
		XCTAssertEqual(inst!.item![0].type!.code!, "service")
		XCTAssertEqual(inst!.item![0].unitPrice!.code!, "USD")
		XCTAssertEqual(inst!.item![0].unitPrice!.system!, NSURL(string: "urn:std:iso:4217")!)
		XCTAssertEqual(inst!.item![0].unitPrice!.value!, NSDecimalNumber(string: "135.57"))
		XCTAssertEqual(inst!.item![1].bodySite!.code!, "21")
		XCTAssertEqual(inst!.item![1].bodySite!.system!, NSURL(string: "http://fdi.org/fhir/oraltoothcodes")!)
		XCTAssertEqual(inst!.item![1].net!.code!, "USD")
		XCTAssertEqual(inst!.item![1].net!.system!, NSURL(string: "urn:std:iso:4217")!)
		XCTAssertEqual(inst!.item![1].net!.value!, NSDecimalNumber(string: "105.0"))
		XCTAssertEqual(inst!.item![1].provider!.reference!, "Practitioner/1")
		XCTAssertEqual(inst!.item![1].sequence!, 2)
		XCTAssertEqual(inst!.item![1].service!.code!, "21211")
		XCTAssertEqual(inst!.item![1].service!.system!, NSURL(string: "http://hl7.org/fhir/oralservicecodes")!)
		XCTAssertEqual(inst!.item![1].serviceDate!, NSDate.dateFromISOString("2014-08-16")!)
		XCTAssertEqual(inst!.item![1].subsite![0].code!, "L")
		XCTAssertEqual(inst!.item![1].subsite![0].system!, NSURL(string: "http://fdi.org/fhir/oralsurfacecodes")!)
		XCTAssertEqual(inst!.item![1].type!.code!, "service")
		XCTAssertEqual(inst!.item![1].unitPrice!.code!, "USD")
		XCTAssertEqual(inst!.item![1].unitPrice!.system!, NSURL(string: "urn:std:iso:4217")!)
		XCTAssertEqual(inst!.item![1].unitPrice!.value!, NSDecimalNumber(string: "105.0"))
		XCTAssertEqual(inst!.item![2].bodySite!.code!, "36")
		XCTAssertEqual(inst!.item![2].bodySite!.system!, NSURL(string: "http://fdi.org/fhir/oraltoothcodes")!)
		XCTAssertEqual(inst!.item![2].detail![0].net!.code!, "USD")
		XCTAssertEqual(inst!.item![2].detail![0].net!.system!, NSURL(string: "urn:std:iso:4217")!)
		XCTAssertEqual(inst!.item![2].detail![0].net!.value!, NSDecimalNumber(string: "750.0"))
		XCTAssertEqual(inst!.item![2].detail![0].sequence!, 1)
		XCTAssertEqual(inst!.item![2].detail![0].service!.code!, "27211")
		XCTAssertEqual(inst!.item![2].detail![0].service!.system!, NSURL(string: "http://hl7.org/fhir/oralservicecodes")!)
		XCTAssertEqual(inst!.item![2].detail![0].type!.code!, "service")
		XCTAssertEqual(inst!.item![2].detail![0].unitPrice!.code!, "USD")
		XCTAssertEqual(inst!.item![2].detail![0].unitPrice!.system!, NSURL(string: "urn:std:iso:4217")!)
		XCTAssertEqual(inst!.item![2].detail![0].unitPrice!.value!, NSDecimalNumber(string: "750.0"))
		XCTAssertEqual(inst!.item![2].detail![1].net!.code!, "USD")
		XCTAssertEqual(inst!.item![2].detail![1].net!.system!, NSURL(string: "urn:std:iso:4217")!)
		XCTAssertEqual(inst!.item![2].detail![1].net!.value!, NSDecimalNumber(string: "350.0"))
		XCTAssertEqual(inst!.item![2].detail![1].sequence!, 2)
		XCTAssertEqual(inst!.item![2].detail![1].service!.code!, "lab")
		XCTAssertEqual(inst!.item![2].detail![1].service!.system!, NSURL(string: "http://hl7.org/fhir/oralservicecodes")!)
		XCTAssertEqual(inst!.item![2].detail![1].type!.code!, "service")
		XCTAssertEqual(inst!.item![2].detail![1].unitPrice!.code!, "USD")
		XCTAssertEqual(inst!.item![2].detail![1].unitPrice!.system!, NSURL(string: "urn:std:iso:4217")!)
		XCTAssertEqual(inst!.item![2].detail![1].unitPrice!.value!, NSDecimalNumber(string: "350.0"))
		XCTAssertEqual(inst!.item![2].net!.code!, "USD")
		XCTAssertEqual(inst!.item![2].net!.system!, NSURL(string: "urn:std:iso:4217")!)
		XCTAssertEqual(inst!.item![2].net!.value!, NSDecimalNumber(string: "1100.0"))
		XCTAssertEqual(inst!.item![2].provider!.reference!, "Practitioner/1")
		XCTAssertEqual(inst!.item![2].sequence!, 3)
		XCTAssertEqual(inst!.item![2].service!.code!, "27211")
		XCTAssertEqual(inst!.item![2].service!.system!, NSURL(string: "http://hl7.org/fhir/oralservicecodes")!)
		XCTAssertEqual(inst!.item![2].serviceDate!, NSDate.dateFromISOString("2014-08-16")!)
		XCTAssertEqual(inst!.item![2].type!.code!, "group")
		XCTAssertEqual(inst!.item![2].unitPrice!.code!, "USD")
		XCTAssertEqual(inst!.item![2].unitPrice!.system!, NSURL(string: "urn:std:iso:4217")!)
		XCTAssertEqual(inst!.item![2].unitPrice!.value!, NSDecimalNumber(string: "1100.0"))
		XCTAssertEqual(inst!.organization!.reference!, "Organization/1")
		XCTAssertEqual(inst!.patient!.reference!, "Patient/1")
		XCTAssertEqual(inst!.payee!.type!.code!, "provider")
		XCTAssertEqual(inst!.priority!.code!, "normal")
		XCTAssertEqual(inst!.target!.reference!, "Organization/2")
		XCTAssertEqual(inst!.use!, "complete")
	}
	
	func testOralHealthClaim2() {
		let inst = instantiateFrom("oralhealthclaim-example-average.canonical.json")
		XCTAssertNotNil(inst, "Must have instantiated a OralHealthClaim instance")
	
		XCTAssertEqual(inst!.coverage![0].coverage!.reference!, "Coverage/9876B1")
		XCTAssertTrue(inst!.coverage![0].focal!)
		XCTAssertEqual(inst!.coverage![0].relationship!.code!, "self")
		XCTAssertEqual(inst!.coverage![0].sequence!, 1)
		XCTAssertEqual(inst!.created!, NSDate.dateFromISOString("2014-08-16")!)
		XCTAssertEqual(inst!.diagnosis![0].diagnosis!.code!, "123456")
		XCTAssertEqual(inst!.diagnosis![0].sequence!, 1)
		XCTAssertEqual(inst!.identifier![0].system!, NSURL(string: "http://happyvalley.com/claims")!)
		XCTAssertEqual(inst!.identifier![0].value!, "12346")
		XCTAssertEqual(inst!.item![0].net!.code!, "USD")
		XCTAssertEqual(inst!.item![0].net!.system!, NSURL(string: "urn:std:iso:4217")!)
		XCTAssertEqual(inst!.item![0].net!.value!, NSDecimalNumber(string: "135.57"))
		XCTAssertEqual(inst!.item![0].provider!.reference!, "Practitioner/1")
		XCTAssertEqual(inst!.item![0].sequence!, 1)
		XCTAssertEqual(inst!.item![0].service!.code!, "1200")
		XCTAssertEqual(inst!.item![0].service!.system!, NSURL(string: "http://hl7.org/fhir/oralservicecodes")!)
		XCTAssertEqual(inst!.item![0].serviceDate!, NSDate.dateFromISOString("2014-08-16")!)
		XCTAssertEqual(inst!.item![0].type!.code!, "service")
		XCTAssertEqual(inst!.item![0].unitPrice!.code!, "USD")
		XCTAssertEqual(inst!.item![0].unitPrice!.system!, NSURL(string: "urn:std:iso:4217")!)
		XCTAssertEqual(inst!.item![0].unitPrice!.value!, NSDecimalNumber(string: "135.57"))
		XCTAssertEqual(inst!.item![1].bodySite!.code!, "21")
		XCTAssertEqual(inst!.item![1].bodySite!.system!, NSURL(string: "http://fdi.org/fhir/oraltoothcodes")!)
		XCTAssertEqual(inst!.item![1].net!.code!, "USD")
		XCTAssertEqual(inst!.item![1].net!.system!, NSURL(string: "urn:std:iso:4217")!)
		XCTAssertEqual(inst!.item![1].net!.value!, NSDecimalNumber(string: "105.0"))
		XCTAssertEqual(inst!.item![1].provider!.reference!, "Practitioner/1")
		XCTAssertEqual(inst!.item![1].sequence!, 2)
		XCTAssertEqual(inst!.item![1].service!.code!, "21211")
		XCTAssertEqual(inst!.item![1].service!.system!, NSURL(string: "http://hl7.org/fhir/oralservicecodes")!)
		XCTAssertEqual(inst!.item![1].serviceDate!, NSDate.dateFromISOString("2014-08-16")!)
		XCTAssertEqual(inst!.item![1].subsite![0].code!, "L")
		XCTAssertEqual(inst!.item![1].subsite![0].system!, NSURL(string: "http://fdi.org/fhir/oralsurfacecodes")!)
		XCTAssertEqual(inst!.item![1].type!.code!, "service")
		XCTAssertEqual(inst!.item![1].unitPrice!.code!, "USD")
		XCTAssertEqual(inst!.item![1].unitPrice!.system!, NSURL(string: "urn:std:iso:4217")!)
		XCTAssertEqual(inst!.item![1].unitPrice!.value!, NSDecimalNumber(string: "105.0"))
		XCTAssertEqual(inst!.item![2].bodySite!.code!, "36")
		XCTAssertEqual(inst!.item![2].bodySite!.system!, NSURL(string: "http://fdi.org/fhir/oraltoothcodes")!)
		XCTAssertEqual(inst!.item![2].detail![0].net!.code!, "USD")
		XCTAssertEqual(inst!.item![2].detail![0].net!.system!, NSURL(string: "urn:std:iso:4217")!)
		XCTAssertEqual(inst!.item![2].detail![0].net!.value!, NSDecimalNumber(string: "750.0"))
		XCTAssertEqual(inst!.item![2].detail![0].sequence!, 1)
		XCTAssertEqual(inst!.item![2].detail![0].service!.code!, "27211")
		XCTAssertEqual(inst!.item![2].detail![0].service!.system!, NSURL(string: "http://hl7.org/fhir/oralservicecodes")!)
		XCTAssertEqual(inst!.item![2].detail![0].type!.code!, "service")
		XCTAssertEqual(inst!.item![2].detail![0].unitPrice!.code!, "USD")
		XCTAssertEqual(inst!.item![2].detail![0].unitPrice!.system!, NSURL(string: "urn:std:iso:4217")!)
		XCTAssertEqual(inst!.item![2].detail![0].unitPrice!.value!, NSDecimalNumber(string: "750.0"))
		XCTAssertEqual(inst!.item![2].detail![1].net!.code!, "USD")
		XCTAssertEqual(inst!.item![2].detail![1].net!.system!, NSURL(string: "urn:std:iso:4217")!)
		XCTAssertEqual(inst!.item![2].detail![1].net!.value!, NSDecimalNumber(string: "350.0"))
		XCTAssertEqual(inst!.item![2].detail![1].sequence!, 2)
		XCTAssertEqual(inst!.item![2].detail![1].service!.code!, "lab")
		XCTAssertEqual(inst!.item![2].detail![1].service!.system!, NSURL(string: "http://hl7.org/fhir/oralservicecodes")!)
		XCTAssertEqual(inst!.item![2].detail![1].type!.code!, "service")
		XCTAssertEqual(inst!.item![2].detail![1].unitPrice!.code!, "USD")
		XCTAssertEqual(inst!.item![2].detail![1].unitPrice!.system!, NSURL(string: "urn:std:iso:4217")!)
		XCTAssertEqual(inst!.item![2].detail![1].unitPrice!.value!, NSDecimalNumber(string: "350.0"))
		XCTAssertEqual(inst!.item![2].net!.code!, "USD")
		XCTAssertEqual(inst!.item![2].net!.system!, NSURL(string: "urn:std:iso:4217")!)
		XCTAssertEqual(inst!.item![2].net!.value!, NSDecimalNumber(string: "1100.0"))
		XCTAssertEqual(inst!.item![2].provider!.reference!, "Practitioner/1")
		XCTAssertEqual(inst!.item![2].sequence!, 3)
		XCTAssertEqual(inst!.item![2].service!.code!, "27211")
		XCTAssertEqual(inst!.item![2].service!.system!, NSURL(string: "http://hl7.org/fhir/oralservicecodes")!)
		XCTAssertEqual(inst!.item![2].serviceDate!, NSDate.dateFromISOString("2014-08-16")!)
		XCTAssertEqual(inst!.item![2].type!.code!, "group")
		XCTAssertEqual(inst!.item![2].unitPrice!.code!, "USD")
		XCTAssertEqual(inst!.item![2].unitPrice!.system!, NSURL(string: "urn:std:iso:4217")!)
		XCTAssertEqual(inst!.item![2].unitPrice!.value!, NSDecimalNumber(string: "1100.0"))
		XCTAssertEqual(inst!.organization!.reference!, "Organization/1")
		XCTAssertEqual(inst!.patient!.reference!, "Patient/1")
		XCTAssertEqual(inst!.payee!.type!.code!, "provider")
		XCTAssertEqual(inst!.priority!.code!, "normal")
		XCTAssertEqual(inst!.target!.reference!, "Organization/2")
		XCTAssertEqual(inst!.use!, "complete")
	}
	
	func testOralHealthClaim3() {
		let inst = instantiateFrom("oralhealthclaim-example-average.json")
		XCTAssertNotNil(inst, "Must have instantiated a OralHealthClaim instance")
	
		XCTAssertEqual(inst!.coverage![0].coverage!.reference!, "Coverage/9876B1")
		XCTAssertTrue(inst!.coverage![0].focal!)
		XCTAssertEqual(inst!.coverage![0].relationship!.code!, "self")
		XCTAssertEqual(inst!.coverage![0].sequence!, 1)
		XCTAssertEqual(inst!.created!, NSDate.dateFromISOString("2014-08-16")!)
		XCTAssertEqual(inst!.diagnosis![0].diagnosis!.code!, "123456")
		XCTAssertEqual(inst!.diagnosis![0].sequence!, 1)
		XCTAssertEqual(inst!.identifier![0].system!, NSURL(string: "http://happyvalley.com/claims")!)
		XCTAssertEqual(inst!.identifier![0].value!, "12346")
		XCTAssertEqual(inst!.item![0].net!.code!, "USD")
		XCTAssertEqual(inst!.item![0].net!.system!, NSURL(string: "urn:std:iso:4217")!)
		XCTAssertEqual(inst!.item![0].net!.value!, NSDecimalNumber(string: "135.57"))
		XCTAssertEqual(inst!.item![0].provider!.reference!, "Practitioner/1")
		XCTAssertEqual(inst!.item![0].sequence!, 1)
		XCTAssertEqual(inst!.item![0].service!.code!, "1200")
		XCTAssertEqual(inst!.item![0].service!.system!, NSURL(string: "http://hl7.org/fhir/oralservicecodes")!)
		XCTAssertEqual(inst!.item![0].serviceDate!, NSDate.dateFromISOString("2014-08-16")!)
		XCTAssertEqual(inst!.item![0].type!.code!, "service")
		XCTAssertEqual(inst!.item![0].unitPrice!.code!, "USD")
		XCTAssertEqual(inst!.item![0].unitPrice!.system!, NSURL(string: "urn:std:iso:4217")!)
		XCTAssertEqual(inst!.item![0].unitPrice!.value!, NSDecimalNumber(string: "135.57"))
		XCTAssertEqual(inst!.item![1].bodySite!.code!, "21")
		XCTAssertEqual(inst!.item![1].bodySite!.system!, NSURL(string: "http://fdi.org/fhir/oraltoothcodes")!)
		XCTAssertEqual(inst!.item![1].net!.code!, "USD")
		XCTAssertEqual(inst!.item![1].net!.system!, NSURL(string: "urn:std:iso:4217")!)
		XCTAssertEqual(inst!.item![1].net!.value!, NSDecimalNumber(string: "105.0"))
		XCTAssertEqual(inst!.item![1].provider!.reference!, "Practitioner/1")
		XCTAssertEqual(inst!.item![1].sequence!, 2)
		XCTAssertEqual(inst!.item![1].service!.code!, "21211")
		XCTAssertEqual(inst!.item![1].service!.system!, NSURL(string: "http://hl7.org/fhir/oralservicecodes")!)
		XCTAssertEqual(inst!.item![1].serviceDate!, NSDate.dateFromISOString("2014-08-16")!)
		XCTAssertEqual(inst!.item![1].subsite![0].code!, "L")
		XCTAssertEqual(inst!.item![1].subsite![0].system!, NSURL(string: "http://fdi.org/fhir/oralsurfacecodes")!)
		XCTAssertEqual(inst!.item![1].type!.code!, "service")
		XCTAssertEqual(inst!.item![1].unitPrice!.code!, "USD")
		XCTAssertEqual(inst!.item![1].unitPrice!.system!, NSURL(string: "urn:std:iso:4217")!)
		XCTAssertEqual(inst!.item![1].unitPrice!.value!, NSDecimalNumber(string: "105.0"))
		XCTAssertEqual(inst!.item![2].bodySite!.code!, "36")
		XCTAssertEqual(inst!.item![2].bodySite!.system!, NSURL(string: "http://fdi.org/fhir/oraltoothcodes")!)
		XCTAssertEqual(inst!.item![2].detail![0].net!.code!, "USD")
		XCTAssertEqual(inst!.item![2].detail![0].net!.system!, NSURL(string: "urn:std:iso:4217")!)
		XCTAssertEqual(inst!.item![2].detail![0].net!.value!, NSDecimalNumber(string: "750.0"))
		XCTAssertEqual(inst!.item![2].detail![0].sequence!, 1)
		XCTAssertEqual(inst!.item![2].detail![0].service!.code!, "27211")
		XCTAssertEqual(inst!.item![2].detail![0].service!.system!, NSURL(string: "http://hl7.org/fhir/oralservicecodes")!)
		XCTAssertEqual(inst!.item![2].detail![0].type!.code!, "service")
		XCTAssertEqual(inst!.item![2].detail![0].unitPrice!.code!, "USD")
		XCTAssertEqual(inst!.item![2].detail![0].unitPrice!.system!, NSURL(string: "urn:std:iso:4217")!)
		XCTAssertEqual(inst!.item![2].detail![0].unitPrice!.value!, NSDecimalNumber(string: "750.0"))
		XCTAssertEqual(inst!.item![2].detail![1].net!.code!, "USD")
		XCTAssertEqual(inst!.item![2].detail![1].net!.system!, NSURL(string: "urn:std:iso:4217")!)
		XCTAssertEqual(inst!.item![2].detail![1].net!.value!, NSDecimalNumber(string: "350.0"))
		XCTAssertEqual(inst!.item![2].detail![1].sequence!, 2)
		XCTAssertEqual(inst!.item![2].detail![1].service!.code!, "lab")
		XCTAssertEqual(inst!.item![2].detail![1].service!.system!, NSURL(string: "http://hl7.org/fhir/oralservicecodes")!)
		XCTAssertEqual(inst!.item![2].detail![1].type!.code!, "service")
		XCTAssertEqual(inst!.item![2].detail![1].unitPrice!.code!, "USD")
		XCTAssertEqual(inst!.item![2].detail![1].unitPrice!.system!, NSURL(string: "urn:std:iso:4217")!)
		XCTAssertEqual(inst!.item![2].detail![1].unitPrice!.value!, NSDecimalNumber(string: "350.0"))
		XCTAssertEqual(inst!.item![2].net!.code!, "USD")
		XCTAssertEqual(inst!.item![2].net!.system!, NSURL(string: "urn:std:iso:4217")!)
		XCTAssertEqual(inst!.item![2].net!.value!, NSDecimalNumber(string: "1100.0"))
		XCTAssertEqual(inst!.item![2].provider!.reference!, "Practitioner/1")
		XCTAssertEqual(inst!.item![2].sequence!, 3)
		XCTAssertEqual(inst!.item![2].service!.code!, "27211")
		XCTAssertEqual(inst!.item![2].service!.system!, NSURL(string: "http://hl7.org/fhir/oralservicecodes")!)
		XCTAssertEqual(inst!.item![2].serviceDate!, NSDate.dateFromISOString("2014-08-16")!)
		XCTAssertEqual(inst!.item![2].type!.code!, "group")
		XCTAssertEqual(inst!.item![2].unitPrice!.code!, "USD")
		XCTAssertEqual(inst!.item![2].unitPrice!.system!, NSURL(string: "urn:std:iso:4217")!)
		XCTAssertEqual(inst!.item![2].unitPrice!.value!, NSDecimalNumber(string: "1100.0"))
		XCTAssertEqual(inst!.organization!.reference!, "Organization/1")
		XCTAssertEqual(inst!.patient!.reference!, "Patient/1")
		XCTAssertEqual(inst!.payee!.type!.code!, "provider")
		XCTAssertEqual(inst!.priority!.code!, "normal")
		XCTAssertEqual(inst!.target!.reference!, "Organization/2")
		XCTAssertEqual(inst!.use!, "complete")
	}
	
	func testOralHealthClaim4() {
		let inst = instantiateFrom("oralhealthclaim-example-contained.canonical.json")
		XCTAssertNotNil(inst, "Must have instantiated a OralHealthClaim instance")
	
		XCTAssertEqual(inst!.coverage![0].coverage!.reference!, "#coverage-1")
		XCTAssertTrue(inst!.coverage![0].focal!)
		XCTAssertEqual(inst!.coverage![0].relationship!.code!, "self")
		XCTAssertEqual(inst!.coverage![0].sequence!, 1)
		XCTAssertEqual(inst!.created!, NSDate.dateFromISOString("2014-08-16")!)
		XCTAssertEqual(inst!.diagnosis![0].diagnosis!.code!, "123456")
		XCTAssertEqual(inst!.diagnosis![0].sequence!, 1)
		XCTAssertEqual(inst!.identifier![0].system!, NSURL(string: "http://happyvalley.com/claims")!)
		XCTAssertEqual(inst!.identifier![0].value!, "12347")
		XCTAssertEqual(inst!.item![0].net!.code!, "USD")
		XCTAssertEqual(inst!.item![0].net!.system!, NSURL(string: "urn:std:iso:4217")!)
		XCTAssertEqual(inst!.item![0].net!.value!, NSDecimalNumber(string: "135.57"))
		XCTAssertEqual(inst!.item![0].provider!.reference!, "#practitioner-1")
		XCTAssertEqual(inst!.item![0].sequence!, 1)
		XCTAssertEqual(inst!.item![0].service!.code!, "1200")
		XCTAssertEqual(inst!.item![0].serviceDate!, NSDate.dateFromISOString("2014-08-16")!)
		XCTAssertEqual(inst!.item![0].type!.code!, "service")
		XCTAssertEqual(inst!.item![0].unitPrice!.code!, "USD")
		XCTAssertEqual(inst!.item![0].unitPrice!.system!, NSURL(string: "urn:std:iso:4217")!)
		XCTAssertEqual(inst!.item![0].unitPrice!.value!, NSDecimalNumber(string: "135.57"))
		XCTAssertEqual(inst!.organization!.reference!, "#organization-1")
		XCTAssertEqual(inst!.patient!.reference!, "#patient-1")
		XCTAssertEqual(inst!.payee!.type!.code!, "provider")
		XCTAssertEqual(inst!.priority!.code!, "normal")
		XCTAssertEqual(inst!.target!.reference!, "#organization-2")
		XCTAssertEqual(inst!.use!, "complete")
	}
	
	func testOralHealthClaim5() {
		let inst = instantiateFrom("oralhealthclaim-example-contained.json")
		XCTAssertNotNil(inst, "Must have instantiated a OralHealthClaim instance")
	
		XCTAssertEqual(inst!.coverage![0].coverage!.reference!, "#coverage-1")
		XCTAssertTrue(inst!.coverage![0].focal!)
		XCTAssertEqual(inst!.coverage![0].relationship!.code!, "self")
		XCTAssertEqual(inst!.coverage![0].sequence!, 1)
		XCTAssertEqual(inst!.created!, NSDate.dateFromISOString("2014-08-16")!)
		XCTAssertEqual(inst!.diagnosis![0].diagnosis!.code!, "123456")
		XCTAssertEqual(inst!.diagnosis![0].sequence!, 1)
		XCTAssertEqual(inst!.identifier![0].system!, NSURL(string: "http://happyvalley.com/claims")!)
		XCTAssertEqual(inst!.identifier![0].value!, "12347")
		XCTAssertEqual(inst!.item![0].net!.code!, "USD")
		XCTAssertEqual(inst!.item![0].net!.system!, NSURL(string: "urn:std:iso:4217")!)
		XCTAssertEqual(inst!.item![0].net!.value!, NSDecimalNumber(string: "135.57"))
		XCTAssertEqual(inst!.item![0].provider!.reference!, "#practitioner-1")
		XCTAssertEqual(inst!.item![0].sequence!, 1)
		XCTAssertEqual(inst!.item![0].service!.code!, "1200")
		XCTAssertEqual(inst!.item![0].serviceDate!, NSDate.dateFromISOString("2014-08-16")!)
		XCTAssertEqual(inst!.item![0].type!.code!, "service")
		XCTAssertEqual(inst!.item![0].unitPrice!.code!, "USD")
		XCTAssertEqual(inst!.item![0].unitPrice!.system!, NSURL(string: "urn:std:iso:4217")!)
		XCTAssertEqual(inst!.item![0].unitPrice!.value!, NSDecimalNumber(string: "135.57"))
		XCTAssertEqual(inst!.organization!.reference!, "#organization-1")
		XCTAssertEqual(inst!.patient!.reference!, "#patient-1")
		XCTAssertEqual(inst!.payee!.type!.code!, "provider")
		XCTAssertEqual(inst!.priority!.code!, "normal")
		XCTAssertEqual(inst!.target!.reference!, "#organization-2")
		XCTAssertEqual(inst!.use!, "complete")
	}
	
	func testOralHealthClaim6() {
		let inst = instantiateFrom("oralhealthclaim-example.canonical.json")
		XCTAssertNotNil(inst, "Must have instantiated a OralHealthClaim instance")
	
		XCTAssertEqual(inst!.coverage![0].coverage!.reference!, "Coverage/9876B1")
		XCTAssertTrue(inst!.coverage![0].focal!)
		XCTAssertEqual(inst!.coverage![0].relationship!.code!, "self")
		XCTAssertEqual(inst!.coverage![0].sequence!, 1)
		XCTAssertEqual(inst!.created!, NSDate.dateFromISOString("2014-08-16")!)
		XCTAssertEqual(inst!.diagnosis![0].diagnosis!.code!, "123456")
		XCTAssertEqual(inst!.diagnosis![0].sequence!, 1)
		XCTAssertEqual(inst!.identifier![0].system!, NSURL(string: "http://happyvalley.com/claims")!)
		XCTAssertEqual(inst!.identifier![0].value!, "12345")
		XCTAssertEqual(inst!.item![0].net!.code!, "USD")
		XCTAssertEqual(inst!.item![0].net!.system!, NSURL(string: "urn:std:iso:4217")!)
		XCTAssertEqual(inst!.item![0].net!.value!, NSDecimalNumber(string: "135.57"))
		XCTAssertEqual(inst!.item![0].provider!.reference!, "Practitioner/1")
		XCTAssertEqual(inst!.item![0].sequence!, 1)
		XCTAssertEqual(inst!.item![0].service!.code!, "1200")
		XCTAssertEqual(inst!.item![0].serviceDate!, NSDate.dateFromISOString("2014-08-16")!)
		XCTAssertEqual(inst!.item![0].type!.code!, "service")
		XCTAssertEqual(inst!.item![0].unitPrice!.code!, "USD")
		XCTAssertEqual(inst!.item![0].unitPrice!.system!, NSURL(string: "urn:std:iso:4217")!)
		XCTAssertEqual(inst!.item![0].unitPrice!.value!, NSDecimalNumber(string: "135.57"))
		XCTAssertEqual(inst!.organization!.reference!, "Organization/1")
		XCTAssertEqual(inst!.patient!.reference!, "Patient/1")
		XCTAssertEqual(inst!.payee!.type!.code!, "provider")
		XCTAssertEqual(inst!.priority!.code!, "normal")
		XCTAssertEqual(inst!.target!.reference!, "Organization/2")
		XCTAssertEqual(inst!.use!, "complete")
	}
	
	func testOralHealthClaim7() {
		let inst = instantiateFrom("oralhealthclaim-example.json")
		XCTAssertNotNil(inst, "Must have instantiated a OralHealthClaim instance")
	
		XCTAssertEqual(inst!.coverage![0].coverage!.reference!, "Coverage/9876B1")
		XCTAssertTrue(inst!.coverage![0].focal!)
		XCTAssertEqual(inst!.coverage![0].relationship!.code!, "self")
		XCTAssertEqual(inst!.coverage![0].sequence!, 1)
		XCTAssertEqual(inst!.created!, NSDate.dateFromISOString("2014-08-16")!)
		XCTAssertEqual(inst!.diagnosis![0].diagnosis!.code!, "123456")
		XCTAssertEqual(inst!.diagnosis![0].sequence!, 1)
		XCTAssertEqual(inst!.identifier![0].system!, NSURL(string: "http://happyvalley.com/claims")!)
		XCTAssertEqual(inst!.identifier![0].value!, "12345")
		XCTAssertEqual(inst!.item![0].net!.code!, "USD")
		XCTAssertEqual(inst!.item![0].net!.system!, NSURL(string: "urn:std:iso:4217")!)
		XCTAssertEqual(inst!.item![0].net!.value!, NSDecimalNumber(string: "135.57"))
		XCTAssertEqual(inst!.item![0].provider!.reference!, "Practitioner/1")
		XCTAssertEqual(inst!.item![0].sequence!, 1)
		XCTAssertEqual(inst!.item![0].service!.code!, "1200")
		XCTAssertEqual(inst!.item![0].serviceDate!, NSDate.dateFromISOString("2014-08-16")!)
		XCTAssertEqual(inst!.item![0].type!.code!, "service")
		XCTAssertEqual(inst!.item![0].unitPrice!.code!, "USD")
		XCTAssertEqual(inst!.item![0].unitPrice!.system!, NSURL(string: "urn:std:iso:4217")!)
		XCTAssertEqual(inst!.item![0].unitPrice!.value!, NSDecimalNumber(string: "135.57"))
		XCTAssertEqual(inst!.organization!.reference!, "Organization/1")
		XCTAssertEqual(inst!.patient!.reference!, "Patient/1")
		XCTAssertEqual(inst!.payee!.type!.code!, "provider")
		XCTAssertEqual(inst!.priority!.code!, "normal")
		XCTAssertEqual(inst!.target!.reference!, "Organization/2")
		XCTAssertEqual(inst!.use!, "complete")
	}
}
