//
//  OrganizationTests.swift
//  OrganizationTests
//
//  Generated from FHIR 0.4.0.3903 on 2014-12-22.
//  2014, SMART Platforms.
//

import Cocoa
import XCTest
import SwiftFHIR


class OrganizationTests: FHIRModelTestCase
{
	func instantiateFrom(filename: String) -> Organization? {
		let json = readJSONFile(filename)
		let instance = Organization(json: json)
		XCTAssertNotNil(instance, "Must have instantiated a test instance")
		return instance
	}
	
	func testOrganization1() {
		let inst = instantiateFrom("org-uslab-example1.canonical.json")
		XCTAssertNotNil(inst, "Must have instantiated a Organization instance")
	
		XCTAssertEqual(inst!.address![0].city!, "Harrisburg")
		XCTAssertEqual(inst!.address![0].country!, "USA")
		XCTAssertEqual(inst!.address![0].line![0], "Firstcare Way")
		XCTAssertEqual(inst!.address![0].line![1], "Building 1")
		XCTAssertEqual(inst!.address![0].postalCode!, "17111")
		XCTAssertEqual(inst!.address![0].state!, "PA")
		XCTAssertEqual(inst!.address![0].use!, "work")
		XCTAssertEqual(inst!.identifier![0].assigner!.display!, "The Centers for Medicare and Medicaid Services (CMS) National Plan and Provider Enumeration System (NPPES)")
		XCTAssertEqual(inst!.identifier![0].assigner!.reference!, "https://nppes.cms.hhs.gov/NPPES/")
		XCTAssertEqual(inst!.identifier![0].label!, "NPI")
		XCTAssertEqual(inst!.identifier![0].use!, "official")
		XCTAssertEqual(inst!.identifier![0].value!, "1235349085")
		XCTAssertEqual(inst!.name!, "University Hospital")
		XCTAssertEqual(inst!.telecom![0].system!, "phone")
		XCTAssertEqual(inst!.telecom![0].value!, "(+1) 555-227-1234")
		XCTAssertEqual(inst!.telecom![1].system!, "fax")
		XCTAssertEqual(inst!.telecom![1].value!, "(+1) 555-227-6622")
	}
	
	func testOrganization2() {
		let inst = instantiateFrom("org-uslab-example1.canonical.json")
		XCTAssertNotNil(inst, "Must have instantiated a Organization instance")
	
		XCTAssertEqual(inst!.address![0].city!, "Harrisburg")
		XCTAssertEqual(inst!.address![0].country!, "USA")
		XCTAssertEqual(inst!.address![0].line![0], "Firstcare Way")
		XCTAssertEqual(inst!.address![0].line![1], "Building 1")
		XCTAssertEqual(inst!.address![0].postalCode!, "17111")
		XCTAssertEqual(inst!.address![0].state!, "PA")
		XCTAssertEqual(inst!.address![0].use!, "work")
		XCTAssertEqual(inst!.identifier![0].assigner!.display!, "The Centers for Medicare and Medicaid Services (CMS) National Plan and Provider Enumeration System (NPPES)")
		XCTAssertEqual(inst!.identifier![0].assigner!.reference!, "https://nppes.cms.hhs.gov/NPPES/")
		XCTAssertEqual(inst!.identifier![0].label!, "NPI")
		XCTAssertEqual(inst!.identifier![0].use!, "official")
		XCTAssertEqual(inst!.identifier![0].value!, "1235349085")
		XCTAssertEqual(inst!.name!, "University Hospital")
		XCTAssertEqual(inst!.telecom![0].system!, "phone")
		XCTAssertEqual(inst!.telecom![0].value!, "(+1) 555-227-1234")
		XCTAssertEqual(inst!.telecom![1].system!, "fax")
		XCTAssertEqual(inst!.telecom![1].value!, "(+1) 555-227-6622")
	}
	
	func testOrganization3() {
		let inst = instantiateFrom("org-uslab-example1.json")
		XCTAssertNotNil(inst, "Must have instantiated a Organization instance")
	
		XCTAssertEqual(inst!.address![0].city!, "Harrisburg")
		XCTAssertEqual(inst!.address![0].country!, "USA")
		XCTAssertEqual(inst!.address![0].line![0], "Firstcare Way")
		XCTAssertEqual(inst!.address![0].line![1], "Building 1")
		XCTAssertEqual(inst!.address![0].postalCode!, "17111")
		XCTAssertEqual(inst!.address![0].state!, "PA")
		XCTAssertEqual(inst!.address![0].use!, "work")
		XCTAssertEqual(inst!.identifier![0].assigner!.display!, "The Centers for Medicare and Medicaid Services (CMS) National Plan and Provider Enumeration System (NPPES)")
		XCTAssertEqual(inst!.identifier![0].assigner!.reference!, "https://nppes.cms.hhs.gov/NPPES/")
		XCTAssertEqual(inst!.identifier![0].label!, "NPI")
		XCTAssertEqual(inst!.identifier![0].use!, "official")
		XCTAssertEqual(inst!.identifier![0].value!, "1235349085")
		XCTAssertEqual(inst!.name!, "University Hospital")
		XCTAssertEqual(inst!.telecom![0].system!, "phone")
		XCTAssertEqual(inst!.telecom![0].value!, "(+1) 555-227-1234")
		XCTAssertEqual(inst!.telecom![1].system!, "fax")
		XCTAssertEqual(inst!.telecom![1].value!, "(+1) 555-227-6622")
	}
	
	func testOrganization4() {
		let inst = instantiateFrom("org-uslab-example2.canonical.json")
		XCTAssertNotNil(inst, "Must have instantiated a Organization instance")
	
		XCTAssertEqual(inst!.address![0].city!, "Boston")
		XCTAssertEqual(inst!.address![0].country!, "USA")
		XCTAssertEqual(inst!.address![0].line![0], "Massachusetts Avenue")
		XCTAssertEqual(inst!.address![0].line![1], "Building 1")
		XCTAssertEqual(inst!.address![0].postalCode!, "25025")
		XCTAssertEqual(inst!.address![0].state!, "MA")
		XCTAssertEqual(inst!.address![0].use!, "work")
		XCTAssertEqual(inst!.contact![0].name!.family![0], "Fran")
		XCTAssertEqual(inst!.contact![0].name!.given![0], "Desk")
		XCTAssertEqual(inst!.contact![0].name!.given![1], "T")
		XCTAssertEqual(inst!.contact![0].name!.prefix![0], "Dr")
		XCTAssertEqual(inst!.contact![0].name!.suffix![0], "Jr")
		XCTAssertEqual(inst!.identifier![0].assigner!.display!, "The Centers for Medicare and Medicaid Services (CMS) National Plan and Provider Enumeration System (NPPES)")
		XCTAssertEqual(inst!.identifier![0].assigner!.reference!, "https://nppes.cms.hhs.gov/NPPES/")
		XCTAssertEqual(inst!.identifier![0].label!, "NPI")
		XCTAssertEqual(inst!.identifier![0].use!, "official")
		XCTAssertEqual(inst!.identifier![0].value!, "8235849085")
		XCTAssertEqual(inst!.name!, "Children's Hospital")
		XCTAssertEqual(inst!.telecom![0].system!, "phone")
		XCTAssertEqual(inst!.telecom![0].value!, "+1 617 555 1234")
		XCTAssertEqual(inst!.telecom![1].system!, "fax")
		XCTAssertEqual(inst!.telecom![1].value!, "+1 555 227 6622")
	}
	
	func testOrganization5() {
		let inst = instantiateFrom("org-uslab-example2.json")
		XCTAssertNotNil(inst, "Must have instantiated a Organization instance")
	
		XCTAssertEqual(inst!.address![0].city!, "Boston")
		XCTAssertEqual(inst!.address![0].country!, "USA")
		XCTAssertEqual(inst!.address![0].line![0], "Massachusetts Avenue")
		XCTAssertEqual(inst!.address![0].line![1], "Building 1")
		XCTAssertEqual(inst!.address![0].postalCode!, "25025")
		XCTAssertEqual(inst!.address![0].state!, "MA")
		XCTAssertEqual(inst!.address![0].use!, "work")
		XCTAssertEqual(inst!.contact![0].name!.family![0], "Fran")
		XCTAssertEqual(inst!.contact![0].name!.given![0], "Desk")
		XCTAssertEqual(inst!.contact![0].name!.given![1], "T")
		XCTAssertEqual(inst!.contact![0].name!.prefix![0], "Dr")
		XCTAssertEqual(inst!.contact![0].name!.suffix![0], "Jr")
		XCTAssertEqual(inst!.identifier![0].assigner!.display!, "The Centers for Medicare and Medicaid Services (CMS) National Plan and Provider Enumeration System (NPPES)")
		XCTAssertEqual(inst!.identifier![0].assigner!.reference!, "https://nppes.cms.hhs.gov/NPPES/")
		XCTAssertEqual(inst!.identifier![0].label!, "NPI")
		XCTAssertEqual(inst!.identifier![0].use!, "official")
		XCTAssertEqual(inst!.identifier![0].value!, "8235849085")
		XCTAssertEqual(inst!.name!, "Children's Hospital")
		XCTAssertEqual(inst!.telecom![0].system!, "phone")
		XCTAssertEqual(inst!.telecom![0].value!, "+1 617 555 1234")
		XCTAssertEqual(inst!.telecom![1].system!, "fax")
		XCTAssertEqual(inst!.telecom![1].value!, "+1 555 227 6622")
	}
	
	func testOrganization6() {
		let inst = instantiateFrom("org-uslab-example3.canonical.json")
		XCTAssertNotNil(inst, "Must have instantiated a Organization instance")
	
		XCTAssertEqual(inst!.address![0].city!, "Harrisburg")
		XCTAssertEqual(inst!.address![0].country!, "USA")
		XCTAssertEqual(inst!.address![0].line![0], "Firstcare Way")
		XCTAssertEqual(inst!.address![0].line![1], "Building 2")
		XCTAssertEqual(inst!.address![0].postalCode!, "42043")
		XCTAssertEqual(inst!.address![0].state!, "PA")
		XCTAssertEqual(inst!.address![0].use!, "work")
		XCTAssertEqual(inst!.contact![0].name!.family![0], "House")
		XCTAssertEqual(inst!.contact![0].name!.given![0], "Gregory")
		XCTAssertEqual(inst!.contact![0].name!.given![1], "F")
		XCTAssertEqual(inst!.contact![0].name!.prefix![0], "Dr")
		XCTAssertEqual(inst!.contact![0].name!.suffix![0], "PhD")
		XCTAssertEqual(inst!.identifier![0].assigner!.display!, "The Centers for Medicare and Medicaid Services (CMS)  Clinical Laboratory Improvement Amendments (CLIA)")
		XCTAssertEqual(inst!.identifier![0].assigner!.reference!, "http://www.cms.gov/Regulations-and-Guidance/Legislation/CLIA/index.html")
		XCTAssertEqual(inst!.identifier![0].label!, "CLIA")
		XCTAssertEqual(inst!.identifier![0].use!, "official")
		XCTAssertEqual(inst!.identifier![0].value!, "01D1111111")
		XCTAssertEqual(inst!.name!, "Acme Labs")
	}
	
	func testOrganization7() {
		let inst = instantiateFrom("org-uslab-example3.json")
		XCTAssertNotNil(inst, "Must have instantiated a Organization instance")
	
		XCTAssertEqual(inst!.address![0].city!, "Harrisburg")
		XCTAssertEqual(inst!.address![0].country!, "USA")
		XCTAssertEqual(inst!.address![0].line![0], "Firstcare Way")
		XCTAssertEqual(inst!.address![0].line![1], "Building 2")
		XCTAssertEqual(inst!.address![0].postalCode!, "42043")
		XCTAssertEqual(inst!.address![0].state!, "PA")
		XCTAssertEqual(inst!.address![0].use!, "work")
		XCTAssertEqual(inst!.contact![0].name!.family![0], "House")
		XCTAssertEqual(inst!.contact![0].name!.given![0], "Gregory")
		XCTAssertEqual(inst!.contact![0].name!.given![1], "F")
		XCTAssertEqual(inst!.contact![0].name!.prefix![0], "Dr")
		XCTAssertEqual(inst!.contact![0].name!.suffix![0], "PhD")
		XCTAssertEqual(inst!.identifier![0].assigner!.display!, "The Centers for Medicare and Medicaid Services (CMS)  Clinical Laboratory Improvement Amendments (CLIA)")
		XCTAssertEqual(inst!.identifier![0].assigner!.reference!, "http://www.cms.gov/Regulations-and-Guidance/Legislation/CLIA/index.html")
		XCTAssertEqual(inst!.identifier![0].label!, "CLIA")
		XCTAssertEqual(inst!.identifier![0].use!, "official")
		XCTAssertEqual(inst!.identifier![0].value!, "01D1111111")
		XCTAssertEqual(inst!.name!, "Acme Labs")
	}
	
	func testOrganization8() {
		let inst = instantiateFrom("organization-example-f001-burgers.canonical.json")
		XCTAssertNotNil(inst, "Must have instantiated a Organization instance")
	
		XCTAssertEqual(inst!.address![0].city!, "Den Burg")
		XCTAssertEqual(inst!.address![0].country!, "NLD")
		XCTAssertEqual(inst!.address![0].line![0], "Galapagosweg 91")
		XCTAssertEqual(inst!.address![0].postalCode!, "9105 PZ")
		XCTAssertEqual(inst!.address![0].use!, "work")
		XCTAssertEqual(inst!.address![1].city!, "Den Burg")
		XCTAssertEqual(inst!.address![1].country!, "NLD")
		XCTAssertEqual(inst!.address![1].line![0], "PO Box 2311")
		XCTAssertEqual(inst!.address![1].postalCode!, "9100 AA")
		XCTAssertEqual(inst!.address![1].use!, "work")
		XCTAssertEqual(inst!.contact![0].purpose!.coding![0].code!, "PRESS")
		XCTAssertEqual(inst!.contact![0].purpose!.coding![0].system!, NSURL(string: "http://hl7.org/fhir/contactentity-type")!)
		XCTAssertEqual(inst!.contact![0].telecom![0].system!, "phone")
		XCTAssertEqual(inst!.contact![0].telecom![0].value!, "022-655 2334")
		XCTAssertEqual(inst!.contact![1].purpose!.coding![0].code!, "PATINF")
		XCTAssertEqual(inst!.contact![1].purpose!.coding![0].system!, NSURL(string: "http://hl7.org/fhir/contactentity-type")!)
		XCTAssertEqual(inst!.contact![1].telecom![0].system!, "phone")
		XCTAssertEqual(inst!.contact![1].telecom![0].value!, "022-655 2335")
		XCTAssertEqual(inst!.identifier![0].system!, NSURL(string: "urn:oid:2.16.528.1")!)
		XCTAssertEqual(inst!.identifier![0].use!, "official")
		XCTAssertEqual(inst!.identifier![0].value!, "91654")
		XCTAssertEqual(inst!.identifier![1].system!, NSURL(string: "urn:oid:2.16.840.1.113883.2.4.6.1")!)
		XCTAssertEqual(inst!.identifier![1].use!, "usual")
		XCTAssertEqual(inst!.identifier![1].value!, "17-0112278")
		XCTAssertEqual(inst!.name!, "Burgers University Medical Center")
		XCTAssertEqual(inst!.telecom![0].system!, "phone")
		XCTAssertEqual(inst!.telecom![0].use!, "work")
		XCTAssertEqual(inst!.telecom![0].value!, "022-655 2300")
		XCTAssertEqual(inst!.type!.coding![0].code!, "V6")
		XCTAssertEqual(inst!.type!.coding![0].display!, "University Medical Hospital")
		XCTAssertEqual(inst!.type!.coding![0].system!, NSURL(string: "urn:oid:2.16.840.1.113883.2.4.15.1060")!)
		XCTAssertEqual(inst!.type!.coding![1].code!, "prov")
		XCTAssertEqual(inst!.type!.coding![1].display!, "Healthcare Provider")
		XCTAssertEqual(inst!.type!.coding![1].system!, NSURL(string: "http://hl7.org/fhir/organization-type")!)
	}
	
	func testOrganization9() {
		let inst = instantiateFrom("organization-example-f001-burgers.json")
		XCTAssertNotNil(inst, "Must have instantiated a Organization instance")
	
		XCTAssertEqual(inst!.address![0].city!, "Den Burg")
		XCTAssertEqual(inst!.address![0].country!, "NLD")
		XCTAssertEqual(inst!.address![0].line![0], "Galapagosweg 91")
		XCTAssertEqual(inst!.address![0].postalCode!, "9105 PZ")
		XCTAssertEqual(inst!.address![0].use!, "work")
		XCTAssertEqual(inst!.address![1].city!, "Den Burg")
		XCTAssertEqual(inst!.address![1].country!, "NLD")
		XCTAssertEqual(inst!.address![1].line![0], "PO Box 2311")
		XCTAssertEqual(inst!.address![1].postalCode!, "9100 AA")
		XCTAssertEqual(inst!.address![1].use!, "work")
		XCTAssertEqual(inst!.contact![0].purpose!.coding![0].code!, "PRESS")
		XCTAssertEqual(inst!.contact![0].purpose!.coding![0].system!, NSURL(string: "http://hl7.org/fhir/contactentity-type")!)
		XCTAssertEqual(inst!.contact![0].telecom![0].system!, "phone")
		XCTAssertEqual(inst!.contact![0].telecom![0].value!, "022-655 2334")
		XCTAssertEqual(inst!.contact![1].purpose!.coding![0].code!, "PATINF")
		XCTAssertEqual(inst!.contact![1].purpose!.coding![0].system!, NSURL(string: "http://hl7.org/fhir/contactentity-type")!)
		XCTAssertEqual(inst!.contact![1].telecom![0].system!, "phone")
		XCTAssertEqual(inst!.contact![1].telecom![0].value!, "022-655 2335")
		XCTAssertEqual(inst!.identifier![0].system!, NSURL(string: "urn:oid:2.16.528.1")!)
		XCTAssertEqual(inst!.identifier![0].use!, "official")
		XCTAssertEqual(inst!.identifier![0].value!, "91654")
		XCTAssertEqual(inst!.identifier![1].system!, NSURL(string: "urn:oid:2.16.840.1.113883.2.4.6.1")!)
		XCTAssertEqual(inst!.identifier![1].use!, "usual")
		XCTAssertEqual(inst!.identifier![1].value!, "17-0112278")
		XCTAssertEqual(inst!.name!, "Burgers University Medical Center")
		XCTAssertEqual(inst!.telecom![0].system!, "phone")
		XCTAssertEqual(inst!.telecom![0].use!, "work")
		XCTAssertEqual(inst!.telecom![0].value!, "022-655 2300")
		XCTAssertEqual(inst!.type!.coding![0].code!, "V6")
		XCTAssertEqual(inst!.type!.coding![0].display!, "University Medical Hospital")
		XCTAssertEqual(inst!.type!.coding![0].system!, NSURL(string: "urn:oid:2.16.840.1.113883.2.4.15.1060")!)
		XCTAssertEqual(inst!.type!.coding![1].code!, "prov")
		XCTAssertEqual(inst!.type!.coding![1].display!, "Healthcare Provider")
		XCTAssertEqual(inst!.type!.coding![1].system!, NSURL(string: "http://hl7.org/fhir/organization-type")!)
	}
	
	func testOrganization10() {
		let inst = instantiateFrom("organization-example-f002-burgers-card.canonical.json")
		XCTAssertNotNil(inst, "Must have instantiated a Organization instance")
	
		XCTAssertFalse(inst!.active!)
		XCTAssertEqual(inst!.address![0].line![0], "South Wing, floor 2")
		XCTAssertEqual(inst!.contact![0].address!.line![0], "South Wing, floor 2")
		XCTAssertEqual(inst!.contact![0].name!.text!, "mevr. D. de Haan")
		XCTAssertEqual(inst!.contact![0].purpose!.coding![0].code!, "ADMIN")
		XCTAssertEqual(inst!.contact![0].purpose!.coding![0].system!, NSURL(string: "http://hl7.org/fhir/contactentity-type")!)
		XCTAssertEqual(inst!.contact![0].telecom![0].system!, "phone")
		XCTAssertEqual(inst!.contact![0].telecom![0].value!, "022-655 2321")
		XCTAssertEqual(inst!.contact![0].telecom![1].system!, "email")
		XCTAssertEqual(inst!.contact![0].telecom![1].value!, "cardio@burgersumc.nl")
		XCTAssertEqual(inst!.contact![0].telecom![2].system!, "fax")
		XCTAssertEqual(inst!.contact![0].telecom![2].value!, "022-655 2322")
		XCTAssertEqual(inst!.name!, "Burgers UMC Cardiology unit")
		XCTAssertEqual(inst!.partOf!.reference!, "Organization/f001")
		XCTAssertEqual(inst!.telecom![0].system!, "phone")
		XCTAssertEqual(inst!.telecom![0].value!, "022-655 2320")
		XCTAssertEqual(inst!.type!.coding![0].code!, "dept")
		XCTAssertEqual(inst!.type!.coding![0].display!, "Hospital Department")
		XCTAssertEqual(inst!.type!.coding![0].system!, NSURL(string: "http://hl7.org/fhir/organization-type")!)
	}
}
