//
//  QuestionnaireResponseTests.swift
//  SwiftFHIR
//
//  Generated from FHIR 3.0.0.11828 on 2017-04-18.
//  2017, SMART Health IT.
//

import XCTest
#if !NO_MODEL_IMPORT
import Models
typealias SwiftFHIRQuestionnaireResponse = Models.QuestionnaireResponse
#else
import SwiftFHIR
typealias SwiftFHIRQuestionnaireResponse = SwiftFHIR.QuestionnaireResponse
#endif


class QuestionnaireResponseTests: XCTestCase {
	
	func instantiateFrom(filename: String) throws -> SwiftFHIRQuestionnaireResponse {
		return try instantiateFrom(json: try readJSONFile(filename))
	}
	
	func instantiateFrom(json: FHIRJSON) throws -> SwiftFHIRQuestionnaireResponse {
		return try SwiftFHIRQuestionnaireResponse(json: json)
	}
	
	func testQuestionnaireResponse1() {
		do {
			let instance = try runQuestionnaireResponse1()
			try runQuestionnaireResponse1(instance.asJSON())
		}
		catch let error {
			XCTAssertTrue(false, "Must instantiate and test QuestionnaireResponse successfully, but threw:\n---\n\(error)\n---")
		}
	}
	
	@discardableResult
	func runQuestionnaireResponse1(_ json: FHIRJSON? = nil) throws -> SwiftFHIRQuestionnaireResponse {
		let inst = (nil != json) ? try instantiateFrom(json: json!) : try instantiateFrom(filename: "questionnaireresponse-example-bluebook.json")
		
		XCTAssertEqual(inst.author?.reference, "http://hl7.org/fhir/Practitioner/example")
		XCTAssertEqual(inst.authored?.description, "2013-02-19T14:15:00+10:00")
		XCTAssertEqual(inst.id, "bb")
		XCTAssertEqual(inst.item?[0].item?[0].item?[0].answer?[0].valueString, "Cathy Jones")
		XCTAssertEqual(inst.item?[0].item?[0].item?[0].linkId, "nameOfChild")
		XCTAssertEqual(inst.item?[0].item?[0].item?[0].text, "Name of child")
		XCTAssertEqual(inst.item?[0].item?[0].item?[1].answer?[0].valueCoding?.code, "f")
		XCTAssertEqual(inst.item?[0].item?[0].item?[1].linkId, "sex")
		XCTAssertEqual(inst.item?[0].item?[0].item?[1].text, "Sex")
		XCTAssertEqual(inst.item?[0].item?[0].linkId, "group")
		XCTAssertEqual(inst.item?[0].item?[1].item?[0].answer?[0].valueDecimal, "3.25")
		XCTAssertEqual(inst.item?[0].item?[1].item?[0].linkId, "birthWeight")
		XCTAssertEqual(inst.item?[0].item?[1].item?[0].text, "Birth weight (kg)")
		XCTAssertEqual(inst.item?[0].item?[1].item?[1].answer?[0].valueDecimal, "44.3")
		XCTAssertEqual(inst.item?[0].item?[1].item?[1].linkId, "birthLength")
		XCTAssertEqual(inst.item?[0].item?[1].item?[1].text, "Birth length (cm)")
		XCTAssertEqual(inst.item?[0].item?[1].item?[2].answer?[0].item?[0].item?[0].answer?[0].valueDate?.description, "1972-11-30")
		XCTAssertEqual(inst.item?[0].item?[1].item?[2].answer?[0].item?[0].item?[0].linkId, "vitaminKDose1")
		XCTAssertEqual(inst.item?[0].item?[1].item?[2].answer?[0].item?[0].item?[0].text, "1st dose")
		XCTAssertEqual(inst.item?[0].item?[1].item?[2].answer?[0].item?[0].item?[1].answer?[0].valueDate?.description, "1972-12-11")
		XCTAssertEqual(inst.item?[0].item?[1].item?[2].answer?[0].item?[0].item?[1].linkId, "vitaminKDose2")
		XCTAssertEqual(inst.item?[0].item?[1].item?[2].answer?[0].item?[0].item?[1].text, "2nd dose")
		XCTAssertEqual(inst.item?[0].item?[1].item?[2].answer?[0].item?[0].linkId, "vitaminKgivenDoses")
		XCTAssertEqual(inst.item?[0].item?[1].item?[2].answer?[0].valueCoding?.code, "INJECTION")
		XCTAssertEqual(inst.item?[0].item?[1].item?[2].linkId, "vitaminKgiven")
		XCTAssertEqual(inst.item?[0].item?[1].item?[2].text, "Vitamin K given")
		XCTAssertEqual(inst.item?[0].item?[1].item?[3].answer?[0].item?[0].answer?[0].valueDate?.description, "1972-12-04")
		XCTAssertEqual(inst.item?[0].item?[1].item?[3].answer?[0].item?[0].linkId, "hepBgivenDate")
		XCTAssertEqual(inst.item?[0].item?[1].item?[3].answer?[0].item?[0].text, "Date given")
		XCTAssertEqual(inst.item?[0].item?[1].item?[3].answer?[0].valueBoolean, true)
		XCTAssertEqual(inst.item?[0].item?[1].item?[3].linkId, "hepBgiven")
		XCTAssertEqual(inst.item?[0].item?[1].item?[3].text, "Hep B given y / n")
		XCTAssertEqual(inst.item?[0].item?[1].item?[4].answer?[0].valueString, "Already able to speak Chinese")
		XCTAssertEqual(inst.item?[0].item?[1].item?[4].linkId, "abnormalitiesAtBirth")
		XCTAssertEqual(inst.item?[0].item?[1].item?[4].text, "Abnormalities noted at birth")
		XCTAssertEqual(inst.item?[0].item?[1].linkId, "neonatalInformation")
		XCTAssertEqual(inst.item?[0].item?[1].text, "Neonatal Information")
		XCTAssertEqual(inst.item?[0].linkId, "birthDetails")
		XCTAssertEqual(inst.item?[0].text, "Birth details - To be completed by health professional")
		XCTAssertEqual(inst.status, QuestionnaireResponseStatus(rawValue: "completed")!)
		XCTAssertEqual(inst.subject?.reference, "http://hl7.org/fhir/Patient/1")
		XCTAssertEqual(inst.text?.status, NarrativeStatus(rawValue: "generated")!)
		
		return inst
	}
	
	func testQuestionnaireResponse2() {
		do {
			let instance = try runQuestionnaireResponse2()
			try runQuestionnaireResponse2(instance.asJSON())
		}
		catch let error {
			XCTAssertTrue(false, "Must instantiate and test QuestionnaireResponse successfully, but threw:\n---\n\(error)\n---")
		}
	}
	
	@discardableResult
	func runQuestionnaireResponse2(_ json: FHIRJSON? = nil) throws -> SwiftFHIRQuestionnaireResponse {
		let inst = (nil != json) ? try instantiateFrom(json: json!) : try instantiateFrom(filename: "questionnaireresponse-example-f201-lifelines.json")
		
		XCTAssertEqual(inst.author?.reference, "Practitioner/f201")
		XCTAssertEqual(inst.authored?.description, "2013-06-18T00:00:00+01:00")
		XCTAssertEqual(inst.id, "f201")
		XCTAssertEqual(inst.item?[0].item?[0].answer?[0].valueString, "I am allergic to house dust")
		XCTAssertEqual(inst.item?[0].item?[0].linkId, "1.1")
		XCTAssertEqual(inst.item?[0].item?[0].text, "Do you have allergies?")
		XCTAssertEqual(inst.item?[0].linkId, "1")
		XCTAssertEqual(inst.item?[1].item?[0].answer?[0].valueString, "Male")
		XCTAssertEqual(inst.item?[1].item?[0].linkId, "2.1")
		XCTAssertEqual(inst.item?[1].item?[0].text, "What is your gender?")
		XCTAssertEqual(inst.item?[1].item?[1].answer?[0].valueDate?.description, "1960-03-13")
		XCTAssertEqual(inst.item?[1].item?[1].linkId, "2.2")
		XCTAssertEqual(inst.item?[1].item?[1].text, "What is your date of birth?")
		XCTAssertEqual(inst.item?[1].item?[2].answer?[0].valueString, "The Netherlands")
		XCTAssertEqual(inst.item?[1].item?[2].linkId, "2.3")
		XCTAssertEqual(inst.item?[1].item?[2].text, "What is your country of birth?")
		XCTAssertEqual(inst.item?[1].item?[3].answer?[0].valueString, "married")
		XCTAssertEqual(inst.item?[1].item?[3].linkId, "2.4")
		XCTAssertEqual(inst.item?[1].item?[3].text, "What is your marital status?")
		XCTAssertEqual(inst.item?[1].linkId, "2")
		XCTAssertEqual(inst.item?[1].text, "General questions")
		XCTAssertEqual(inst.item?[2].item?[0].answer?[0].valueString, "No")
		XCTAssertEqual(inst.item?[2].item?[0].linkId, "3.1")
		XCTAssertEqual(inst.item?[2].item?[0].text, "Do you smoke?")
		XCTAssertEqual(inst.item?[2].item?[1].answer?[0].valueString, "No, but I used to drink")
		XCTAssertEqual(inst.item?[2].item?[1].linkId, "3.2")
		XCTAssertEqual(inst.item?[2].item?[1].text, "Do you drink alchohol?")
		XCTAssertEqual(inst.item?[2].linkId, "3")
		XCTAssertEqual(inst.item?[2].text, "Intoxications")
		XCTAssertEqual(inst.source?.reference, "Practitioner/f201")
		XCTAssertEqual(inst.status, QuestionnaireResponseStatus(rawValue: "completed")!)
		XCTAssertEqual(inst.subject?.display, "Roel")
		XCTAssertEqual(inst.subject?.reference, "Patient/f201")
		XCTAssertEqual(inst.text?.status, NarrativeStatus(rawValue: "generated")!)
		
		return inst
	}
	
	func testQuestionnaireResponse3() {
		do {
			let instance = try runQuestionnaireResponse3()
			try runQuestionnaireResponse3(instance.asJSON())
		}
		catch let error {
			XCTAssertTrue(false, "Must instantiate and test QuestionnaireResponse successfully, but threw:\n---\n\(error)\n---")
		}
	}
	
	@discardableResult
	func runQuestionnaireResponse3(_ json: FHIRJSON? = nil) throws -> SwiftFHIRQuestionnaireResponse {
		let inst = (nil != json) ? try instantiateFrom(json: json!) : try instantiateFrom(filename: "questionnaireresponse-example-gcs.json")
		
		XCTAssertEqual(inst.authored?.description, "2014-12-11T04:44:16Z")
		XCTAssertEqual(inst.id, "gcs")
		XCTAssertEqual(inst.item?[0].answer?[0].valueCoding?.code, "LA6560-2")
		XCTAssertEqual(inst.item?[0].answer?[0].valueCoding?.display, "Confused")
		XCTAssertEqual(inst.item?[0].answer?[0].valueCoding?.extension_fhir?[0].url?.absoluteString, "http://hl7.org/fhir/StructureDefinition/iso21090-CO-value")
		XCTAssertEqual(inst.item?[0].answer?[0].valueCoding?.extension_fhir?[0].valueDecimal, "4")
		XCTAssertEqual(inst.item?[0].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[0].linkId, "1.1")
		XCTAssertEqual(inst.item?[1].answer?[0].valueCoding?.code, "LA6566-9")
		XCTAssertEqual(inst.item?[1].answer?[0].valueCoding?.display, "Localizing pain")
		XCTAssertEqual(inst.item?[1].answer?[0].valueCoding?.extension_fhir?[0].url?.absoluteString, "http://hl7.org/fhir/StructureDefinition/iso21090-CO-value")
		XCTAssertEqual(inst.item?[1].answer?[0].valueCoding?.extension_fhir?[0].valueDecimal, "5")
		XCTAssertEqual(inst.item?[1].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[1].linkId, "1.2")
		XCTAssertEqual(inst.item?[2].answer?[0].valueCoding?.code, "LA6556-0")
		XCTAssertEqual(inst.item?[2].answer?[0].valueCoding?.display, "Eyes open spontaneously")
		XCTAssertEqual(inst.item?[2].answer?[0].valueCoding?.extension_fhir?[0].url?.absoluteString, "http://hl7.org/fhir/StructureDefinition/iso21090-CO-value")
		XCTAssertEqual(inst.item?[2].answer?[0].valueCoding?.extension_fhir?[0].valueDecimal, "4")
		XCTAssertEqual(inst.item?[2].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].linkId, "1.3")
		XCTAssertEqual(inst.questionnaire?.reference, "Questionnaire/gcs")
		XCTAssertEqual(inst.source?.reference, "Practitioner/f007")
		XCTAssertEqual(inst.status, QuestionnaireResponseStatus(rawValue: "completed")!)
		XCTAssertEqual(inst.subject?.display, "Peter James Chalmers")
		XCTAssertEqual(inst.subject?.reference, "Patient/example")
		XCTAssertEqual(inst.text?.status, NarrativeStatus(rawValue: "generated")!)
		
		return inst
	}
	
	func testQuestionnaireResponse4() {
		do {
			let instance = try runQuestionnaireResponse4()
			try runQuestionnaireResponse4(instance.asJSON())
		}
		catch let error {
			XCTAssertTrue(false, "Must instantiate and test QuestionnaireResponse successfully, but threw:\n---\n\(error)\n---")
		}
	}
	
	@discardableResult
	func runQuestionnaireResponse4(_ json: FHIRJSON? = nil) throws -> SwiftFHIRQuestionnaireResponse {
		let inst = (nil != json) ? try instantiateFrom(json: json!) : try instantiateFrom(filename: "questionnaireresponse-example-ussg-fht-answers.json")
		
		XCTAssertEqual(inst.authored?.description, "2008-01-17")
		XCTAssertEqual(inst.id, "ussg-fht-answers")
		XCTAssertEqual(inst.item?[0].item?[0].answer?[0].valueDate?.description, "2008-01-17")
		XCTAssertEqual(inst.item?[0].item?[0].linkId, "0.1")
		XCTAssertEqual(inst.item?[0].item?[0].text, "Date Done")
		XCTAssertEqual(inst.item?[0].linkId, "0")
		XCTAssertEqual(inst.item?[1].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54126-8")
		XCTAssertEqual(inst.item?[1].item?[0].item?[0].answer?[0].valueString, "Annie Proband")
		XCTAssertEqual(inst.item?[1].item?[0].item?[0].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54125-0")
		XCTAssertEqual(inst.item?[1].item?[0].item?[0].linkId, "1.1.1")
		XCTAssertEqual(inst.item?[1].item?[0].item?[0].text, "Name")
		XCTAssertEqual(inst.item?[1].item?[0].item?[1].answer?[0].valueCoding?.code, "LA3-6")
		XCTAssertEqual(inst.item?[1].item?[0].item?[1].answer?[0].valueCoding?.display, "Female")
		XCTAssertEqual(inst.item?[1].item?[0].item?[1].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[1].item?[0].item?[1].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54131-8")
		XCTAssertEqual(inst.item?[1].item?[0].item?[1].linkId, "1.1.2")
		XCTAssertEqual(inst.item?[1].item?[0].item?[1].text, "Gender")
		XCTAssertEqual(inst.item?[1].item?[0].item?[2].answer?[0].valueDate?.description, "1966-04-04")
		XCTAssertEqual(inst.item?[1].item?[0].item?[2].definition?.absoluteString, "http://loinc.org/fhir/DataElement/21112-8")
		XCTAssertEqual(inst.item?[1].item?[0].item?[2].linkId, "1.1.3")
		XCTAssertEqual(inst.item?[1].item?[0].item?[2].text, "Date of Birth")
		XCTAssertEqual(inst.item?[1].item?[0].item?[3].answer?[0].valueCoding?.code, "LA32-8")
		XCTAssertEqual(inst.item?[1].item?[0].item?[3].answer?[0].valueCoding?.display, "No")
		XCTAssertEqual(inst.item?[1].item?[0].item?[3].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[1].item?[0].item?[3].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54132-6")
		XCTAssertEqual(inst.item?[1].item?[0].item?[3].linkId, "1.1.4")
		XCTAssertEqual(inst.item?[1].item?[0].item?[3].text, "Were you born a twin?")
		XCTAssertEqual(inst.item?[1].item?[0].item?[4].answer?[0].valueCoding?.code, "LA32-8")
		XCTAssertEqual(inst.item?[1].item?[0].item?[4].answer?[0].valueCoding?.display, "No")
		XCTAssertEqual(inst.item?[1].item?[0].item?[4].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[1].item?[0].item?[4].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54128-4")
		XCTAssertEqual(inst.item?[1].item?[0].item?[4].linkId, "1.1.5")
		XCTAssertEqual(inst.item?[1].item?[0].item?[4].text, "Were you adopted?")
		XCTAssertEqual(inst.item?[1].item?[0].item?[5].answer?[0].valueCoding?.code, "LA32-8")
		XCTAssertEqual(inst.item?[1].item?[0].item?[5].answer?[0].valueCoding?.display, "No")
		XCTAssertEqual(inst.item?[1].item?[0].item?[5].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[1].item?[0].item?[5].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54135-9")
		XCTAssertEqual(inst.item?[1].item?[0].item?[5].linkId, "1.1.6")
		XCTAssertEqual(inst.item?[1].item?[0].item?[5].text, "Are your parents related to each other in any way other than marriage?")
		XCTAssertEqual(inst.item?[1].item?[0].item?[6].answer?[0].item?[0].item?[0].answer?[0].valueCoding?.code, "[in_i]")
		XCTAssertEqual(inst.item?[1].item?[0].item?[6].answer?[0].item?[0].item?[0].answer?[0].valueCoding?.display, "inches")
		XCTAssertEqual(inst.item?[1].item?[0].item?[6].answer?[0].item?[0].item?[0].answer?[0].valueCoding?.system?.absoluteString, "http://unitsofmeasure.org")
		XCTAssertEqual(inst.item?[1].item?[0].item?[6].answer?[0].item?[0].item?[0].linkId, "1.1.7.1.1")
		XCTAssertEqual(inst.item?[1].item?[0].item?[6].answer?[0].item?[0].item?[0].text, "Units")
		XCTAssertEqual(inst.item?[1].item?[0].item?[6].answer?[0].item?[0].linkId, "1.1.7.1")
		XCTAssertEqual(inst.item?[1].item?[0].item?[6].answer?[0].valueDecimal, "63")
		XCTAssertEqual(inst.item?[1].item?[0].item?[6].definition?.absoluteString, "http://loinc.org/fhir/DataElement/8302-2")
		XCTAssertEqual(inst.item?[1].item?[0].item?[6].linkId, "1.1.7")
		XCTAssertEqual(inst.item?[1].item?[0].item?[6].text, "Height")
		XCTAssertEqual(inst.item?[1].item?[0].item?[7].answer?[0].item?[0].item?[0].answer?[0].valueCoding?.code, "lb")
		XCTAssertEqual(inst.item?[1].item?[0].item?[7].answer?[0].item?[0].item?[0].answer?[0].valueCoding?.display, "pounds")
		XCTAssertEqual(inst.item?[1].item?[0].item?[7].answer?[0].item?[0].item?[0].answer?[0].valueCoding?.system?.absoluteString, "http://unitsofmeasure.org")
		XCTAssertEqual(inst.item?[1].item?[0].item?[7].answer?[0].item?[0].item?[0].linkId, "1.1.8.1.1")
		XCTAssertEqual(inst.item?[1].item?[0].item?[7].answer?[0].item?[0].item?[0].text, "Units")
		XCTAssertEqual(inst.item?[1].item?[0].item?[7].answer?[0].item?[0].linkId, "1.1.8.1")
		XCTAssertEqual(inst.item?[1].item?[0].item?[7].answer?[0].valueDecimal, "127")
		XCTAssertEqual(inst.item?[1].item?[0].item?[7].definition?.absoluteString, "http://loinc.org/fhir/DataElement/29463-7")
		XCTAssertEqual(inst.item?[1].item?[0].item?[7].linkId, "1.1.8")
		XCTAssertEqual(inst.item?[1].item?[0].item?[7].text, "Weight")
		XCTAssertEqual(inst.item?[1].item?[0].item?[8].answer?[0].valueDecimal, "22.5")
		XCTAssertEqual(inst.item?[1].item?[0].item?[8].definition?.absoluteString, "http://loinc.org/fhir/DataElement/39156-5")
		XCTAssertEqual(inst.item?[1].item?[0].item?[8].linkId, "1.1.9")
		XCTAssertEqual(inst.item?[1].item?[0].item?[8].text, "Body mass index (BMI) [Ratio]")
		XCTAssertEqual(inst.item?[1].item?[0].item?[9].answer?[0].valueCoding?.code, "LA4457-3")
		XCTAssertEqual(inst.item?[1].item?[0].item?[9].answer?[0].valueCoding?.display, "White")
		XCTAssertEqual(inst.item?[1].item?[0].item?[9].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[1].item?[0].item?[9].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54134-2")
		XCTAssertEqual(inst.item?[1].item?[0].item?[9].linkId, "1.1.10")
		XCTAssertEqual(inst.item?[1].item?[0].item?[9].text, "Race")
		XCTAssertEqual(inst.item?[1].item?[0].linkId, "1.1")
		XCTAssertEqual(inst.item?[1].linkId, "1")
		XCTAssertEqual(inst.item?[1].text, "Your health information")
		XCTAssertEqual(inst.item?[2].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54114-4")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].item?[0].answer?[0].valueCoding?.code, "LA10405-1")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].item?[0].answer?[0].valueCoding?.display, "Daughter")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].item?[0].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].item?[0].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54136-7")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].item?[0].linkId, "2.1.1.1")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].item?[0].text, "Relationship to you")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].item?[1].answer?[0].valueString, "Susan")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].item?[1].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54138-3")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].item?[1].linkId, "2.1.1.2")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].item?[1].text, "Name")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].item?[2].answer?[0].valueCoding?.code, "LA3-6")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].item?[2].answer?[0].valueCoding?.display, "Female")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].item?[2].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].item?[2].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54123-5")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].item?[2].linkId, "2.1.1.3")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].item?[2].text, "Gender")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].item?[3].answer?[0].item?[0].item?[0].answer?[0].valueDecimal, "17")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].item?[3].answer?[0].item?[0].item?[0].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54141-7")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].item?[3].answer?[0].item?[0].item?[0].linkId, "2.1.1.4.2.2")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].item?[3].answer?[0].item?[0].item?[0].text, "Age")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].item?[3].answer?[0].item?[0].linkId, "2.1.1.4.2")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].item?[3].answer?[0].valueCoding?.code, "LA33-6")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].item?[3].answer?[0].valueCoding?.display, "Yes")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].item?[3].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].item?[3].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54139-1")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].item?[3].linkId, "2.1.1.4")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].item?[3].text, "Living?")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].item?[4].answer?[0].valueCoding?.code, "LA32-8")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].item?[4].answer?[0].valueCoding?.display, "No")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].item?[4].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].item?[4].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54121-9")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].item?[4].linkId, "2.1.1.5")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].item?[4].text, "Was this person born a twin?")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].item?[5].answer?[0].valueCoding?.code, "LA32-8")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].item?[5].answer?[0].valueCoding?.display, "No")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].item?[5].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].item?[5].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54122-7")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].item?[5].linkId, "2.1.1.6")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].item?[5].text, "Was this person adopted?")
		XCTAssertEqual(inst.item?[2].item?[0].item?[0].linkId, "2.1.1")
		XCTAssertEqual(inst.item?[2].item?[0].linkId, "2.1")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].item?[0].answer?[0].valueCoding?.code, "LA10415-0")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].item?[0].answer?[0].valueCoding?.display, "Brother")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].item?[0].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].item?[0].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54136-7")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].item?[0].linkId, "2.1.1.1")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].item?[0].text, "Relationship to you")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].item?[1].answer?[0].valueString, "Brian")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].item?[1].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54138-3")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].item?[1].linkId, "2.1.1.2")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].item?[1].text, "Name")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].item?[2].answer?[0].valueCoding?.code, "LA2-8")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].item?[2].answer?[0].valueCoding?.display, "Male")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].item?[2].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].item?[2].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54123-5")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].item?[2].linkId, "2.1.1.3")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].item?[2].text, "Gender")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].item?[3].answer?[0].item?[0].item?[0].answer?[0].valueDecimal, "32")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].item?[3].answer?[0].item?[0].item?[0].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54141-7")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].item?[3].answer?[0].item?[0].item?[0].linkId, "2.1.1.4.2.2")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].item?[3].answer?[0].item?[0].item?[0].text, "Age")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].item?[3].answer?[0].item?[0].linkId, "2.1.1.4.2")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].item?[3].answer?[0].valueCoding?.code, "LA33-6")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].item?[3].answer?[0].valueCoding?.display, "Yes")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].item?[3].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].item?[3].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54139-1")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].item?[3].linkId, "2.1.1.4")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].item?[3].text, "Living?")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].item?[4].answer?[0].valueCoding?.code, "LA32-8")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].item?[4].answer?[0].valueCoding?.display, "No")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].item?[4].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].item?[4].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54121-9")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].item?[4].linkId, "2.1.1.5")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].item?[4].text, "Was this person born a twin?")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].item?[5].answer?[0].valueCoding?.code, "LA32-8")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].item?[5].answer?[0].valueCoding?.display, "No")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].item?[5].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].item?[5].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54122-7")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].item?[5].linkId, "2.1.1.6")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].item?[5].text, "Was this person adopted?")
		XCTAssertEqual(inst.item?[2].item?[1].item?[0].linkId, "2.1.1")
		XCTAssertEqual(inst.item?[2].item?[1].item?[1].item?[0].answer?[0].valueCoding?.code, "LA10550-4")
		XCTAssertEqual(inst.item?[2].item?[1].item?[1].item?[0].answer?[0].valueCoding?.display, "-- Other Cancer")
		XCTAssertEqual(inst.item?[2].item?[1].item?[1].item?[0].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[1].item?[1].item?[0].linkId, "2.1.2.1")
		XCTAssertEqual(inst.item?[2].item?[1].item?[1].item?[0].text, "Disease or Condition")
		XCTAssertEqual(inst.item?[2].item?[1].item?[1].item?[1].answer?[0].valueCoding?.code, "LA10397-0")
		XCTAssertEqual(inst.item?[2].item?[1].item?[1].item?[1].answer?[0].valueCoding?.display, "30-39")
		XCTAssertEqual(inst.item?[2].item?[1].item?[1].item?[1].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[1].item?[1].item?[1].linkId, "2.1.2.2")
		XCTAssertEqual(inst.item?[2].item?[1].item?[1].item?[1].text, "Age at Diagnosis")
		XCTAssertEqual(inst.item?[2].item?[1].item?[1].linkId, "2.1.2")
		XCTAssertEqual(inst.item?[2].item?[1].item?[1].text, "This family member's history of disease")
		XCTAssertEqual(inst.item?[2].item?[1].linkId, "2.1")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].item?[0].answer?[0].valueCoding?.code, "LA10418-4")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].item?[0].answer?[0].valueCoding?.display, "Sister")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].item?[0].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].item?[0].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54136-7")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].item?[0].linkId, "2.1.1.1")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].item?[0].text, "Relationship to you")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].item?[1].answer?[0].valueString, "Janet")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].item?[1].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54138-3")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].item?[1].linkId, "2.1.1.2")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].item?[1].text, "Name")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].item?[2].answer?[0].valueCoding?.code, "LA3-6")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].item?[2].answer?[0].valueCoding?.display, "Female")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].item?[2].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].item?[2].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54123-5")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].item?[2].linkId, "2.1.1.3")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].item?[2].text, "Gender")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].item?[3].answer?[0].item?[0].item?[0].answer?[0].valueDecimal, "36")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].item?[3].answer?[0].item?[0].item?[0].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54141-7")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].item?[3].answer?[0].item?[0].item?[0].linkId, "2.1.1.4.2.2")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].item?[3].answer?[0].item?[0].item?[0].text, "Age")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].item?[3].answer?[0].item?[0].linkId, "2.1.1.4.2")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].item?[3].answer?[0].valueCoding?.code, "LA33-6")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].item?[3].answer?[0].valueCoding?.display, "Yes")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].item?[3].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].item?[3].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54139-1")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].item?[3].linkId, "2.1.1.4")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].item?[3].text, "Living?")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].item?[4].answer?[0].valueCoding?.code, "LA32-8")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].item?[4].answer?[0].valueCoding?.display, "No")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].item?[4].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].item?[4].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54121-9")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].item?[4].linkId, "2.1.1.5")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].item?[4].text, "Was this person born a twin?")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].item?[5].answer?[0].valueCoding?.code, "LA32-8")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].item?[5].answer?[0].valueCoding?.display, "No")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].item?[5].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].item?[5].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54122-7")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].item?[5].linkId, "2.1.1.6")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].item?[5].text, "Was this person adopted?")
		XCTAssertEqual(inst.item?[2].item?[2].item?[0].linkId, "2.1.1")
		XCTAssertEqual(inst.item?[2].item?[2].item?[1].item?[0].answer?[0].valueCoding?.code, "LA10536-3")
		XCTAssertEqual(inst.item?[2].item?[2].item?[1].item?[0].answer?[0].valueCoding?.display, "-- Breast Cancer")
		XCTAssertEqual(inst.item?[2].item?[2].item?[1].item?[0].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[2].item?[1].item?[0].linkId, "2.1.2.1")
		XCTAssertEqual(inst.item?[2].item?[2].item?[1].item?[0].text, "Disease or Condition")
		XCTAssertEqual(inst.item?[2].item?[2].item?[1].item?[1].answer?[0].valueCoding?.code, "LA10397-0")
		XCTAssertEqual(inst.item?[2].item?[2].item?[1].item?[1].answer?[0].valueCoding?.display, "30-39")
		XCTAssertEqual(inst.item?[2].item?[2].item?[1].item?[1].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[2].item?[1].item?[1].linkId, "2.1.2.2")
		XCTAssertEqual(inst.item?[2].item?[2].item?[1].item?[1].text, "Age at Diagnosis")
		XCTAssertEqual(inst.item?[2].item?[2].item?[1].linkId, "2.1.2")
		XCTAssertEqual(inst.item?[2].item?[2].item?[1].text, "This family member's history of disease")
		XCTAssertEqual(inst.item?[2].item?[2].linkId, "2.1")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].item?[0].answer?[0].valueCoding?.code, "LA10419-2")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].item?[0].answer?[0].valueCoding?.display, "Nephew")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].item?[0].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].item?[0].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54136-7")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].item?[0].linkId, "2.1.1.1")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].item?[0].text, "Relationship to you")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].item?[1].answer?[0].valueString, "Ian")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].item?[1].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54138-3")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].item?[1].linkId, "2.1.1.2")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].item?[1].text, "Name")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].item?[2].answer?[0].valueCoding?.code, "LA2-8")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].item?[2].answer?[0].valueCoding?.display, "Male")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].item?[2].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].item?[2].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54123-5")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].item?[2].linkId, "2.1.1.3")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].item?[2].text, "Gender")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].item?[3].answer?[0].item?[0].item?[0].answer?[0].valueDecimal, "16")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].item?[3].answer?[0].item?[0].item?[0].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54141-7")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].item?[3].answer?[0].item?[0].item?[0].linkId, "2.1.1.4.2.2")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].item?[3].answer?[0].item?[0].item?[0].text, "Age")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].item?[3].answer?[0].item?[0].linkId, "2.1.1.4.2")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].item?[3].answer?[0].valueCoding?.code, "LA33-6")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].item?[3].answer?[0].valueCoding?.display, "Yes")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].item?[3].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].item?[3].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54139-1")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].item?[3].linkId, "2.1.1.4")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].item?[3].text, "Living?")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].item?[4].answer?[0].valueCoding?.code, "LA32-8")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].item?[4].answer?[0].valueCoding?.display, "No")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].item?[4].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].item?[4].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54121-9")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].item?[4].linkId, "2.1.1.5")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].item?[4].text, "Was this person born a twin?")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].item?[5].answer?[0].valueCoding?.code, "LA32-8")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].item?[5].answer?[0].valueCoding?.display, "No")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].item?[5].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].item?[5].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54122-7")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].item?[5].linkId, "2.1.1.6")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].item?[5].text, "Was this person adopted?")
		XCTAssertEqual(inst.item?[2].item?[3].item?[0].linkId, "2.1.1")
		XCTAssertEqual(inst.item?[2].item?[3].linkId, "2.1")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].item?[0].answer?[0].valueCoding?.code, "LA10420-0")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].item?[0].answer?[0].valueCoding?.display, "Niece")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].item?[0].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].item?[0].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54136-7")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].item?[0].linkId, "2.1.1.1")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].item?[0].text, "Relationship to you")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].item?[1].answer?[0].valueString, "Helen")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].item?[1].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54138-3")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].item?[1].linkId, "2.1.1.2")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].item?[1].text, "Name")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].item?[2].answer?[0].valueCoding?.code, "LA3-6")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].item?[2].answer?[0].valueCoding?.display, "Female")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].item?[2].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].item?[2].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54123-5")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].item?[2].linkId, "2.1.1.3")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].item?[2].text, "Gender")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].item?[3].answer?[0].item?[0].item?[0].answer?[0].valueDecimal, "15")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].item?[3].answer?[0].item?[0].item?[0].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54141-7")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].item?[3].answer?[0].item?[0].item?[0].linkId, "2.1.1.4.2.2")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].item?[3].answer?[0].item?[0].item?[0].text, "Age")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].item?[3].answer?[0].item?[0].linkId, "2.1.1.4.2")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].item?[3].answer?[0].valueCoding?.code, "LA33-6")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].item?[3].answer?[0].valueCoding?.display, "Yes")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].item?[3].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].item?[3].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54139-1")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].item?[3].linkId, "2.1.1.4")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].item?[3].text, "Living?")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].item?[4].answer?[0].valueCoding?.code, "LA32-8")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].item?[4].answer?[0].valueCoding?.display, "No")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].item?[4].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].item?[4].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54121-9")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].item?[4].linkId, "2.1.1.5")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].item?[4].text, "Was this person born a twin?")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].item?[5].answer?[0].valueCoding?.code, "LA32-8")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].item?[5].answer?[0].valueCoding?.display, "No")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].item?[5].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].item?[5].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54122-7")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].item?[5].linkId, "2.1.1.6")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].item?[5].text, "Was this person adopted?")
		XCTAssertEqual(inst.item?[2].item?[4].item?[0].linkId, "2.1.1")
		XCTAssertEqual(inst.item?[2].item?[4].linkId, "2.1")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].item?[0].answer?[0].valueCoding?.code, "LA10416-8")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].item?[0].answer?[0].valueCoding?.display, "Father")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].item?[0].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].item?[0].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54136-7")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].item?[0].linkId, "2.1.1.1")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].item?[0].text, "Relationship to you")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].item?[1].answer?[0].valueString, "Donald")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].item?[1].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54138-3")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].item?[1].linkId, "2.1.1.2")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].item?[1].text, "Name")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].item?[2].answer?[0].valueCoding?.code, "LA2-8")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].item?[2].answer?[0].valueCoding?.display, "Male")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].item?[2].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].item?[2].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54123-5")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].item?[2].linkId, "2.1.1.3")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].item?[2].text, "Gender")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].item?[3].answer?[0].item?[0].item?[0].answer?[0].valueDecimal, "52")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].item?[3].answer?[0].item?[0].item?[0].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54141-7")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].item?[3].answer?[0].item?[0].item?[0].linkId, "2.1.1.4.2.2")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].item?[3].answer?[0].item?[0].item?[0].text, "Age")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].item?[3].answer?[0].item?[0].linkId, "2.1.1.4.2")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].item?[3].answer?[0].valueCoding?.code, "LA33-6")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].item?[3].answer?[0].valueCoding?.display, "Yes")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].item?[3].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].item?[3].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54139-1")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].item?[3].linkId, "2.1.1.4")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].item?[3].text, "Living?")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].item?[4].answer?[0].valueCoding?.code, "LA32-8")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].item?[4].answer?[0].valueCoding?.display, "No")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].item?[4].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].item?[4].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54121-9")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].item?[4].linkId, "2.1.1.5")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].item?[4].text, "Was this person born a twin?")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].item?[5].answer?[0].valueCoding?.code, "LA32-8")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].item?[5].answer?[0].valueCoding?.display, "No")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].item?[5].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].item?[5].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54122-7")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].item?[5].linkId, "2.1.1.6")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].item?[5].text, "Was this person adopted?")
		XCTAssertEqual(inst.item?[2].item?[5].item?[0].linkId, "2.1.1")
		XCTAssertEqual(inst.item?[2].item?[5].linkId, "2.1")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].item?[0].answer?[0].valueCoding?.code, "LA10425-9")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].item?[0].answer?[0].valueCoding?.display, "Paternal Uncle")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].item?[0].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].item?[0].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54136-7")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].item?[0].linkId, "2.1.1.1")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].item?[0].text, "Relationship to you")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].item?[1].answer?[0].valueString, "Eric")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].item?[1].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54138-3")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].item?[1].linkId, "2.1.1.2")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].item?[1].text, "Name")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].item?[2].answer?[0].valueCoding?.code, "LA2-8")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].item?[2].answer?[0].valueCoding?.display, "Male")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].item?[2].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].item?[2].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54123-5")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].item?[2].linkId, "2.1.1.3")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].item?[2].text, "Gender")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].item?[3].answer?[0].item?[0].item?[0].answer?[0].valueDecimal, "56")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].item?[3].answer?[0].item?[0].item?[0].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54141-7")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].item?[3].answer?[0].item?[0].item?[0].linkId, "2.1.1.4.2.2")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].item?[3].answer?[0].item?[0].item?[0].text, "Age")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].item?[3].answer?[0].item?[0].linkId, "2.1.1.4.2")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].item?[3].answer?[0].valueCoding?.code, "LA33-6")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].item?[3].answer?[0].valueCoding?.display, "Yes")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].item?[3].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].item?[3].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54139-1")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].item?[3].linkId, "2.1.1.4")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].item?[3].text, "Living?")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].item?[4].answer?[0].valueCoding?.code, "LA32-8")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].item?[4].answer?[0].valueCoding?.display, "No")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].item?[4].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].item?[4].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54121-9")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].item?[4].linkId, "2.1.1.5")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].item?[4].text, "Was this person born a twin?")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].item?[5].answer?[0].valueCoding?.code, "LA32-8")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].item?[5].answer?[0].valueCoding?.display, "No")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].item?[5].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].item?[5].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54122-7")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].item?[5].linkId, "2.1.1.6")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].item?[5].text, "Was this person adopted?")
		XCTAssertEqual(inst.item?[2].item?[6].item?[0].linkId, "2.1.1")
		XCTAssertEqual(inst.item?[2].item?[6].linkId, "2.1")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].item?[0].answer?[0].valueCoding?.code, "LA10421-8")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].item?[0].answer?[0].valueCoding?.display, "Paternal Aunt")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].item?[0].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].item?[0].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54136-7")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].item?[0].linkId, "2.1.1.1")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].item?[0].text, "Relationship to you")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].item?[1].answer?[0].valueString, "Fiona")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].item?[1].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54138-3")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].item?[1].linkId, "2.1.1.2")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].item?[1].text, "Name")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].item?[2].answer?[0].valueCoding?.code, "LA3-6")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].item?[2].answer?[0].valueCoding?.display, "Female")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].item?[2].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].item?[2].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54123-5")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].item?[2].linkId, "2.1.1.3")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].item?[2].text, "Gender")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].item?[3].answer?[0].item?[0].item?[0].answer?[0].valueDecimal, "57")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].item?[3].answer?[0].item?[0].item?[0].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54141-7")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].item?[3].answer?[0].item?[0].item?[0].linkId, "2.1.1.4.2.2")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].item?[3].answer?[0].item?[0].item?[0].text, "Age")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].item?[3].answer?[0].item?[0].linkId, "2.1.1.4.2")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].item?[3].answer?[0].valueCoding?.code, "LA33-6")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].item?[3].answer?[0].valueCoding?.display, "Yes")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].item?[3].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].item?[3].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54139-1")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].item?[3].linkId, "2.1.1.4")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].item?[3].text, "Living?")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].item?[4].answer?[0].valueCoding?.code, "LA32-8")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].item?[4].answer?[0].valueCoding?.display, "No")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].item?[4].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].item?[4].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54121-9")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].item?[4].linkId, "2.1.1.5")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].item?[4].text, "Was this person born a twin?")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].item?[5].answer?[0].valueCoding?.code, "LA32-8")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].item?[5].answer?[0].valueCoding?.display, "No")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].item?[5].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].item?[5].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54122-7")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].item?[5].linkId, "2.1.1.6")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].item?[5].text, "Was this person adopted?")
		XCTAssertEqual(inst.item?[2].item?[7].item?[0].linkId, "2.1.1")
		XCTAssertEqual(inst.item?[2].item?[7].item?[1].item?[0].answer?[0].valueCoding?.code, "LA10543-9")
		XCTAssertEqual(inst.item?[2].item?[7].item?[1].item?[0].answer?[0].valueCoding?.display, "-- Skin Cancer")
		XCTAssertEqual(inst.item?[2].item?[7].item?[1].item?[0].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[7].item?[1].item?[0].linkId, "2.1.2.1")
		XCTAssertEqual(inst.item?[2].item?[7].item?[1].item?[0].text, "Disease or Condition")
		XCTAssertEqual(inst.item?[2].item?[7].item?[1].linkId, "2.1.2")
		XCTAssertEqual(inst.item?[2].item?[7].item?[1].text, "This family member's history of disease")
		XCTAssertEqual(inst.item?[2].item?[7].linkId, "2.1")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[0].answer?[0].valueCoding?.code, "LA10423-4")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[0].answer?[0].valueCoding?.display, "Paternal Grandfather")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[0].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[0].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54136-7")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[0].linkId, "2.1.1.1")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[0].text, "Relationship to you")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[1].answer?[0].valueString, "Bob")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[1].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54138-3")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[1].linkId, "2.1.1.2")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[1].text, "Name")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[2].answer?[0].valueCoding?.code, "LA2-8")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[2].answer?[0].valueCoding?.display, "Male")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[2].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[2].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54123-5")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[2].linkId, "2.1.1.3")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[2].text, "Gender")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[3].answer?[0].item?[0].item?[0].answer?[0].valueCoding?.code, "LA10537-1")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[3].answer?[0].item?[0].item?[0].answer?[0].valueCoding?.display, "-- Colon Cancer")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[3].answer?[0].item?[0].item?[0].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[3].answer?[0].item?[0].item?[0].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54112-8")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[3].answer?[0].item?[0].item?[0].linkId, "2.1.1.4.1.1")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[3].answer?[0].item?[0].item?[0].text, "Cause of Death")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[3].answer?[0].item?[0].item?[1].answer?[0].valueCoding?.code, "LA10400-2")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[3].answer?[0].item?[0].item?[1].answer?[0].valueCoding?.display, "OVER 60")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[3].answer?[0].item?[0].item?[1].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[3].answer?[0].item?[0].item?[1].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54113-6")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[3].answer?[0].item?[0].item?[1].linkId, "2.1.1.4.1.2")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[3].answer?[0].item?[0].item?[1].text, "Age at Death")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[3].answer?[0].item?[0].linkId, "2.1.1.4.1")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[3].answer?[0].valueCoding?.code, "LA32-8")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[3].answer?[0].valueCoding?.display, "No")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[3].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[3].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54139-1")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[3].linkId, "2.1.1.4")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[3].text, "Living?")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[4].answer?[0].valueCoding?.code, "LA32-8")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[4].answer?[0].valueCoding?.display, "No")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[4].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[4].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54121-9")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[4].linkId, "2.1.1.5")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[4].text, "Was this person born a twin?")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[5].answer?[0].valueCoding?.code, "LA32-8")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[5].answer?[0].valueCoding?.display, "No")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[5].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[5].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54122-7")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[5].linkId, "2.1.1.6")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].item?[5].text, "Was this person adopted?")
		XCTAssertEqual(inst.item?[2].item?[8].item?[0].linkId, "2.1.1")
		XCTAssertEqual(inst.item?[2].item?[8].item?[1].item?[0].answer?[0].valueCoding?.code, "LA10537-1")
		XCTAssertEqual(inst.item?[2].item?[8].item?[1].item?[0].answer?[0].valueCoding?.display, "-- Colon Cancer")
		XCTAssertEqual(inst.item?[2].item?[8].item?[1].item?[0].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[8].item?[1].item?[0].linkId, "2.1.2.1")
		XCTAssertEqual(inst.item?[2].item?[8].item?[1].item?[0].text, "Disease or Condition")
		XCTAssertEqual(inst.item?[2].item?[8].item?[1].item?[1].answer?[0].valueCoding?.code, "LA10400-2")
		XCTAssertEqual(inst.item?[2].item?[8].item?[1].item?[1].answer?[0].valueCoding?.display, "OVER 60")
		XCTAssertEqual(inst.item?[2].item?[8].item?[1].item?[1].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[8].item?[1].item?[1].linkId, "2.1.2.2")
		XCTAssertEqual(inst.item?[2].item?[8].item?[1].item?[1].text, "Age at Diagnosis")
		XCTAssertEqual(inst.item?[2].item?[8].item?[1].linkId, "2.1.2")
		XCTAssertEqual(inst.item?[2].item?[8].item?[1].text, "This family member's history of disease")
		XCTAssertEqual(inst.item?[2].item?[8].linkId, "2.1")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[0].answer?[0].valueCoding?.code, "LA10424-2")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[0].answer?[0].valueCoding?.display, "Paternal Grandmother")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[0].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[0].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54136-7")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[0].linkId, "2.1.1.1")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[0].text, "Relationship to you")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[1].answer?[0].valueString, "Claire")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[1].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54138-3")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[1].linkId, "2.1.1.2")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[1].text, "Name")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[2].answer?[0].valueCoding?.code, "LA3-6")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[2].answer?[0].valueCoding?.display, "Female")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[2].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[2].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54123-5")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[2].linkId, "2.1.1.3")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[2].text, "Gender")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[3].answer?[0].item?[0].item?[0].answer?[0].item?[0].answer?[0].valueString, "Lou Gehrigs")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[3].answer?[0].item?[0].item?[0].answer?[0].item?[0].linkId, "2.1.1.4.1.1.1")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[3].answer?[0].item?[0].item?[0].answer?[0].item?[0].text, "Please specify")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[3].answer?[0].item?[0].item?[0].answer?[0].valueCoding?.code, "LA10589-2")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[3].answer?[0].item?[0].item?[0].answer?[0].valueCoding?.display, "-- Other/Unexpected")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[3].answer?[0].item?[0].item?[0].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[3].answer?[0].item?[0].item?[0].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54112-8")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[3].answer?[0].item?[0].item?[0].linkId, "2.1.1.4.1.1")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[3].answer?[0].item?[0].item?[0].text, "Cause of Death")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[3].answer?[0].item?[0].item?[1].answer?[0].valueCoding?.code, "LA10400-2")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[3].answer?[0].item?[0].item?[1].answer?[0].valueCoding?.display, "OVER 60")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[3].answer?[0].item?[0].item?[1].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[3].answer?[0].item?[0].item?[1].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54113-6")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[3].answer?[0].item?[0].item?[1].linkId, "2.1.1.4.1.2")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[3].answer?[0].item?[0].item?[1].text, "Age at Death")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[3].answer?[0].item?[0].linkId, "2.1.1.4.1")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[3].answer?[0].valueCoding?.code, "LA32-8")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[3].answer?[0].valueCoding?.display, "No")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[3].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[3].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54139-1")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[3].linkId, "2.1.1.4")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[3].text, "Living?")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[4].answer?[0].valueCoding?.code, "LA32-8")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[4].answer?[0].valueCoding?.display, "No")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[4].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[4].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54121-9")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[4].linkId, "2.1.1.5")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[4].text, "Was this person born a twin?")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[5].answer?[0].valueCoding?.code, "LA32-8")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[5].answer?[0].valueCoding?.display, "No")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[5].answer?[0].valueCoding?.system?.absoluteString, "http://loinc.org")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[5].definition?.absoluteString, "http://loinc.org/fhir/DataElement/54122-7")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[5].linkId, "2.1.1.6")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].item?[5].text, "Was this person adopted?")
		XCTAssertEqual(inst.item?[2].item?[9].item?[0].linkId, "2.1.1")
		XCTAssertEqual(inst.item?[2].item?[9].linkId, "2.1")
		XCTAssertEqual(inst.item?[2].linkId, "2")
		XCTAssertEqual(inst.item?[2].subject?.reference, "Patient/pat1")
		XCTAssertEqual(inst.item?[2].text, "Family member health information")
		XCTAssertEqual(inst.questionnaire?.reference, "Questionnaire/ussg-fht")
		XCTAssertEqual(inst.status, QuestionnaireResponseStatus(rawValue: "in-progress")!)
		XCTAssertEqual(inst.subject?.reference, "http://hl7.org/fhir/Patient/proband")
		XCTAssertEqual(inst.text?.status, NarrativeStatus(rawValue: "generated")!)
		
		return inst
	}
	
	func testQuestionnaireResponse5() {
		do {
			let instance = try runQuestionnaireResponse5()
			try runQuestionnaireResponse5(instance.asJSON())
		}
		catch let error {
			XCTAssertTrue(false, "Must instantiate and test QuestionnaireResponse successfully, but threw:\n---\n\(error)\n---")
		}
	}
	
	@discardableResult
	func runQuestionnaireResponse5(_ json: FHIRJSON? = nil) throws -> SwiftFHIRQuestionnaireResponse {
		let inst = (nil != json) ? try instantiateFrom(json: json!) : try instantiateFrom(filename: "questionnaireresponse-example.json")
		
		XCTAssertEqual(inst.author?.reference, "#questauth")
		XCTAssertEqual(inst.authored?.description, "2013-02-19T14:15:00-05:00")
		XCTAssertEqual(inst.basedOn?[0].reference, "#order")
		XCTAssertEqual(inst.contained?[0].id, "patsub")
		XCTAssertEqual(inst.contained?[1].id, "order")
		XCTAssertEqual(inst.contained?[2].id, "questauth")
		XCTAssertEqual(inst.context?.reference, "Encounter/example")
		XCTAssertEqual(inst.id, "3141")
		XCTAssertEqual(inst.identifier?.system?.absoluteString, "http://example.org/fhir/NamingSystem/questionnaire-ids")
		XCTAssertEqual(inst.identifier?.value, "Q12349876")
		XCTAssertEqual(inst.item?[0].item?[0].answer?[0].item?[0].item?[0].answer?[0].valueCoding?.code, "1")
		XCTAssertEqual(inst.item?[0].item?[0].answer?[0].item?[0].item?[0].answer?[0].valueCoding?.system?.absoluteString, "http://cancer.questionnaire.org/system/code/yesno")
		XCTAssertEqual(inst.item?[0].item?[0].answer?[0].item?[0].item?[0].linkId, "1.1.1.1")
		XCTAssertEqual(inst.item?[0].item?[0].answer?[0].item?[0].item?[1].answer?[0].valueCoding?.code, "1")
		XCTAssertEqual(inst.item?[0].item?[0].answer?[0].item?[0].item?[1].answer?[0].valueCoding?.system?.absoluteString, "http://cancer.questionnaire.org/system/code/yesno")
		XCTAssertEqual(inst.item?[0].item?[0].answer?[0].item?[0].item?[1].linkId, "1.1.1.2")
		XCTAssertEqual(inst.item?[0].item?[0].answer?[0].item?[0].item?[2].answer?[0].valueCoding?.code, "0")
		XCTAssertEqual(inst.item?[0].item?[0].answer?[0].item?[0].item?[2].answer?[0].valueCoding?.system?.absoluteString, "http://cancer.questionnaire.org/system/code/yesno")
		XCTAssertEqual(inst.item?[0].item?[0].answer?[0].item?[0].item?[2].linkId, "1.1.1.3")
		XCTAssertEqual(inst.item?[0].item?[0].answer?[0].item?[0].linkId, "1.1.1")
		XCTAssertEqual(inst.item?[0].item?[0].answer?[0].valueCoding?.code, "1")
		XCTAssertEqual(inst.item?[0].item?[0].answer?[0].valueCoding?.display, "Yes")
		XCTAssertEqual(inst.item?[0].item?[0].answer?[0].valueCoding?.system?.absoluteString, "http://cancer.questionnaire.org/system/code/yesno")
		XCTAssertEqual(inst.item?[0].item?[0].linkId, "1.1")
		XCTAssertEqual(inst.item?[0].linkId, "1")
		XCTAssertEqual(inst.parent?[0].reference, "Procedure/f201")
		XCTAssertEqual(inst.status, QuestionnaireResponseStatus(rawValue: "completed")!)
		XCTAssertEqual(inst.subject?.reference, "#patsub")
		XCTAssertEqual(inst.text?.status, NarrativeStatus(rawValue: "generated")!)
		
		return inst
	}
}
