//
//  TestScriptTests.swift
//  SwiftFHIR
//
//  Generated from FHIR 4.0.0-a53ec6ee1b on 2019-02-26.
//  2019, SMART Health IT.
//

import XCTest
#if !NO_MODEL_IMPORT
import Models
typealias SwiftFHIRTestScript = Models.TestScript
#else
import SwiftFHIR
typealias SwiftFHIRTestScript = SwiftFHIR.TestScript
#endif


class TestScriptTests: XCTestCase {
	
	func instantiateFrom(filename: String) throws -> SwiftFHIRTestScript {
		return try instantiateFrom(json: try readJSONFile(filename))
	}
	
	func instantiateFrom(json: FHIRJSON) throws -> SwiftFHIRTestScript {
		return try SwiftFHIRTestScript(json: json)
	}
	
	func testTestScript1() {
		do {
			let instance = try runTestScript1()
			try runTestScript1(instance.asJSON())
		}
		catch let error {
			XCTAssertTrue(false, "Must instantiate and test TestScript successfully, but threw:\n---\n\(error)\n---")
		}
	}
	
	@discardableResult
	func runTestScript1(_ json: FHIRJSON? = nil) throws -> SwiftFHIRTestScript {
		let inst = (nil != json) ? try instantiateFrom(json: json!) : try instantiateFrom(filename: "testscript-example-multisystem.json")
		
		XCTAssertEqual(inst.contact?[0].name, "Support")
		XCTAssertEqual(inst.contact?[0].telecom?[0].system, ContactPointSystem(rawValue: "email")!)
		XCTAssertEqual(inst.contact?[0].telecom?[0].use, ContactPointUse(rawValue: "work")!)
		XCTAssertEqual(inst.contact?[0].telecom?[0].value, "support@HL7.org")
		XCTAssertEqual(inst.copyright, "© HL7.org 2011+")
		XCTAssertEqual(inst.date?.description, "2017-01-18")
		XCTAssertEqual(inst.destination?[0].index, 1)
		XCTAssertEqual(inst.destination?[0].profile?.code, "FHIR-Server")
		XCTAssertEqual(inst.destination?[1].index, 2)
		XCTAssertEqual(inst.destination?[1].profile?.code, "FHIR-Server")
		XCTAssertEqual(inst.experimental, true)
		XCTAssertEqual(inst.id, "testscript-example-multisystem")
		XCTAssertEqual(inst.identifier?.system?.absoluteString, "urn:ietf:rfc:3986")
		XCTAssertEqual(inst.identifier?.value, "urn:oid:1.3.6.1.4.1.21367.2005.3.7.9878")
		XCTAssertEqual(inst.jurisdiction?[0].coding?[0].code, "US")
		XCTAssertEqual(inst.jurisdiction?[0].coding?[0].display, "United States of America (the)")
		XCTAssertEqual(inst.jurisdiction?[0].coding?[0].system?.absoluteString, "urn:iso:std:iso:3166")
		XCTAssertEqual(inst.metadata?.capability?[0].capabilities?.absoluteString, "CapabilityStatement/example")
		XCTAssertEqual(inst.metadata?.capability?[0].description_fhir, "Patient Read Operation")
		XCTAssertEqual(inst.metadata?.capability?[0].destination, 1)
		XCTAssertEqual(inst.metadata?.capability?[0].link?[0].absoluteString, "http://hl7.org/fhir/http.html#read")
		XCTAssertEqual(inst.metadata?.capability?[0].origin?[0], 1)
		XCTAssertEqual(inst.metadata?.capability?[0].required, true)
		XCTAssertEqual(inst.metadata?.capability?[0].validated, false)
		XCTAssertEqual(inst.metadata?.capability?[1].capabilities?.absoluteString, "CapabilityStatement/example")
		XCTAssertEqual(inst.metadata?.capability?[1].description_fhir, "Patient Read Operation")
		XCTAssertEqual(inst.metadata?.capability?[1].destination, 2)
		XCTAssertEqual(inst.metadata?.capability?[1].link?[0].absoluteString, "http://hl7.org/fhir/http.html#read")
		XCTAssertEqual(inst.metadata?.capability?[1].origin?[0], 1)
		XCTAssertEqual(inst.metadata?.capability?[1].required, true)
		XCTAssertEqual(inst.metadata?.capability?[1].validated, false)
		XCTAssertEqual(inst.metadata?.link?[0].description_fhir, "Demographics and other administrative information about an individual or animal receiving care or other health-related services.")
		XCTAssertEqual(inst.metadata?.link?[0].url?.absoluteString, "http://hl7.org/fhir/patient.html")
		XCTAssertEqual(inst.name, "testscript-example-multisystem")
		XCTAssertEqual(inst.origin?[0].index, 1)
		XCTAssertEqual(inst.origin?[0].profile?.code, "FHIR-Client")
		XCTAssertEqual(inst.publisher, "HL7")
		XCTAssertEqual(inst.purpose, "Patient Read Operation")
		XCTAssertEqual(inst.status, PublicationStatus(rawValue: "draft")!)
		XCTAssertEqual(inst.test?[0].action?[0].operation?.accept, "xml")
		XCTAssertEqual(inst.test?[0].action?[0].operation?.contentType, "xml")
		XCTAssertEqual(inst.test?[0].action?[0].operation?.description_fhir, "Read a Patient from the first destination test system and perform basic validation.")
		XCTAssertEqual(inst.test?[0].action?[0].operation?.destination, 1)
		XCTAssertEqual(inst.test?[0].action?[0].operation?.encodeRequestUrl, true)
		XCTAssertEqual(inst.test?[0].action?[0].operation?.origin, 1)
		XCTAssertEqual(inst.test?[0].action?[0].operation?.params, "/${Dest1PatientResourceId}")
		XCTAssertEqual(inst.test?[0].action?[0].operation?.requestId, "request-read-patient-01")
		XCTAssertEqual(inst.test?[0].action?[0].operation?.resource, "Patient")
		XCTAssertEqual(inst.test?[0].action?[0].operation?.type?.code, "read")
		XCTAssertEqual(inst.test?[0].action?[0].operation?.type?.system?.absoluteString, "http://terminology.hl7.org/CodeSystem/testscript-operation-codes")
		XCTAssertEqual(inst.test?[0].action?[1].assert?.description_fhir, "Confirm that the request method GET was sent by the client system under test.")
		XCTAssertEqual(inst.test?[0].action?[1].assert?.requestMethod, TestScriptRequestMethodCode(rawValue: "get")!)
		XCTAssertEqual(inst.test?[0].action?[1].assert?.warningOnly, false)
		XCTAssertEqual(inst.test?[0].action?[2].assert?.description_fhir, "Confirm that the client requested an Accept of xml.")
		XCTAssertEqual(inst.test?[0].action?[2].assert?.direction, AssertionDirectionType(rawValue: "request")!)
		XCTAssertEqual(inst.test?[0].action?[2].assert?.headerField, "Accept")
		XCTAssertEqual(inst.test?[0].action?[2].assert?.operator_fhir, AssertionOperatorType(rawValue: "contains")!)
		XCTAssertEqual(inst.test?[0].action?[2].assert?.value, "xml")
		XCTAssertEqual(inst.test?[0].action?[2].assert?.warningOnly, false)
		XCTAssertEqual(inst.test?[0].action?[3].assert?.description_fhir, "Confirm that the returned HTTP status is 200(OK).")
		XCTAssertEqual(inst.test?[0].action?[3].assert?.direction, AssertionDirectionType(rawValue: "response")!)
		XCTAssertEqual(inst.test?[0].action?[3].assert?.response, AssertionResponseTypes(rawValue: "okay")!)
		XCTAssertEqual(inst.test?[0].action?[3].assert?.warningOnly, false)
		XCTAssertEqual(inst.test?[0].action?[4].assert?.contentType, "xml")
		XCTAssertEqual(inst.test?[0].action?[4].assert?.description_fhir, "Confirm that the returned format is XML.")
		XCTAssertEqual(inst.test?[0].action?[4].assert?.direction, AssertionDirectionType(rawValue: "response")!)
		XCTAssertEqual(inst.test?[0].action?[4].assert?.warningOnly, false)
		XCTAssertEqual(inst.test?[0].action?[5].assert?.description_fhir, "Confirm that the returned resource type is Patient.")
		XCTAssertEqual(inst.test?[0].action?[5].assert?.direction, AssertionDirectionType(rawValue: "response")!)
		XCTAssertEqual(inst.test?[0].action?[5].assert?.resource, "Patient")
		XCTAssertEqual(inst.test?[0].action?[5].assert?.warningOnly, false)
		XCTAssertEqual(inst.test?[0].description_fhir, "Read a Patient from the first destination test system using the user defined dynamic variable ${Dest1PatientResourceId}. Perform basic validation.")
		XCTAssertEqual(inst.test?[0].id, "01-ReadPatient-Destination1")
		XCTAssertEqual(inst.test?[0].name, "ReadPatient-Destination1")
		XCTAssertEqual(inst.test?[1].action?[0].operation?.accept, "xml")
		XCTAssertEqual(inst.test?[1].action?[0].operation?.contentType, "xml")
		XCTAssertEqual(inst.test?[1].action?[0].operation?.description_fhir, "Read a Patient from the second destination test system and perform basic validation.")
		XCTAssertEqual(inst.test?[1].action?[0].operation?.destination, 2)
		XCTAssertEqual(inst.test?[1].action?[0].operation?.encodeRequestUrl, true)
		XCTAssertEqual(inst.test?[1].action?[0].operation?.origin, 1)
		XCTAssertEqual(inst.test?[1].action?[0].operation?.params, "/${Dest2PatientResourceId}")
		XCTAssertEqual(inst.test?[1].action?[0].operation?.requestHeader?[0].field, "Accept-Charset")
		XCTAssertEqual(inst.test?[1].action?[0].operation?.requestHeader?[0].value, "utf-8")
		XCTAssertEqual(inst.test?[1].action?[0].operation?.resource, "Patient")
		XCTAssertEqual(inst.test?[1].action?[0].operation?.type?.code, "read")
		XCTAssertEqual(inst.test?[1].action?[0].operation?.type?.system?.absoluteString, "http://terminology.hl7.org/CodeSystem/testscript-operation-codes")
		XCTAssertEqual(inst.test?[1].action?[1].assert?.description_fhir, "Confirm that the client requested an Accept of xml.")
		XCTAssertEqual(inst.test?[1].action?[1].assert?.direction, AssertionDirectionType(rawValue: "request")!)
		XCTAssertEqual(inst.test?[1].action?[1].assert?.headerField, "Accept")
		XCTAssertEqual(inst.test?[1].action?[1].assert?.operator_fhir, AssertionOperatorType(rawValue: "contains")!)
		XCTAssertEqual(inst.test?[1].action?[1].assert?.value, "xml")
		XCTAssertEqual(inst.test?[1].action?[1].assert?.warningOnly, false)
		XCTAssertEqual(inst.test?[1].action?[2].assert?.description_fhir, "Confirm that the returned HTTP status is 200(OK).")
		XCTAssertEqual(inst.test?[1].action?[2].assert?.direction, AssertionDirectionType(rawValue: "response")!)
		XCTAssertEqual(inst.test?[1].action?[2].assert?.response, AssertionResponseTypes(rawValue: "okay")!)
		XCTAssertEqual(inst.test?[1].action?[2].assert?.warningOnly, false)
		XCTAssertEqual(inst.test?[1].action?[3].assert?.contentType, "xml")
		XCTAssertEqual(inst.test?[1].action?[3].assert?.description_fhir, "Confirm that the returned format is XML.")
		XCTAssertEqual(inst.test?[1].action?[3].assert?.direction, AssertionDirectionType(rawValue: "response")!)
		XCTAssertEqual(inst.test?[1].action?[3].assert?.warningOnly, false)
		XCTAssertEqual(inst.test?[1].action?[4].assert?.description_fhir, "Confirm that the returned resource type is Patient.")
		XCTAssertEqual(inst.test?[1].action?[4].assert?.direction, AssertionDirectionType(rawValue: "response")!)
		XCTAssertEqual(inst.test?[1].action?[4].assert?.resource, "Patient")
		XCTAssertEqual(inst.test?[1].action?[4].assert?.warningOnly, false)
		XCTAssertEqual(inst.test?[1].description_fhir, "Read a Patient from the second destination test system using the user defined dynamic variable ${Dest2PatientResourceId}. Perform basic validation.")
		XCTAssertEqual(inst.test?[1].id, "02-ReadPatient-Destination2")
		XCTAssertEqual(inst.test?[1].name, "ReadPatient-Destination2")
		XCTAssertEqual(inst.text?.status, NarrativeStatus(rawValue: "generated")!)
		XCTAssertEqual(inst.title, "Multisystem Test Script")
		XCTAssertEqual(inst.url?.absoluteString, "http://hl7.org/fhir/TestScript/testscript-example-multisystem")
		XCTAssertEqual(inst.variable?[0].defaultValue, "example")
		XCTAssertEqual(inst.variable?[0].name, "Dest1PatientResourceId")
		XCTAssertEqual(inst.variable?[1].defaultValue, "example")
		XCTAssertEqual(inst.variable?[1].name, "Dest2PatientResourceId")
		XCTAssertEqual(inst.version, "1.0")
		
		return inst
	}
	
	func testTestScript2() {
		do {
			let instance = try runTestScript2()
			try runTestScript2(instance.asJSON())
		}
		catch let error {
			XCTAssertTrue(false, "Must instantiate and test TestScript successfully, but threw:\n---\n\(error)\n---")
		}
	}
	
	@discardableResult
	func runTestScript2(_ json: FHIRJSON? = nil) throws -> SwiftFHIRTestScript {
		let inst = (nil != json) ? try instantiateFrom(json: json!) : try instantiateFrom(filename: "testscript-example-history.json")
		
		XCTAssertEqual(inst.contact?[0].name, "Support")
		XCTAssertEqual(inst.contact?[0].telecom?[0].system, ContactPointSystem(rawValue: "email")!)
		XCTAssertEqual(inst.contact?[0].telecom?[0].use, ContactPointUse(rawValue: "work")!)
		XCTAssertEqual(inst.contact?[0].telecom?[0].value, "support@HL7.org")
		XCTAssertEqual(inst.copyright, "© HL7.org 2011+")
		XCTAssertEqual(inst.date?.description, "2017-01-18")
		XCTAssertEqual(inst.experimental, true)
		XCTAssertEqual(inst.fixture?[0].autocreate, false)
		XCTAssertEqual(inst.fixture?[0].autodelete, false)
		XCTAssertEqual(inst.fixture?[0].id, "fixture-patient-create")
		XCTAssertEqual(inst.fixture?[0].resource?.display, "Peter Chalmers")
		XCTAssertEqual(inst.fixture?[0].resource?.reference, "Patient/example")
		XCTAssertEqual(inst.fixture?[1].autocreate, false)
		XCTAssertEqual(inst.fixture?[1].autodelete, false)
		XCTAssertEqual(inst.fixture?[1].id, "fixture-patient-update")
		XCTAssertEqual(inst.fixture?[1].resource?.display, "Donald Duck")
		XCTAssertEqual(inst.fixture?[1].resource?.reference, "Patient/pat1")
		XCTAssertEqual(inst.id, "testscript-example-history")
		XCTAssertEqual(inst.identifier?.system?.absoluteString, "urn:ietf:rfc:3986")
		XCTAssertEqual(inst.identifier?.value, "urn:oid:1.3.6.1.4.1.21367.2005.3.7.9877")
		XCTAssertEqual(inst.jurisdiction?[0].coding?[0].code, "US")
		XCTAssertEqual(inst.jurisdiction?[0].coding?[0].display, "United States of America (the)")
		XCTAssertEqual(inst.jurisdiction?[0].coding?[0].system?.absoluteString, "urn:iso:std:iso:3166")
		XCTAssertEqual(inst.metadata?.capability?[0].capabilities?.absoluteString, "CapabilityStatement/example")
		XCTAssertEqual(inst.metadata?.capability?[0].description_fhir, "Patient Update, Delete and History (Instance) Operations")
		XCTAssertEqual(inst.metadata?.capability?[0].link?[0].absoluteString, "http://hl7.org/fhir/http.html#update")
		XCTAssertEqual(inst.metadata?.capability?[0].link?[1].absoluteString, "http://hl7.org/fhir/http.html#delete")
		XCTAssertEqual(inst.metadata?.capability?[0].link?[2].absoluteString, "http://hl7.org/fhir/http.html#history")
		XCTAssertEqual(inst.metadata?.capability?[0].required, true)
		XCTAssertEqual(inst.metadata?.capability?[0].validated, false)
		XCTAssertEqual(inst.metadata?.link?[0].description_fhir, "Demographics and other administrative information about an individual or animal receiving care or other health-related services.")
		XCTAssertEqual(inst.metadata?.link?[0].url?.absoluteString, "http://hl7.org/fhir/patient.html")
		XCTAssertEqual(inst.name, "TestScript Example History")
		XCTAssertEqual(inst.profile?[0].id, "bundle-profile")
		XCTAssertEqual(inst.profile?[0].reference, "http://hl7.org/fhir/StructureDefinition/Bundle")
		XCTAssertEqual(inst.publisher, "HL7")
		XCTAssertEqual(inst.purpose, "Patient (Conditional) Create, Update, Delete and History (Instance) Operations")
		XCTAssertEqual(inst.setup?.action?[0].operation?.accept, "json")
		XCTAssertEqual(inst.setup?.action?[0].operation?.description_fhir, "Execute a delete operation to insure the patient does not exist on the server.")
		XCTAssertEqual(inst.setup?.action?[0].operation?.encodeRequestUrl, true)
		XCTAssertEqual(inst.setup?.action?[0].operation?.label, "SetupDeletePatient")
		XCTAssertEqual(inst.setup?.action?[0].operation?.params, "/${createResourceId}")
		XCTAssertEqual(inst.setup?.action?[0].operation?.resource, "Patient")
		XCTAssertEqual(inst.setup?.action?[0].operation?.type?.code, "delete")
		XCTAssertEqual(inst.setup?.action?[0].operation?.type?.system?.absoluteString, "http://terminology.hl7.org/CodeSystem/testscript-operation-codes")
		XCTAssertEqual(inst.setup?.action?[1].assert?.description_fhir, "Confirm that the returned HTTP status is 200(OK) or 204(No Content).")
		XCTAssertEqual(inst.setup?.action?[1].assert?.direction, AssertionDirectionType(rawValue: "response")!)
		XCTAssertEqual(inst.setup?.action?[1].assert?.operator_fhir, AssertionOperatorType(rawValue: "in")!)
		XCTAssertEqual(inst.setup?.action?[1].assert?.responseCode, "200,204")
		XCTAssertEqual(inst.setup?.action?[1].assert?.warningOnly, false)
		XCTAssertEqual(inst.setup?.action?[2].operation?.accept, "json")
		XCTAssertEqual(inst.setup?.action?[2].operation?.contentType, "json")
		XCTAssertEqual(inst.setup?.action?[2].operation?.description_fhir, "Create patient resource on test server using the contents of fixture-patient-create")
		XCTAssertEqual(inst.setup?.action?[2].operation?.encodeRequestUrl, true)
		XCTAssertEqual(inst.setup?.action?[2].operation?.label, "SetupCreatePatient")
		XCTAssertEqual(inst.setup?.action?[2].operation?.params, "/${createResourceId}")
		XCTAssertEqual(inst.setup?.action?[2].operation?.resource, "Patient")
		XCTAssertEqual(inst.setup?.action?[2].operation?.sourceId, "fixture-patient-create")
		XCTAssertEqual(inst.setup?.action?[2].operation?.type?.code, "update")
		XCTAssertEqual(inst.setup?.action?[2].operation?.type?.system?.absoluteString, "http://terminology.hl7.org/CodeSystem/testscript-operation-codes")
		XCTAssertEqual(inst.setup?.action?[3].assert?.description_fhir, "Confirm that the returned HTTP status is 201(Created).")
		XCTAssertEqual(inst.setup?.action?[3].assert?.direction, AssertionDirectionType(rawValue: "response")!)
		XCTAssertEqual(inst.setup?.action?[3].assert?.responseCode, "201")
		XCTAssertEqual(inst.setup?.action?[3].assert?.warningOnly, false)
		XCTAssertEqual(inst.setup?.action?[4].operation?.accept, "json")
		XCTAssertEqual(inst.setup?.action?[4].operation?.contentType, "json")
		XCTAssertEqual(inst.setup?.action?[4].operation?.description_fhir, "Update patient resource on test server using the contents of fixture-patient-update")
		XCTAssertEqual(inst.setup?.action?[4].operation?.encodeRequestUrl, true)
		XCTAssertEqual(inst.setup?.action?[4].operation?.label, "SetupUpdatePatient")
		XCTAssertEqual(inst.setup?.action?[4].operation?.params, "/${createResourceId}")
		XCTAssertEqual(inst.setup?.action?[4].operation?.resource, "Patient")
		XCTAssertEqual(inst.setup?.action?[4].operation?.sourceId, "fixture-patient-update")
		XCTAssertEqual(inst.setup?.action?[4].operation?.type?.code, "update")
		XCTAssertEqual(inst.setup?.action?[4].operation?.type?.system?.absoluteString, "http://terminology.hl7.org/CodeSystem/testscript-operation-codes")
		XCTAssertEqual(inst.setup?.action?[5].assert?.description_fhir, "Confirm that the returned HTTP status is 200(OK).")
		XCTAssertEqual(inst.setup?.action?[5].assert?.direction, AssertionDirectionType(rawValue: "response")!)
		XCTAssertEqual(inst.setup?.action?[5].assert?.responseCode, "200")
		XCTAssertEqual(inst.setup?.action?[5].assert?.warningOnly, false)
		XCTAssertEqual(inst.status, PublicationStatus(rawValue: "draft")!)
		XCTAssertEqual(inst.test?[0].action?[0].operation?.accept, "json")
		XCTAssertEqual(inst.test?[0].action?[0].operation?.contentType, "json")
		XCTAssertEqual(inst.test?[0].action?[0].operation?.description_fhir, "Get the Patient history on the test server using the id from fixture-patient-create.")
		XCTAssertEqual(inst.test?[0].action?[0].operation?.encodeRequestUrl, true)
		XCTAssertEqual(inst.test?[0].action?[0].operation?.resource, "Patient")
		XCTAssertEqual(inst.test?[0].action?[0].operation?.targetId, "fixture-patient-create")
		XCTAssertEqual(inst.test?[0].action?[0].operation?.type?.code, "history")
		XCTAssertEqual(inst.test?[0].action?[0].operation?.type?.system?.absoluteString, "http://terminology.hl7.org/CodeSystem/testscript-operation-codes")
		XCTAssertEqual(inst.test?[0].action?[1].assert?.description_fhir, "Confirm that the returned HTTP status is 200(OK).")
		XCTAssertEqual(inst.test?[0].action?[1].assert?.direction, AssertionDirectionType(rawValue: "response")!)
		XCTAssertEqual(inst.test?[0].action?[1].assert?.response, AssertionResponseTypes(rawValue: "okay")!)
		XCTAssertEqual(inst.test?[0].action?[1].assert?.warningOnly, false)
		XCTAssertEqual(inst.test?[0].action?[2].assert?.description_fhir, "Confirm that the returned resource type is Bundle.")
		XCTAssertEqual(inst.test?[0].action?[2].assert?.resource, "Bundle")
		XCTAssertEqual(inst.test?[0].action?[2].assert?.warningOnly, false)
		XCTAssertEqual(inst.test?[0].action?[3].assert?.description_fhir, "Confirm that the returned Bundle conforms to the base FHIR specification.")
		XCTAssertEqual(inst.test?[0].action?[3].assert?.validateProfileId, "bundle-profile")
		XCTAssertEqual(inst.test?[0].action?[3].assert?.warningOnly, false)
		XCTAssertEqual(inst.test?[0].action?[4].assert?.description_fhir, "Confirm that the returned Bundle type equals 'history'.")
		XCTAssertEqual(inst.test?[0].action?[4].assert?.operator_fhir, AssertionOperatorType(rawValue: "equals")!)
		XCTAssertEqual(inst.test?[0].action?[4].assert?.path, "fhir:Bundle/fhir:type/@value")
		XCTAssertEqual(inst.test?[0].action?[4].assert?.value, "history")
		XCTAssertEqual(inst.test?[0].action?[4].assert?.warningOnly, false)
		XCTAssertEqual(inst.test?[0].description_fhir, "Get the history for a known Patient and validate response.")
		XCTAssertEqual(inst.test?[0].id, "01-HistoryPatient")
		XCTAssertEqual(inst.test?[0].name, "History Patient")
		XCTAssertEqual(inst.text?.status, NarrativeStatus(rawValue: "generated")!)
		XCTAssertEqual(inst.url?.absoluteString, "http://hl7.org/fhir/TestScript/testscript-example-history")
		XCTAssertEqual(inst.variable?[0].name, "createResourceId")
		XCTAssertEqual(inst.variable?[0].path, "Patient/id")
		XCTAssertEqual(inst.variable?[0].sourceId, "fixture-patient-create")
		XCTAssertEqual(inst.version, "1.0")
		
		return inst
	}
	
	func testTestScript3() {
		do {
			let instance = try runTestScript3()
			try runTestScript3(instance.asJSON())
		}
		catch let error {
			XCTAssertTrue(false, "Must instantiate and test TestScript successfully, but threw:\n---\n\(error)\n---")
		}
	}
	
	@discardableResult
	func runTestScript3(_ json: FHIRJSON? = nil) throws -> SwiftFHIRTestScript {
		let inst = (nil != json) ? try instantiateFrom(json: json!) : try instantiateFrom(filename: "testscript-example-update.json")
		
		XCTAssertEqual(inst.contact?[0].name, "Support")
		XCTAssertEqual(inst.contact?[0].telecom?[0].system, ContactPointSystem(rawValue: "email")!)
		XCTAssertEqual(inst.contact?[0].telecom?[0].use, ContactPointUse(rawValue: "work")!)
		XCTAssertEqual(inst.contact?[0].telecom?[0].value, "support@HL7.org")
		XCTAssertEqual(inst.copyright, "© HL7.org 2011+")
		XCTAssertEqual(inst.date?.description, "2017-01-18")
		XCTAssertEqual(inst.description_fhir, "TestScript example resource with setup to delete if present and create a new instance of a Patient; and single test definition to update that Patient with various asserts.")
		XCTAssertEqual(inst.experimental, true)
		XCTAssertEqual(inst.fixture?[0].autocreate, false)
		XCTAssertEqual(inst.fixture?[0].autodelete, false)
		XCTAssertEqual(inst.fixture?[0].id, "fixture-patient-create")
		XCTAssertEqual(inst.fixture?[0].resource?.display, "Peter Chalmers")
		XCTAssertEqual(inst.fixture?[0].resource?.reference, "Patient/example")
		XCTAssertEqual(inst.fixture?[1].autocreate, false)
		XCTAssertEqual(inst.fixture?[1].autodelete, false)
		XCTAssertEqual(inst.fixture?[1].id, "fixture-patient-update")
		XCTAssertEqual(inst.fixture?[1].resource?.display, "Donald Duck")
		XCTAssertEqual(inst.fixture?[1].resource?.reference, "Patient/pat1")
		XCTAssertEqual(inst.id, "testscript-example-update")
		XCTAssertEqual(inst.identifier?.system?.absoluteString, "urn:ietf:rfc:3986")
		XCTAssertEqual(inst.identifier?.value, "urn:oid:1.3.6.1.4.1.21367.2005.3.7.9882")
		XCTAssertEqual(inst.jurisdiction?[0].coding?[0].code, "US")
		XCTAssertEqual(inst.jurisdiction?[0].coding?[0].display, "United States of America (the)")
		XCTAssertEqual(inst.jurisdiction?[0].coding?[0].system?.absoluteString, "urn:iso:std:iso:3166")
		XCTAssertEqual(inst.metadata?.capability?[0].capabilities?.absoluteString, "CapabilityStatement/example")
		XCTAssertEqual(inst.metadata?.capability?[0].description_fhir, "Patient Update and Delete Operations")
		XCTAssertEqual(inst.metadata?.capability?[0].link?[0].absoluteString, "http://hl7.org/fhir/http.html#update")
		XCTAssertEqual(inst.metadata?.capability?[0].link?[1].absoluteString, "http://hl7.org/fhir/http.html#delete")
		XCTAssertEqual(inst.metadata?.capability?[0].required, true)
		XCTAssertEqual(inst.metadata?.capability?[0].validated, false)
		XCTAssertEqual(inst.metadata?.link?[0].description_fhir, "Demographics and other administrative information about an individual or animal receiving care or other health-related services.")
		XCTAssertEqual(inst.metadata?.link?[0].url?.absoluteString, "http://hl7.org/fhir/patient.html")
		XCTAssertEqual(inst.name, "TestScript Example Update")
		XCTAssertEqual(inst.profile?[0].id, "patient-profile")
		XCTAssertEqual(inst.profile?[0].reference, "http://hl7.org/fhir/StructureDefinition/Patient")
		XCTAssertEqual(inst.publisher, "HL7")
		XCTAssertEqual(inst.purpose, "Patient (Conditional) Create, Update, Delete Operations")
		XCTAssertEqual(inst.setup?.action?[0].operation?.accept, "xml")
		XCTAssertEqual(inst.setup?.action?[0].operation?.description_fhir, "Execute a delete operation to insure the patient does not exist on the server.")
		XCTAssertEqual(inst.setup?.action?[0].operation?.encodeRequestUrl, true)
		XCTAssertEqual(inst.setup?.action?[0].operation?.label, "SetupDeletePatient")
		XCTAssertEqual(inst.setup?.action?[0].operation?.params, "/${createResourceId}")
		XCTAssertEqual(inst.setup?.action?[0].operation?.resource, "Patient")
		XCTAssertEqual(inst.setup?.action?[0].operation?.type?.code, "delete")
		XCTAssertEqual(inst.setup?.action?[0].operation?.type?.system?.absoluteString, "http://terminology.hl7.org/CodeSystem/testscript-operation-codes")
		XCTAssertEqual(inst.setup?.action?[1].assert?.description_fhir, "Confirm that the returned HTTP status is 200(OK) or 204(No Content).")
		XCTAssertEqual(inst.setup?.action?[1].assert?.direction, AssertionDirectionType(rawValue: "response")!)
		XCTAssertEqual(inst.setup?.action?[1].assert?.operator_fhir, AssertionOperatorType(rawValue: "in")!)
		XCTAssertEqual(inst.setup?.action?[1].assert?.responseCode, "200,204")
		XCTAssertEqual(inst.setup?.action?[1].assert?.warningOnly, false)
		XCTAssertEqual(inst.setup?.action?[2].operation?.accept, "xml")
		XCTAssertEqual(inst.setup?.action?[2].operation?.contentType, "xml")
		XCTAssertEqual(inst.setup?.action?[2].operation?.description_fhir, "Create patient resource on test server using the contents of fixture-patient-create")
		XCTAssertEqual(inst.setup?.action?[2].operation?.encodeRequestUrl, true)
		XCTAssertEqual(inst.setup?.action?[2].operation?.label, "SetupCreatePatient")
		XCTAssertEqual(inst.setup?.action?[2].operation?.params, "/${createResourceId}")
		XCTAssertEqual(inst.setup?.action?[2].operation?.resource, "Patient")
		XCTAssertEqual(inst.setup?.action?[2].operation?.sourceId, "fixture-patient-create")
		XCTAssertEqual(inst.setup?.action?[2].operation?.type?.code, "update")
		XCTAssertEqual(inst.setup?.action?[2].operation?.type?.system?.absoluteString, "http://terminology.hl7.org/CodeSystem/testscript-operation-codes")
		XCTAssertEqual(inst.setup?.action?[3].assert?.description_fhir, "Confirm that the returned HTTP status is 201(Created).")
		XCTAssertEqual(inst.setup?.action?[3].assert?.direction, AssertionDirectionType(rawValue: "response")!)
		XCTAssertEqual(inst.setup?.action?[3].assert?.responseCode, "201")
		XCTAssertEqual(inst.setup?.action?[3].assert?.warningOnly, false)
		XCTAssertEqual(inst.status, PublicationStatus(rawValue: "draft")!)
		XCTAssertEqual(inst.test?[0].action?[0].operation?.accept, "xml")
		XCTAssertEqual(inst.test?[0].action?[0].operation?.contentType, "xml")
		XCTAssertEqual(inst.test?[0].action?[0].operation?.description_fhir, "Update patient resource on test server using the contents of fixture-patient-update")
		XCTAssertEqual(inst.test?[0].action?[0].operation?.encodeRequestUrl, true)
		XCTAssertEqual(inst.test?[0].action?[0].operation?.label, "SetupUpdatePatient")
		XCTAssertEqual(inst.test?[0].action?[0].operation?.params, "/${createResourceId}")
		XCTAssertEqual(inst.test?[0].action?[0].operation?.resource, "Patient")
		XCTAssertEqual(inst.test?[0].action?[0].operation?.sourceId, "fixture-patient-update")
		XCTAssertEqual(inst.test?[0].action?[0].operation?.type?.code, "update")
		XCTAssertEqual(inst.test?[0].action?[0].operation?.type?.system?.absoluteString, "http://terminology.hl7.org/CodeSystem/testscript-operation-codes")
		XCTAssertEqual(inst.test?[0].action?[1].assert?.description_fhir, "Confirm that the returned HTTP status is 200(OK).")
		XCTAssertEqual(inst.test?[0].action?[1].assert?.response, AssertionResponseTypes(rawValue: "okay")!)
		XCTAssertEqual(inst.test?[0].action?[1].assert?.warningOnly, false)
		XCTAssertEqual(inst.test?[0].action?[2].assert?.contentType, "xml")
		XCTAssertEqual(inst.test?[0].action?[2].assert?.description_fhir, "Confirm that the returned format is XML.")
		XCTAssertEqual(inst.test?[0].action?[2].assert?.warningOnly, false)
		XCTAssertEqual(inst.test?[0].action?[3].assert?.description_fhir, "Confirm that the returned HTTP Header Last-Modified is present. Warning only as the server might not support versioning.")
		XCTAssertEqual(inst.test?[0].action?[3].assert?.headerField, "Last-Modified")
		XCTAssertEqual(inst.test?[0].action?[3].assert?.operator_fhir, AssertionOperatorType(rawValue: "notEmpty")!)
		XCTAssertEqual(inst.test?[0].action?[3].assert?.warningOnly, true)
		XCTAssertEqual(inst.test?[0].description_fhir, "Update a Patient and validate response.")
		XCTAssertEqual(inst.test?[0].id, "01-UpdatePatient")
		XCTAssertEqual(inst.test?[0].name, "Update Patient")
		XCTAssertEqual(inst.text?.status, NarrativeStatus(rawValue: "generated")!)
		XCTAssertEqual(inst.url?.absoluteString, "http://hl7.org/fhir/TestScript/testscript-example-update")
		XCTAssertEqual(inst.variable?[0].name, "createResourceId")
		XCTAssertEqual(inst.variable?[0].path, "Patient/id")
		XCTAssertEqual(inst.variable?[0].sourceId, "fixture-patient-create")
		XCTAssertEqual(inst.version, "1.0")
		
		return inst
	}
	
	func testTestScript4() {
		do {
			let instance = try runTestScript4()
			try runTestScript4(instance.asJSON())
		}
		catch let error {
			XCTAssertTrue(false, "Must instantiate and test TestScript successfully, but threw:\n---\n\(error)\n---")
		}
	}
	
	@discardableResult
	func runTestScript4(_ json: FHIRJSON? = nil) throws -> SwiftFHIRTestScript {
		let inst = (nil != json) ? try instantiateFrom(json: json!) : try instantiateFrom(filename: "testscript-example-search.json")
		
		XCTAssertEqual(inst.contact?[0].name, "Support")
		XCTAssertEqual(inst.contact?[0].telecom?[0].system, ContactPointSystem(rawValue: "email")!)
		XCTAssertEqual(inst.contact?[0].telecom?[0].use, ContactPointUse(rawValue: "work")!)
		XCTAssertEqual(inst.contact?[0].telecom?[0].value, "support@HL7.org")
		XCTAssertEqual(inst.copyright, "© HL7.org 2011+")
		XCTAssertEqual(inst.date?.description, "2017-01-18")
		XCTAssertEqual(inst.description_fhir, "TestScript example resource with simple Patient search test. The read tests will utilize user defined dynamic variables that will hold the Patient search parameter values.")
		XCTAssertEqual(inst.experimental, true)
		XCTAssertEqual(inst.fixture?[0].autocreate, false)
		XCTAssertEqual(inst.fixture?[0].autodelete, false)
		XCTAssertEqual(inst.fixture?[0].id, "fixture-patient-create")
		XCTAssertEqual(inst.fixture?[0].resource?.display, "Peter Chalmers")
		XCTAssertEqual(inst.fixture?[0].resource?.reference, "Patient/example")
		XCTAssertEqual(inst.id, "testscript-example-search")
		XCTAssertEqual(inst.identifier?.system?.absoluteString, "urn:ietf:rfc:3986")
		XCTAssertEqual(inst.identifier?.value, "urn:oid:1.3.6.1.4.1.21367.2005.3.7.9881")
		XCTAssertEqual(inst.jurisdiction?[0].coding?[0].code, "US")
		XCTAssertEqual(inst.jurisdiction?[0].coding?[0].display, "United States of America (the)")
		XCTAssertEqual(inst.jurisdiction?[0].coding?[0].system?.absoluteString, "urn:iso:std:iso:3166")
		XCTAssertEqual(inst.metadata?.capability?[0].capabilities?.absoluteString, "CapabilityStatement/example")
		XCTAssertEqual(inst.metadata?.capability?[0].description_fhir, "Patient Search Operation")
		XCTAssertEqual(inst.metadata?.capability?[0].link?[0].absoluteString, "http://hl7.org/fhir/http.html#search")
		XCTAssertEqual(inst.metadata?.capability?[0].required, true)
		XCTAssertEqual(inst.metadata?.capability?[0].validated, false)
		XCTAssertEqual(inst.metadata?.link?[0].description_fhir, "Demographics and other administrative information about an individual or animal receiving care or other health-related services.")
		XCTAssertEqual(inst.metadata?.link?[0].url?.absoluteString, "http://hl7.org/fhir/patient.html")
		XCTAssertEqual(inst.name, "TestScript Example Search")
		XCTAssertEqual(inst.profile?[0].id, "bundle-profile")
		XCTAssertEqual(inst.profile?[0].reference, "http://hl7.org/fhir/StructureDefinition/Bundle")
		XCTAssertEqual(inst.publisher, "HL7")
		XCTAssertEqual(inst.purpose, "Patient Search Operation")
		XCTAssertEqual(inst.setup?.action?[0].operation?.accept, "xml")
		XCTAssertEqual(inst.setup?.action?[0].operation?.description_fhir, "Test simple search to verify server support.")
		XCTAssertEqual(inst.setup?.action?[0].operation?.encodeRequestUrl, true)
		XCTAssertEqual(inst.setup?.action?[0].operation?.params, "?family=DONTEXPECTAMATCH&given=DONTEXPECTAMATCH")
		XCTAssertEqual(inst.setup?.action?[0].operation?.resource, "Patient")
		XCTAssertEqual(inst.setup?.action?[0].operation?.type?.code, "search")
		XCTAssertEqual(inst.setup?.action?[0].operation?.type?.system?.absoluteString, "http://terminology.hl7.org/CodeSystem/testscript-operation-codes")
		XCTAssertEqual(inst.setup?.action?[1].assert?.description_fhir, "Confirm that the request url contains the family search parameter.")
		XCTAssertEqual(inst.setup?.action?[1].assert?.direction, AssertionDirectionType(rawValue: "request")!)
		XCTAssertEqual(inst.setup?.action?[1].assert?.operator_fhir, AssertionOperatorType(rawValue: "contains")!)
		XCTAssertEqual(inst.setup?.action?[1].assert?.requestURL, "family")
		XCTAssertEqual(inst.setup?.action?[1].assert?.warningOnly, false)
		XCTAssertEqual(inst.setup?.action?[2].assert?.description_fhir, "Confirm that the returned HTTP status is 200(OK).")
		XCTAssertEqual(inst.setup?.action?[2].assert?.direction, AssertionDirectionType(rawValue: "response")!)
		XCTAssertEqual(inst.setup?.action?[2].assert?.responseCode, "200")
		XCTAssertEqual(inst.setup?.action?[2].assert?.warningOnly, false)
		XCTAssertEqual(inst.setup?.action?[3].assert?.description_fhir, "Confirm that the returned resource type is Bundle.")
		XCTAssertEqual(inst.setup?.action?[3].assert?.resource, "Bundle")
		XCTAssertEqual(inst.setup?.action?[3].assert?.warningOnly, false)
		XCTAssertEqual(inst.setup?.action?[4].assert?.description_fhir, "Confirm that the returned Bundle correctly defines the navigation links.")
		XCTAssertEqual(inst.setup?.action?[4].assert?.navigationLinks, true)
		XCTAssertEqual(inst.setup?.action?[4].assert?.warningOnly, false)
		XCTAssertEqual(inst.status, PublicationStatus(rawValue: "draft")!)
		XCTAssertEqual(inst.test?[0].action?[0].operation?.accept, "xml")
		XCTAssertEqual(inst.test?[0].action?[0].operation?.contentType, "xml")
		XCTAssertEqual(inst.test?[0].action?[0].operation?.description_fhir, "Create a Patient resource and capture the returned HTTP Header Location.")
		XCTAssertEqual(inst.test?[0].action?[0].operation?.encodeRequestUrl, true)
		XCTAssertEqual(inst.test?[0].action?[0].operation?.resource, "Patient")
		XCTAssertEqual(inst.test?[0].action?[0].operation?.responseId, "PatientCreateResponse")
		XCTAssertEqual(inst.test?[0].action?[0].operation?.sourceId, "fixture-patient-create")
		XCTAssertEqual(inst.test?[0].action?[0].operation?.type?.code, "create")
		XCTAssertEqual(inst.test?[0].action?[0].operation?.type?.system?.absoluteString, "http://terminology.hl7.org/CodeSystem/testscript-operation-codes")
		XCTAssertEqual(inst.test?[0].action?[1].assert?.description_fhir, "Confirm that the returned HTTP status is 201(Created).")
		XCTAssertEqual(inst.test?[0].action?[1].assert?.response, AssertionResponseTypes(rawValue: "created")!)
		XCTAssertEqual(inst.test?[0].action?[1].assert?.warningOnly, false)
		XCTAssertEqual(inst.test?[0].action?[2].assert?.description_fhir, "Confirm that the returned HTTP Header Location is present.")
		XCTAssertEqual(inst.test?[0].action?[2].assert?.direction, AssertionDirectionType(rawValue: "response")!)
		XCTAssertEqual(inst.test?[0].action?[2].assert?.headerField, "Location")
		XCTAssertEqual(inst.test?[0].action?[2].assert?.operator_fhir, AssertionOperatorType(rawValue: "notEmpty")!)
		XCTAssertEqual(inst.test?[0].action?[2].assert?.warningOnly, false)
		XCTAssertEqual(inst.test?[0].action?[3].operation?.accept, "xml")
		XCTAssertEqual(inst.test?[0].action?[3].operation?.description_fhir, "Read the created Patient using the captured Location URL value.")
		XCTAssertEqual(inst.test?[0].action?[3].operation?.encodeRequestUrl, true)
		XCTAssertEqual(inst.test?[0].action?[3].operation?.type?.code, "read")
		XCTAssertEqual(inst.test?[0].action?[3].operation?.type?.system?.absoluteString, "http://terminology.hl7.org/CodeSystem/testscript-operation-codes")
		XCTAssertEqual(inst.test?[0].action?[3].operation?.url, "${PatientCreateLocation}")
		XCTAssertEqual(inst.test?[0].action?[4].assert?.description_fhir, "Confirm that the returned HTTP status is 200(OK).")
		XCTAssertEqual(inst.test?[0].action?[4].assert?.response, AssertionResponseTypes(rawValue: "okay")!)
		XCTAssertEqual(inst.test?[0].action?[4].assert?.warningOnly, false)
		XCTAssertEqual(inst.test?[0].action?[5].assert?.description_fhir, "Confirm that the returned resource type is Patient.")
		XCTAssertEqual(inst.test?[0].action?[5].assert?.resource, "Patient")
		XCTAssertEqual(inst.test?[0].action?[5].assert?.warningOnly, false)
		XCTAssertEqual(inst.test?[0].description_fhir, "Create a Patient resource and capture the returned HTTP Header Location. Then search for (read) that Patient using the Location URL value and validate the response.")
		XCTAssertEqual(inst.test?[0].id, "01-PatientCreateSearch")
		XCTAssertEqual(inst.test?[0].name, "Patient Create Search")
		XCTAssertEqual(inst.test?[1].action?[0].operation?.accept, "xml")
		XCTAssertEqual(inst.test?[1].action?[0].operation?.description_fhir, "Search for Patient resources on the destination test system.")
		XCTAssertEqual(inst.test?[1].action?[0].operation?.encodeRequestUrl, true)
		XCTAssertEqual(inst.test?[1].action?[0].operation?.params, "?family=${PatientSearchFamilyName}&given=${PatientSearchGivenName}")
		XCTAssertEqual(inst.test?[1].action?[0].operation?.resource, "Patient")
		XCTAssertEqual(inst.test?[1].action?[0].operation?.type?.code, "search")
		XCTAssertEqual(inst.test?[1].action?[0].operation?.type?.system?.absoluteString, "http://terminology.hl7.org/CodeSystem/testscript-operation-codes")
		XCTAssertEqual(inst.test?[1].action?[1].assert?.description_fhir, "Confirm that the returned HTTP status is 200(OK).")
		XCTAssertEqual(inst.test?[1].action?[1].assert?.response, AssertionResponseTypes(rawValue: "okay")!)
		XCTAssertEqual(inst.test?[1].action?[1].assert?.warningOnly, false)
		XCTAssertEqual(inst.test?[1].action?[2].assert?.contentType, "xml")
		XCTAssertEqual(inst.test?[1].action?[2].assert?.description_fhir, "Confirm that the returned format is XML.")
		XCTAssertEqual(inst.test?[1].action?[2].assert?.warningOnly, false)
		XCTAssertEqual(inst.test?[1].action?[3].assert?.description_fhir, "Confirm that the returned resource type is Bundle.")
		XCTAssertEqual(inst.test?[1].action?[3].assert?.resource, "Bundle")
		XCTAssertEqual(inst.test?[1].action?[3].assert?.warningOnly, false)
		XCTAssertEqual(inst.test?[1].action?[4].assert?.description_fhir, "Confirm that the returned Bundle conforms to the base FHIR specification.")
		XCTAssertEqual(inst.test?[1].action?[4].assert?.validateProfileId, "bundle-profile")
		XCTAssertEqual(inst.test?[1].action?[4].assert?.warningOnly, false)
		XCTAssertEqual(inst.test?[1].action?[5].assert?.description_fhir, "Confirm that the returned Bundle type equals 'searchset'.")
		XCTAssertEqual(inst.test?[1].action?[5].assert?.operator_fhir, AssertionOperatorType(rawValue: "equals")!)
		XCTAssertEqual(inst.test?[1].action?[5].assert?.path, "fhir:Bundle/fhir:type/@value")
		XCTAssertEqual(inst.test?[1].action?[5].assert?.value, "searchset")
		XCTAssertEqual(inst.test?[1].action?[5].assert?.warningOnly, false)
		XCTAssertEqual(inst.test?[1].action?[6].assert?.description_fhir, "Confirm that the returned Bundle total is greater than or equal to the number of returned entries.")
		XCTAssertEqual(inst.test?[1].action?[6].assert?.expression, "Bundle.total.toInteger() >= entry.count()")
		XCTAssertEqual(inst.test?[1].action?[6].assert?.warningOnly, false)
		XCTAssertEqual(inst.test?[1].description_fhir, "Search for Patient resources using the user defined dynamic variables ${PatientSearchFamilyName} and ${PatientSearchGivenName} and validate response.")
		XCTAssertEqual(inst.test?[1].id, "02-PatientSearchDynamic")
		XCTAssertEqual(inst.test?[1].name, "Patient Search Dynamic")
		XCTAssertEqual(inst.text?.status, NarrativeStatus(rawValue: "generated")!)
		XCTAssertEqual(inst.url?.absoluteString, "http://hl7.org/fhir/TestScript/testscript-example-search")
		XCTAssertEqual(inst.variable?[0].headerField, "Location")
		XCTAssertEqual(inst.variable?[0].name, "PatientCreateLocation")
		XCTAssertEqual(inst.variable?[0].sourceId, "PatientCreateResponse")
		XCTAssertEqual(inst.variable?[1].description_fhir, "Enter patient search criteria for a known family name on the target system")
		XCTAssertEqual(inst.variable?[1].hint, "[Family name]")
		XCTAssertEqual(inst.variable?[1].name, "PatientSearchFamilyName")
		XCTAssertEqual(inst.variable?[2].description_fhir, "Enter patient search criteria for a known given name on the target system")
		XCTAssertEqual(inst.variable?[2].hint, "[Given name]")
		XCTAssertEqual(inst.variable?[2].name, "PatientSearchGivenName")
		XCTAssertEqual(inst.variable?[3].description_fhir, "Evaluate the returned Patient searchset Bundle.total value")
		XCTAssertEqual(inst.variable?[3].expression, "Bundle.total.toInteger()")
		XCTAssertEqual(inst.variable?[3].name, "PatientSearchBundleTotal")
		XCTAssertEqual(inst.version, "1.0")
		
		return inst
	}
	
	func testTestScript5() {
		do {
			let instance = try runTestScript5()
			try runTestScript5(instance.asJSON())
		}
		catch let error {
			XCTAssertTrue(false, "Must instantiate and test TestScript successfully, but threw:\n---\n\(error)\n---")
		}
	}
	
	@discardableResult
	func runTestScript5(_ json: FHIRJSON? = nil) throws -> SwiftFHIRTestScript {
		let inst = (nil != json) ? try instantiateFrom(json: json!) : try instantiateFrom(filename: "testscript-example.json")
		
		XCTAssertEqual(inst.contact?[0].name, "Support")
		XCTAssertEqual(inst.contact?[0].telecom?[0].system, ContactPointSystem(rawValue: "email")!)
		XCTAssertEqual(inst.contact?[0].telecom?[0].use, ContactPointUse(rawValue: "work")!)
		XCTAssertEqual(inst.contact?[0].telecom?[0].value, "support@HL7.org")
		XCTAssertEqual(inst.copyright, "© HL7.org 2011+")
		XCTAssertEqual(inst.date?.description, "2017-01-18")
		XCTAssertEqual(inst.description_fhir, "TestScript example resource with setup to delete if present and create a new instance of a Patient; and single test definition to read the created Patient with various asserts.")
		XCTAssertEqual(inst.experimental, true)
		XCTAssertEqual(inst.fixture?[0].autocreate, false)
		XCTAssertEqual(inst.fixture?[0].autodelete, false)
		XCTAssertEqual(inst.fixture?[0].id, "fixture-patient-create")
		XCTAssertEqual(inst.fixture?[0].resource?.display, "Peter Chalmers")
		XCTAssertEqual(inst.fixture?[0].resource?.reference, "Patient/example")
		XCTAssertEqual(inst.fixture?[1].autocreate, false)
		XCTAssertEqual(inst.fixture?[1].autodelete, false)
		XCTAssertEqual(inst.fixture?[1].id, "fixture-patient-minimum")
		XCTAssertEqual(inst.fixture?[1].resource?.display, "Peter Chalmers (minimum)")
		XCTAssertEqual(inst.fixture?[1].resource?.reference, "Patient/example")
		XCTAssertEqual(inst.id, "testscript-example")
		XCTAssertEqual(inst.identifier?.system?.absoluteString, "urn:ietf:rfc:3986")
		XCTAssertEqual(inst.identifier?.value, "urn:oid:1.3.6.1.4.1.21367.2005.3.7.9876")
		XCTAssertEqual(inst.jurisdiction?[0].coding?[0].code, "US")
		XCTAssertEqual(inst.jurisdiction?[0].coding?[0].display, "United States of America (the)")
		XCTAssertEqual(inst.jurisdiction?[0].coding?[0].system?.absoluteString, "urn:iso:std:iso:3166")
		XCTAssertEqual(inst.metadata?.capability?[0].capabilities?.absoluteString, "CapabilityStatement/example")
		XCTAssertEqual(inst.metadata?.capability?[0].description_fhir, "Patient Update, Read and Delete Operations")
		XCTAssertEqual(inst.metadata?.capability?[0].link?[0].absoluteString, "http://hl7.org/fhir/http.html#delete")
		XCTAssertEqual(inst.metadata?.capability?[0].link?[1].absoluteString, "http://hl7.org/fhir/http.html#read")
		XCTAssertEqual(inst.metadata?.capability?[0].link?[2].absoluteString, "http://hl7.org/fhir/http.html#update")
		XCTAssertEqual(inst.metadata?.capability?[0].required, true)
		XCTAssertEqual(inst.metadata?.capability?[0].validated, false)
		XCTAssertEqual(inst.metadata?.link?[0].description_fhir, "Demographics and other administrative information about an individual or animal receiving care or other health-related services.")
		XCTAssertEqual(inst.metadata?.link?[0].url?.absoluteString, "http://hl7.org/fhir/patient.html")
		XCTAssertEqual(inst.name, "TestScript Example")
		XCTAssertEqual(inst.profile?[0].id, "patient-profile")
		XCTAssertEqual(inst.profile?[0].reference, "http://hl7.org/fhir/StructureDefinition/Patient")
		XCTAssertEqual(inst.publisher, "HL7")
		XCTAssertEqual(inst.purpose, "Patient Conditional Create (Update), Read and Delete Operations")
		XCTAssertEqual(inst.setup?.action?[0].operation?.accept, "json")
		XCTAssertEqual(inst.setup?.action?[0].operation?.description_fhir, "Execute a delete operation to insure the patient does not exist on the server.")
		XCTAssertEqual(inst.setup?.action?[0].operation?.encodeRequestUrl, true)
		XCTAssertEqual(inst.setup?.action?[0].operation?.label, "SetupDeletePatient")
		XCTAssertEqual(inst.setup?.action?[0].operation?.params, "/${createResourceId}")
		XCTAssertEqual(inst.setup?.action?[0].operation?.resource, "Patient")
		XCTAssertEqual(inst.setup?.action?[0].operation?.type?.code, "delete")
		XCTAssertEqual(inst.setup?.action?[0].operation?.type?.system?.absoluteString, "http://terminology.hl7.org/CodeSystem/testscript-operation-codes")
		XCTAssertEqual(inst.setup?.action?[1].assert?.description_fhir, "Confirm that the returned HTTP status is 200(OK) or 204(No Content).")
		XCTAssertEqual(inst.setup?.action?[1].assert?.direction, AssertionDirectionType(rawValue: "response")!)
		XCTAssertEqual(inst.setup?.action?[1].assert?.operator_fhir, AssertionOperatorType(rawValue: "in")!)
		XCTAssertEqual(inst.setup?.action?[1].assert?.responseCode, "200,204")
		XCTAssertEqual(inst.setup?.action?[1].assert?.warningOnly, false)
		XCTAssertEqual(inst.setup?.action?[2].operation?.accept, "json")
		XCTAssertEqual(inst.setup?.action?[2].operation?.contentType, "json")
		XCTAssertEqual(inst.setup?.action?[2].operation?.description_fhir, "Create patient resource on test server using the contents of fixture-patient-create")
		XCTAssertEqual(inst.setup?.action?[2].operation?.encodeRequestUrl, true)
		XCTAssertEqual(inst.setup?.action?[2].operation?.label, "SetupCreatePatient")
		XCTAssertEqual(inst.setup?.action?[2].operation?.params, "/${createResourceId}")
		XCTAssertEqual(inst.setup?.action?[2].operation?.resource, "Patient")
		XCTAssertEqual(inst.setup?.action?[2].operation?.sourceId, "fixture-patient-create")
		XCTAssertEqual(inst.setup?.action?[2].operation?.type?.code, "update")
		XCTAssertEqual(inst.setup?.action?[2].operation?.type?.system?.absoluteString, "http://terminology.hl7.org/CodeSystem/testscript-operation-codes")
		XCTAssertEqual(inst.setup?.action?[3].assert?.description_fhir, "Confirm that the returned HTTP status is 201(Created).")
		XCTAssertEqual(inst.setup?.action?[3].assert?.direction, AssertionDirectionType(rawValue: "response")!)
		XCTAssertEqual(inst.setup?.action?[3].assert?.responseCode, "201")
		XCTAssertEqual(inst.setup?.action?[3].assert?.warningOnly, false)
		XCTAssertEqual(inst.setup?.action?[4].operation?.description_fhir, "Read the created patient resource on the test server using the id from fixture-patient-create. Verify contents.")
		XCTAssertEqual(inst.setup?.action?[4].operation?.encodeRequestUrl, true)
		XCTAssertEqual(inst.setup?.action?[4].operation?.resource, "Patient")
		XCTAssertEqual(inst.setup?.action?[4].operation?.targetId, "fixture-patient-create")
		XCTAssertEqual(inst.setup?.action?[4].operation?.type?.code, "read")
		XCTAssertEqual(inst.setup?.action?[4].operation?.type?.system?.absoluteString, "http://terminology.hl7.org/CodeSystem/testscript-operation-codes")
		XCTAssertEqual(inst.setup?.action?[5].assert?.description_fhir, "Confirm that the returned HTTP status is 200(OK).")
		XCTAssertEqual(inst.setup?.action?[5].assert?.direction, AssertionDirectionType(rawValue: "response")!)
		XCTAssertEqual(inst.setup?.action?[5].assert?.response, AssertionResponseTypes(rawValue: "okay")!)
		XCTAssertEqual(inst.setup?.action?[5].assert?.warningOnly, false)
		XCTAssertEqual(inst.setup?.action?[6].assert?.compareToSourceExpression, "Patient.name.first().family")
		XCTAssertEqual(inst.setup?.action?[6].assert?.compareToSourceId, "fixture-patient-create")
		XCTAssertEqual(inst.setup?.action?[6].assert?.description_fhir, "Confirm that the returned Patient contains the expected family name 'Chalmers'. Uses explicit compareToSourceId reference to fixture-patient-create used to create the Patient.")
		XCTAssertEqual(inst.setup?.action?[6].assert?.operator_fhir, AssertionOperatorType(rawValue: "equals")!)
		XCTAssertEqual(inst.setup?.action?[6].assert?.warningOnly, false)
		XCTAssertEqual(inst.status, PublicationStatus(rawValue: "draft")!)
		XCTAssertEqual(inst.teardown?.action?[0].operation?.description_fhir, "Delete the patient resource on the test server using the id from fixture-patient-create.")
		XCTAssertEqual(inst.teardown?.action?[0].operation?.encodeRequestUrl, true)
		XCTAssertEqual(inst.teardown?.action?[0].operation?.resource, "Patient")
		XCTAssertEqual(inst.teardown?.action?[0].operation?.targetId, "fixture-patient-create")
		XCTAssertEqual(inst.teardown?.action?[0].operation?.type?.code, "delete")
		XCTAssertEqual(inst.teardown?.action?[0].operation?.type?.system?.absoluteString, "http://terminology.hl7.org/CodeSystem/testscript-operation-codes")
		XCTAssertEqual(inst.test?[0].action?[0].operation?.description_fhir, "Read the patient resource on the test server using the id from fixture-patient-create. Prevent URL encoding of the request.")
		XCTAssertEqual(inst.test?[0].action?[0].operation?.encodeRequestUrl, false)
		XCTAssertEqual(inst.test?[0].action?[0].operation?.resource, "Patient")
		XCTAssertEqual(inst.test?[0].action?[0].operation?.responseId, "fixture-patient-read")
		XCTAssertEqual(inst.test?[0].action?[0].operation?.targetId, "fixture-patient-create")
		XCTAssertEqual(inst.test?[0].action?[0].operation?.type?.code, "read")
		XCTAssertEqual(inst.test?[0].action?[0].operation?.type?.system?.absoluteString, "http://terminology.hl7.org/CodeSystem/testscript-operation-codes")
		XCTAssertEqual(inst.test?[0].action?[1].assert?.description_fhir, "Confirm that the returned HTTP status is 200(OK).")
		XCTAssertEqual(inst.test?[0].action?[1].assert?.direction, AssertionDirectionType(rawValue: "response")!)
		XCTAssertEqual(inst.test?[0].action?[1].assert?.label, "01-ReadPatientOK")
		XCTAssertEqual(inst.test?[0].action?[1].assert?.response, AssertionResponseTypes(rawValue: "okay")!)
		XCTAssertEqual(inst.test?[0].action?[1].assert?.warningOnly, false)
		XCTAssertEqual(inst.test?[0].action?[2].assert?.description_fhir, "Confirm that the returned HTTP Header Last-Modified is present. Warning only as the server might not support versioning.")
		XCTAssertEqual(inst.test?[0].action?[2].assert?.direction, AssertionDirectionType(rawValue: "response")!)
		XCTAssertEqual(inst.test?[0].action?[2].assert?.headerField, "Last-Modified")
		XCTAssertEqual(inst.test?[0].action?[2].assert?.operator_fhir, AssertionOperatorType(rawValue: "notEmpty")!)
		XCTAssertEqual(inst.test?[0].action?[2].assert?.warningOnly, true)
		XCTAssertEqual(inst.test?[0].action?[3].assert?.description_fhir, "Confirm that the returned resource type is Patient.")
		XCTAssertEqual(inst.test?[0].action?[3].assert?.resource, "Patient")
		XCTAssertEqual(inst.test?[0].action?[3].assert?.warningOnly, false)
		XCTAssertEqual(inst.test?[0].action?[4].assert?.description_fhir, "Confirm that the returned Patient conforms to the base FHIR specification.")
		XCTAssertEqual(inst.test?[0].action?[4].assert?.validateProfileId, "patient-profile")
		XCTAssertEqual(inst.test?[0].action?[4].assert?.warningOnly, false)
		XCTAssertEqual(inst.test?[0].action?[5].assert?.description_fhir, "Confirm that the returned Patient contains the expected family name 'Chalmers'. Uses explicit sourceId reference to read responseId fixture.")
		XCTAssertEqual(inst.test?[0].action?[5].assert?.operator_fhir, AssertionOperatorType(rawValue: "equals")!)
		XCTAssertEqual(inst.test?[0].action?[5].assert?.path, "fhir:Patient/fhir:name/fhir:family/@value")
		XCTAssertEqual(inst.test?[0].action?[5].assert?.sourceId, "fixture-patient-read")
		XCTAssertEqual(inst.test?[0].action?[5].assert?.value, "Chalmers")
		XCTAssertEqual(inst.test?[0].action?[5].assert?.warningOnly, false)
		XCTAssertEqual(inst.test?[0].action?[6].assert?.description_fhir, "Confirm that the returned Patient contains the expected given name 'Peter'. Uses explicit sourceId reference to read responseId fixture.")
		XCTAssertEqual(inst.test?[0].action?[6].assert?.operator_fhir, AssertionOperatorType(rawValue: "equals")!)
		XCTAssertEqual(inst.test?[0].action?[6].assert?.path, "fhir:Patient/fhir:name/fhir:given/@value")
		XCTAssertEqual(inst.test?[0].action?[6].assert?.sourceId, "fixture-patient-read")
		XCTAssertEqual(inst.test?[0].action?[6].assert?.value, "Peter")
		XCTAssertEqual(inst.test?[0].action?[6].assert?.warningOnly, false)
		XCTAssertEqual(inst.test?[0].action?[7].assert?.compareToSourceId, "fixture-patient-create")
		XCTAssertEqual(inst.test?[0].action?[7].assert?.compareToSourcePath, "fhir:Patient/fhir:name/fhir:family/@value")
		XCTAssertEqual(inst.test?[0].action?[7].assert?.operator_fhir, AssertionOperatorType(rawValue: "equals")!)
		XCTAssertEqual(inst.test?[0].action?[7].assert?.path, "fhir:Patient/fhir:name/fhir:family/@value")
		XCTAssertEqual(inst.test?[0].action?[7].assert?.warningOnly, false)
		XCTAssertEqual(inst.test?[0].action?[8].assert?.compareToSourceId, "fixture-patient-create")
		XCTAssertEqual(inst.test?[0].action?[8].assert?.compareToSourcePath, "fhir:Patient/fhir:name/fhir:given/@value")
		XCTAssertEqual(inst.test?[0].action?[8].assert?.path, "fhir:Patient/fhir:name/fhir:given/@value")
		XCTAssertEqual(inst.test?[0].action?[8].assert?.sourceId, "fixture-patient-read")
		XCTAssertEqual(inst.test?[0].action?[8].assert?.warningOnly, false)
		XCTAssertEqual(inst.test?[0].action?[9].assert?.description_fhir, "Confirm that the returned resource contains the expected retained elements and values. Warning only to provide users with reviewable results.")
		XCTAssertEqual(inst.test?[0].action?[9].assert?.minimumId, "fixture-patient-minimum")
		XCTAssertEqual(inst.test?[0].action?[9].assert?.warningOnly, true)
		XCTAssertEqual(inst.test?[0].description_fhir, "Read a Patient and validate response.")
		XCTAssertEqual(inst.test?[0].id, "01-ReadPatient")
		XCTAssertEqual(inst.test?[0].name, "Read Patient")
		XCTAssertEqual(inst.text?.status, NarrativeStatus(rawValue: "generated")!)
		XCTAssertEqual(inst.url?.absoluteString, "http://hl7.org/fhir/TestScript/testscript-example")
		XCTAssertEqual(inst.useContext?[0].code?.code, "focus")
		XCTAssertEqual(inst.useContext?[0].code?.system?.absoluteString, "http://terminology.hl7.org/CodeSystem/usage-context-type")
		XCTAssertEqual(inst.useContext?[0].valueCodeableConcept?.coding?[0].code, "positive")
		XCTAssertEqual(inst.useContext?[0].valueCodeableConcept?.coding?[0].system?.absoluteString, "http://terminology.hl7.org/CodeSystem/variant-state")
		XCTAssertEqual(inst.variable?[0].name, "createResourceId")
		XCTAssertEqual(inst.variable?[0].path, "Patient/id")
		XCTAssertEqual(inst.variable?[0].sourceId, "fixture-patient-create")
		XCTAssertEqual(inst.version, "1.0")
		
		return inst
	}
	
	func testTestScript6() {
		do {
			let instance = try runTestScript6()
			try runTestScript6(instance.asJSON())
		}
		catch let error {
			XCTAssertTrue(false, "Must instantiate and test TestScript successfully, but threw:\n---\n\(error)\n---")
		}
	}
	
	@discardableResult
	func runTestScript6(_ json: FHIRJSON? = nil) throws -> SwiftFHIRTestScript {
		let inst = (nil != json) ? try instantiateFrom(json: json!) : try instantiateFrom(filename: "testscript-example-readtest.json")
		
		XCTAssertEqual(inst.contact?[0].name, "Support")
		XCTAssertEqual(inst.contact?[0].telecom?[0].system, ContactPointSystem(rawValue: "email")!)
		XCTAssertEqual(inst.contact?[0].telecom?[0].use, ContactPointUse(rawValue: "work")!)
		XCTAssertEqual(inst.contact?[0].telecom?[0].value, "support@HL7.org")
		XCTAssertEqual(inst.copyright, "© HL7.org 2011+")
		XCTAssertEqual(inst.date?.description, "2017-01-18")
		XCTAssertEqual(inst.description_fhir, "TestScript example resource with ported Sprinkler basic read tests R001, R002, R003, R004. The read tests will utilize user defined dynamic variables that will hold the Patient resource id values.")
		XCTAssertEqual(inst.experimental, true)
		XCTAssertEqual(inst.id, "testscript-example-readtest")
		XCTAssertEqual(inst.identifier?.system?.absoluteString, "urn:ietf:rfc:3986")
		XCTAssertEqual(inst.identifier?.value, "urn:oid:1.3.6.1.4.1.21367.2005.3.7.9879")
		XCTAssertEqual(inst.jurisdiction?[0].coding?[0].code, "US")
		XCTAssertEqual(inst.jurisdiction?[0].coding?[0].display, "United States of America (the)")
		XCTAssertEqual(inst.jurisdiction?[0].coding?[0].system?.absoluteString, "urn:iso:std:iso:3166")
		XCTAssertEqual(inst.metadata?.capability?[0].capabilities?.absoluteString, "CapabilityStatement/example")
		XCTAssertEqual(inst.metadata?.capability?[0].description_fhir, "Patient Read Operation")
		XCTAssertEqual(inst.metadata?.capability?[0].link?[0].absoluteString, "http://hl7.org/fhir/http.html#read")
		XCTAssertEqual(inst.metadata?.capability?[0].required, true)
		XCTAssertEqual(inst.metadata?.capability?[0].validated, false)
		XCTAssertEqual(inst.metadata?.link?[0].description_fhir, "Demographics and other administrative information about an individual or animal receiving care or other health-related services.")
		XCTAssertEqual(inst.metadata?.link?[0].url?.absoluteString, "http://hl7.org/fhir/patient.html")
		XCTAssertEqual(inst.name, "TestScript Example Read Test")
		XCTAssertEqual(inst.profile?[0].id, "patient-profile")
		XCTAssertEqual(inst.profile?[0].reference, "http://hl7.org/fhir/StructureDefinition/Patient")
		XCTAssertEqual(inst.publisher, "HL7")
		XCTAssertEqual(inst.purpose, "Patient Read Operation")
		XCTAssertEqual(inst.status, PublicationStatus(rawValue: "draft")!)
		XCTAssertEqual(inst.test?[0].action?[0].operation?.accept, "xml")
		XCTAssertEqual(inst.test?[0].action?[0].operation?.description_fhir, "Read the known Patient resource on the destination test system using the user defined dynamic variable ${KnownPatientResourceId}.")
		XCTAssertEqual(inst.test?[0].action?[0].operation?.encodeRequestUrl, true)
		XCTAssertEqual(inst.test?[0].action?[0].operation?.params, "/${KnownPatientResourceId}")
		XCTAssertEqual(inst.test?[0].action?[0].operation?.resource, "Patient")
		XCTAssertEqual(inst.test?[0].action?[0].operation?.type?.code, "read")
		XCTAssertEqual(inst.test?[0].action?[0].operation?.type?.system?.absoluteString, "http://terminology.hl7.org/CodeSystem/testscript-operation-codes")
		XCTAssertEqual(inst.test?[0].action?[1].assert?.description_fhir, "Confirm that the returned HTTP status is 200(OK).")
		XCTAssertEqual(inst.test?[0].action?[1].assert?.response, AssertionResponseTypes(rawValue: "okay")!)
		XCTAssertEqual(inst.test?[0].action?[1].assert?.warningOnly, false)
		XCTAssertEqual(inst.test?[0].action?[2].assert?.contentType, "xml")
		XCTAssertEqual(inst.test?[0].action?[2].assert?.description_fhir, "Confirm that the returned format is XML.")
		XCTAssertEqual(inst.test?[0].action?[2].assert?.warningOnly, false)
		XCTAssertEqual(inst.test?[0].action?[3].assert?.description_fhir, "Confirm that the returned HTTP Header Last-Modified is present. Warning only as the server might not support versioning.")
		XCTAssertEqual(inst.test?[0].action?[3].assert?.headerField, "Last-Modified")
		XCTAssertEqual(inst.test?[0].action?[3].assert?.operator_fhir, AssertionOperatorType(rawValue: "notEmpty")!)
		XCTAssertEqual(inst.test?[0].action?[3].assert?.warningOnly, true)
		XCTAssertEqual(inst.test?[0].action?[4].assert?.description_fhir, "Confirm that the returned resource type is Patient.")
		XCTAssertEqual(inst.test?[0].action?[4].assert?.resource, "Patient")
		XCTAssertEqual(inst.test?[0].action?[4].assert?.warningOnly, false)
		XCTAssertEqual(inst.test?[0].action?[5].assert?.description_fhir, "Confirm that the returned Patient conforms to the base FHIR specification.")
		XCTAssertEqual(inst.test?[0].action?[5].assert?.validateProfileId, "patient-profile")
		XCTAssertEqual(inst.test?[0].action?[5].assert?.warningOnly, false)
		XCTAssertEqual(inst.test?[0].description_fhir, "Read a known Patient and validate response.")
		XCTAssertEqual(inst.test?[0].id, "R001")
		XCTAssertEqual(inst.test?[0].name, "Sprinkler Read Test R001")
		XCTAssertEqual(inst.test?[1].action?[0].operation?.accept, "xml")
		XCTAssertEqual(inst.test?[1].action?[0].operation?.encodeRequestUrl, true)
		XCTAssertEqual(inst.test?[1].action?[0].operation?.params, "/1")
		XCTAssertEqual(inst.test?[1].action?[0].operation?.resource, "Patient")
		XCTAssertEqual(inst.test?[1].action?[0].operation?.type?.code, "read")
		XCTAssertEqual(inst.test?[1].action?[0].operation?.type?.system?.absoluteString, "http://terminology.hl7.org/CodeSystem/testscript-operation-codes")
		XCTAssertEqual(inst.test?[1].action?[1].assert?.description_fhir, "Confirm that the returned HTTP status is 404(Not Found).")
		XCTAssertEqual(inst.test?[1].action?[1].assert?.response, AssertionResponseTypes(rawValue: "notFound")!)
		XCTAssertEqual(inst.test?[1].action?[1].assert?.warningOnly, false)
		XCTAssertEqual(inst.test?[1].description_fhir, "Read an unknown Resource Type and validate response.")
		XCTAssertEqual(inst.test?[1].id, "R002")
		XCTAssertEqual(inst.test?[1].name, "Sprinkler Read Test R002")
		XCTAssertEqual(inst.test?[2].action?[0].operation?.accept, "xml")
		XCTAssertEqual(inst.test?[2].action?[0].operation?.description_fhir, "Attempt to read the non-existing Patient resource on the destination test system using the user defined dynamic variable ${NonExistsPatientResourceId}.")
		XCTAssertEqual(inst.test?[2].action?[0].operation?.encodeRequestUrl, true)
		XCTAssertEqual(inst.test?[2].action?[0].operation?.params, "/${NonExistsPatientResourceId}")
		XCTAssertEqual(inst.test?[2].action?[0].operation?.resource, "Patient")
		XCTAssertEqual(inst.test?[2].action?[0].operation?.type?.code, "read")
		XCTAssertEqual(inst.test?[2].action?[0].operation?.type?.system?.absoluteString, "http://terminology.hl7.org/CodeSystem/testscript-operation-codes")
		XCTAssertEqual(inst.test?[2].action?[1].assert?.description_fhir, "Confirm that the returned HTTP status is 404(Not Found).")
		XCTAssertEqual(inst.test?[2].action?[1].assert?.response, AssertionResponseTypes(rawValue: "notFound")!)
		XCTAssertEqual(inst.test?[2].action?[1].assert?.warningOnly, false)
		XCTAssertEqual(inst.test?[2].description_fhir, "Read a known, non-existing Patient and validate response.")
		XCTAssertEqual(inst.test?[2].id, "R003")
		XCTAssertEqual(inst.test?[2].name, "Sprinkler Read Test R003")
		XCTAssertEqual(inst.test?[3].action?[0].operation?.accept, "xml")
		XCTAssertEqual(inst.test?[3].action?[0].operation?.description_fhir, "Attempt to read a Patient resource on the destination test system using known bad formatted resource id.")
		XCTAssertEqual(inst.test?[3].action?[0].operation?.encodeRequestUrl, true)
		XCTAssertEqual(inst.test?[3].action?[0].operation?.params, "/ID-may-not-contain-CAPITALS")
		XCTAssertEqual(inst.test?[3].action?[0].operation?.resource, "Patient")
		XCTAssertEqual(inst.test?[3].action?[0].operation?.type?.code, "read")
		XCTAssertEqual(inst.test?[3].action?[0].operation?.type?.system?.absoluteString, "http://terminology.hl7.org/CodeSystem/testscript-operation-codes")
		XCTAssertEqual(inst.test?[3].action?[1].assert?.description_fhir, "Confirm that the returned HTTP status is 400(Bad Request).")
		XCTAssertEqual(inst.test?[3].action?[1].assert?.response, AssertionResponseTypes(rawValue: "bad")!)
		XCTAssertEqual(inst.test?[3].action?[1].assert?.warningOnly, false)
		XCTAssertEqual(inst.test?[3].description_fhir, "Read a Patient using a known bad formatted resource id and validate response.")
		XCTAssertEqual(inst.test?[3].id, "R004")
		XCTAssertEqual(inst.test?[3].name, "Sprinkler Read Test R004")
		XCTAssertEqual(inst.text?.status, NarrativeStatus(rawValue: "generated")!)
		XCTAssertEqual(inst.url?.absoluteString, "http://hl7.org/fhir/TestScript/testscript-example-readtest")
		XCTAssertEqual(inst.variable?[0].defaultValue, "example")
		XCTAssertEqual(inst.variable?[0].name, "KnownPatientResourceId")
		XCTAssertEqual(inst.variable?[1].defaultValue, "does-not-exist")
		XCTAssertEqual(inst.variable?[1].name, "NonExistsPatientResourceId")
		XCTAssertEqual(inst.version, "1.0")
		
		return inst
	}
}
